### ISSUE TITLE
Too many open files is fatal for Listener.accept

### ISSUE THREAD

**Issue by hayd** [denoland/deno#10148]
if you run wrk against either native http or std http bench examples with a large connection number:

```sh
# one terminal
❱ target/release/deno run -A --unstable cli/bench/deno_http_native.js
Server listening on 127.0.0.1:4500
error: Uncaught (in promise) Error: Too many open files (os error 24)
    at unwrapOpResult (deno:core/core.js:100:13)
    at async Listener.accept (deno:runtime/js/30_net.js:98:19)
    at async Listener.next (deno:runtime/js/30_net.js:105:16)
    at async file:///Users/somewhere/deno/cli/bench/deno_http_native.js:10:18


# another (note the large number of connections)
❱ wrk -d 20 -c 500 --latency http://127.0.0.1:4500
```
This can probably be worked around with increasing ulimits. But this could conceivably happen unexpectedly on a server if it had a spike in traffic.

Note: `node cli/bench/node_http.js` handles this without error (or printing anything).

---

Hyper's AddrIncoming (higher level API) has [`sleep_on_error`](https://docs.rs/hyper/0.14.5/hyper/server/conn/struct.AddrIncoming.html#method.set_sleep_on_errors) which sleeps for a second after an non connection error:
https://github.com/hyperium/hyper/blob/41f99578a53845e5e0bb999c101bef8307e1ce5f/src/server/tcp.rs#L130-L145

Deno should do that as well.

**Comment by bnoordhuis** [comment]
The way Node.js addresses that is by:

1. Raising the `RLIMIT_NOFILE` resource limit from the soft limit to the hard limit, and

2. Keeping an extra file descriptor around. When accepting a new connection fails because of `EMFILE` or `ENFILE`, close the file descriptor, accept the new connection, and close it.

(2) is not completely race free (can race with other threads) but it's one of those "good enough" hacks.

On my system:
```
$ ulimit -n -S # soft limit
1024

$ ulimit -n -H # hard limit
1048576
```
