### ISSUE TITLE
Failed to run tool/build.py 

### ISSUE THREAD

**Issue by Kermit-Xuan** [denoland/deno#1017]
System Version: Mac OS 10.14

Screenshot：

<img width="1095" alt="wx20181019-093820 2x" src="https://user-images.githubusercontent.com/33770367/47192924-c343a680-d382-11e8-8d7d-a3ab767af98b.png">

**Comment by hayd** [comment]
Have you already run `./tools/setup.py` successfully?

**Comment by ztplz** [comment]
Please run `git submodule update`.

**Comment by Kermit-Xuan** [comment]
@hayd Yes, run ./tools/setup.py is success.

**Comment by Kermit-Xuan** [comment]
> Please run `git submodule update`.

After running `git submodule update`, it's not working.

**Comment by Kermit-Xuan** [comment]
> Have you already run `./tools/setup.py` successfully?

Yes, it's success.

**Comment by rjoydip** [comment]
properly not installed npm. The node_modules contains only on binary.
https://github.com/denoland/deno_third_party/tree/master/node_modules/ts-node

**Comment by rjoydip** [comment]
I think during the build after `fix_symlinks` execution the third_party modules not installing(by `run_yarn`). And then when "tools > main.ts" executing `build_library.ts` the [new Project](https://github.com/denoland/deno/blob/master/tools/ts_library_builder/build_library.ts#L298) picking up `.ts` file and trying to execute but `ts-node` dependencies are not installed that's why the error has introduced. 
May be I am wrong !. Correct me if I am.
