### ISSUE TITLE
Exported function causing error in latest version

### ISSUE THREAD

**Issue by rssaranece94** [denoland/deno#10209]
# Issue

Setup:

- Deno Version: <1.9.0>
- v8 Version: <9.1.269.5>
- Typescript Version: <4.2.2>

## Details

add.ts
```

export const add = (a: number, b: number) => {
  return a + b;
};

```

app.ts
```
import { add } from './add.ts';
...
console.log(add(1,2));

```

error: TS2612 [ERROR]: Property 'resolve' will overwrite the base property in 'Deferred<undefined>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    public readonly resolve!: () => void;
                    ~~~~~~~
    at https://deno.land/x/evt@v1.9.12/tools/Deferred.ts:57:21


kindly help me out of it

**Comment by kitsonk** [comment]
You are not providing a full reproduction, because you are not importing any 3rd party modules in your example, but the error is occurring in a 3rd party module.

What happened when you raised an issue with the [3rd party module provider](https://github.com/garronej/evt) about not supporting Deno 1.9?

**Comment by rssaranece94** [comment]
Got fixed, due to old version of 3rd party module were imported in the file caused this issue. Thanks for help.
