### ISSUE TITLE
Embedding Deno with Typescript support

### ISSUE THREAD

**Issue by attila-lin** [denoland/deno#10283]
Now we can embed deno with `deno_core` crate with js supprot, like [link](https://deno.land/manual@v1.9.0/embedding_deno).

Maybe we can create a `deno_ts` with the typescript support. The `deno_ts` crate can separate from the `deno_cli`.

**Comment by kitsonk** [comment]
It is complicated, as TypeScript is tightly coupled with other strong concepts in the CLI like module resolution. It is a low priority for the project, so it is unlikely to happen anytime soon.

For embedded, it is far more likely to create something specific to their needs on top of Deno core instead of waiting for something like that to come from the CLI and CLI can be used as a reference.

Also, there are really two "TypeScript" engines in the CLI, swc for transpiling and bundling and tsc for type checking and an embedder would want to consider if they really want or need both.

**Comment by scarf005** [comment]
> See also the examples in the `deno_core` repo.

https://github.com/denoland/deno_core/blob/ebb6b4a9911fe39f2daf9322a23e4da0b80d21c0/README.md

could you point out where to reference? README seems to be empty.
