### ISSUE TITLE
Consider enabling `emitDecoratorMetadata` by default.

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#10342]
Consider enabling `emitDecoratorMetadata` by default in typescript configuration

**Comment by kitsonk** [comment]
I would be opposed to this. It emits extra information which increases the emit size when decorators are used. It should be opt-in. This is different from enabling experimental decorators because if you don't use them, they never appear in the emit.

Also, like experimental decorators, emitting metadata as it currently works, is a technical dead end that will not make it part of the language, and should generally be discouraged and avoided.

**Comment by getspooky** [comment]
`emitDecoratorMetadata` is experimental features in typescript , so there is no need to integrate it in deno. If you need it you just create `tsconfig.json` like: 
```ts
{
  "compilerOptions": {
    "emitDecoratorMetadata": true
  }
}

```

**Comment by lucacasonato** [comment]
We are not going to enable this by default.
