### ISSUE TITLE
Native HTTP listener hangs with TLS

### ISSUE THREAD

**Issue by aegooby** [denoland/deno#10419]
Essentially the same as what's happening in #8107, but when using `Deno.listenTls()`. I noticed that issue was closed but the problem is still persisting. Every once in a while, the server will output errors like,
```
Sending fatal alert HandshakeFailure
```
or 
```
Illegal SNI hostname received [49, 53, 57, 46, 56, 57, 46, 50, 50, 46, 50, 51, 57]
Sending fatal alert DecodeError
```
Eventually after a while, the TLS listener will simply hang and will cease to receive new connections (the following loop will cease to progress),
```
const listener = Deno.listenTls(/* ... */);
for await (const connection of listener)
    /* this loop freezes */
```
This doesn't happen with a non-TLS listener (using `Deno.listen()`). I belive `std/http` has a similar problem. Previously, this would cause the server to crash completely, so at least there was a workaround in putting the server in an infinite loop to restart whenever it crashes, but since it just causes the loop to hang, this is not really an option without resorting to something much more complicated.

**Comment by rsmirnov90** [comment]
Yup, same is happening for me. I currently set my service to restart every 12 hours, but that is very problematic... 

![image](https://user-images.githubusercontent.com/3675352/116647128-d2d6d980-a947-11eb-981f-c958640b75da.png)

**Comment by lucacasonato** [comment]
You can check if resources keep accumulating with `Deno.resources()`. We are working on a rewrite of the TLS subsystem: #10146

**Comment by rsmirnov90** [comment]
> You can check if resources keep accumulating with `Deno.resources()`. We are working on a rewrite of the TLS subsystem: #10146

Thank you... Could you provide me with a safe snippet to insert into the code so that I could send you the output? This is a production app running live (and as always the issue only happens in production), but I can insert relatively-safe logging code into there during the next restart and capture the stdout/stderr output to paste here. 

We can also have a live session right on the server if you'd be interested in debugging it live... We obviously can't disrupt the app, but if you have tools to monitor it and get the info you need then I'm all for it. 

But if you guys are rewriting it anyway, then would it make more sense for us to just wait? This app is used but only during certain hours, which is why the daily restarts in the middle of the night are not a huge deal.

However, I am currently writing another API service app for a different client which is using deno as well... They (the client) wants to go live in like 2 months though. But that service will be much bigger and more high-usage (24-hour restarts wouldn't be feasible). Do you think you'll be done by then, or should we switch gears and use something else by now?**

_**PS: Btw, just wanted to make sure that this post doesn't get interpreted the wrong way!!! Deno was the thing I've only dreamt of since I started using node almost a decade ago, and I am head over heels in love with it. Please keep up the good work!!! The question I asked above is in no way intended to hint or poke at anything; it is literally just a direct line-of-business question on whether we need to use something else in the meanwhile, and if yes -- that is OK... We will still switch back to deno in the long run once it's ready. But if it will be ready before or around 2 months then we can just continue doing what we're doing now because it's been a breeze so far._

**Comment by aegooby** [comment]
> You can check if resources keep accumulating with `Deno.resources()`. We are working on a rewrite of the TLS subsystem: #10146

Aside from accumulation, I noticed that instead of selecting the lowest available `rid`, the values just keep increasing. I don't know if this would cause overflow or not but maybe this is connected to the issue. Either way, it seems like that PR should fix things. I do share similar concerns to @rsmirnov90 since I am running a production app that occasionally goes down because of this. The workaround I am currently thinking of is running my server in a looping subprocess, along with an async fetching loop that will close the server and reopen it once the requests time out if the server hangs. Definitely doable but it's pretty hellish. If that TLS rework is a long way away then let me know so I can set up this workaround for now.

**Comment by lucacasonato** [comment]
The rid increasing is not an issue. What is an issue is if resource counts keep growing (old resources are not being closed). Some resources need to be explicitly closed with `conn.close()`.

**Comment by aegooby** [comment]
Okay, that makes sense. So for this example here for using the Oak handler with that simple listen loop,
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

const listener = Deno.listen({ hostname: "localhost", port: 8000 });

for await (const conn of listener) {
  (async () => {
    const requests = Deno.serveHttp(conn);
    for await (const { request, respondWith } of requests) {
      const response = await app.handle(request, conn);
      if (response) {
        respondWith(response);
      }
    }
  });
}
```
where would I need to explicitly close resources?

**Comment by lucacasonato** [comment]
`conn.close()` after the inner `for await`.

**Comment by lucacasonato** [comment]
Also like this you are blocking the accepting of more connections after the first one has been accepted. (because you are awaiting inside the outer for await loop.

**Comment by aegooby** [comment]
Oh actually I think I miswrote the example, it should be a self executing function for the inner loop. Editing it now.

**Comment by aegooby** [comment]
I have added the `conn.close()` and made sure that I am not blocking connections, but my server still hangs. Is there an ETA on when this will be fixed (TLS subsystem rewrite)?

**Comment by lucacasonato** [comment]
The rewrite landed a few weeks ago. Are you still experiencing this issue?

**Comment by bartlomieju** [comment]
Due to lack of information I'm going to close it. Feel free to reopen if the problem persists.

**Comment by nnmrts** [comment]
Please reopen, I still have this error and related ones today using oak (but the error really seems to be with deno and not oak). They just seem to happen basically randomly and don't crash the server but still spam the terminal like this:

```
Sending fatal alert HandshakeFailure
[uncaught application error]: Http - error writing a body to connection: peer is incompatible: client didn't describe signature schemes

    at async HttpConn.nextRequest (deno:ext/http/01_http.js:76:23)
    at async serve (https://deno.land/x/oak@v10.1.1/http_server_native.ts:237:34)
Http: error writing a body to connection: peer is incompatible: client didn't describe signature schemes
    at async HttpConn.nextRequest (deno:ext/http/01_http.js:76:23)
    at async serve (https://deno.land/x/oak@v10.1.1/http_server_native.ts:237:34)
```

or

```
Illegal SNI hostname received [49, 48, 52, 46, 50, 52, 56, 46, 51, 53, 46, 49, 50, 55]
Sending fatal alert DecodeError
[uncaught application error]: Http - error writing a body to connection: received corrupt message of type Handshake

    at async HttpConn.nextRequest (deno:ext/http/01_http.js:76:23)
    at async serve (https://deno.land/x/oak@v10.1.1/http_server_native.ts:237:34)
Http: error writing a body to connection: received corrupt message of type Handshake
    at async HttpConn.nextRequest (deno:ext/http/01_http.js:76:23)
    at async serve (https://deno.land/x/oak@v10.1.1/http_server_native.ts:237:34)
```

I have a very simple oak server that basically looks like this:

```js
const {
  env
} = Deno;

const options = {
  port: secure ? 443 : 80,
  secure,
  alpnProtocols: ["h2", "http/1.1"]
}

if (secure) {
  const certFile = env.get("certFile");
  const keyFile = env.get("keyFile");

  Object.assign(options, {certFile, keyFile});
}

app.listen(options);
```

If `secure` is `false` here, everything is fine, if it's `true, Deno logs error after error even though nothing is "really" broken on the website I'm serving.

I have the suspicion this isn't even an issue with Deno but who knows...🤷‍♂️

**Comment by mmastrac** [comment]
`[49, 48, 52, 46, 50, 52, 56, 46, 51, 53, 46, 49, 50, 55]` = `104.248.35.127`

I believe that this was fixed with the rustls upgrade a while back which allowed for TLS with IP addresses as common names. Closing for now, but please reopen if it reoccurs.
