### ISSUE TITLE
re-enable test "integration::file_watcher::test_watch"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#10552]
Disabled in https://github.com/denoland/deno/pull/10550 because of flakiness on Windows

https://github.com/denoland/deno/pull/10481/checks?check_run_id=2543043090
https://github.com/denoland/deno/runs/2542717077

CC @Liamolucko

**Comment by bartlomieju** [comment]
Disabling altogether because very flaky: https://github.com/denoland/deno/pull/10594

https://github.com/denoland/deno/runs/2556975703

**Comment by Liamolucko** [comment]
I think some of them are being caused by situations like this:
```
Watcher Test finished. Restarting on file change...
Watcher File change detected! Restarting!
Watcher File change detected! Restarting!
running 1 test from file:///home/liam/src/playground/a_test.js
test a_273 ... ok (2ms)

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (25ms)

running 1 test from file:///home/liam/src/playground/a_test.js
test a_273 ... ok (3ms)
running 1 test from file:///home/liam/src/playground/b_test.js
test b_273 ... ok (3ms)

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (40ms)
```

The debounce happens to check for changed files right between two files being changed, leading to the output being unexpected.

That doesn't explain https://github.com/denoland/deno/runs/2556975703 though, because the only time multiple files are changed at once are when the first four files are added.

**Comment by ry** [comment]
this was already re-enabled
