### ISSUE TITLE
Unable to ignore deno(deno-warn) warns in VSCode

### ISSUE THREAD

**Issue by Hunam6** [denoland/deno#10822]
`Implicitly using latest version (v0.1.9-alpha) for https://deno.land/x/deno_dom/deno-dom-wasm.tsdeno(deno-warn)`

Example:
![image](https://user-images.githubusercontent.com/38606542/120510026-53667b00-c3c9-11eb-9293-01c80f69b780.png)

**Comment by kitsonk** [comment]
This is working as designed.  There is no way to ignore it, it is a warning that you are implicitly using a version which is risky. You are welcome to ignore the warning.

**Comment by martin-braun** [comment]
@kitsonk There should be a quick-fix available to convert it to the latest version, automatically. Also, I think there should be a way to ignore warnings (i.e. on next line using a comment), for the people who prefer to load the most recent version. Yes it's risky, but it's not your choice to decide if it's right or wrong. The warning makes it clear enough.

Please rethink your choice on this issue. Thank you in advance.

**Comment by Hunam6** [comment]
> @kitsonk There should be a quick-fix available to convert it to the latest version, automatically. Also, I think there should be a way to ignore warnings (i.e. on next line using a comment), for the people who prefer to load the most recent version. Yes it's risky, but it's not your choice to decide if it's right or wrong. The warning makes it clear enough.
> 
> Please rethink your choice on this issue. Thank you in advance.

I agree, I like "the warning makes it clear enough".

**Comment by johnschult** [comment]
You get the same warning for standard libs, which is understandable since they are just URLs being imported, however, it's fairly standard practice to import standard libraries using the latest version isn't it? Having a quick fix option to ignore the rule for the file or line would be a nice addition to the extension.

Alternately, and maybe not the best idea, would be to not run that rule for standard lib imports. Does the linter accept that kind of specific exception?

<img width="1051" alt="Screen Shot 2021-11-01 at 6 13 50 AM" src="https://user-images.githubusercontent.com/9453/139656663-484f55fc-4032-496f-a6ab-f235b711b8a4.png">

**Comment by lucacasonato** [comment]
> however, it's fairly standard practice to import standard libraries using the latest version isn't it?

Not really. All imports should always be versioned.

**Comment by bartlomieju** [comment]
@johnschult it is not recommended to use latest version of standard library. It is still unstable and breaking changes are happening between versions.

**Comment by kitsonk** [comment]
> @johnschult it is not recommended to use latest version of standard library. It is still unstable and breaking changes are happening between versions.

Actually, not correct. `https://deno.land/std/` will always pull from the latest tag, which does not change between releases, but as @lucacasonato it is still recommended to use the version of `std` that is fixed and that the code is tested against.

**Comment by johnschult** [comment]
@kitsonk Thanks for the pointer 😄

**Comment by l-cornelius-dol** [comment]
FWIW, I also deeply disagree with this. I have developer tools that I wish to use the latest std library version without having to constantly update their source to specify that. @kitsonk is perfectly correct; there may be considerations but it ought to be our choice when to do this, not yours. Otherwise all code files in VSCode get highlighted as having "problems" which are problems, but a deliberate choice.

Respectfully, please reconsider.
