### ISSUE TITLE
Use typescript::Config::no_empty_export from SWC

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#10868]
SWC has now [`no_empty_export` option](https://rustdoc.swc.rs/swc_ecma_transforms_typescript/strip/struct.Config.html#structfield.no_empty_export) that automatically adds `export {}` statements to preserve module context. We should use this option instead of manually adding `export {}` in various places.

Temporarily set to `true` in https://github.com/denoland/deno/pull/10867

CC @kitsonk @caspervonb

**Comment by kitsonk** [comment]
@bartlomieju sounds good to me.

**Comment by caspervonb** [comment]
> SWC has now [`no_empty_export` option](https://rustdoc.swc.rs/swc_ecma_transforms_typescript/strip/struct.Config.html#structfield.no_empty_export) that automatically adds `export {}` statements to preserve module context. We should use this option instead of manually adding `export {}` in various places.
> 
> Temporarily set to `true` in #10867
> 
> CC @kitsonk @caspervonb

SGTM @bartlomieju! Makes source generation cleaner.

**Comment by nayeemrmn** [comment]
@bartlomieju We add `export {};` in https://github.com/denoland/deno/blob/3b220c64f615a4e18346e8a1c07ad7b1aae9fcc6/cli/tools/test_runner.rs#L380 to typescript code so tsc knows that these are supposed to be modules, because tsc infers between scripts and modules based on syntax usage. Code transpiled by swc is not fed to tsc, what would be the reason to have `export {};` in the emits?

This [change](https://github.com/swc-project/swc/issues/1698) was made in swc to match tsc, which probably tries to ensure that emitted code will have the same properties if it was passed as input again. But we're better off keeping `no_empty_export: true` since all emitted code is consumed in module context no matter what.

**Comment by bartlomieju** [comment]
@nayeemrmn thanks for pointing this out - indeed it seems to provide compatiblity with TSC but doesn't solve the main issue which is requiring adding `export {};` manually to inform TSC we're in a module. 

I guess this is a TypeScript issue and we can't solve it.
