### ISSUE TITLE
deno fmt - Incremental formatting backed by a cache

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#10906]
I was thinking we could speed up `deno fmt` by having it backed by a single file of formatted file hashes (stored behind the scenes in the deno user data directory).

So you have the deno fmt cache that stores the version of deno that just ran deno fmt along with a bunch of formatted file hashes in it limited to the X most recent hashes. If the hash of the file appears in the cache then it doesn't need to be formatted again.

This has the negative of being slightly slower on the first run, but in dprint I do something similar and haven't noticed much of a slowdown on the first run compared to not having incremental (it's using https://crates.io/crates/twox-hash to do the hashing). A huge advantage is that most runs will complete almost instantaenously.

**Comment by MarkTiedemann** [comment]
An alternative to storing the hash of the formatted file in a text file would be to store it in an extended file attribute of the formatted file.

Previously, I have used this technique with timestamps rather than hashes for performance reasons. Rather than store a hash of the file, I'd store the timestamp when it was last formatted in an extended file attribute. Then, before formatting the file, I'd compare the last modified timestamp with the last formatted time stamp to see whether it needed to be formatted again or not.

**Comment by kitsonk** [comment]
The advantage of hashes are that they are a lot more accurate that mtime.  Just because a file has been touched it doesn't mean it has been modified.

There are a few places where we use hashes (lockfile, cache invalidation, language server managing non-open editor files, tsc incremental build detection) so it feels to me that there is no specific advantage to using mtime and we use hashes elsewhere that if twox-hash is "better" than our other hash that we would want to consolidate all of that an look at how we could incorporate something throughout the stack.

**Comment by MarkTiedemann** [comment]
> The advantage of hashes are that they are a lot more accurate that mtime. Just because a file has been touched it doesn't mean it has been modified.

The advantage of using timestamps is that the lookup of both modification and formatting time is essentially constant so, contrary to hashing, it doesn't matter how large the files are. So it may (or may not) be faster to unnecessarily format the few files that have been touched but not modified rather than to calculate the hashes for all files.

Last time, I implemented this for a codebase of ~3k files a couple of years ago, it was much faster to use timestamps rather than hashes even with a few files that were formatted unnecessarily.

It should be rather simple to write benchmarks for this.

> There are a few places where we use hashes (lockfile, cache invalidation, language server managing non-open editor files, tsc incremental build detection) so it feels to me that there is no specific advantage to using mtime

Fair point.

I also don't think extended file attributes are used in Deno (yet).

**Comment by dsherret** [comment]
One important note I should make is that [xxHash](https://github.com/Cyan4973/xxHash) is not cryptographically secure. It's built for speed so works well in this use case. Not sure if we have another cryptographically insecure hashing algorithm, but we could use whatever that is instead.

> Last time, I implemented this for a codebase of ~3k files a couple of years ago, it was much faster to use timestamps rather than hashes even with a few files that were formatted unnecessarily.

I think the difference is only going to be a few hundred milliseconds in most code bases. I've found incremental in dprint using hashes to be pretty fast.

> An alternative to storing the hash of the formatted file in a text file would be to store it in an extended file attribute of the formatted file.

Interesting idea! Not sure how I feel about adding these being added to every file that happens to be formatted though... I like how when you delete the deno cache directory then everything goes away.

**Comment by lucacasonato** [comment]
Also somewhat related, we have been discussing using SQLite for storing metadata info like this in DENO_DIR for a while now. It is already in the deps now, so if there is interest we could use it for this. Good chance it will be slower than a simple line delimited file though if the only thing we are storing are hashes. If there is other metadata though, it might make more sense.

**Comment by dsherret** [comment]
After thinking about this more, I don't think we should do it. `deno fmt` is already really fast and the double format issue might cause problems (double format issue is when there's a bug in deno fmt where it takes 2 or more formats to actually format a file). There's also some added complexity with making this work with configuration.

**Comment by dsherret** [comment]
Actually, I recently implemented a way to handle this in dprint where it will format a file twice if the file changed while formatting with incremental. This is still really fast and prevents an unstable file from ending up in the incremental cache. We could do the same.
