### ISSUE TITLE
lsp: deno/virtualTextDocument: inform clients what Language ID to apply

### ISSUE THREAD

**Issue by rwols** [denoland/deno#10928]
Currently the `deno/virtualTextDocument` request provides content for `deno:` schemes but it doesn't inform the client what Language ID to apply (aka what syntax). Currently I'm using TSX as that seems to be a catch-all for all possible language constructs that deno supports but it isn't precise.

**Comment by kitsonk** [comment]
Up to this point we have left it up to the client because [Virtual Documents](https://code.visualstudio.com/api/extension-guides/virtual-documents) in vscode apply the same file type detection as if they were local files (based on extension).  The LSP mangles the "real" specifier to have an appropriate extension.

Would having and explicit `"javascript", "javascriptreact", "typescript", "typescriptreact"` help other clients?  For vscode, there is no way I am aware of, of asserting that.  You only have a provider which "responds" to URIs that match your custom scheme providing content and you can send events that the document has changed.

**Comment by rwols** [comment]
I can extract the path component from the `deno:` URI and deduce what syntax to apply based on that. Is that a reliable method that won't change in the future? Will there ever be a time when URI fragments or URI query params start to matter? (I don't think so ;) but who knows)

**Comment by kitsonk** [comment]
I would never say never, but the feature is based off virtual documents from VSCode and the only way to ensure VSCode applies the right language syntax is to provide an appropriate extension, therefore the LSP ensures that the provided URI is mapped back to a unique resource in the LSP accounting for querystrings and the like.

I will make it more clear in the LSP documentation that this is intentional behaviour. If VSCode ever allowed asserting the language of a virtual document, we would likely want to add it and not make parsing the URI extension required.

Saying that there is no harm in providing a language ID, it just wouldn't be usable by the vscode client. If it is easier to write other clients with that provided I am more than willing to add it.
