### ISSUE TITLE
Bug: typechecker runs every time when stable and unstable scripts share a dependency

### ISSUE THREAD

**Issue by drmercer** [denoland/deno#11088]
When you have two scripts that depend on a module, and one script is run with `--unstable` but the other script is not, then the cache for one of them gets in a weird state where Deno has to typecheck it every time you run it. This is annoying and seems like a bug.

I built a small repro case here: https://github.com/drmercer/deno-cache-bug-repro

One possible solution: use a separate cache when `--unstable` flag is given. This would have some downsides, but since `--unstable` affects how the contents of the cache are generated, it seems appropriate.

**Comment by kitsonk** [comment]
Initially I thought it was working as intended, but in fact what appears to be occurring is a bit different.

A more concise reproduction:

**dependency.ts**

```ts
export const a = "a";
```

**stable.ts**

```ts
import { a } from "./dependency.ts";

console.log(a);
```

**unstable.ts**

```ts
import { a } from "./dependency.ts";

console.log(a);
```

```
> deno run stable.ts
Check file:///stable.ts
a

> deno run --unstable unstable.ts
Check file:///stable.ts
a

> deno run stable.ts
Check file:///stable.ts
a

> deno run --unstable unstable.ts
a

```

`stable.ts` will always be type checked, which is what is the undesired behaviour.

**Comment by drmercer** [comment]
For whatever it's worth, I think whichever one is run first is the one that ends up always type checked. E.g. in your repro, stable and unstable could be swapped and unstable would end up with the undesired behavior. (Although maybe it's not a problem if that behavior happens when `--unstable` is used? I realized that after opening the ticket.)

**Comment by kitsonk** [comment]
Looking at the debug logs, it appears that we send the program for type checking, because we think something has changed and `tsc` reads the `deno:///.tsbuildinfo` and notices that nothing has changed and so it doesn't emit anything, which means we don't update the cache to indicate that it shouldn't be further typed checked.

Feels like we have a logic error in determining if we need to type check a program.  We only care about if the root module was type checked with the same settings, not a transitory dependency.  For transitory dependency, we only care if its content was modified.

Possibly also, when we send something into `tsc` to type check and it doesn't emit anything, we should either either remove the `.tsbuildinfo` from the cache or mark it is "good" in some fashion.

**Comment by lucacasonato** [comment]
We do not have seperate unstable types anymore, so this is now resolved.
