### ISSUE TITLE
The TypeScript signature for the URL constructor only accepts strings

### ISSUE THREAD

**Issue by metanomial** [denoland/deno#11149]
The Typescript signature for the URL constructor should accept anything that can be coerced to a string.

**example.js**
```js
const url = new URL("https://example.com");
const url2 = new URL(url); // No problem
```

**example.ts**
```ts
const url = new URL("https://example.com");
const url2 = new URL(url); // [Error]: Argument of type 'URL' is not assignable to parameter of type 'string'.
```

The [definition of the URL constructor](https://url.spec.whatwg.org/#constructors) in the URL Standard doesn't directly give the type of "url", but the [definition of the URL parser](https://url.spec.whatwg.org/#concept-basic-url-parser) accepts a string. In practice, however, browsers allow passing any stringifiable object.

**Comment by CrimsonCodes0** [comment]
You seem to have a misunderstanding of how either, the HTML spec typings work, or TypeScript works. The WebIDL type signature declares the types that the input should be converted to for usage within the spec algorithms. TypeScript tries to prevent passing incorrect types of values they shouldn't be; in this case, that would be the `URL` constructor. If TypeScript allowed one to pass around values of any type, then it would be no better than plain JavaScript.

If you find that Deno's implementation fails to convert a type correctly in any of its APIs, then raising an issue about it would get it fixed.

**Comment by kitsonk** [comment]
There are a lot of APIs that take advantage of JavaScript implicit coercion. One of the main advantages of TypeScript is that it can avoid errors around implicit coercion and require explicit coercion. Weakening the types to accommodate implicit coercion is a "bad" idea and not one we should consider.

If the `lib.dom.d.ts` typing that ship with TypeScript varied from our definition, we would consider changing them. It doesn't.

**Comment by trgwii** [comment]
This will probably change reasonably soon.
TypeScript 4.3 uses [`@types/web (aka lib.dom.d.ts) 0.0.1`](https://github.com/microsoft/TypeScript-DOM-lib-generator#typeslib-to-typescript-versions)
And TypeScript 4.4 Beta uses `0.0.2` for the time being (it may upgrade before 4.4 releases)

But in the latest release of `@types/web` (`0.0.15`) the URL type changed to this:
```ts
declare var URL: {
    prototype: URL;
    new(url: string | URL, base?: string | URL): URL;
    createObjectURL(object: any): string;
    revokeObjectURL(url: string): void;
};
```
( https://cdn.jsdelivr.net/npm/@types/web@0.0.15/index.d.ts )

Allowing `string | URL` as the first parameter. So Deno could probably change this whenever it updates to a future TypeScript version that includes this change (or jump the gun since this is a non-breaking change).

## If anyone is reading this issue in the future
.. and TypeScript 4.4 or later has been released and does NOT error on `new URL(new URL('http://example.com'))` when provided with `"lib": [ "DOM" ]` ([playground](https://www.typescriptlang.org/play?#code/HYUw7gBAqgSgMgClJWiDkALALlgDgLgHpCQAPAQwFtcAbEAOgGMB7StASnaA)), please add a comment so we can implement the same change in Deno.
