### ISSUE TITLE
Implement direct sockets

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#11151]
Links: 
 - https://github.com/WICG/raw-sockets
 - https://docs.google.com/document/d/1CRERH0H68BsbgKvf9OQAWPb8CjWaKQuip2h5CMu7bk0
 - https://wicg.github.io/raw-sockets/

**Comment by crowlKats** [comment]
Not a fan:
- a modern API that uses blobs
- the spec doesn't cover implementation steps, only interfaces (and that not even extensively); same as WebSocketStream and that's just makes it extremely difficult to implement while trying to stay conformant to the spec
- we would have both `Deno.listenDatagram` and `openUDPSocket` because the latter is only a "client". Sure we could ignore that aspect and just fully support udp, but eh.

**Comment by caspervonb** [comment]
> Not a fan:
> 
> * a modern API that uses blobs instead of uint8array/arraybuffer
> * the spec doesn't cover implementation steps, only interfaces (and that not even extensively); same as WebSocketStream and that's just makes it extremely difficult to implement while trying to stay conformant to the spec
> * we would have both `Deno.listenDatagram` and `openUDPSocket` because the latter is only a "client". Sure we could ignore that aspect and just fully support udp, but eh.

Agreed, but this is a young specification that still has interest from at-least one person from Chrome and we are in a position to guide it as one of the two implementors.
