### ISSUE TITLE
lsp: an unexpected specifier (deno:...) was provided

### ISSUE THREAD

**Issue by rwols** [denoland/deno#11232]
We're slowly moving towards more general URI handling. One of those steps is to attach language servers to virtual views. The virtual view provided by the `deno/virtualTextDocument` request supposedly has URIs like `deno:/https/deno.land/std/http/server.ts`.

However, the server doesn't understand these URIs:

```
:: --> Deno textDocument/hover(5): {'position': {'character': 18, 'line': 298}, 'textDocument': {'uri': 'deno:/https/deno.land/std/http/server.ts'}}
:: --> Deno textDocument/codeAction(6): {'range': {'start': {'character': 18, 'line': 298}, 'end': {'character': 18, 'line': 298}}, 'context': {'diagnostics': []}, 'textDocument': {'uri': 'deno:/https/deno.land/std/http/server.ts'}}
:: <~~ Deno 5: {'code': -32602, 'message': 'An unexpected specifier (deno:/https/deno.land/std/http/server.ts) was provided.'}
:: <<< Deno 6: None
```

If an URI like `deno:/https/deno.land/std/http/server.ts` that is supposed to be provided to `deno/virtualTextDocument` is not the expected URI, then what is?

**Comment by rwols** [comment]
Note that this vscode client does register for deno schemes here:

https://github.com/denoland/vscode_deno/blob/6bf04545b39903ab6ed1eab599b10f5f5c56887f/client/src/extension.ts#L151-L154

**Comment by rwols** [comment]
It seems to fail at https://github.com/denoland/deno/blob/d4de477ef903e2e47c6427e14f0fe543106b1297/cli/lsp/language_server.rs#L226

That seems to be due to Sublime Text restarting with the virtual view, but then we haven't called `deno/virtualTextDocument` yet.

If you open the virtual view with a fresh session via goto-def, say, then `deno/virtualTextDocument` is called and subsequently things are working correctly.

Is it the job of the client, when restarting the editor from a previous session, to call `deno/virtualTextDocument` for all virtual views that were part of the previous session?

**Comment by kitsonk** [comment]
Within the server, we deal with unmodified URLs which we convert to and from strings for the LSP.  It seems that vscode only allowed special custom schemes to handle non-`file` schemes, so we used `deno`.  When a virtual text document is request, it "opens" the document and we analyze it and make it available for things like tsc to be able to type check.  When we restart we obviously lose that state and didn't anticipate a client requesting to get information on something that wasn't previously "opened".

I think we can modify the logic to try to resolve and "missing" `deno:` files and populate that state so that clients don't have to request the virtual text document.
