### ISSUE TITLE
ReadableStream async iterator behaviour is not spec compliant

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11253]
We have many WPT failures for this: https://wpt.fyi/results/streams/readable-streams/async-iterator.any.html?label=master&label=experimental&product=chrome&product=deno&product=firefox&product=safari&aligned&q=streams

**Comment by andreubotella** [comment]
This happens because some of the async iterator promises are not resolving because of a failed assertion. This is bad because, although when run on the main thread, the test runner will exit before the rest of tests are done, and that will be marked as a failure – when run on a worker, the test runner will hang forever.

Changing the definition of `uponPromise` to only perform `PromisePrototypeThen(promise, onFulfilled, onRejected)` makes those promises reject, which prevents the worker tests from hanging, but it introduces new failures in piping-related tests.
