### ISSUE TITLE
Is there Deno VM like NodeJS.vm ?

### ISSUE THREAD

**Issue by skaneprime** [denoland/deno#11267]
Hi! In NodeJS there was module "vm" which allowed you to run untrusted code in new context 
The one limit was that you couldn't run TYPESCRIPT code in NodeJS's vm

But I didn't find any of that in Deno. Is there a way to run untrusted TYPESCRIPT code in Deno with a context?

**Comment by lucacasonato** [comment]
The "vm" module in Node can **not** be used to run untrusted code. **It is not a security mechanism!** Let me repeat,

## The "vm" module in Node is NOT a security mechanism! Do not use it to run untrusted code! If you do this in production, shut down the server right now.

Read the first line in the Node.js docs: https://nodejs.org/api/vm.html#vm_vm_executing_javascript

---

Deno can run untrusted code in [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) if you constrain their permissions. They make for a more adequate sandbox. With just web workers you might be vulnerable to in process timing attacks. To prevent this, use deno subprocesses instead of workers.
