### ISSUE TITLE
Throwing DOMException in `deno run` will error without information

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#11451]
This doesn't happen in REPL, only in run

<img width="366" alt="Screenshot 2021-07-19 at 16 43 31" src="https://user-images.githubusercontent.com/13135287/126178719-481df994-32a4-40d8-b1b1-3225d463834a.png">

**Comment by nayeemrmn** [comment]
This is happening because the condition in https://github.com/denoland/deno/blob/02b23e057561f11daf004b4ed8d455081dbeac65/core/error.rs#L192 is returning false, it's a V8 binding. Seems we can fix it by re-adding `extends Error` to the `DOMException` declaration (removed in #11259). @lucacasonato would there be a compat problem with this?

**Comment by lucacasonato** [comment]
Yes - `DOMException` is not really an error. Try `DOMException instanceof Error` in Chrome or FF. We might need to make `DOMException` a native binding then.

**Comment by nayeemrmn** [comment]
@lucacasonato I think you meant `new DOMException() instanceof Error`, which is true in both browsers and currently in Deno from setting the prototype.

On second thought, it would be ideal to upstream a fix to V8 so that `exception.is_native_error()` uses similar logic.

**Comment by lucacasonato** [comment]
Oh right... my bad.
