### ISSUE TITLE
feature requests(lsp): Fallback on invalid languageId

### ISSUE THREAD

**Issue by ayame113** [denoland/deno#11521]
Currently, the only valid `languageId` for "textDocument/didOpen" requests are "javascript", "javascriptreact", "typescript", "typescriptreact", "json", "jsonc", and "markdown".
LSP's TypeScript diagnostics are also displayed when an invalid `languageId` (eg "github markdown") is passed.

How about hiding TypeScript diagnostics or throwing an error if the `languageId` is invalid?

**Comment by kitsonk** [comment]
A client shouldn't send a language ID that is supported by the Deno language server.  Sadly the protocol does not provide for indicating what languages are supported.

I will make it clearer in the documentation what language IDs are supported. Also need to check that our determination of if we should return diagnostics for a file is correct when dealing with an unknown language id.

**Comment by jaydenseric** [comment]
The [Nova](https://nova.app) text editor for mac utilizes the LSP but unfortunately for some languages it uses different syntax identifiers than is [standard for LSP](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocumentItem):

- `jsx` vs `javascriptreact`
- `tsx` vs `typescriptreact`

The Deno language server only understands the standard ones, and errors at initialization when you use `jsx` or `tsx`. This makes it difficult for us to make Deno extensions for Nova.

I've [reported the problem in the Nova dev form](https://devforum.nova.app/t/how-to-workaround-nova-syntax-ids-differing-with-a-language-server/1100), but I really doubt Nova would change the syntax identifiers their ecosystem is build around at this point. I suggested that instead of both Nova and the language server using the same syntax identifiers, the Nova [`LanguageClient`](https://docs.nova.app/api-reference/language-client/#constructoridentifier-name-serveroptions-clientoptions) constructor option `syntaxes` should be changed to an object with keys and values that map Nova syntax identifiers to language server identifiers. Nova has a very small team of devs (only 1 full time at the moment) so this feature request might take a long time to be implemented, if ever.

`javascriptreact` and `typescriptreact` are pretty gross identifiers as people use JSX and TSX in non-React projects, so I can see other editors in the future using the more semantically correct (although non-standard) `jsx` and `tsx`.

Would Deno consider supporting the `jsx` and `tsx` identifiers out of the box as aliases for `javascriptreact` and `typescriptreact`?

If not, how about allowing syntax identifier aliases to be a configuration option?

**Comment by kitsonk** [comment]
I will try to take care of this issue today.
