### ISSUE TITLE
Deno.upgradeWebSocket unstable API is in the wrong place

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#11538]
Currently `Deno.upgradeWebSocket` is defined in https://github.com/denoland/deno/blob/main/extensions/http/lib.deno_http.unstable.d.ts while `Deno.serveHttp` is defined in https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L1119

Consequently the API doesn't show up in the https://doc.deno.land/builtin/unstable

**Comment by nayeemrmn** [comment]
While it probably wasn't intentional to have these two in different files, both of those locations should be valid. What we should do is upload the output of `deno types --unstable` to https://doc-proxy.deno.dev/builtin/unstable on release and have https://doc.deno.land/builtin/unstable render that instead of https://raw.githubusercontent.com/denoland/deno/main/cli/dts/lib.deno.unstable.d.ts. Then it would match https://doc.deno.land/builtin/stable -> https://doc-proxy.deno.dev/builtin/stable.
