### ISSUE TITLE
Some LSP clients don't support disabled code actions

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#11610]
```
deno 1.12.2+02c74fb (canary, x86_64-unknown-linux-gnu)
```
In Neovim 0.5 using the built in LSP and the standard Deno config from https://github.com/neovim/nvim-lspconfig/ , every line of TypeScript code triggers a code action alert, including spaces and comments. When you trigger the code action you get:
```
Code Actions:                                                                                                                                                                           
1. Extract function
2. Extract constant
3. Convert default export to named export
4. Convert named export to default export
5. Convert namespace import to named imports
Type number and <Enter> or click with the mouse (q or empty cancels):
```
and whatever you press it crashes.

Deno LSP worked perfectly until this update. Is this a bug in the Deno LSP, or do the settings in the Neovim config need updating?

https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/denols.lua

@kitagry Maybe you could have a look? Thanks!

**Comment by kitsonk** [comment]
We are following the language server protocol: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction

In particular, we are sending the refactorings disabled, as per the protocol:

```ts
export interface CodeAction {
        /**
	 * Marks that the code action cannot currently be applied.
	 *
	 * Clients should follow the following guidelines regarding disabled code
	 * actions:
	 *
	 * - Disabled code actions are not shown in automatic lightbulbs code
	 *   action menus.
	 *
	 * - Disabled actions are shown as faded out in the code action menu when
	 *   the user request a more specific type of code action, such as
	 *   refactorings.
	 *
	 * - If the user has a keybinding that auto applies a code action and only
	 *   a disabled code actions are returned, the client should show the user
	 *   an error message with `reason` in the editor.
	 *
	 * @since 3.16.0
	 */
	disabled?: {

		/**
		 * Human readable description of why the code action is currently
		 * disabled.
		 *
		 * This is displayed in the code actions UI.
		 */
		reason: string;
	};
}
```

Though maybe the client doesn't support the 3.16 protocol.  Which really limits a few things.  I think we might want to check that clients have the support for disabled:

```ts
export interface CodeActionClientCapabilities {
	/**
	 * Whether the client supports resolving additional code action
	 * properties via a separate `codeAction/resolve` request.
	 *
	 * @since 3.16.0
	 */
	resolveSupport?: {
		/**
		 * The properties that a client can resolve lazily.
		 */
		properties: string[];
	};
}
```

But if the client doesn't support the 3.16 protocol, it also shouldn't support code action resolvers, which is a bigger problem, because that is a big performance win.

Whomever is maintaining the lsp client should advise on their support for the 3.16 protocol and in particular disabled support on code actions.

**Comment by David-Else** [comment]
@mjlbach Please could you comment on the above post and Neovim's support for the 3.16 protocol and in particular disabled support on code actions?

**Comment by mjlbach** [comment]
We support some (most?) of 3.16. I don't use code actions myself, and probably will not implement any features related to them but will review/accept PRs. We do not have support for disabled code actions or `codeAction/resolve` currently.

**Comment by kitsonk** [comment]
For context, a lack of support `codeAction/resolve` means that some code actions from tsc are likely broken, as it gives the opportunity for the server to identify specific locations where a code fix applies without having to calculate all the changes until the code action resolves.  To work around a lack of client support for `codeAction/resolve` is non-trivial and not something that I would like to consider. (Also, there were a few things that added _resolve_ methods to the LSP in 3.16, and the Deno language server just assumes they are supported without specifically checking the client capabilities).

As for a lack of the disabled support, it is just a matter of filtering out disabled code actions before they are sent back to the client, so I am going to raise a PR in a few minutes that addresses that.

**Comment by David-Else** [comment]
Neovim LSP works again, thanks!

**Comment by David-Else** [comment]
Just tried deno 1.13.

While the disabled code actions problem is fixed, the refactoring options in Neovim unfortunately don't work properly, but that seems expected at this point. They all appear as expected, but when you run them you get:

```
Error executing vim.schedule lua callback: ...nt_nvimPgykEF/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:458: command: ex
pected string, got nil
stack traceback:
        ...nt_nvimPgykEF/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:458: in function 'execute_command'
        ...imPgykEF/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:142: in function 'handler'
        ....mount_nvimPgykEF/usr/share/nvim/runtime/lua/vim/lsp.lua:897: in function 'cb'
        vim.lua:277: in function <vim.lua:277>
```
![Screenshot from 2021-08-10 20-52-06](https://user-images.githubusercontent.com/12832280/128926341-5829306b-ebd1-4b34-862e-ae6a147ae080.png)

**Comment by kitsonk** [comment]
Yes, this is because the client does not support `codeAction/resolve`.  At this point in time, I don't think it is advisable to degrade to support clients that do not support this as it is a big performance challenge, as the refactor has to be fully calculated before sending the code action to the client.  The way the TypeScript language server behind the scenes is built is to support this two step process.

The best solution is to get the client to support `codeAction/resolve`.
