### ISSUE TITLE
Revoking a blob url after creating a `Request` should still fetch successfully

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#11817]
Failing WPT is "Revoke blob URL after creating Request, will fetch" from wpt/FileAPI/url/url-with-fetch.any.html.

**Comment by lucacasonato** [comment]
Looked into this. It's magical as usual.

@andreubotella found the following that explains the behaviour:

> The URL parser sets the url's "blob URL entry" at the time of parsing (https://url.spec.whatwg.org/#url-parsing step 4)

We can't implement this as specified because for us URLs are just strings, with no way to attach for example a blob to track GC.

**Comment by bartlomieju** [comment]
> We can't implement this as specified because for us URLs are just strings, with no way to attach for example a blob to track GC.

Can you elaborate on this part?

**Comment by kitsonk** [comment]
I believe that up until the point where we actually start reading the blob as part of the body, we only hold onto the URL specifier for the blob (a string GUID).  So when we revoke the string GUID, we can no longer access the content of the blob.  It would require having an opaque handle/rid to the contents of the blob that has been revoked.

The only solution I can think of @lucacasonato would be some sort of weakref to the blob content that is owned by the response and that we do the cleanup on the Rust side on deref.

**Comment by andreubotella** [comment]
I've been looking into how blobs and blob parts are implemented on the Rust side, and it seems like we could add an `op_blob_from_object_url` op that returns a blob's MIME type and uuid's. If some of those blob parts already existed on the `BlobStore`, the uuid's returned would be new, so the `BlobReference`s being GC'd can't invalidate other blobs. The resulting `Blob` could then be stored in the inner request, and used during fetching. When the `Request` gets GC'd, so do the `BlobReference`s.

**Comment by andreubotella** [comment]
I've been looking through other things we implement that are built on fetch at the spec level, and it seems like all of them behave in the same way with blob URLs: the blob is resolved synchronously when the API is called, so that revoking the object URL immediately afterwards will not affect the result.

Affected APIs are:

- `new Worker(blobUrl)`, for both classic and module workers. [(WPT test)](https://github.com/web-platform-tests/wpt/blob/master/workers/dedicated-worker-from-blob-url.window.js)
- `import(blobUrl)`. I suspect this bug also applies to non-dynamic imports, but that's harder to test. [(WPT PR)](https://github.com/web-platform-tests/wpt/pull/30381) [(WPT test)](https://github.com/web-platform-tests/wpt/blob/andreubotella/blob-url-revoke/html/semantics/scripting-1/the-script-element/module/dynamic-import/blob-url.any.js)
- Classic worker's `importScripts(blobUrl)`. We do happen to follow the spec here by chance, since we fetch all scripts before running any one of them. [(WPT PR)](https://github.com/web-platform-tests/wpt/pull/30381) [(WPT test)](https://github.com/web-platform-tests/wpt/blob/andreubotella/blob-url-revoke/workers/interfaces/WorkerUtils/importScripts/blob-url.worker.js)

The PR I'm about to open only fixes the `fetch` case – the `new Worker` and `import()` cases can be fixed as follow-ups.
