### ISSUE TITLE
lsp: support inlay hints

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11853]
TypeScript 4.4 supports [inlay hints](https://github.com/denoland/vscode_deno/issues/509) and we should support them in the LSP.

**Comment by grian32** [comment]
It might be a good thing to add support for inlay hints to Deno LSP and not add it to the VSCode extension(until that's possible), Deno LSP support is on the [WebStorm 2021.3 Roadmap](https://blog.jetbrains.com/webstorm/2021/09/webstorm-2021-3-roadmap/) and WebStorm has support for inlay hints already.

**Comment by kitsonk** [comment]
The LSP protocol doesn't support it at the moment  so I would prefer to wait until it does to add it.

**Comment by sno2** [comment]
The minimum support required has now been attained because [`lsp-types` now supports the LSP Proposed 3.17 Specification's Inlay Hints](https://github.com/gluon-lang/lsp-types/pull/231) and [`tower-lsp` allows using the proposed types with their APIs](https://github.com/ebkalderon/tower-lsp/pull/330).  It seems we are only waiting on a new release of `tower-lsp` to use these new types.

**Comment by kitsonk** [comment]
Well, and actually doing the integration... 😄  but getting closer...

**Comment by sno2** [comment]
Hello, forgot about this issue. Anyways, all of the versions have been released so we can now safely integrate inlay hints into the Deno LSP.
