### ISSUE TITLE
lsp: Ignore files that starts with other shebang

### ISSUE THREAD

**Issue by k0warite** [denoland/deno#11881]
The extension should ignore files with other shebang (for example, `!#/usr/bin/env node`) as it's set for other interpreters.
By "ignore" I mean disable the extension for that file (switch back to TS language server)

**Comment by kitsonk** [comment]
We have the infrastructure now in the language server to be able to do this I think.  Basically we would set the file as undiagnosable.  The one challenge is that we would need to reflect that back to typescript plugin so it unmutes the diagnostics from tsc.

**Comment by bartlomieju** [comment]
@kitsonk could https://github.com/denoland/deno/pull/13220 have any impact on this issue?

**Comment by kitsonk** [comment]
No. That has to do with loading/etc.  This is analysis when a document is "read"/"opened" in the LSP.

**Comment by Sleepful** [comment]
having this issue, for example:

`nvim/lsp.log`
```
[ERROR][2023-09-10 01:45:08] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/jose/.local/share/nvim/mason/bin/deno"	"stderr"	'Could not set npm package requirements. Error getting response at https://registry.npmjs.org/tailwindcss for package "tailwindcss": An npm specifier not found in cache: "tailwindcss", --cached-only is specified.\n'
```
because I have a `tailwind.config.js` file that I am _not_ using with Deno, but I need it to build my bundle.

**Comment by Sleepful** [comment]
Hi, my last comment is valid in the sense that I get the error from the LSP logs, but I think the real issue halting my deno-ls is this other issue: 
https://github.com/denoland/deno/issues/20445

Just FYI

**Comment by nayeemrmn** [comment]
We have `deno.disablePaths` now, I recommend using that instead. This is probably unfeasible because enabling/disable the built-in TS server is an expensive operation which we currently only do on config changes which affects enabled scopes, or on `deno.json` file creations. With this we'd have to start reading and watching files on the client to determine the enabled status and maybe restart the TS server each time. Also, script entrypoints are an arbitrary subset of use cases to add this convenience for, as opposed to encouraging the out-of-band setting.
