### ISSUE TITLE
Add JSON schema file for configuration file

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#11885]
Currently Deno supports configuration file for altering TypeScript compiler settings. With #11686 and #11857 we'll have more configuration options and config file will be usable with `deno lint` and `deno fmt`.

The idea is to make the configuration file strict - ie. it will not accept "unknown" fields (it will fail the parsing step if there are extraneous fields). This is to avoid the problem similar to `package.json` where random tools piggy-back on this file and add tens (or hundreds) of fields specific to each tool. 

To alleviate the problem we should introduce a [JSON schema file](http://json-schema.org/). Most IDEs already support this format and it's used widely in the wild, eg. here's [TypeScript JSON schema](http://json.schemastore.org/tsconfig) and here's [dprint JSON schema](https://github.com/dprint/dprint/blob/main/website/assets/schemas/v0.json). Additional advantage is that these schema files are versioned, which should help with making sure Deno's configuration file does not introduce breaking changes.

**Comment by dsherret** [comment]
**`$schema` Property is VSCode Specific**

For associating a config file something that is done is a [`$schema` property](https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json) that specifies a url:

https://github.com/denoland/deno/blob/b518f5e1ba4c3281d4aee4c637f410db382ce751/.dprint.json#L2

However, I would recommend against this because:

1. It is actually a VSCode specific property.
2. It is something the user needs to manually maintain.

I am going to be moving away from this in dprint soon towards something better.

**Better Solution?**

Instead I would recommend we come up with a solution where the deno binary can provide either the entire schema text or a url to the schema (for example, we could have the schema as a release artifact). Probably providing a url would be best as it will most likely be portable. For example, perhaps the deno language server could provide the JSON schema url at startup then it would be up to the editors to associate that schema with `Deno.json`.

For vscode specifically, we can provide the schema programatically in vscode-deno based on the version of `deno` the user is using with the extension (was just coincidentally told about this today while doing research for dprint https://github.com/microsoft/vscode/issues/127812).

Maybe there is a better way of doing all this with the LSP to do this though so all editors get the schema associated out of the box? I don't see a way of doing it, but I'm not super familiar with the LSP. cc @kitsonk

**Comment by bartlomieju** [comment]
Thanks for clearing that up David, I could have sworn I used JSON schema in JetBrains IDEs as well.

I'm curious to see Kitson's opinion before we decide either way.

**Comment by kitsonk** [comment]
You can associate files with a schema without using the `$schema` property. For example that is how we support suggestions/checking for import maps in vscode_deno. So we can associate a schema with `Deno.json`.

We have a JSON schema for the output of `deno info --json` that is located in the manual. We should have a schema for everything. I have started one for `deno doc --json` that will be part of `deno_doc`.

**Comment by jthegedus** [comment]
> Thanks for clearing that up David, I could have sworn I used JSON schema in JetBrains IDEs as well.

JetBrains IDEs ship a default plugin to fetch JSON schemas from 
http://www.schemastore.org/json/

VSCode handles this type of association on a per VSCode Extension basis. I believe the VSCode RedHat YAML ext is trying to be a catch all for users. I'm unaware of how VSCode handles conflicts but I often see issues with my GitHub Workflow schemas being incorrectly associated with other schemas.

Best bet is to pick either adding to schemastore or handling schema in the Deno LSP/Ext, but not both.

**Comment by David-Else** [comment]
Where do I get the current `deno.jsonc` schema? Could it be provided at [json.schemastore.org](https://www.schemastore.org/json/) like the following for the VS Code JSON language server? These can be used by other editors (in this example Neovim)

```
      schemas = {
        {
          fileMatch = { 'package.json' },
          url = 'https://json.schemastore.org/package.json',
        },
        {
          fileMatch = { 'tsconfig.json', 'tsconfig.*.json' },
          url = 'http://json.schemastore.org/tsconfig',
        },
        {
          fileMatch = { '.eslintrc.json', '.eslintrc' },
          url = 'http://json.schemastore.org/eslintrc',
        },
        {
          fileMatch = { '.prettierrc', '.prettierrc.json', 'prettier.config.json' },
          url = 'http://json.schemastore.org/prettierrc',
        },
        {
          fileMatch = { '.stylelintrc', '.stylelintrc.json', 'stylelint.config.json' },
          url = 'http://json.schemastore.org/stylelintrc',
        },
      },
```

**Comment by mary-ext** [comment]
The original schema URL (`https://deno.land/schemas/config-file.v1.json`) and the current schema URL (`https://deno.land/x/deno/cli/schemas/config-file.v1.json`) seems to lead to a 404.

The [documentation page](https://docs.deno.com/runtime/fundamentals/configuration/#json-schema) pretty much links directly to the schema file in GitHub.

is GitHub's raw URL the official way to use the JSON schema now? or is it being hosted somewhere else?

**Comment by emonadeo** [comment]
> The original schema URL (`https://deno.land/schemas/config-file.v1.json`) and the current schema URL (`https://deno.land/x/deno/cli/schemas/config-file.v1.json`) seems to lead to a 404.
> 
> The [documentation page](https://docs.deno.com/runtime/fundamentals/configuration/#json-schema) pretty much links directly to the schema file in GitHub.
> 
> is GitHub's raw URL the official way to use the JSON schema now? or is it being hosted somewhere else?

With a version specified it works:
[`https://deno.land/x/deno@v2.4.3/cli/schemas/config-file.v1.json`](https://deno.land/x/deno@v2.4.3/cli/schemas/config-file.v1.json)

But I would still probably consider a schema id url that leads to a 404 a bug.
