### ISSUE TITLE
No "good" solution to loading WASM in Deno

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#11918]
None of the patterns for loading WASM in Deno are "good" right now, as they all have their drawbacks.

- The pattern we use in `std` is that we base64 encode the web assembly and embed that in a JavaScript module that is decoded at startup using top-level await.
  - Advantages are
    - That it is cache-able in the DENO_DIR
    - It is more easily portable to other runtimes, like web browsers.
  - Disadvantages are:
    - That it is horribly inefficient, especially for large WASM payloads
    - Using TLA to bootstrap the code is blocking module loading and can often appear as "startup" delay.
- The pattern we use in `deno_graph` and `deno_doc` is that we load the web assembly via the `Deno.readFile` or via `fetch()` and then does a TLA to instantiate the module.
  - Advantages are:
    - It loads a lot quicker, even when fetching a remote module.
    - When the WASM is served up with the correct content-type it uses instantiate streaming, which is even more efficient.
  - Disadvantages:
    - It doesn't cache in the DENO_DIR, and is not "bundle-able"

The only really viable solution is that there is some form of supportable way of loading WASM modules.  @lucacasonato is working on trying to put forward something to TC39, but that may (likely) will take a long time.  Other solutions might work for Deno, but then make it not portable.  The more people use web-assembly with Deno though (and more widely) the greater this pain point will be.

**Comment by 12101111** [comment]
It's possible to cache `CompiledWasmModule`. In C++ class `v8::CompiledWasmModule`, there are 3 methods:

* `MemorySpan<const uint8_t> v8::CompiledWasmModule::GetWireBytesRef()` Get the (wasm-encoded) wire bytes that were used to compile this module. Binding in Rust: [`pub fn get_wire_bytes_ref(&self) -> &[u8]`](https://docs.rs/v8/0.33.0/v8/struct.CompiledWasmModule.html#method.get_wire_bytes_ref)
* `const std::string& v8::CompiledWasmModule::source_url()` Get the url of this wasm module. Binding in Rust: [`pub fn source_url(&self) -> &str`](https://docs.rs/v8/0.33.0/v8/struct.CompiledWasmModule.html#method.source_url)
* `OwnedBuffer v8::CompiledWasmModule::Serialize()` Serialize the compiled module. The serialized data does not include the wire bytes. We need to create Rust binding for this method.

To make the cache work, we need save the url as key and data from `v8::CompiledWasmModule::Serialize()` to `DENO_DIR`. The data from`GetWireBytesRef()` is also needed.

Also we need another 2 bindings for `v8::WasmStreaming`

* `bool SetCompiledModuleBytes (const uint8_t *bytes, size_t size)`: 

> Passes previously compiled module bytes. This must be called before {OnBytesReceived}, {Finish}, or {Abort}. Returns true if the module bytes can be used, false otherwise. The buffer passed via {bytes} and {size} is owned by the caller. If {SetCompiledModuleBytes} returns true, the buffer must remain valid until either {Finish} or {Abort} completes.

* `void v8::WasmStreaming::SetClient ( std::shared_ptr<Client> client )`

> Sets the client object that will receive streaming event notifications. This must be called before {OnBytesReceived}, {Finish}, or {Abort}.

This `Client` have a virtual method `virtual void OnModuleCompiled (CompiledWasmModule compiled_module)` and will be called after a wasm module is compiled. The client can save this compiled module using `v8::CompiledWasmModule::Serialize()`
 
When a wasm module is loaded in the first time, we can serialize the CompiledWasmModule to `DENO_DIR` in our client implement. If the wasm module is loaded again, we can check the cache, load the cached module and run `SetCompiledModuleBytes`, this logic can be happend in a new op. This new op will execute after `op_wasm_streaming_set_url` and before `op_wasm_streaming_feed` in `handleWasmStreaming`. `op_wasm_streaming_feed` is still needed even the cache is valid, because the check is happened in `WasmStreaming.finish`, See the code of https://github.com/v8/v8/blob/main/src/wasm/streaming-decoder.cc#L270

The implement of chromium is in https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/bindings/core/v8/v8_wasm_response_extensions.cc

**Comment by bartlomieju** [comment]
I'm gonna close this issue in favor of https://github.com/denoland/deno/issues/2552. I have this on my radar, but currently we're not able to implement it due to missing V8 APIs
