### ISSUE TITLE
Program doesn't stop with external library after deno v1.11.5

### ISSUE THREAD

**Issue by AndyDecker** [denoland/deno#11928]
Hey,
i'm using a deno library that uses a normal .js library [knexjs](https://knexjs.org/) . Until v1.11.5 the program did normally stop after everything is done, but in any newer version it just keeps running. Since i use the library in my test environment a simple Deno.exit() won't do the trick for me. 

Simple code example to retry:

`import { default as SQLQueryBuilder } from "https://raw.githubusercontent.com/aghussb/dex/master/mod.ts";

let queryBuilder = SQLQueryBuilder(
    {
        client: "postgres",
    },
);

console.log("done?")`

Thanks for any help,
Andy

**Comment by leizongmin** [comment]
Hi, @AndyDecker 
It seems the `@jspm/core` library use `MessageChannel` to keep the Deno process running.
https://github.com/jspm/jspm-core/blob/e11caee6cffd12176262f9219c1184248dd388f6/nodelibs/browser/timers.js#L151

```js
 } else if (global.MessageChannel) {
      // For web workers, where supported
      installMessageChannelImplementation();
}

    function installMessageChannelImplementation() {
      var channel = new MessageChannel();

      channel.port1.onmessage = function (event) {
        var handle = event.data;
        runIfPresent(handle);
      };

      registerImmediate = function (handle) {
        channel.port2.postMessage(handle);
      };
    }
```

Deno was added `MessageChannel` and `MessagePort` APIs since v1.12.0.
In v1.11.5 and early versions, the `@jspm/core` library not use `MessageChannel`, so Deno process will exit after `console.log("done?")`.

**Comment by diblex** [comment]
Hi @AndyDecker ,
I was having the same issue in my tests with Deno v1.13.0. 
However, I updated to v1.14.0 and the issue is gone.

I was able to reproduce the issue with the code you provided as well.
I hope it helps.
