### ISSUE TITLE
Support SO_REUSEADDR

### ISSUE THREAD

**Issue by ry** [denoland/deno#1195]
Because of the lack of this, many networking tests resort to using different ports.

**Comment by ry** [comment]
Feb 24, 2020: Still an issue that we want to solve.

**Comment by bartlomieju** [comment]
To implement this feature, `net2` crate should be added to dependencies and [`reuse_address`](https://docs.rs/net2/0.2.33/net2/struct.TcpBuilder.html#method.reuse_address) method should be called before creating a socket.

**Comment by attliaLin** [comment]
Is it still be an issue? Can I take it?

**Comment by bartlomieju** [comment]
Marking as good first issue. For example how to implement this see https://github.com/denoland/deno/pull/13103

**Comment by Trolloldem** [comment]
@bartlomieju I tried to add the requested feature. I decided to not use `net2` as suggested, since the library is now deprecated. 
In order to achieve the same functionality I used the `socket2` crate, which is already a dependency listed in `ext/net/Cargo.toml`.

For now I have a working unit test for `op_net_listen`, now I have to adapt the changes for the TLS version. 
In order to achieve retro compatibility, the proposed method is composed as follows:

I should be able to open a PR in the following days. But first I have a question:
```
const listener1 = Deno.listen({ hostname: "127.0.0.1", port: 3500, reuseAddress: true});
const listener2 = Deno.listen({ hostname: "192.168.1.7", port: 3500, reuseAddress: true});
```
where the `reuseAddress` field is optional and defaults to `false`.
 
- in this is issue is mentioned that  support for **SO_REUSEADDR** is needed
- this options allows the use case in which the same host has two different ip (127.0.0.1 and 192.168.1.7 for example)
- the exposed use case shows that without this feature it is necessary to use different ports
- I think that it in order to fully achieve the wanted result it is necessary to support the  **SO_REUSEPORT** option
- in this way it is possible to support the following code:
 ```
const listener1 = Deno.listen({ hostname: "127.0.0.1", port: 3500, reusePort: true});
const listener2 = Deno.listen({ hostname: "127.0.0.1", port: 3500, reusePort: true});
```
where the `reuseAddress` field is optional and defaults to `false`.

Let me know if you think that these changes could be interesting and if it is the case to open a PR to add them.

**Comment by bartlomieju** [comment]
@Trolloldem thanks for looking into this. What you described sounds good to me and the proposed API looks good. `socket2` is indeed preferable in this case.

It might be hard to test these properly, but please open a PR first and let's work from there.

**Comment by lucacasonato** [comment]
We specify SO_REUSEADDR on all sockets by default, just like Node.js and Go.
