### ISSUE TITLE
Feature request - Allow watching files outside of the module graph

### ISSUE THREAD

**Issue by bebraw** [denoland/deno#12197]
I am reading JSON files that then affect what Deno serves. The problem is that the operation is outside of Deno's module graph and the `watch` feature won't notice these type of changes.

Based on https://github.com/denoland/deno/issues/2401#issuecomment-859901801 I was thinking patterns are supported already but looking at the source (https://github.com/denoland/deno/blob/3c97dbf06bc26fc79f0f58a360ef821f75ba82e9/cli/flags.rs#L226) they are not.

Therefore I would propose adding support to `--watch=./**/*.ts,./**/*.tsx` kind of syntax (i.e. `watch` would accept a string of globs) to allow watching arbitrary files even outside of Deno's module graph.

Related to https://github.com/jurassiscripts/velociraptor/issues/80.

**Comment by bartlomieju** [comment]
> @bartlomieju let's just start with individual files and folders in the arguments to --watch, and go from there.

Sounds good to me, PRs are welcome

**Comment by bartlomieju** [comment]
For anyone interested in tackling this issue, here are some some pointers how to do it:

In `cli/flags.rs`:
- change `watch_arg()` function to accept values, and update the description that passing values has only effect on the `deno run` subcommand
- change `watch` field in `Flags` struct to accept `Option<Vec<PathBuf>>` instead of a `bool`
- in `run_parse` change parsing logic to create a vector of paths
- in other functions that parse `watch` flag they should set `watch` equal to `Some(vec![])` is "watch" flag is present

In `cli/main.rs`:
- change `run_with_watch` function to extend `paths_to_watch` with the value of vector from `Flags::watch`

Add a test to `cli/tests/integration/watcher_tests.rs` that verifies that additional files passed to the flag actually cause the process to restart.

I'm going to mark this as a "good first issue", even though it's on the harder spectrum of "first issues".

**Comment by jespertheend** [comment]
I'd like to have a go at this if that's ok!

**Comment by lucacasonato** [comment]
@jespertheend Please do! If you need some more guidance, please hop into the #dev channel on Discord: https://discord.gg/deno
