### ISSUE TITLE
Debug panic in fmt if there is a tab in a comment

### ISSUE THREAD

**Issue by espindola** [denoland/deno#12211]
I tried running fmt with a debug build on a file with a tab in it and got a debug panic. The backtrace is attached.
[fmt-backtrace.txt](https://github.com/denoland/deno/files/7227865/fmt-backtrace.txt)

**Comment by dsherret** [comment]
@espindola could you please attach the file that the debug panic occurred on? Do you mean a tab in a string literal?

**Comment by espindola** [comment]
It was a tab in a file. Sorry, "in the string" is from the dprint panic. From dprint't point of view it is a string.

**Comment by dsherret** [comment]
@espindola ok, could you please attach the file? This is a context specific panic.

**Comment by espindola** [comment]
I think it was this file, which is textproto/mod.ts

I am trying to run dprint directly on it, since I now realize this is very likely a bug in dprint't typescript plugin.

[test.ts.txt](https://github.com/denoland/deno/files/7228095/test.ts.txt)

**Comment by dsherret** [comment]
Thanks! Yeah, this occurs if there is a tab in a comment. It's not a big deal because comments aren't used for the line width calculation so this doesn't indicate a potential bug in deno fmt in release mode (as debug panics usually would).

I've opened https://github.com/dprint/dprint-plugin-typescript/issues/298 for us to track this there and I'm going to close this issue.
