### ISSUE TITLE
Add  ability to use import map in packages / modules

### ISSUE THREAD

**Issue by ElikaFilin** [denoland/deno#12213]
When we are using import map in any package(for example package A). After we want to import into package B this package A with import map usage,  Deno won't search for deps resultion in package A, it will try to search only in package B.
Therefore suggest to add feature of recursive search of import_map in package, or ability to inline into import_map in package B address of import_map of package A

**Comment by bartlomieju** [comment]
This is currently not supported by the spec and we're wary of adding non-standard features to standardized functionality.

Ref https://github.com/WICG/import-maps/issues/252 https://github.com/WICG/import-maps/issues/261

**Comment by castarco** [comment]
I believe that waiting for the standard to advance, when there's nobody working on it, is the wrong move.

I've seen people advocating for dynamic import maps, dynamic import maps generation... but the main problem can be solved mostly statically with just a few metadata annotations.

It is a real problem to handle nested dependencies when you want to publish a Deno-compatible library, and it gets even worse if you want to make it compatible with NodeJS at the same time.

Having the ability to write something like in our library files...
```typescript
// @pragma-import-map: https://import-map/path

import { whatever } from 'package-name'
```
would make wonders. Of course, the "pragma" annotation would only be applied at this level (and below) of the import tree, to avoid unexpected side effects at the nodes that live upper in the tree, closer to its root.

**Comment by kitsonk** [comment]
> I believe that waiting for the standard to advance, when there's nobody working on it, is the wrong move.

I disagree.  Almost every choice we would make could easily and likely be changed when the standard changes.  The internet is littered with "preemptive" movements let alone ones closer to home (like TypeScript decorators).  The best thing to do is advocate with the standards body to move forward.

**Comment by ahuigo** [comment]
I think every package should have a `import_map.json`.

Since we know the main package's URI(https://github.com/WICG/import-maps#packages-via-trailing-slashes). e.g. :
```
{
  "imports": {
    "moment": "/node_modules/moment/src/moment.js",
    "moment/": "/node_modules/moment/src/"
  }
}
```
Maybe，it is better use `${package}/import_map.json` as package's `import_map` path. e.g.
```
/node_modules/moment/src/import_map.json
```

**Comment by arnim279** [comment]
Is there an update on this? I also ran into this issue because both a package I imported and my current package have `lib/` as an import alias. I get that Deno wants to be as close to the standard as possible, but this behavious is really annoying and specifying scopes for every imported package and manually rewriting its import aliases is **not** the solution.

From my understanding it shouldn't be too hard to automatically generate import map scopes and the changes could easily be reverted/modified when there is an official spec.

**Comment by arnim279** [comment]
I've read a bit more about the import map spec and have some thoughts.
In my opinion, import maps only make sense as a development tool but not in production, at least if [they are supposed to be only used for applications, not libraries](https://github.com/WICG/import-maps#scope).
Why? Application authors should not have to decide which dependency at which version they have to add to make another dependency work. This is true even with proper tooling because if libraries don't have an import map or another equivalent to `package.json`, how would the tools even know which other dependencies they also have to add (without checking every single code file of the dependency)?
Maybe I'm also just missing something here.

As a development tool however, import maps seem great! If the import map is used to replace relative imports with absolute ones before publishing, developers can not only specify the exact modules they depend on (with version and source(url), not just by specifier which could be misleading) as they can with the `deps.ts`  file currently used in Deno, but they also get to specify relative paths within their module, replacing the horrendous `../../../helpers/` with `helpers/` in their source code.
Maybe Deno could implement a tool like this? I'm not really sure because of the "just being able to run it" nature of Deno, which would be degraded if this were added. The above mentioned issue with import maps would also not be solved by this, if other modules still use them, the app author would still have to add their respective dependencies.

**Comment by lucacasonato** [comment]
This is possible when using JSR: https://jsr.io/docs/publishing-packages#importing-npm-packages
