### ISSUE TITLE
Why is useDefineForClassFields non-overridable?

### ISSUE THREAD

**Issue by ondras** [denoland/deno#12393]
Hello,

the `useDefineForClassFields` TSC option is hardcoded to `true` and it is not possible to turn it off (to effectively remove value-less public class fields). Is there any particular reason why this is forbidden?

For reference, I was using this *feature* to implement flag-fields-to-class-names:

```js
class X {
  a!: boolean;
  b!: boolean;
  /* ... */
  get node(): HTMLElement;
}

["a", "b", "c", "d", "e"].forEach(name => {
  Object.defineProperty(X.prototype, name, {
    set(value) { this.node.classList.toggle(name, value) }
  }
})
```

**Comment by kitsonk** [comment]
`useDefineForClassFields` is hardcoded to `true` because it matches the behaviour of class fields as implemented in modern JavaScript versus the legacy behaviour of class fields that TypeScript implemented.  While we hard code targetting `esnext`, the `useDefineForClassFields` set to `false` causes some random diagnostic errors where the expected behaviour of classes doesn't match the runtime behaviour.  Having the TypeScript behaviour match the JavaScript behaviour is important to have reliable code, therefore why it is not allow to be adjusted.  For example:

```javascript
class A {
  a;
  b;
}

const a = new A();

console.log(Object.keys(a)); // will log [ "a", "b" ]
```

@dgreensp the inline document is an error.
