### ISSUE TITLE
REPL misinterprets expressions that start with `await Promise.resolve(...)`

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#12468]
![image](https://user-images.githubusercontent.com/218257/137625273-f39dc18f-ea14-4ae1-8243-e3967cca0276.png)

**Comment by andreubotella** [comment]
This seems to be a swc bug: `await Promise.resolve("hello") + " world"` is a single statement according to the acorn, babel and tsc parsers, and as best I can tell from the spec, but swc treats it as:

```js
await Promise.resolve("hello");
+" world";
```

The `await Promise.resolve(3) * 3` case is similar, with the difference that `* 3` is not a valid statement. For some reason, rather than failing to parse, the AST contains an invalid node that gets serialized as:

```js
await Promise.resolve(3);
<invalid> * 3;
```

@dsherret

**Comment by bartlomieju** [comment]
Still a problem in v1.21
```
Deno 1.21.0
exit using ctrl+d or close()
> await Promise.resolve(3) * 3
parse error: Expression expected at 1:26
> close()

```

**Comment by magic-akari** [comment]
```
❯ deno
Deno 1.21.2
exit using ctrl+d or close()
> async function foo() {
    return await Promise.resolve(3) * 3;
}
undefined
> foo()
Promise { 9 }
> await Promise.resolve(3) * 3
parse error: Expression expected at 1:26
> 
```

**Comment by dsherret** [comment]
Seems fixed:

```
> deno
Deno 1.24.1
exit using ctrl+d or close()
> await Promise.resolve("hello");
"hello"
> await Promise.resolve(3);
3
> await Promise.resolve("hello") + " world"
"hello world"
> await Promise.resolve(3) * 3
9
> await Promise.resolve(3) + 7
10
>
```
