### ISSUE TITLE
`eval`ing a `thow` errors with unexpected token

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#12499]
```
deno eval -p "throw Error('foo')"
error: The module's source code could not be parsed: Unexpected token `throw`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier at file:///Users/crowlkats/WebstormProjects/deno/$deno$eval.js:1:13
```

**Comment by lucacasonato** [comment]
Should we try to fix this, or let's just say working as expected?

**Comment by nayeemrmn** [comment]
I suppose instead of wrapping code in `console.log(`...`)`, we can use `eval_context()` which can capture the last evaluation. It would be run as a script but it's not like it can use static imports anyway.
```
    -p, --print
            Print the result to stdout. Note: If '-p'  is specified, the code will be run as a classic script rather than a module.
```
Or we could wait for https://github.com/tc39/proposal-do-expressions and wrap esm code in `console.log(do {`...`})`. Or both.

**Comment by crowlKats** [comment]
Closing as working as expected.
