### ISSUE TITLE
x-typescript-types not working in LSP anymore

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#12675]
Deno 1.15.3:

![image](https://user-images.githubusercontent.com/7829205/140656756-35910032-1eea-4e14-afa6-49e42c7f2737.png)

Latest Deno Canary (0f8299d011420408b9a432a2c01af387af9d5fb2)

![image](https://user-images.githubusercontent.com/7829205/140656787-4a19d0e9-fd9c-4f60-9db5-e180f910b462.png)

**Comment by kitsonk** [comment]
Working on it now.

**Comment by kitsonk** [comment]
We didn't have a test for it, and sure enough, I forgot to handle it when I refactored the code to use deno_graph. 😢 

I've got a failing test now, and should have a PR with the fix soon.

**Comment by kitsonk** [comment]
For the record, it is just the hover text.  The type checking and goto definition and the like actually work behind the scenes.  This has to do with how we properly place the value of that header in the `maybe_types_dependency` slot of the target module, instead of "bubbling" it up into the `maybe_type` slot of the importing module.  Need to reflect this in the over text though, so people know it has resolved.
