### ISSUE TITLE
HTTP hijacking (for Node WS/CONNECT, etc...)

### ISSUE THREAD

**Issue by piscisaureus** [denoland/deno#12718]

**Comment by jimmywarting** [comment]
how about something web-worker ish implementation?

```js
/** @param {FetchEvent} evt */
function handleFetch (evt) {
  const { request, respondWith } = evt
  respondWith( new Response(...) )
}

globalThis.onfetch = handleFetch
```

**Comment by bartlomieju** [comment]
> how about something web-worker ish implementation?
> 
> ```js
> /** @param {FetchEvent} evt */
> function handleFetch (evt) {
>   const { request, respondWith } = evt
>   respondWith( new Response(...) )
> }
> 
> globalThis.onfetch = handleFetch
> ```

@jimmywarting is `onfetch` specced anywhere or is just an idea?

**Comment by jimmywarting** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onfetch

**Comment by crowlKats** [comment]
I dont see how that is relevant to this issue. that is just the fetch event that we have on deploy, it has nothing to do with this

**Comment by jimmywarting** [comment]
then i must have misinterpreted what the issue is about, i tough it was to hijack/intercept a ongoing request

eg: making a fetch call to get something would trigger a fetch event that you could use to monitor/log all outgoing request. (unless that's what [PerformanceEventTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming) will be for, but a fetch event could for higher level stuff
```js

globalThis.onfetch = evt => {
  // hijiack the request and respond with mocked data instead
}

fetch('https://httpbin.org/get') // would trigger a fetch event

```

**Comment by crowlKats** [comment]
Ah, no this is something completely different, though the issue name is not great and there isnt a description, so cant blame you.
Basically this is about an API to get the underlying tcp/tls stream of a request, so one can implement custom protocols that are based on http (ie websocket)
