### ISSUE TITLE
"Uncaught TypeError: Invalid URL" with an empty string in "new Request"

### ISSUE THREAD

**Issue by oles** [denoland/deno#12737]
I'm trying to use the [Airtable browser build](https://github.com/Airtable/airtable.js#browser) with Deno, and I get this error when I import it:
```
error: Uncaught TypeError: Invalid URL
    } else if ("signal" in new Request("")) {
                           ^
    at Object.opSync (deno:core/01_core.js:138:12)
    at opUrlParse (deno:ext/url/00_url.js:47:27)
    at new URL (deno:ext/url/00_url.js:320:20)
    at new Request (deno:ext/fetch/23_request.js:239:27)
```

Seems like Airtable is doing some silly stuff when checking for AbortController support:
```
var AbortController;
if (typeof window === 'undefined') {
    AbortController = require('abort-controller');
}
else if ('signal' in new Request('')) {
    AbortController = window.AbortController;
}
else {
    /* eslint-disable @typescript-eslint/no-var-requires */
    var polyfill = require('abortcontroller-polyfill/dist/cjs-ponyfill');
    /* eslint-enable @typescript-eslint/no-var-requires */
    AbortController = polyfill.AbortController;
}
module.exports = AbortController;
```

I've narrowed it down all the way; just having Deno run `new Request('')` gives the same error, while it works in Firefox and Chrome.

Perhaps this is a more fitting issue for Airtable, but seeing that it works in Firefox and Chrome, and what's written on the [Web Platform APIs](https://deno.land/manual@v1.8.3/runtime/web_platform_apis#web-platform-apis), this seems to be the right place.

**Comment by lucacasonato** [comment]
Deno does support `new Request('')` when `--location` is passed. `new Request("")` creates a request with a URL relative to the current `window.location`. `window.location` is just unset in Deno by default.

This is problematic code in the Airtable SDK though: it will break when run in a worker or iframe created from a data URL or blob, because those are "can-not-be-a-base" URLs (don't support relative URL creation).

The code should be something like `"signal" in new Request("https://example.com")` for it to work reliably everywhere.

**Comment by oles** [comment]
Thank you for the great and swift response, @lucacasonato.

Passing `--location 'http://localhost'` made the error go away, thank you!

Indeed, I'll get to creating an issue with them later :+1:
