### ISSUE TITLE
Proposal: add tasks to the config file

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12764]
## Context

Currently, there is no way to express "entry" points to an Deno application as well as provide a way of lightweight task orchestration when working with more complex projects.  This makes it difficult to manage solutions.

In Node.js, package managers support this via a `"main"` and `"scripts"` keys in the `package.json`.

## Semantics

- When a config file is applied, a top level key of `"tasks"` will be introspected.
- For subcommands that match a key of `"tasks"`, the command will be applied.  e.g. `"lint"`, `"test"` and `"compile"` would supply the arguments for `deno lint` and `deno test` and `deno compile`. 
- Other values are invoked when using the `run` subcommand as a "bare" specifier.  For example `deno run --config ./deno.jsonc build` would inspect the config file for a _task_ named `build` and invoke it if found.

## Examples

**deno.jsonc**

```jsonc
{
  "tasks": {
    "run": "./mod.ts",
    "build": "--allow-read --allow-write ./build.ts",
    "lint": "src/*.ts",
    "test": {
      "args": "--unstable",
      "permissions": { /* see: #12763 */ },
    }
  },
  "permissions": {
    // see: #12763
  }
}
```

Running:

```
> deno run --config deno.jsonc
```

Would be the equivalent of:

```
> deno run ./mod.ts
```

Running:

```
> deno run --config deno.jsonc build
```

Would be the equivalent of:

```
> deno run --allow-read --allow-write ./build.ts
```

Running:

```
> deno lint --config deno.jsonc
```

Would be the equivalent of:

```
> deno lint src/*.ts
```

Running:

```
> deno test --config deno.jsonc
```

Would be the equivalent of:

```
> deno test --unstable // in addition to permission flags set in the config file
```

## Considerations

- In #12763, remote configuration files are being proposed as supported, which means the semantics of relative specifiers in task command lines needs to be defined.  It is logical that they use the remote configuration file as the base. (e.g. `./mod.ts` with a configuration file of `https://example.com/deno.jsonc` would resolve to `https://example.com/mod.ts`).
- Chaining commands, like is available via package managers in the `package.json` `"scripts"` is undefined here. My personal opinion is that we leave that undefined for now, until we experiment a bit more with it.
- We should probably resolve `"tasks"` as bare specifiers over import maps.  For example a task of `"lodash"` and a command line of `deno run --config
- This isn't very useful without the semantics around automatic resolution of a config file being define.  I know @ry and @bartlomieju have discussed it and proposed some semantics.  It feels like it is a good time to implement them.
- Should we consider allowing `deno run https://example.com/deno.jsonc` work effectively the same as `deno run --config https://example.com/deno.jsonc`?  It makes sense to me, but always could be added later.

**Comment by Amatsagu** [comment]
I don't think that's a good idea. I understand why Deno received compat mode for now (I hope it's not forever).
Adding scripts will only make Deno in general heavier. Many things from Node are just not worth copying. I think that many people liked Deno in first place not because of security aspect but simplicity and less "boiler code" which is everywhere when you develop Node projects.

Creating & running custom scripts sound just like another toy for me. I think that's one of those things that should be left to community. Let projects like `diplo` or `velociraptor` to handle this. What's the point of forcing everyone to use this by embedding it into Deno itself.

**Comment by Amatsagu** [comment]
I feel like people forgot or ignored existence of local bash files....

**Comment by kitsonk** [comment]
> I feel like people forgot or ignored existence of local bash files....

Not everyone uses a bash shell, nor does everyone use and OS where it is easy to express in a universal way your tasks. Also not everyone is comfortable with shell scripting in general and would much prefer to express their tasks in the tool they are using with the least amount of friction.

**Comment by saadq** [comment]
> What's the point of forcing everyone to use this by embedding it into Deno itself.

This won't be forcing it on people though, you don't have to use it. For people who want to have a standardized way of having projects scripts though it is nice imo, and one thing I was missing while working in Deno.

**Comment by Im-Beast** [comment]
> I don't think that's a good idea. I understand why Deno received compat mode for now (I hope it's not forever). Adding scripts will only make Deno in general heavier. Many things from Node are just not worth copying. I think that many people liked Deno in first place not because of security aspect but simplicity and less "boiler code" which is everywhere when you develop Node projects.
> 
> Creating & running custom scripts sound just like another toy for me. I think that's one of those things that should be left to community. Let projects like `diplo` or `velociraptor` to handle this. What's the point of forcing everyone to use this by embedding it into Deno itself.

You're quite missing the point that `deno.jsonc` would be optional, you could still not use it or use external tools, like ones you mentioned – `diplo` or `velociraptor`.

**Comment by Soremwar** [comment]
I feel like the line between task and subcommand is unnecesarily blurred here. I do see a use case for just `deno run --config=deno.jsonc` but in my opinion it just adds unnecesary complexity to an otherwise easy to wrasp concept

Consider the following example:

```json
{
  "tasks": {
    "my_task": "./mod.ts",
  }
}
```

- Is there a situation in which I'd want to run `deno lint --config=deno.json my_task` or `deno test --config=deno.json my_task`? Why couldn't I just include the subcommand alongside the task if no other subcommand can make use of this task?
- Similarly, if I wanted to run `my_task` without having previous knowledge of how it's suppossed to be run should I guess what the subcommand for `my_task` is?
- If a new subcommand were to be added to Deno would that break tasks named the same as this subcommand?

The obvious drawback to this would be that the task section gets more verbose and you lose the ability to specify single line tasks
```jsonc
// Would otherwise be "my_task": "mod.ts"
{
  "tasks": {
    "my_task": {
      "command": "run",
      "task": "./mod.ts",
    }
  }
}
```

**Comment by Soremwar** [comment]
What would be the right way to specify arguments for a task with the current approach?

```bash
deno run --config=deno.json my_task argument_1 argument_2
# or
deno run --config=deno.json my_task -- argument_1 argument_2
```

Are we allowed to mix arguments?
```jsonc
{
  "tasks": {
    "my_task": "mod.ts -- argument_1"
  }
}
// Running with deno --config=deno.json my_task argument_2
// Should this work at all?
```

**Comment by bartlomieju** [comment]
I agree with @Soremwar on the matter that overloading subcommands with tasks is confusing.

I would like to propose my own proposal that I feel is explicit (and thus less "magical"), while being powerful and simple to grasp: `"tasks"` object in configuration file provides a configuration for `deno task <task_name>` subcommand.

_NOTICE: all example assume that config file lookup will be done automatically, for now they would require to add `--config=deno.jsonc` flag_

Example:

```jsonc
// deno.jsonc
{
    "tasks": {
        "run": "run --allow-read ./mod.ts",
        "dev": {
            "command": "run",
            "watch": true,
            "allow-read": ["./src/", "./dist/"],
            "allow-write": ["./src/", "./dist/"],
            "allow-env": true,
            "allow-net": ["localhost"],
            "script": "./devserver.ts"
        },
        "lint": "lint --ignore=dist/",
        "bundle": {
            "command": "bundle",
            "import-map": "./import_map.json",
            "script": "./entrypoint.js"
        }
    }
}
```

```sh
$ deno task run
// equivalent to 
// deno run --allow-read ./mod.ts

$ deno task dev
// equivalent to
// deno run --watch \
//  --allow-read=./src/,./dist/ \ 
//  --allow-write=./src/,./dist/ \ 
//  --allow-env \
//  --allow-net=localhost
//  ./devserver.ts

$ deno task lint
// equivalent to
// deno lint --ignore=dist/

$ deno task bundle
// equivalent to
// deno bundle --import-map=./import_map.json ./entrypoint.js
```

There are two ways to express a task:

a) short-hand method - string is passed explicitly to CLI arg parser
b) object method - objects are deserialized directly into `Flags` structure in `cli/flags.rs`

My only worry with this approach is that providing schema file might be challenging; 
as available fields in the objects depend on the value of `"command"` field in that object.

I also think it's simpler to implement - all functionality is scoped to a single subcommand, which makes it easier
than adding conditionals that would handle overloads for existing subcommands.

On the matter of runtime arguments passed to the tasks, I think appropriate fields should have `"args"` field (eg. objects 
using `run` command), and additional arguments specified on the CLI should be passed through, eg.:
```jsonc
// deno.jsonc
{
  "tasks": {
      "dev": {
          "command": "run",
          "script": "./devserver.ts",
          "args": ["--force", "--ipv4"]
      }
  }
}
```

```sh
$ deno task dev --port 8000 --out=./dist
// equivalent to
// deno run ./devserver.ts --force --ipv4 --port 8000 --out=./dist
```

**Comment by lucacasonato** [comment]
I am not in favor of implementing this as currently discussed:

**The "string style" tasks are not well enough described.**

It says that "the string is passed explicitly to CLI arg parser". `clap` takes pre-cut command line arguments (a `[&str]`, not a `&str`). This gives rise to the question of how to split the command string into multiple parts.

We can not just split on spaces, as this would break for quoted arguments. The splitter would need to be aware of quotes, escaped quotes, etc. This means that we are essentially re-specifying a shell syntax:
- do we use bash's interpretation of quoted arguments, or do we base it off fish/zsh/powershell etc
- is `"run" "--allow-net"` valid?
- how is `run '--allow-read="\'123"' "my url with spaces and \' \' \"" ` parsed?

**Why are commands limited to `deno` subcommands only?**

I expect many users would like to invoke external commands through the `deno task` interface: e.g `deno task bundle` that expands to `esbuild --target=browser main.js --out-dir=out`. If we are implementing a shell parser anyway for the "string style" tasks, why not support all commands?

If we decide not to support this, how should users approach workflows like these?

**Do we want to support the use case of users running multiple tasks concurrently?**

This is a [popular feature](https://www.npmjs.com/package/concurrently) in npm `"scripts"` that users may want in Deno too. For an example see https://remix.run/docs/en/v1/guides/styling#tailwind. How should one go about doing something like this in Deno tasks? Maybe they create a `./tools/dev.ts` file that spawns both subprocesses?

**Should we support executing multiple tasks in series?**

Similar to the one above. In npm's `"scripts"` you can do `"deploy": "node index.js && esbuild && npm run deploy:gcp"`. How should people go about doing these kinds of workflows with Deno tasks? Do they create a `./tools/deploy.ts` file that spawns both subprocesses?

**Should there be support for using env vars as argments?**

```json
      "dev": {
          "command": "run",
          "script": "./devserver.ts",
          "permissions": [
            "net": "0.0.0.0:$PORT"
          ],
          "args": ["--config", "$SERVER_CONFIG_FILE"]
      }
```

This goes both for arguments in "string style" and in "object style".

**How do we handle glob expansion?**

Should we do glob expansion for arguments and permissions? This goes both for arguments in "string style" and in "object style". We have so far always said that Deno does no glob expansion for arguments, because your shell should do that. If we are the shell that executes the script, the only logical thing to do would be that we need to support glob expansion.

What kind of glob syntax do we support? Do we align to `bash`, `fish`, `zsh`, `powershell`?

---

I am not strictly opposed to something like this, but I do think there are real issues here that we need to work out and find solutions for. I am **not in favor** of any kind of shell style parsing at all, as that is not a can of worms I want to have anywhere near us. We already have a scripting language (JS) in our runtime, so we don't need another one (deno task shell). I think this proposal would be a lot more straightforward if we remove the "string style" tasks.

But even then, this is a hugely complex undertaking. We are going to be building essentially a fake shell. Is this really something we want? Should we not defer this to tools that are made for this? We could defer to a user's own shell, but that means that tasks would not be portable anymore.

An alternative would be to bundle GNU make with Deno: `deno make` could then just execute your makefiles on Windows, macOS, and Linux.

I think before deciding to continue with this proposal we need to answer these open questions as they are integral to the design of a `deno task` system.

**Comment by kitsonk** [comment]
> Do we want to support the use case of users running multiple tasks concurrently?

This was something @bartlomieju and I touched on briefly when chatting.  I don't know about "concurrently" as much as being able to "chain" tasks easily.  I suggested something along the line of if there was an array of tasks like `["build", "test", "deploy"]` that they would result in a chained execution.  Do you think concurrently is a requirement?

> An alternative would be to bundle GNU make with Deno: `deno make` could then just execute your makefiles on Windows, macOS, and Linux.

There is a reason `"scripts"`, while designed to be a package manager hooks became so popular in the ecosystem, people don't like Makefiles.  I for one find shell scripting annoying and inaccessible. Writing Deno tasks in Deno and running them in Deno seems a lot better of a solution.  Having the feature doesn't not preclude people from using makefiles, but it lowers the barrier of people approaching a new project with Deno.

There were other solutions for task orchestration before `"package.json"` `"scripts"` became popular, that weren't makefile.  Grunt and Gulp are two examples, all the while makefiles were there, but people don't like using them.

**Comment by Soremwar** [comment]
Running a list of scripts would probably require a different json schema anyways. So options such as "concurrent" could be provided in that schema. This could also translate to a CLI flag to add a little more functionality to the `task` subcommand if implemented

```bash
deno task do_many
# or
deno task --concurrent lint format coverage
```
```jsonc
{
  "do_many": {
    "command": "task",
    "concurrent": true,
    "tasks": ["lint", "format", "coverage"],
  }
}
```

Another feature that could be considered is the `or` operator. In NPM, `"do_lint || do_fmt || do_coverage"` would execute the three tasks sequentially regardless of the previous one exit status (this is admittedly not as widely used, since it wasn't supported on Windows til December 2019)

**Comment by jespertheend** [comment]
I use [`npm concurrently`](https://www.npmjs.com/package/concurrently) for pretty much all projects. So having support for running tasks concurrently would be much appreciated as it would mean I would have one dependency less.

A use case could be `deno task dev` which: starts a local server for static files, watches for file changes and builds one of the scripts used on the site, starts a websocket server to be used by the client.

**Comment by nayeemrmn** [comment]
> Why are commands limited to `deno` subcommands only?

+1. In the end we won't be able to justify a design that can't run non-Deno commands or leaves that to another outer script runner.

> An alternative would be to bundle GNU make with Deno: `deno make` could then just execute your makefiles on Windows, macOS, and Linux.

Bundling some preexisting unix tool untampered into a Deno subcommand is a very good and underrated solution. 
1. `/bin/dash` -> `deno sh` or
2. `/bin/bash` -> `deno sh` or
3. `/usr/bin/make` -> `deno make`

```sh
> cat run
deno run --allow-read=. --allow-write=. --allow-net main.ts
> deno sh run
Check file:///.../main.ts
...
```
It would be an increase in executable size but not in design surface area. When shell scripts are suggested for task orchestration, the question is always how that will work on Windows, and this is the shortest answer.

Yeah you can site the popularity of npm `"scripts"` in spite of these tools existing. But if windows compat compat is bridged and the Deno manual suggests `deno sh run`, Deno users aren't going to gravitate away without a real reason.

Once we accept the need to orchestrate external commands just as well as Deno commands, we land on a generic script runner like npm `"scripts"`. The JSON structures proposed here honestly just seem like a contrived way of avoiding this. So I think we should adopt a small ubiquitous scripting language with its basic cli instead of tepidly reinventing the same thing.

**Comment by kitsonk** [comment]
> Bundling some preexisting unix tool untampered into a Deno subcommand is a very good and underrated solution.

I personally don't want to do shell scripting to run things in my command line JavaScript/TypeScript scripting tool.  We have a scripting language included already in the Deno binary.

**Comment by nayeemrmn** [comment]
> I personally don't want to do shell scripting to run things in my command line JavaScript/TypeScript scripting tool. We have a scripting language included already in the Deno binary.

Then how do we intend to support running and piping etc. with external commands, and isn't that what npm `"scripts"` is?

**Comment by justinmchase** [comment]
I made a module that sort of does this:

https://deno.land/x/scripts@0.2.1

**Comment by justinmchase** [comment]
The only thing I would add to this is the notion that your task scripts could be a url to external tools and that it should work similar to `deno install` but to a relative path instead of global.

**Comment by kitsonk** [comment]
With `deno task` shipping in Deno 1.20 (see: https://deno.land/manual@main/tools/task_runner), we can close this.  While it doesn't provide all the functionality in this proposal, it is a foundation we can evolve, but those evolutions can be discussed in new issues.
