### ISSUE TITLE
Misleading error when calling non-existent op

### ISSUE THREAD

**Issue by DjDeveloperr** [denoland/deno#12919]
Found this when debugging #12918 

When you call a non-existent op, the error is kind of misleading and doesn't tell what is actually wrong.

**Reproduction**

Try `Deno.core.opSync("non_existent")` in REPL and you'll get
```
Uncaught TypeError: invalid op id: expected type `v8::data::Integer`, got `v8::data::Value`
    at Object.opSync (deno:core/01_core.js:142:27)
    at <anonymous>:2:11
```

**Comment by bartlomieju** [comment]
I hit this problem as well this week, I agree that the error is not informative. I think we'd need to update `rusty_v8` to have better output for `v8::Value`.

**Comment by bartlomieju** [comment]
@bnoordhuis what do you think?

**Comment by andreubotella** [comment]
I think these are separate concerns – `serde_v8` should probably have a better output in this case, sure, but any `serde_v8` error output would be of no use to someone calling a non-existent op. That should raise a `deno_core`-specific error.

**Comment by bartlomieju** [comment]
> I think these are separate concerns – `serde_v8` should probably have a better output in this case, sure, but any `serde_v8` error output would be of no use to a user of `deno_core` calling a non-existent op. That should raise a `deno_core`-specific error.

Sure, but `v8::Value` can be a number of things, I believe the representation could show what's "hidden" behind the value (`undefined, `integer`, etc.). There's already `deno_core` specific error here: `invalid op id:`

**Comment by bnoordhuis** [comment]
I was griping about that error message just yesterday so I definitely would like to see it improved.

I wouldn't say it's a rusty_v8 or serde_v8 issue, I don't think they can improve the error message much. The problem is that `undefined` is passed where a number is expected.

 Note how `opSync()` doesn't check if `opsName` is a key in `opsCache`:
https://github.com/denoland/deno/blob/3881e2e7bf3bbe4a5d62872a9fb7b6e2e3d82f81/core/01_core.js#L148-L150
It basically evaluates to `opcallSync(undefined, arg1, arg2)`.
