### ISSUE TITLE
Typescript global types not maintained for dynamic imports with dynamic path

### ISSUE THREAD

**Issue by JakeStanger** [denoland/deno#13155]
When using `import()` and passing a variable instead of a string literal, global types are not preserved and the program exits with a TypeScript error. This occurs for both on-disk paths and URLs.

Passing a string literal (`await import('./print.ts')`) does not error and works as expected.

```
error: Uncaught (in promise) TypeError: TS2304 [ERROR]: Cannot find name 'foo'.
console.log(foo);
            ~~~
    at file:///home/jake/Programming/deno-bug/print.ts:1:13
await import(path);
^
    at async file:///home/jake/Programming/deno-bug/index.ts:13:1
```

Minimal reproduction:

```ts
// index.ts
declare global {
  const foo: string;
  interface Window {
    foo: string;
  }
}

window.foo = 'bar';

const path = './print.ts';
await import(path);
```

```ts
// print.ts
console.log(foo); // -- errors --
```

Running using:
```
deno run -r --allow-read index.ts
```

Deno version:
```
λ deno --version                   
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

**Comment by nayeemrmn** [comment]
This is an interesting case. The only way we can support this is to include all of the existing graph data in the type check when prepare-loading a true dynamic import. For me it's a wontfix...

@JakeStanger You can create a type-only dependency which points back to the global types being depended on:
```ts
// print.ts
/// <reference path="./index.ts" />
console.log(foo);
```
Rather than a workaround I think this is a sound permanent solution because it only forces you to express an actual dependency of that module.

**Comment by JakeStanger** [comment]
Thanks for the alternative, that's something I can make work. 

It's worth pointing out (and sorry for not including this in my first post) that this was actually working for me all of last week on Deno 1.16 and 1.17 & stopped today with no code changes. That makes no sense from my own understanding but is it possible there's something environmental that could have changed and caused this?

---

If this is a wontfix and deemed unsupported behaviour, is there anything that can be built into the typechecker/runtime/whatever to catch it and avoid the otherwise slightly confusing scenario?

**Comment by nayeemrmn** [comment]
> this was actually working for me all of last week on Deno 1.16 and 1.17 & stopped today with no code changes.

Yeah that's easy to reproduce. If you run with `await import('./print.ts')`, have it pass the type check, change it back to `const path = './print.ts'; await import(path)` and run it again, it won't bother type checking it again because it already passed and neither `print.ts` nor any of its _expressed_ dependencies have changed. Upgrading Deno triggers a cache bust which makes you see the error again.

This is an anomaly that can occur with global types in a system that relies on module graph analysis, but should no longer happen with `/// <reference path="./index.ts" />`.

**Comment by JakeStanger** [comment]
> it won't bother type checking it again because it already passed and neither print.ts nor any of its expressed dependencies have changed.

Is this true even with the `--reload` flag? I've been purposely using that to force reload my deps as I was playing with dynamic url imports.

**Comment by nayeemrmn** [comment]
> Is this true even with the `--reload` flag? I've been purposely using that to force reload my deps as I was playing with dynamic url imports.

No, the calls with `--reload` should indeed resurface the type error which is the behaviour I'm seeing. Though calls after that without `--reload` would still be missing the error since the emit and their validity status didn't change.
