### ISSUE TITLE
no comma space in headers

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#13254]
I expected this to include a space `', '`

```js
fetch('https://httpbin.org/get', {
  headers: [['Foo', 'bar'], ['Foo', 'baz']]
}).then(r => r.json()).then(json => json.headers.Foo.includes(', ')).then(console.log)
```
All browser yields true, deno yields false

What's weird is that 
`new Headers([['foo', 'bar'], ['foo', 'bar']]).get('foo')` includes a `', '` but the request didn't

this works doe:
```js
fetch('https://httpbin.org/get', {
  headers: new Headers([['Foo', 'bar'], ['Foo', 'baz']])
}).then(r => r.json()).then(json => json.headers.Foo.includes(', ')).then(console.log)
```

----

deno 1.16.4 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.4.2

**Comment by lucacasonato** [comment]
The headers are sent over the wire as two individual kv pairs as is specified in the header list.

**Comment by lucacasonato** [comment]
I don't think the fetch spec prescribes if headers need to be concatenated on the wire. We don't concatenate headers on the wire. Semantically these raw headers are equivalent in HTTP:

```
Foo: abc
Foo: xyz
```

```
Foo: abc, xyz
```

---

The reason the second example does what you expect, is because you are really doing `headers: [... new Headers([['Foo', 'bar'], ['Foo', 'baz']])]`. If you look at the output of that, you will see that the array is: `[ [ "foo", "bar, baz" ] ]`. For the first example, the two values in the array are added to the internal "header list" unmodified as is specified by the fetch spec.

**Comment by lucacasonato** [comment]
Checked in with @annevk, and this is behavior is spec compliant.
