### ISSUE TITLE
Property decorators work differently with `run` and `run --no-check`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#13281]
The following script prints `42` with `deno run --no-check`, but prints `undefined` with `deno run`

```ts
function bar(_target: unknown, _key: string): any {
  return {
    value: 42
  }
}
class A {
  @bar
  foo?: number;
}
console.log(new A().foo);
```

---

- deno 1.17.1 (release, x86_64-apple-darwin)
- v8 9.7.106.15
- typescript 4.5.2

**Comment by kt3k** [comment]
From my experience with decorators, the behavior looks correct with swc, and not correct with tsc in this case.

I think this is related to `useDefineForClassFields` config property and the upstream issue https://github.com/microsoft/TypeScript/issues/44449

**Comment by kt3k** [comment]
It seems that #13060 solves this issue

**Comment by kitsonk** [comment]
I don't know how it would, it only impacts `Deno.emit()` and only allows `useDefineForClassFields` to be unset.

`useDefineForClassFields` needs to be turned on, as class fields in esnext are emitted functionally that way, even though they just appear in the class definition, and `useDefineForClassFields` causes tsc to report some errors.

[`tsc`/check emits](https://www.typescriptlang.org/play?useDefineForClassFields=true&emitDecoratorMetadata=false&target=99#code/GYVwdgxgLglg9mABAIwIYCcAUB9KGDmAplAFyLgDWYcA7mADSLYWECeZAzlOjGPgJRlUYVogDeAKESJ0xEOiSTp0gG6oANiEJkALACYpiAL4SThAB4AHOOiiII61Bw6IAguMMABNOkPA4cAD8ZGAgALbIhOgA3KYSEAgccOqEAHTqcPiYYIQ0bpj8qf5w-LFAA):

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
function bar(_target, _key) {
    return {
        value: 42
    };
}
export class A {
    foo;
}
__decorate([
    bar
], A.prototype, "foo", void 0);
console.log(new A().foo);
```

[And swc emits](https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAAx3MwQqDMBAE0Hu%2BYo4RiofSUzy0fonEsIqY7pZNopXivzd4mhl4zFQ45EUYo1c7ZK8zZYfCK8vONwwrHQ4p68Jz4%2BD5wM8ASrkoXxXYfCzk8LjXdZrT0PcjmhGiTwn9hV71vcYk8nTg8h5JuyqDcJJIbZTZMu3obdNW03TmD4VVCyiXAAAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1FsWLLnyHHkI4SnDxD0mBGuO713FTshvm85gGb3FgGxRkIT6V1KT4AQtaC4ljXxQWUBmW8kELrOQyo2aWn9NHiryTjg2JeRgz%2BiFnIbAbBhmT6JPf6kl3ORYmkTvCtId%2Fsw9WzOtxGm0emMwn9Jtx7by8ruL88AWSNXqjyQAAAA%3D%3D):

```js
function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) {
    var desc = {
    };
    Object.keys(descriptor).forEach(function(key) {
        desc[key] = descriptor[key];
    });
    desc.enumerable = !!desc.enumerable;
    desc.configurable = !!desc.configurable;
    if ("value" in desc || desc.initializer) {
        desc.writable = true;
    }
    desc = decorators.slice().reverse().reduce(function(desc, decorator) {
        return decorator ? decorator(target, property, desc) || desc : desc;
    }, desc);
    if (context && desc.initializer !== void 0) {
        desc.value = desc.initializer ? desc.initializer.call(context) : void 0;
        desc.initializer = undefined;
    }
    var own = Object.getOwnPropertyDescriptor(target, property);
    if (own && (own.get || own.set)) {
        delete desc.writable;
        delete desc.initializer;
    }
    if (desc.initializer === void 0) {
        Object.defineProperty(target, property, desc);
        desc = null;
    }
    return desc;
}
function _initializerDefineProperty(target, property, descriptor, context) {
    if (!descriptor) return;
    Object.defineProperty(target, property, {
        enumerable: descriptor.enumerable,
        configurable: descriptor.configurable,
        writable: descriptor.writable,
        value: descriptor.initializer ? descriptor.initializer.call(context) : void 0
    });
}
var _class, _descriptor;
function bar(_target, _key) {
    return {
        value: 42
    };
}
export let A = ((_class = class A {
    constructor(){
        _initializerDefineProperty(this, "foo", _descriptor, this);
    }
}) || _class, _descriptor = _applyDecoratedDescriptor(_class.prototype, "foo", [
    bar
], {
    configurable: true,
    enumerable: true,
    writable: true,
    initializer: void 0
}), _class);
console.log(new A().foo);
```

So effectively swc replaces the descriptor that is used as the initializer on the class, but it is arguable that it really should do that, because it is also defining it on the prototype.  Because tsc "properly" emits it as a class field, it has the right behaviour from what people expect for a class field and is defined in the specification, but it masks the decorator on the prototype.

Because decorators are experimental and broken proposal, the behaviour is undefined.  We should not/cannot disable `useDefineForClassFields` as the runtime behaviour of class fields becomes non-spec compliant.  It feels like the experimental and broken specification is incompatible with the current ECMAScript specification.  Using experimental decorators is a bad idea.

Also, without the decorator at all, the behaviour between swc and tsc differ as well in a slightly important way:

Given:

```ts
export class A {
  foo?: number;
}
console.log(new A().foo);
```

You get the following from `tsc`:

```js
export class A {
    foo;
}
console.log(new A().foo);
```

And the following from `swc`:

```js
export class A {
}
console.log(new A().foo);
```

**Comment by kt3k** [comment]
Sorry, there was probably a mistake in checking the result. I checked it again and now #13060 doesn't seem solving this issue 🤦‍♂️ (probably there was swc transpiled cached remained in DENO_DIR)

**Comment by kt3k** [comment]
I've read the above comment carefully again, and there seems nothing actionable here (ECMAScript class fields and typescript fields decorators are just incompatible). So I'm closing the issue.
