### ISSUE TITLE
`deno::Flags` should be reference counted

### ISSUE THREAD

**Issue by ry** [denoland/deno#13311]
The [`Flags` struct](https://github.com/denoland/deno/blob/1fb5858009f598ce3f917f9f49c466db81f4d9b0/cli/flags.rs#L211-L256) has a lot of data in it and it is cloned multiple times. It makes sense to wrap it in an `Rc`.

For example:

https://github.com/denoland/deno/blob/1fb5858009f598ce3f917f9f49c466db81f4d9b0/cli/main.rs#L378

https://github.com/denoland/deno/blob/1fb5858009f598ce3f917f9f49c466db81f4d9b0/cli/main.rs#L572

**Comment by bartlomieju** [comment]
I'm afraid this change might not work, because in some places `Flags` are modified in-place to override certain options.

**Comment by ratika-12** [comment]
@ry I want to work on this

**Comment by bartlomieju** [comment]
@ratika-12 please do

**Comment by biryukovmaxim** [comment]
Hello guys! It's been a while since your last comment, @ratika-12 . 
May I take this issue, @bartlomieju ?

**Comment by biryukovmaxim** [comment]
@bartlomieju ProcState is Sync and Send. This means that wrapper should be Arc instead of Rc, but a lot of cloning operations in a single thread. As a result there are 2 options:

1.  Type Flags shoud be renamed to Inner, Create a new type Flags that wraps Rc<Inner>. Inner cloning is used in one place - Proc::build
2. Type Flags shoud be renamed to Inner and Create a new type Flags that wraps Arc<Inner>

**Comment by bartlomieju** [comment]
@biryukovmaxim please do, using `Arc` instead of `Rc` is correct and we should be passing `Arc<Flags>`

**Comment by dsherret** [comment]
I think this is the wrong solution to the problem unfortunately. Once flags is moved to `ProcState` then it can be referenced from there. We should just remove the `clone()` calls and change the code to not requiring cloning the entire flags to construct `Permissions`.
