### ISSUE TITLE
`bundle` and `compile` should use options for final output

### ISSUE THREAD

**Issue by x80486** [denoland/deno#13338]
As of Deno `1.17.x`, `compile` uses `--output` option to _say_ where to place the result from the operation. On the other hand `bundle` makes use of an optional argument.

I know the two _directives_ work different, but since the argument is optional, wouldn't be more aligned with the current behavior of the other commands if `bundle` would just use an option (`--output`) as well, in the same way `compile` does to output the final result?

**Comment by kitsonk** [comment]
`--output` for compile is optional... so I am not sure what you are suggesting.

If you are suggesting that if `--output` is not used that it defaults to writing out a file versus sending the output to stdout for `deno bundle` I don't think that change in behaviour makes total sense.  `deno compile` doesn't output to stdout by default because piping a binary to stdout doesn't make sense, and while you may not use it, there are people who use the output of deno bundle piped for post processing.  Also, while some intelligence can be implied to infer a good name for a binary, it is less obvious what a good default would be for the the bundle name.

**Comment by x80486** [comment]
What I was trying to explain is that `bundle` could make use of an `--output` option as well, instead of providing a path as an argument.

For instance, instead of `deno bundle src/main.ts dist/deno-sandbox.bundle.js`, it could be `deno bundle --output dist/deno-sandbox.bundle.js src/main.ts`.

Currently, both are optional in any case: `--output` for `compile` and the argument for `bundle`.

**Comment by lucacasonato** [comment]
`bundle` has been removed, so everything is aligned now (`deno compile` and `deno upgrade` both use `--output`).
