### ISSUE TITLE
Access token environment variable for remote files authorisation doesn't work

### ISSUE THREAD

**Issue by natebowang** [denoland/deno#13366]
I'm stuck to importing private TS files without exposing the access key described in this [doc](https://deno.land/manual@v1.8.3/linking_to_external_code/private). In the screenshot, there is a token in the environment variables, the token works with `curl`, but loading with Deno failed.
$ deno --version
deno 1.17.2 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2

![image](https://user-images.githubusercontent.com/30286194/149406641-5d5e1893-00d1-4da8-829b-68617b47409d.png)

**Comment by bnoordhuis** [comment]
By the looks of it, you need to drop `@raw.githubusercontent.com` from your `DENO_AUTH_TOKENS`.

If `curl -H "Authorization: bearer $DENO_AUTH_TOKENS" <url>` works, then so should deno.

**Comment by kitsonk** [comment]
@bnoordhuis `DENO_AUTH_TOKENS` is _token_@_origin_ format, so that the CLI knows what origins to set for what token.

I am not sure why it isn't working in this specific environment, as we have tests for it and this is the first report of it not working in well over a year. I haven't specifically tried to recreate it with the specific version noted yet, but I really suspect it is something environmental.

**Comment by natebowang** [comment]
Sorry. I forget to export the `DENO_AUTH_TOKENS` to the child process. It works very well. 
```bash
$ export DENO_AUTH_TOKENS='your_auth_tokens@raw.githubusercontent.com'
$ deno run index.js
Hello from a Github
```
