### ISSUE TITLE
Feature Request: `Deno.isUnstable`

### ISSUE THREAD

**Issue by MierenManz** [denoland/deno#13370]
`Deno.isUnstable` will be set to true or false depending on if `--unstable` is provided or not
The reason why I would like this api in deno is because some modules need `--unstable` for additional functionality which could be enabled or disabled by this flag and not just throw when trying to use a unstable feature when in stable mode

**Comment by kitsonk** [comment]
I would disagree with this, because the unstable APIs can and do change from version to version.  That is why they are unstable.  If there was detection of it, people would make wrong assumptions about what is available, basically this would amount to UA sniffing which has not gone well.

If people need to determine if a feature is present, they should feature detect individual features.  If a feature is exposed in a way that it isn't determinable if the feature is present, then that is worth discussing to see if the API's design is correct or not.

**Comment by MierenManz** [comment]
Would it be an idea to have `Deno.isUnstable` which takes a string argument of the api name like `Deno.isUnstable("Deno.setRaw");`

**Comment by janispritzkau** [comment]
Detection of `TcpConn.setNoDelay` and `TcpConn.setKeepAlive` is currently not possible, since the method exists and the program just exits immediately when it is used.

**Comment by bartlomieju** [comment]
> Detection of `TcpConn.setNoDelay` and `TcpConn.setKeepAlive` is currently not possible, since the method exists and the program just exits immediately when it is used.

FYI I've opened https://github.com/denoland/deno/pull/17003. I'm still not a fan of adding `Deno.isUnstable` API.

**Comment by lucacasonato** [comment]
We're not going to do this. Feature detect the specific features you'd like to use, like `typeof WebSocketStream === "undefined"`. We'll try to avoid adding unstable features that are not feature detectable in the future.
