### ISSUE TITLE
Improve time to lint diagnostics in LSP

### ISSUE THREAD

**Issue by ry** [denoland/deno#13410]
This can be measured using the following benchmark:
```
# cargo bench --bench lsp_bench_standalone
   Compiling deno v1.17.3 (/Users/ry/src/deno/cli)
    Finished bench [optimized] target(s) in 7.03s
     Running unittests (target/release/deps/lsp_bench_standalone-50969af938e69a9b)

running 1 test
test incremental_change_wait ... bench: 288,701,433 ns/iter (+/- 6,529,414)
```

Currently it takes well over 200ms to receive lint diagnostics due to the debouncing mechanism.

**Comment by kitsonk** [comment]
@dsherret a couple thoughts I had on it.  The debounce triggers a calculation of diagnostics here:

https://github.com/denoland/deno/blob/0f3a53e5d477ca2c422ed58a65bd368d1eb0a5b2/cli/lsp/diagnostics.rs#L197-L203

And in `update_diagnostics()` and the lint diagnostics are calculated here:

https://github.com/denoland/deno/blob/0f3a53e5d477ca2c422ed58a65bd368d1eb0a5b2/cli/lsp/diagnostics.rs#L197-L203

Ideally only the ts diagnostics need to be debounced, and that the lint update can occur here:

https://github.com/denoland/deno/blob/0f3a53e5d477ca2c422ed58a65bd368d1eb0a5b2/cli/lsp/diagnostics.rs#L211-L217

I think the challenge is though we track "dirty" diagnostics as a single entity per document and we need to make sure we don't end up in some situation where because we trigger them at different times we don't end up with an inconsistent state.  We may just want to limit the dirtiness to the ts diagnostics anyways, since the other two categories are calculated very quickly and can be calculated in a blocking way per change.
