### ISSUE TITLE
Show error cause reccursion information

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#13413]
Node does this
(code tested is https://github.com/denoland/deno/blob/167982be9e7af35e6c12ef6c40c002200bf5e0c0/cli/tests/testdata/error_cause_recursive.ts)
![image](https://user-images.githubusercontent.com/13135287/150013522-115eb12a-1cfd-4014-874a-72c75cb94e93.png)
We should do the same

**Comment by RushilMehra** [comment]
Going to attempt to pick this issue up. Will take me some time to familiarize myself with everything

**Comment by Grubba27** [comment]
Hello there! This issue is still open for contribuitons ? I would start by addeding another option for errors here at [errors](https://github.com/denoland/deno/blob/main/cli/errors.rs) or somewhere else ?  How could I test this ?
I have some implementation doubts also like, I'm able to always tell when this is happening ? or i would do this kind of message: "RangeError: Maximum call stack size exceeded"

**Comment by crowlKats** [comment]
Hey @Grubba27, @RushilMehra is still working on this, but feel free to take a stab at this. We implemented this in the object inspection recently (https://github.com/denoland/deno/pull/13555); obviously this wont map to rust, but it might still give some ideas.

> I would start by addeding another option for [errors](https://github.com/denoland/deno/blob/main/cli/errors.rs) here at errors or somewhere else ?

Take a look at https://github.com/denoland/deno/pull/13209, we changed https://github.com/denoland/deno/blob/main/core/error.rs.

>  How could I test this ?

In the issue description i have linked a file with the testcase.

> I have some implementation doubts also like, I'm able to always tell when this is happening ?

Not sure what you mean.

**Comment by luk3skyw4lker** [comment]
Is someone still working on this? I would like to grab this issue.

**Comment by RushilMehra** [comment]
> Is someone still working on this? I would like to grab this issue.

I’m still taking a look, but I’ve been really busy at work. Feel free to take a stab.

**Comment by luk3skyw4lker** [comment]
Alright, I'll try something out and send the updates here, thanks!

**Comment by luk3skyw4lker** [comment]
@RushilMehra could you give some pointers later about where can I start? Only if it doesn't bothers you, I would appreciate it

**Comment by RushilMehra** [comment]
> @RushilMehra could you give some pointers later about where can I start? Only if it doesn't bothers you, I would appreciate it

Take a look at @crowlKats comment earlier in the thread, it provides some good starting points. Feel free to study node’s implementation as well

**Comment by luk3skyw4lker** [comment]
Nice, thanks for the tip!

**Comment by Dgarc359** [comment]
I'd be interested in taking a stab at this if there's still progress to be made. From a brief look at the source code, it looks like the targets files for this fix would be `error.rs` or `fmt_errors.rs`

This is the output I see from running the test on your `error_cause_recursive.ts`
![image](https://user-images.githubusercontent.com/87497958/165194508-6dc95e67-c39d-414d-aa5b-85e5719a7056.png)

The notable differences being the missing trace that drills down to the object throwing the error. Would it require some changes to how `sourcemap` is used? Is the information that's missing in the linked image already available using the crates currently in use? Or does it require another, external, dependency?

Kind regards

**Comment by luk3skyw4lker** [comment]
I think that maybe only the `error.rs` and `fmr_errrors.rs` (together with `02_error.js` that must be kept in sync with `fmt_errrors.rs`) should be the points of attention. I've looked at the code and the infos seem fine, but I think the formatting may be the most important.

I didn't manage to go through it yet because of work too, but feel free to take a stab.

**Comment by Cre3per** [comment]
Is someone still working on this? If not, I'd like to take over

I've got the sample test file covered

![2022-08-02_16-02](https://user-images.githubusercontent.com/12541974/182394010-6ef334b3-5944-4b8c-a6c7-bcc3b2f15c7c.png)

Open points  
- A test for the sample file
- Add `<ref *>` to non-top-most errors + Test
- Handle aggregate errors + Test
- Possibly sync with JavaScript. Not necessary so far.

Detecting circular references has proven challenging, because `cause` is a clone, rather than a reference as is in JavaScript. My current implementation copies `JsError`, except for the `cause` attribute, to form an `ErrorIdentity`. `ErrorIdentity` can then be compared to other `ErrorIdentity` to check for equality. This is memory intensive, but the best I could come up with so far. Help is welcome. in-dev: https://github.com/Cre3per/deno/blob/circular-cause-in-error/cli/fmt_errors.rs

@crowlKats I've looked at your circular detection for object inspection, thanks for the link! Am I right to assume that in this issue there is at most 1 circular reference, as the `Error.cause` chain is linear?

**Comment by Dgarc359** [comment]
I couldn't get a solution working, feel free to take over

**Comment by Cre3per** [comment]
Feature is implemented in https://github.com/Cre3per/deno/tree/circular-cause-in-error  
My branch has a failing test case (disabled) for when the recursively referenced error is not the top-most error. The test is currently failing due to #15602, I'll re-run the test case once that's fixed.

There's a decent chance I've missing some scenarios when `AggregateError` is involved. Considering `node` doesn't output causes for `AggregateError`s at all, and `AggregateError` isn't all that common, I'd prefer to keep the implementation simple and not to look further into `AggregateError`s.

**Comment by kamilogorek** [comment]
Closed in https://github.com/denoland/deno/pull/16384
