### ISSUE TITLE
lsp: cannot clear errors in module resolution

### ISSUE THREAD

**Issue by socketwiz** [denoland/deno#13673]
I've recently discovered that deno has a language server and has support for neovim.  I've installed and configured everything and it's working really well.  I just have one minor issue, it looks like there is a way for the linter to be disabled, but in practice that does not seem to be the case and try as I might I can't seem to convince it otherwise.

![deno-linter](https://user-images.githubusercontent.com/718481/154056555-ee2a8430-7cd0-4a25-91f8-9a20f79dd509.png)

There is a default configuration for `nvim-lspconfig` here https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#denols that suggests you can disable the linter:

```
init_options = {
  enable = true,
  lint = false,
  unstable = false
}
```
^ I've tried that config but it doesn't seem to work. 

The same page says the server can accept settings via the `settings` key, so I tried

```
settings = {
  deno = {
    lint = false
  }
}
```
^ But this didn't seem to work either.

I even tried creating a deno.json file in the root directory, but that didn't seem to work either.

```
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": false,
    "lib": ["deno.window"],
    "strict": true
  }
}
```

Any ideas on how to disable the deno linter with the neovim lsp configuration?

**Comment by bartlomieju** [comment]
@socketwiz the errors you are seeing are coming from Deno's TS compiler not `deno lint`.

**Comment by socketwiz** [comment]
@bartlomieju I see, interesting.  According to https://deno.land/manual@v1.18.2/typescript/configuration I should be able to set `checkJs` to `false` and that should stop the TS check.  I'm just not sure how to set that through LSP.  The closest I can come up with is with a `deno.json` file, but as you can see I've already tried that. I even tried a `jsconfig.json` file with the same setting, but denols does not seem to be reading either of these files.  Are you aware of a another way to disable this?

**Comment by kitsonk** [comment]
> @socketwiz the errors you are seeing are coming from Deno's TS compiler not `deno lint`.

Actually it is coming from a dependency analysis of Deno, it doesn't touch the TypeScript compiler.

@socketwiz these are hard errors.  You have Deno enabled on the project, so you are getting errors in the code, because they are errors, pointing to code the Deno cannot run.

If you want Deno to be able to run this code (and therefore not have errors) you would need to use an import map to map the bare specifiers and configure the import map to be used by the language server (the `importMap` option).  If Deno shouldn't be analysing and running this code, you should disable Deno.  The language server supports multi-root workspaces to enable/disable parts of projects, but it specific to the language server integration/client, meaning you would need to have a `enable: false` setting for specific files you don't want errors for.

**Comment by socketwiz** [comment]
OK, I understand. Thank you for the explanation. I was hoping to use it for like auto completion, go to definition, and such and use eslint to analyze the code, but I guess I it wasn't designed for that type of thing, it is specific to "Deno" JavaScript, not very useful for JavaScript in general.
