### ISSUE TITLE
bad UX with prompt by default

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#13730]
In 1.19, dynamic imports are prompted even if they are never executed, which causes a bad UX/DX.

For example given something like this:

```js
const TextEncoder = globalThis.TextEncoder ??
  await import("./polyfill.js").TextEncoder;

console.log(TextEncoder);
```

When running under Deno, the dynamic import will never get executed, but:

```
> deno run example.js
⚠️  ️Deno requests read access to "polyfill.js". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  n
[Function: TextEncoder]
```

Whether permission is granted or denied, the code runs as expected.

With no prompt (and versions prior to 1.19):

```
> deno run --no-promot example.js
[Function: TextEncoder]
```

The real world usage is in adding support for Node.js for oak, I needed to dynamically import a couple modules if running under Node.js, so they never get loaded under Deno, but if people haven't granted permissions, they get prompted to load `node_shims.ts` and `http_server_node.ts`, which is very confusing user experience to say the least.

**Comment by rivy** [comment]
Similar ugly UI/UX occurs whenever "node/util.ts" is imported.

Because of a combination of requirements/decisions, "node/util.ts" can no longer be imported without an undesired prompt, unless `--no-prompt` is used or permissions are, by default, just granted.

```shell
$ deno run "https://deno.land/std@0.151.0/node/util.ts"
⚠️  ️Deno requests env access to "NODE_DEBUG". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]
```

Choosing allow or deny doesn't make a difference in the success of the import (just later util debug functionality), but this is a UI/UX wart which makes it impossible to present a more user-friendly UI/UX (as opposed to the now default dev-centered UI/UX).

Before https://github.com/denoland/deno_std/commit/8b34f7363501d17b059ab65575b985902ef190ba was merged, a quiet permission query was used, avoiding the prompt. But, because the query was async, it led to unexpected order of execution, with module being imported after other synchronous modules (see https://github.com/denoland/deno_std/issues/2097). And so, the code was changed to a `try ... catch` which now has the undesired behavior.

And there's no way that I can find to even test to make sure imported code won't prompt. So, just as the change from 'std@0.133.0' to 'std@0.135.0' unexpectedly added this prompt, any dependency change may add unexpected additional prompts which are confusing to users.

A fix would be returning to query-gating all code executed during import which requires permissions. But, to avoid the unexpected order of execution of imported modules, the query-gate would have to be synchronous.

**Comment by lucacasonato** [comment]
This is not the case anymore.
