### ISSUE TITLE
Support `deno run --no-cache` flag or `{ cache: false }` import option to prevent caching of imports

### ISSUE THREAD

**Issue by mimbrown** [denoland/deno#13754]
# Feature Request

I would like to be able to prevent Deno from caching imports on certain runs.

# Use Case

I want to build a tool that supports importing many different kinds of files, such as `.vue` and `.svelte` files, in a server-side dev environment (similar to the [`vite.ssrLoadModule`](https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server) function). I know of no good way to transform/compile a local import on the fly, so my solution is to use a local server and `import` the file using the localhost url. This works, except Deno detects those imports as remote, not local, so it caches them. I don't want those files cached, but I can't find any way to prevent it.

# Proposed API

I think ideally I would like to be able to disable caching on a per-import basis. This could be an extra flag on `import` options, maybe in a special `deno` section:

```js
import('http://localhost:8000/index.svelte', { deno: { cache: false } });
```

An alternative would be to support a `--no-cache` flag:

```
deno run --no-cache ...
```

**Comment by lucsoft** [comment]
its called --reload and its already a thing

**Comment by mimbrown** [comment]
> its called --reload and its already a thing

`--reload` is different. It tells Deno to bypass *checking* the cache for the requested import, but Deno still caches the requested code. I want a flag to tell Deno to bypass the cache entirely. Don't check it, don't add my `import`ed code to it. Just skip it. I don't want a bunch of `localhost` dev imports cluttering up my cache.

**Comment by ejsmith** [comment]
I think you are looking for this: https://github.com/denoland/deno/issues/1739

**Comment by ralyodio** [comment]
why was this closed?

**Comment by asyncanup** [comment]
yes, still need this

how about letting remote urls specifying caching behavior in their response with http cache headers?

**Comment by bastump987** [comment]
Agreed, this would be a great thing to have.  I am also importing local modules over HTTP (for the purposes of a plugin/module-federation-type architecture) and would really like to have these modules not cached.

You can _sort of_ work around caching imports by adding a query param to your dynamic import that contains a random number (saw this on a GitHub issue somewhere but forget where, sorry for no credit):
```TypeScript
const location = new URL('http://localhost:8080/myRemoteModule.ts');
location.searchParams.append('denoAntiCache', Math.random().toString());
```

The issue is that any imports required by the module that you just loaded over the network can still be served from Deno's cache...  So the above workaround is only useful for modules that have no dependencies.

It would completely solve the issue for me if Deno's caching behavior could be controlled by the presence of the `Cache-Control`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) header.

Ideally, I could have the server serving my local modules set `Cache-Control: no-cache` on all its responses.  This would remove the need for me to use the query param workaround and also prevent the need for adding `-r` flags for all the modules that I want to avoid caching.

**Comment by jespertheend** [comment]
If you have control over the server that hosts the scripts, you can include the cache bust pattern in the pathname itself.
So for instance:
```js
await import(`http://localhost:8080/${Date.now()}/myRemoteModule.ts`);
```

And then on the server[^1]:
```ts
import { route, type Route } from "@std/http/unstable-route";
import { serveDir } from "@std/http/file_server";

const routes: Route[] = [
  {
    pattern: new URLPattern({ pathname: "/:cacheBust/*" }),
    handler: (req, _info, params) => {
      serveDir(req, {
        urlRoot: `/${params?.pathname.groups.cacheBust}/`
      }),
    },
  },
];

function defaultHandler(_req: Request) {
  return new Response("Not found", { status: 404 });
}

Deno.serve(route(routes, defaultHandler));
```

This basically allows any string to be prepended to the path, causing any referenced dependencies to inherit the same cache bust value as the parent. As long as the imports are all relative anyway.

[^1]: I didn't test this exact code but hopefully it illustrates the mechanism.
