### ISSUE TITLE
Add fast path in TextDecoder for non streaming decodes

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#13829]
See https://github.com/denoland/deno/blob/main/ext/web/08_text_encoding.js#L98.

Currently for a non streaming decode we perform 3 native calls:

- `op_encoding_new_decoder` to create the decoder
- `op_encoding_decode` to actually perform the decoding
- `core.close` to destroy the decoder

For cases where `options.stream === false` this can be reduced to a single decode op.

To do this, add a new `op_encoding_decode_single` op that performs a single decode on a fresh decoder. Then add a JS fast path to the decode function.

**Comment by juank1809** [comment]
Can I be assigned to this issue? I'd be glad to help

**Comment by lucacasonato** [comment]
@juank1809 Yeah sounds good! I can't actually assign you to the issue, but just pretend I did 🙂

**Comment by randomicon00** [comment]
Hello @lucacasonato, is this issue still available for grabs? Thanks

**Comment by lucacasonato** [comment]
@randomicon00 Yup, @juank1809 never opened a PR.

**Comment by andreubotella** [comment]
> I am unsure about how to proceed though. Basically, I would like, if possible, have an idea about how different the `op_encoding_decode_single` op from the `op_encoding_new_decoder` and `op_encoding_decode` needs to be. Do we have to merge the two ops into a single one?

There is some amount of overhead when you call into an op and return from it. In the streaming case, having three ops (including the call to `core.close`) is justified because at most two of them will run in a single call to `TextDecoder.prototype.decode`, and because they perform logically distinct operations. But for the non-streaming case, you have all three op calls, and `op_encoding_new_decoder` and `core.close` just set up and tear down a resource that is only used for the `op_encoding_decode` call. The idea is to incorporate the decoder creation and the actual decoding in a single op, without storing the decoder as a resource.

For the record, when you've got something implemented, be sure to test it with the [web platform tests](https://deno.land/manual@v1.20.3/contributing/web_platform_tests). Since there are _a lot_ of WPT tests, you probably want to run just the encoding-related ones, which you can do with `./tools/wpt.ts run -- encoding`.

**Comment by randomicon00** [comment]
Ok @andreubotella. Thanks for the explanation. I will give it a go and implement the new op.

**Comment by randomicon00** [comment]
I've mostly understood the rust part. I think that, basically, there is no need send the `rid: ResourceId` back to javascript and just do all the decoding process in rust.  

However, I have a question related to the javascript part. 

Before switching to Rust, the js code performs some checks in order to copy that data prior to passing it to the `core.opSync` method. 

For the op `op_encoding_decode_single`, should we perform the checks and cloning of the input first? In other words, moving all `Uint8Array` creation logic up?

**Comment by andreubotella** [comment]
> Before switching to Rust, the js code performs some checks in order to copy that data prior to passing it to the `core.opSync` method.
> 
> For the op `op_encoding_decode_single`, should we perform the checks and cloning of the input first? In other words, moving all `Uint8Array` creation logic up?

I'm not sure if all of those checks and cloning are needed anymore, with the serde_v8 changes, but if they are needed for `op_encoding_decode`, they should be needed as well for `op_encoding_decode_single`.

**Comment by randomicon00** [comment]
@andreubotella Some tests are still failing. I've made the changes that I think are needed. I've kept the same logic.

`final result: failed. 75 passed; 16 failed; 0 expected failure; total 91`

```
        "/encoding/streams/decode-incomplete-input.any.html - incomplete input with error mode \"replacement\" should end with a replacement character"
        "/encoding/streams/decode-incomplete-input.any.html - incomplete input with error mode \"fatal\" should error the stream"
        "/encoding/streams/decode-incomplete-input.any.worker.html - incomplete input with error mode \"replacement\" should end with a replacement character"
        "/encoding/streams/decode-incomplete-input.any.worker.html - incomplete input with error mode \"fatal\" should error the stream"
        "/encoding/streams/decode-non-utf8.any.html - TextDecoderStream should be able to decode invalid sequences in UTF-16BE"
        "/encoding/streams/decode-non-utf8.any.html - TextDecoderStream should be able to reject invalid sequences in UTF-16BE"
        "/encoding/streams/decode-non-utf8.any.html - TextDecoderStream should be able to decode invalid sequences in UTF-16LE"
        "/encoding/streams/decode-non-utf8.any.html - TextDecoderStream should be able to reject invalid sequences in UTF-16LE"
        "/encoding/streams/decode-non-utf8.any.worker.html - TextDecoderStream should be able to decode invalid sequences in UTF-16BE"
        "/encoding/streams/decode-non-utf8.any.worker.html - TextDecoderStream should be able to reject invalid sequences in UTF-16BE"
        "/encoding/streams/decode-non-utf8.any.worker.html - TextDecoderStream should be able to decode invalid sequences in UTF-16LE"
        "/encoding/streams/decode-non-utf8.any.worker.html - TextDecoderStream should be able to reject invalid sequences in UTF-16LE"
        "/encoding/streams/decode-utf8.any.html - UTF-8 EOF handling - ArrayBuffer"
        "/encoding/streams/decode-utf8.any.html - UTF-8 EOF handling - SharedArrayBuffer"
        "/encoding/streams/decode-utf8.any.worker.html - UTF-8 EOF handling - ArrayBuffer"
        "/encoding/streams/decode-utf8.any.worker.html - UTF-8 EOF handling - SharedArrayBuffer"
        "/encoding/textdecoder-arguments.any.html - TextDecoder decode() with explicit undefined"
        "/encoding/textdecoder-arguments.any.html - TextDecoder decode() with undefined and undefined"
        "/encoding/textdecoder-arguments.any.html - TextDecoder decode() with undefined and options"
        "/encoding/textdecoder-arguments.any.worker.html - TextDecoder decode() with explicit undefined"
        "/encoding/textdecoder-arguments.any.worker.html - TextDecoder decode() with undefined and undefined"
        "/encoding/textdecoder-arguments.any.worker.html - TextDecoder decode() with undefined and options"
        "/encoding/textdecoder-copy.any.html - Modify buffer after passing it in (ArrayBuffer)"
        "/encoding/textdecoder-copy.any.html - Modify buffer after passing it in (SharedArrayBuffer)"
        "/encoding/textdecoder-copy.any.worker.html - Modify buffer after passing it in (ArrayBuffer)"
        "/encoding/textdecoder-copy.any.worker.html - Modify buffer after passing it in (SharedArrayBuffer)"
        "/encoding/textdecoder-eof.any.html - TextDecoder end-of-queue handling using stream: true"
        "/encoding/textdecoder-eof.any.worker.html - TextDecoder end-of-queue handling using stream: true"
        "/encoding/textdecoder-fatal-streaming.any.html - Fatal flag, streaming cases"
        "/encoding/textdecoder-fatal-streaming.any.worker.html - Fatal flag, streaming cases"
        "/encoding/textdecoder-streaming.any.html - Streaming decode: UTF-8 chunk tests (ArrayBuffer)"
        "/encoding/textdecoder-streaming.any.html - Streaming decode: UTF-8 chunk tests (SharedArrayBuffer)"
        "/encoding/textdecoder-streaming.any.worker.html - Streaming decode: UTF-8 chunk tests (ArrayBuffer)"
        "/encoding/textdecoder-streaming.any.worker.html - Streaming decode: UTF-8 chunk tests (SharedArrayBuffer)"

```


Should I give it a try and make a pull request so you can have a look? Or I could spend tomorrow exploring the tests a little bit more.

**Comment by andreubotella** [comment]
It looks like all of those failing tests use `{stream: true}` – either directly, or indirectly through `TextDecoderStream`. Please make sure that you only call into `op_encoding_decode_single` when `options.stream` is falsey and `this.#rid` is null.

The op implementation looks good. As you point out yourself, dropping the decoder in Rust by having `decoder` go out of scope is fine. The reason `core.close()` is needed is because the `Decoder` instance is a Rust value, and it can't be returned into JS. Rather than that, what `op_encoding_new_decoder` does is store the `Decoder` together with the fatal state in a resource table managed by Deno's runtime, and it returns an ID to that resource to JS. `core.close()` is needed to remove that resource from the table.

> Should I give it a try and make a pull request so you can have a look?

Usually reviews of an implementation happen in pull requests, not in the associated issue. Just mark the PR as a draft when you submit it.

**Comment by lucacasonato** [comment]
Yup, thanks.
