### ISSUE TITLE
atob and btoa are slower than node

### ISSUE THREAD

**Issue by ry** [denoland/deno#13838]
https://twitter.com/jarredsumner/status/1499715417773789185

**Comment by aapoalas** [comment]
Would it be best to have the `op_base64_decode` and `_encode` do all the work on Rust side?

ie.
`op_base64_decode` would return a `String` so that JS side doesn't have to do all the `Uint8Array` to `Array` to `string` mapping and joining.

`op_base64_encode` would take a `String`, check it for invalid characters and return an error if necessary (can ops directly return-throw a `DomException`? I see a lot of `DomExceptionSomething` in Rust code so I presume it's okay), convert to u8 slice and pass to `base64::encode_config`?
