### ISSUE TITLE
`WebAssembly.instantiateStreaming` panics when given a `URL` object

### ISSUE THREAD

**Issue by aslilac** [denoland/deno#13917]
```
➜  ~ deno                   
Deno 1.19.3
exit using ctrl+d or close()
> WebAssembly.instantiateStreaming(new URL("./index.wasm", `file://${Deno.cwd()}`), {})

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.19.3
Args: ["deno"]

thread 'main' panicked at 'already borrowed: BorrowMutError', core/bindings.rs:389:28
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: deno_core::bindings::promise_reject_callback
   4: __ZN2v88internal7Isolate19ReportPromiseRejectENS0_6HandleINS0_9JSPromiseEEENS2_INS0_6ObjectEEENS_18PromiseRejectEventE
   5: __ZN2v88internal9JSPromise6RejectENS0_6HandleIS1_EENS2_INS0_6ObjectEEEb
   6: __ZN2v812_GLOBAL__N_112_GLOBAL__N_137AsyncInstantiateCompileResultResolver19OnCompilationFailedENS_8internal6HandleINS3_6ObjectEEE
   7: __ZN2v813WasmStreaming5AbortENS_10MaybeLocalINS_5ValueEEE
   8: deno_core::ops_json::op_sync::{{closure}}
   9: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
  10: deno_core::ops::OpTable::route_op
  11: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
  12: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  13: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  14: __ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

...or at least I think that's what this is? The panic is consistent when trying to run this bit in the REPL tho.

**Comment by andreubotella** [comment]
This is not a bug with calling `WebAssembly.instantiateStreaming` with a URL, since calling it with `await` properly throws an exception:

```
> await WebAssembly.instantiateStreaming(new URL("https://google.com"))
Uncaught TypeError: Failed to call 'WebAssembly.compileStreaming': Argument 1 is not of type Response.
    at makeException (deno:ext/webidl/00_webidl.js:79:12)
    at Array.Response (deno:ext/webidl/00_webidl.js:866:15)
    at deno:ext/fetch/26_fetch.js:514:50
```

It instead seems to be a weird interaction of Deno's way of handling `WebAssembly.instantiateStreaming` with the rest of the event loop. This also happens if you pass a `Response.error()`, but oddly enough, not if you pass the result of calling `fetch` with a nonexistent URL.

**Comment by andreubotella** [comment]
When an exception is thrown during the processing of streaming wasm, `op_wasm_streaming_abort` is called. This op calls into V8, which _immediately_ rejects the promise returned from `WebAssembly.instantiateStreaming` with the passed exception, and immediately calls into the promise rejection handler if needed. But since `op_wasm_streaming_abort` is an op, calling it borrows the isolate's `JsRuntimeState`, which means it is borrowed when V8 calls into `promise_reject_callback`, which tries to borrow it again.

The panic doesn't happen if you call `WebAssembly.instantiateStreaming` with a promise that will reject because apparently V8 itself takes care of awaiting for the argument if it is a promise, and handling it if it rejects. In that case, Deno's `handleWasmStreaming` function never gets called.

One way to fix this would be making `op_wasm_streaming_abort` a binding again, and making extra sure that `v8::WasmStreaming::abort` is only called after the `JsRuntimeState` borrow is dropped.
