### ISSUE TITLE
New line between test files from `deno test` output

### ISSUE THREAD

**Issue by ydcjeff** [denoland/deno#13914]
I found that it is a little hard to find the test files from `deno test` output since they are printed out without new line.

![Screen Shot 2022-03-11 at 22 57 43](https://user-images.githubusercontent.com/32727188/157908357-064a6cb1-fdde-42d1-8fa1-980a564b34cb.png)

I propose to add one new line before `running n tests from ...` so that tests are visually grouped by its own file which could look like a section.

Thanks!

**Comment by bartlomieju** [comment]
We've added different color of "running N tests from ..." prompt which allows to easier differentiate the report. I also experimented in adding empty lines between the files, but it wasn't a good solution due to some technicalities in test reporters. I'm considering this solved by different color prompt.
