### ISSUE TITLE
lsp: information being returned as info versus error

### ISSUE THREAD

**Issue by tclzcja** [denoland/deno#13975]
Hi there, recently I'm getting a deno-ts message from a typo:

> Property 'ok' may not exist on type 'typeof import("file:///Users/.../assert")'. Did you mean 'Ok'? deno-ts(2568)

The information is totally correct, I mis-spelled ok with a lowercase o. I just wonder is there a way I can leverage it as an error in VS Code? Currently it's displayed as an information only, see screenshots:

<img width="76" alt="Screenshot 2022-03-16 at 12 14 11 PM" src="https://user-images.githubusercontent.com/20711476/158515673-d37f0af9-86dc-4888-a692-793280a57d76.png">

<img width="103" alt="Screenshot 2022-03-16 at 12 14 21 PM" src="https://user-images.githubusercontent.com/20711476/158515690-b39d8fb6-4782-45fb-942a-71a346c88b3d.png">

Thank you!

**Comment by kitsonk** [comment]
Moved this from `deno_lint` as it has nothing to do with that.

Can you provide more information, like what version of Deno you are using, what version of the vscode_deno extension you are using, and what type of file this is (e.g. TypeScript or JavaScript)?

If it is JavaScript file, this is the expected behaviour, because it is only advisory.  If you want JavaScript to be checked, you can either set it as a compiler option in your `deno.jsonc` or you can add `// @ts-check` somewhere near the top of your file. This will cause information messages like that to become errors.

**Comment by tclzcja** [comment]
Thank you, sorry for the trouble, my bad.

And yes it is a .js file I'm editing. I'm running Deno 1.19.3 with VS Code Deno extension v3.10.1.

I've modified my deno.json, however it's still being displayed as information. Here's my deno.json:

`
{
	"checkJs": true,
	"compilerOptions": {
		"allowJs": true,
		"strict": true,
		"checkJs": true
	},
	"lint": {
		"rules": {
			"include": ["no-explicit-any"]
		}
	}
}
`

and here's my workspace setting JSON:

`
{
	"settings": {
		"deno.enable": true,
		"deno.lint": true,
		"deno.unstable": true,
		"deno.config": "./deno.json"
	}
}
`
