### ISSUE TITLE
feat(cli): `deno shell` subcommand

### ISSUE THREAD

**Issue by c4spar** [denoland/deno#14068]
Since there is `deno task` and `deno_task_shell`, it would be neat if there was also a `deno shell` subcommand that works like a real shell. I was thinking of the following features:

- Run deno shell commands on commandline: `deno shell -c "ls | wc -l"` and `echo "ls | wc -l" | deno shell`
- Start a deno shell/repl with: `deno shell`
- Execute scripts as deno shell scripts if it starts with a deno shell shebang: `#!/usr/bin/env -S deno shell`

    This would enable support of moving large deno tasks into files:

    > ./deno.json

    ```json
    {
      "tasks": {
        "build": "./my_task"
      }
    }
    ```

    > ./my_task

    ```shell
    #!/usr/bin/env -S deno shell

    ls | wc -l
    # ...
    ```

**Comment by nayeemrmn** [comment]
I had a proposal in mind where `deno task foo/bar.sh`, if it couldn't find a task named `"foo/bar.sh"`, would next try to resolve it as a path and read that file as a script. That way it could be used to run unabashed `.sh` scripts on Windows. I figured there could be a `deno task -c "ls | wc -l"` as well. I still think such a design would be really cool since pretty much the whole motivation for `deno task` can be traced back to not being able to run `.sh` scripts on Windows.

However, IMO `deno_task_shell` needs feature-parity with `/bin/dash` at a minimum to make this desirable and it seems a lot of that has been deemed out of scope. The thought is that more complex scripts should be written as JS/TS. Ref [brief discord convo](https://discord.com/channels/684898665143206084/684911491035430919/954223383204216852).

**Comment by dsherret** [comment]
This would be a hard sell because we have a scripting language in the binary already for running JavaScript and TypeScript files. In the case of `deno task`, the purpose is to provide an easy way to alias commands you run on the command line—provide as close to a 1-1 mapping between what you execute on the command line and what you want to save for others to execute.

See https://github.com/denoland/deno_task_shell/issues/23 for details on executing a ts or js file with a shebang cross platform.

I think what would be neat is for someone to develop a Deno module that reduces the verbosity of doing `sh`-like stuff in JS/TS (ex. piping between processes).

**Comment by dsherret** [comment]
It's a massive problem to get shell scripts working out of the box on Windows and to do this we would have to add compatibility for many more commands. For example, neither `ls` or `wc` used in the example above work on Windows. This might be something better suited for a separate tool. Then if someone would like, they could execute this tool by adding an alias for it in the "tasks" in the config file, then execute it with `deno task <task-name>`.

**Comment by nayeemrmn** [comment]
> we would have to add compatibility for many more commands. For example, neither `ls` or `wc` used in the example above work on Windows

Of course it would always be a subset, the appeal is being _compatible_ with the unix shell ecosystem. This shouldn't only be brought up as an issue when it is suggested to instead put task code in a file that can _also_ be run by a unix shell. Whether this way or that way, most of the time that code will be a one liner `deno` command that will just work.

**Comment by c4spar** [comment]
I agree that a *real shell* would be a bit out of scope from deno and yes we already have a cross plattform scripting language 🙂 

As @nayeemrmn sad, it should be still only a subset and not a full implementation of a shell and all available commands. Maybe the word **real shell** was not the best choice. I was mostly thinking about a repl and support for piping to or from a `deno shell/task -c "..."` command. The repl would be nice for trying out deno task commands.

> I think what would be neat is for someone to develop a Deno module that reduces the verbosity of doing sh-like stuff in JS/TS (ex. piping between processes).

The main motivation of this proposal was indeed to add support for deno tasks to tools like [zx](https://github.com/google/zx) and [dzx](https://github.com/c4spar/deno-dzx). And with a `deno shell -c "..."` or a `deno task -c""` command it could be easy to add support for this.

Than we could write den task in deno scripts this way:

```ts
await $`ls | wc -l`).pipe(Deno.stdout);
```

But this could be also solved with some proper deno bindings for [deno_task_shell](https://crates.io/crates/deno_task_shell) which would also remove the overhead of spawning a subprocess. I already tried to create some [deno task shell bindings](https://github.com/c4spar/deno-shell) and it arleady works to execute deno tasks in deno scripts 🙂 But i'm a total rust noop and its my very first rust project 😅. Would be nice if there were some official deno bindings for `deno_task_shell`. Anything planned in this direction?

**Comment by ry** [comment]
Deno is for executing JavaScript and TypeScript, not shell.
