### ISSUE TITLE
Worker's postMessage not working

### ISSUE THREAD

**Issue by finlaydotb** [denoland/deno#14098]
Starting a working like this:

```
const worker = new Worker(new URL("workers/worker.ts", import.meta.url).href, {
    type: "module",
    deno: {
        namespace: true,
    }
} as any);
worker.postMessage({data: "hello world"})
```

and in `workers/worker.ts` I have:

```
self.onmessage = async (e: any) => {
    console.log("hello there")
    const { data } = e.data;
  };
  ```

Basically following the pattern of the code as documented in the manual here https://deno.land/manual/runtime/workers

But the above does not work, in the sense that the `postMessage` never triggers the code in the `self.onmessage` handler. And what makes this difficult to debug is the absence of any error logs.

Any ideas what could be going wrong? Or any tips on how to get more information (debug etc) that could be useful in troubleshooting?

I have to mention, this was working around last year when i last touched the app. Only difference from then and now was that I upgraded deno

**Comment by andreubotella** [comment]
Is that the entirety of `workers/worker.ts`? If you do `await` before setting `self.onmessage`, messages can be lost (not a bug, just an unfortunate combination of things that don't play nice – this can also happen in browsers), but if that is all of it, then it is a bug in Deno.

**Comment by finlaydotb** [comment]
> Is that the entirety of workers/worker.ts? If you do await before setting self.onmessage ...

I do not have an await before the `self.onmessage`. So unfortunately that is not the problem :(

**Comment by finlaydotb** [comment]
I think I might have identified a situation where it does not work. In `workers/worker.ts` I have some class that I import and instantiate. If I comment out the line of instantiation, it works! If I move the class definition into `workers/worker.ts` and instantiate, that also works!

The `postMessage` only breaks if I import the class definition and then create an instance of it.

That is just strange! any ideas what could be going wrong?

**Comment by andreubotella** [comment]
That's odd, static imports should be resolved before any events are fired, but maybe there's a bug there. Just to check, is there any top-level `await` in that imported file, or in its dependencies? No matter if it's before the class definition or after it.

If you're using Typescript, unused imports get removed, so that's probably what you're seeing if things work when you comment out all uses of the class. It's probably not something directly related to instantiating the class.

**Comment by Macil** [comment]
Importing a dependency can cause this issue if it (or a sub-dependency) uses top-level await.

It took me a while to notice this issue and then to figure out the cause. It would be great if Deno was able to handle this situation or at least log a warning in the case that a worker gains a message event handler late.

**Comment by Macil** [comment]
I made an easy drop-in workaround for when this issue is caused by top-level await (whether in the worker itself or in an imported dependency):

```ts
import { addMessageEventListener } from "https://deno.land/x/worker_message_queuer@v1.0.1/mod.ts";
import { exampleFunction } from "example/module-using-top-level-await";

addMessageEventListener((event) => {
  console.log("Received message:", event.data);
});
```

The [worker-message-queuer module](https://github.com/Macil/worker-message-queuer/blob/main/mod.ts) immediately attaches a message event handler that queues up events, which will happen synchronously if this module is statically imported from a worker module, and then the `addMessageEventListener` function can be called later to replace the message event listener and to process all the queued message events.
