### ISSUE TITLE
REPL: parse error for bare `module` identifier

### ISSUE THREAD

**Issue by chocolateboy** [denoland/deno#14126]
I would expect `module` to work like any other identifier, but that doesn't appear to be the case.

> $ deno

```
Deno 1.20.3
exit using ctrl+d or close()

> const foo = 42
undefined
> foo
42

> const module = 'left-pad'
undefined
> module
parse error: Unexpected eof at 1:7
> module.length
8
> module;
"left-pad"
> (module)
"left-pad"
```

It works fine in scripts:

> $ cat ./script.js

```javascript
const module = 'left-pad'
console.log(module)
module
```

> $ deno run ./script.js

```
left-pad
```

I'm guessing this is ASI-related (it's mentioned [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#automatic_semicolon_insertion) (section 3) as some kind of statement, though I can't find any other references to it), but if it is interpreted as a built-in statement, I would expect it to be prohibited as an identifier, e.g.:

> $ deno

```
Deno 1.20.3
exit using ctrl+d or close()
> const continue = 42
parse error: Expected ident at 1:7
```

---

> $ deno --version

- deno: 1.20.3 (release, x86_64-unknown-linux-gnu)
- v8: 10.0.139.6
- typescript: 4.6.2

**Comment by kitsonk** [comment]
A few points here, when you do `deno run` code is _always_ interpreted and loaded as an ES module.  With Deno run, there is actually no way to force Deno to interpret code in script mode. On the converse, the REPL _has_ to interpret in script mode, because ES Modules are "closed" and can't be appended to.  There are a few things we do to try to make it feel more "module" like, like allowing "static" import statements and running in strict mode, and supporting top level await, but we are basically playing around with script mode.

As you pointed out, `module` is a JavaScript reserved word that is lexically parsed applying ASI rules, and the example code runs afoul of how the keyword should be parsed in script mode, and so you have hit an edge-case that only effects the REPL.

I am afraid it is an edge case that would be difficult if not impossible to support, and as you note, `module;` works around the issue.  It is a design limitation.

**Comment by chocolateboy** [comment]
Thanks for the explanation!

> As you pointed out, `module` is a JavaScript reserved word that is lexically parsed applying ASI rules, and the example code runs afoul of how the keyword should be parsed in script mode

Just to be clear, the only source for that claim appears to be that MDN article. I can't find any reference to it as a reserved word in the [spec](https://tc39.es/ecma262/#sec-keywords-and-reserved-words), and it's not treated as such in other environments such as the Firefox web console or node (where, of course, it's passed as a parameter to `require`d scripts), e.g.:

## Node.js

### REPL

```
> const module = 'left-pad'
undefined
> module
'left-pad'
```

### CLI

> $ node ./script.js

```
SyntaxError: Identifier 'module' has already been declared
```

## Spidermonkey

### REPL

```
js> const module = 'left-pad'
js> module
"left-pad"
```

### CLI

> $ spidermonkey ./script.js

```
left-pad
```

## QuickJS

### REPL

```
qjs > const module = 'left-pad'
undefined
qjs > module
"left-pad"
```

### CLI

> $ qjs --script ./script.js

```
left-pad
```

**Comment by chocolateboy** [comment]
FYI, this was a [bug](https://github.com/swc-project/swc/issues/4176) in swc (and in the [MDN docs](https://github.com/mdn/content/pull/14409)), which is [fixed](https://github.com/swc-project/swc/pull/7400) in the latest version.
