### ISSUE TITLE
Consider making `Deno.core.ops` not user-accessible

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#14137]
`ops/lib.rs` has the following safety comment:

https://github.com/denoland/deno/blob/226209714168e5b85410db773f06debb7cf34511/ops/lib.rs#L120-L123

But `Deno.core.ops` is user-accessible, and its functions can be called by the user, so this guarantee does not necessarily hold.

**Comment by WingZer0o** [comment]
@andreubotella 

Is there a pull request that this was addressed in to take a look at? These three lines of code no longer exist within main.

**Comment by andreubotella** [comment]
It seems like this was fixed in #14228.

**Comment by aapoalas** [comment]
While the original safety issue was fixed, I'm not sure that there aren't any more of them. Additionally, if garbage collectable resources become a thing using `v8::External` objects, then the V8 API dictates that embedders should guarantee that either any two `v8::External` objects can be interchanged safely (ie. the external pointers can be interchanged), or alternatively it should be guaranteed that the wrong object cannot be used in an unrelated API.

The former could be possible if all `External`s internally implemented the same `Resource<T>` trait, but that cannot be guaranteed if FFI also uses `External`s to pass pointers. Then, the only choice becomes to make sure that the wrong object cannot be used. Since FFI may/will provide a way to create `External` objects (at worst, from plain numbers) it means that one cannot rely on `External` objects simply not being exposed to be used in unrelated APIs. The only choice thus becomes to make sure that those unrelated APIs are not exposed, meaning that raw ops should not be user-accessible and that internal usage of ops should always, only and ever work when called with eg. proper classes where an internal property contains the resource pointer in an `External`.
