### ISSUE TITLE
Allow key in deno.json for storing custom data?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#14241]
In the node ecosystem, a lot of tools allow users to store their configuration in the package.json file. For example, prettier:

```jsonc
{
  "name": "example",
  "version": "1.0.0",
  "prettier": {
    // prettier config goes here
  }
}
```

The advantage of this is that users don't need to add yet another configuration file to their directory. The disadvantage is that it creates a free for all in the package.json file where npm needs to be careful about adding future properties because they might conflict with userland properties.

In deno.json, we error when an unknown key exists, which I think makes a lot of sense. That said, perhaps we should allow for a property where people can store whatever they want in it.

For example (not sure about the name of the key):

```jsonc
{
  "thirdParty": {
    "myTool": {
      // my tool config goes here
    }
  }
}
```

**Comment by bartlomieju** [comment]
> In deno.json, we error when an unknown key exists, which I think makes a lot of sense. That said, perhaps we should allow for a property where people can store whatever they want in it.

When does that situation happen?

**Comment by vwkd** [comment]
The idea to merge all configs into a single config file seems a poor attempt to only cures the symptom instead of the cause.

The cause is that the UI is cluttered by many files. So maybe this should be changed by the UI, e.g. hide dot files.

There are more reasons why a single config file likely isn’t ideal:
- finding a file is often easier than a position in a text
- version history is better, e.g. search when a file was changed instead of specific part of same file
- configs don’t necessarily need to be JSON, so the argument to reduce clutter fails anyways if merging isn’t even always possible

**Comment by dsherret** [comment]
I don't thinking hiding configuration files is a good solution for config files, but anyway I was thinking about this more this weekend and I think that having this property is confusing and so for that reason I'm going to close this suggestion.
