### ISSUE TITLE
[fmt] Recent upgrade causes short if statement to be split on multiple lines

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#14291]
Did something change in deno fmt in recent updates? I'm seeing some weird things going on and i just saw a couple others mention it on my libs server so i thought id come ask. I did `deno upgrade` and then `deno fmt` and suddenly:

![image](https://user-images.githubusercontent.com/23035000/163563413-07cd8a75-7a91-4613-8f38-8fdc803b623d.png)

It's Col 32, not like its 150 or something so it shouldnt be wrapping 

![image](https://user-images.githubusercontent.com/23035000/163563433-e5ce74e1-7912-41cd-9961-1b88d953f1f3.png)

**Minimal Example:** Please note a lot of this code does not make sense as i had to remove a lot of lines and just make it ugly to make it minimal to show the problem happening.

```ts
const createGatewayManager = {} as any;

let gateway: any;
let workerId: number;

function spawnGateway(shardId: number, options: Partial<any>) {
  gateway = createGatewayManager({
    handleDiscordPayload: async function handleDiscordPayload(_: any, data: any, shardId: any) {
      const id = (data.t && ["GUILD_CREATE", "GUILD_DELETE", "GUILD_UPDATE"].includes(data.t)
        ? (data.d as any)?.id
        : (data.d as any)?.guild_id) ?? "000000000000000000";

      // IF FINAL SHARD BECAME READY TRIGGER NEXT WORKER
      if (data.t === "READY") {
        console.log(`[Worker #${workerId}]`, `[Worker] Shard #${shardId} online`);
      }
    },
  });
}
```

```json
{
  "fmt": {
    "files": {
      "exclude": ["benchmarks/", "site/node_modules/", "site/build", "site/.docusaurus", "site/.cache-loader"]
    },
    "options": {
      "lineWidth": 120
    }
  }
}
```

```json
{
  "deno.enable": true,
  "deno.lint": false,
  "deno.unstable": true,
  "editor.defaultFormatter": "denoland.vscode-deno",
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.fixAll": true
  }
}
```

**Comment by meister03** [comment]
Noticed this too, its destroying my git commit history 🙈

**Comment by lts20050703** [comment]
Can confirm.
1.20.3 `deno fmt` output no files
1.20.4 `deno fmt` has a """regression""" (not sure if this is intentional or it's dprint changing)
```ts
a
? b
: c
```
changed to
```
a
  ? b
  : c
```
1.20.5 has the same """regression""" as 1.20.4
1.20.6 has the same """regression""" as 1.20.4, plus this one where it split if statements into multiple lines

**Comment by dsherret** [comment]
@lts20050703 that was an actual bug.

The other issue with the if statement I have a fix incoming (just doing some testing). Basically some state in dprint's core library wasn't being updated to account for line numbers changing.

For now, I would recommend exclusing the problem files in the deno.json file. It will be fixed in the next release on Wednesday.

If people want to post a revision in their repos I can try this on to ensure it's fixed that would be helpful. Thanks and sorry about this bug!
