### ISSUE TITLE
Consider supporting non-`GET` methods for `fetch` with `file:` urls

### ISSUE THREAD

**Issue by jed** [denoland/deno#14356]
As of [1.16](https://deno.land/manual@main/runtime/web_platform_apis#fetching-local-files), Deno supports `GET` with `file:` urls as a web-standard version of `Deno.readFile`. It would be nice to extend this other methods like `PUT` (`Deno.writeFile`) and `DELETE` (`Deno.remove`) as well, allowing developers to manipulate the file system using well-understood, standard APIs.

**Comment by nayeemrmn** [comment]
I am against. Reading files through `fetch()` is important because it brings parity to when a module is reading a sibling file as a local module vs a remote module. Writing a file through `fetch()` as a remote module is almost never going to work.

**Comment by lucacasonato** [comment]
I agree with @nayeemrmn on this. Local file reads with `fetch` is already a shaky abstraction at best, but can be explained relatively simply, which is why I agreed to landing it. Local file writes via `fetch` have no browser precedent, have no established API in other systems, and also pose much more challenging questions, like listing directories via local file fetch.
