### ISSUE TITLE
Is it possible add `deno.toml` as configuration file ?

### ISSUE THREAD

**Issue by roadupcc** [denoland/deno#14376]
As configuration file, `toml`file are more friendly. similar to rust project.
`json` or `jsonc` contains more noise.

**Comment by bartlomieju** [comment]
While I have no objections and there are no technical challenges in supporting TOML as a configuration format, it is somewhat questionable if we should do it. If we add support for TOML, then soon we'll have to add support for YAML as well. That would mean probing file system 4 times in each location to find a configuration file (`deno.json`, `deno.jsonc`, `deno.toml`, `deno.yaml`).

I'm also pretty sure other team members are not gonna be keen on adding it.

**Comment by Duelsik** [comment]
Random programmer perspective:

It sounds cool, but adding more config formats will result in dispute about which one is "the best" + will create a need to understand multiple formats in order to get into programming with deno - learning curve will be impacted in negative way and beginner seeking help will have to understand both notations in order to figure out if they have a problem with config.

I really like idea of moving away of json, but it has very strong side - it is not relying on white-space to be interpreted in the correct way.
Adding toml maybe will fit some personal preferences but will rise overall community noise.

(I am kinda scared that more and more formats will be supported and options will make the config options bloated)

As a middle ground - it could be a special task that is executed each time config is interpreted:
1. Interpret config, check if there is "update_config" task.
2. If no - jump to point 4
3. Run this task, interpret the config again.
4. Run initial task
This way - config will stay in json and it will be very clear that deno supports only json.
But - you could setup an "update_config" to run something that parses any file format and then outputs it in json.

I am pretty sure that there are a ton of downsides to my "middle ground", but imo it is a good starting point to:
- Does deno support **insert random config format or config method here**?
- Yes, as long as it outputs json

**Comment by dsherret** [comment]
I strongly believe we should only have one configuration file format. Adding a second way of doing things complicates all the tooling that reads or programatically manipulate a configuration file and it increases the number of places we have to search for a possible configuration file.

**Comment by roadupcc** [comment]
@dsherret @Duelsik @bartlomieju 
yes, I see, thank you

**Comment by anonhostpi** [comment]
> Adding a second way of doing things complicates all the tooling that reads or programatically manipulates a configuration file (everything has to be implemented twice) and it increases the number of places we have to search for a possible configuration file.

I mean one solution to that problem would just be to use a serde library that doesn't care about file format or extension.

Considering how popular the serde topic is within the Rust community, there's probably well over a double-dozen different serde libs/implementations for _that exact statement_ at this point.

Considering:

- the _primary_ format is JSON
- almost any reasonable serde format would be JSON-based (such as JSONC, YAML, TOML, etc),
- the availability of serde tooling in Rust

I, myself, am not convinced this would be hard or unreasonable to implement.
