### ISSUE TITLE
(bug) `Deno.isatty` returns true for wrong resource ids

### ISSUE THREAD

**Issue by Danielduel** [denoland/deno#14398]
(Arch 5.17)
`Deno.isatty` works differently to node `TTY.isatty`

Canary deno:
```
Deno 1.21.0+e24b8f0
exit using ctrl+d or close()
> Deno.isatty(-1)
true
```

Latest deno:
```
Deno 1.21.0
exit using ctrl+d or close()
> Deno.isatty(-1)
true
```

Expected behavior:
```
Deno 1.19.0
exit using ctrl+d or close()
> Deno.isatty(-1)
Uncaught BadResource: Bad resource ID
    at Object.opSync (deno:core/01_core.js:168:12)
    at Object.isatty (deno:runtime/js/40_tty.js:12:17)
    at <anonymous>:2:6
```

I think the change should be done in https://github.com/denoland/deno/blob/main/runtime/ops/tty.rs#L203, but I don't know rust that well to be sure that I will not break anything fixing that :)

**Comment by cjihrig** [comment]
It looks like the value -1 is being incorrectly converted to 0. In `Deno.isatty()` and `opSync()`, the value is -1, but by the time `op_isatty()` is called on the Rust side, the value has become 0.

**Comment by Duelsik** [comment]
> It looks like the value -1 is being incorrectly converted to 0. In `Deno.isatty()` and `opSync()`, the value is -1, but by the time `op_isatty()` is called on the Rust side, the value has become 0.

afaik it was something with parsing `-1` to string on some level, which converted `-` to falsy to `0` to `tty0` or sth like that
(0% sure, it was on discord briefly)

**Comment by kitsonk** [comment]
This is causing a std library failure with the test `node/tty_test.ts:[node/tty isatty] returns false for irrelevant values`.  Not sure why it isn't causing CI to fail, but caught it locally.

**Comment by cjihrig** [comment]
The problem seems to be coming from [here](https://github.com/denoland/deno/blob/d0dec8d36b751638d15a44ef790a36049f1bc359/serde_v8/de.rs#L104-L105). The original value of -1 becomes -1.0, which `as u32` converts into 0 (interestingly, -1 as a signed integer would be converted to 4294967295).

An easy fix for the issue is to update `Deno.isatty()` to use `rid >>> 0` to force the value to an unsigned integer in JavaScript, but the underlying problem will still exist everywhere else we deal with unsigned numbers.

A better solution might be to update `deserialize_unsigned` to cast to a signed integer first before casting to an unsigned integer so that the floating point portion of the number stops causing problems.

@AaronO any thoughts?

**Comment by lucacasonato** [comment]
`Deno.isatty()` has been removed in Deno 2.
