### ISSUE TITLE
perf: Lazy load HTTP headers to JS

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#14433]
Avoid serializing request headers for every request unless it's actually read from the user code.

**Comment by lucacasonato** [comment]
We should be very careful with this. It may be slower depending on what the user is doing. Just because a hello world benchmark does not read incoming headers, that doesn't mean a real world app wouldn't. I don't think we should optimize something if it benefits the hello world benchmark, but makes real applications slower.

**Comment by littledivy** [comment]
`ext/http` and `ext/flash` both do this.
