### ISSUE TITLE
Remove Deno.emit

### ISSUE THREAD

**Issue by ry** [denoland/deno#14461]
Should be handled by external code, not built into runtime. deno_ast, deno_graph largely contain this functionality 

Aiming for 1.22.0

**Comment by dsherret** [comment]
I think we should create a wasm version of `Deno.emit` before doing this or have some documented alternatives? That way users can transition over to it.

**Comment by ry** [comment]
We've been wanting to do this for over a year now - nothing has yet materialized in third party. We'll remove in 1.22 and that will provide a good impetus. Of course if it's done ahead of time, that would be better, but I don't want to delay this removal for more months.

**Comment by AnInternetTroll** [comment]
A deprecated tag on the jsdoc would have been nice to show that you intend to remove Deno.emit. Otherwise it's just out of the blue

As of now there is nothing indicating any intention of removal on https://doc.deno.land/deno/unstable/~/Deno.emit and unless you follow all conversations on discord there never really was any outspoken intention of removal

**Comment by AnInternetTroll** [comment]
That is true, but a bit more communication couldn't hurt

**Comment by KnorpelSenf** [comment]
There's no indication at https://deno.land/manual/typescript/runtime that the feature will be removed, either. I wasn't aware that this is being considered.

Now that we suddenly have to rewrite `Deno.emit` very fast in user land before 1.22 hits, can you suggest where to start with this? For example, can we wrap `ts_morph`?

What do you think about moving this to `/std` instead of dropping it completely?

**Comment by lowlighter** [comment]
> it’s unstable so anything can change at any time.

The [documentation about stability](https://deno.land/manual/runtime/stability) doesn't explicit state that said feature is subject to removal though:

> However, not all of Deno's features are ready for production yet. Features which are not ready, because they are still in draft phase, are locked behind the `--unstable` command line flag.
>
> You should be aware that many unstable APIs have **not undergone a security review**, are likely to have **breaking API changes** in the future, and are **not ready for production**.

It only suggest that a feature usage may change or is unsecure but will *eventually* stabilize, *not* that its support could be entirely dropped. 

I think a full removal implies a lot more than just "breaking API changes", even for unstable features, especially if there are no alternatives yet. 

Though it could be that I misunderstand what the documentation was trying to said too 🤔

**Comment by buttercubz** [comment]
> This is a widely used API and not having an alternative ready to go will cause a huge amount of distrust in our user base. Opening an issue to removing something widely used in a release a couple weeks will break a lot of existing solutions, causing people to not be able to upgrade.
> 
> Feels very irresponsible to me.

yes, currently the [deno-rollup](https://github.com/cmorten/deno-rollup) is broken, because of this any library or package that is making use of it is also [snel](https://github.com/crewdevio/Snel) for example, for now the most feasible replacement seems to be esbuild, I think that in the future it would be better to add the tag deprecated before removing completely to allow time for replacement

**Comment by lowlighter** [comment]
> @lowlighter in this case, the feature ended up being not really removed, but moved to deno.land/x

Tbh I'm fine with it being in deno land.
The initial issue title/content suggested that it was being removed while no credible alternative were provided

On a side note, I feel like that these kind of APIs should have their own namespace on deno.land (like deno.land/std) rather than using the global deno.land/x, since these features seems to be backed by deno team. Could also avoid possible name collisions in the future
