### ISSUE TITLE
Port tools/http_server.py to Rust, merge with hyper_hello

### ISSUE THREAD

**Issue by ry** [denoland/deno#1453]
Be forewarned: This issue is seemingly relatively easy, but it will likely take a great deal of work to make it green. I'd roughly estimate it would be 2 days of work for myself.

Many of our tests depend on a local http server running on localhost:4545 .. this server is currently implemented in python 
https://github.com/denoland/deno/blob/e809673cecef8383d4b3e873de260b35182d2ef9/tools/http_server.py

We would like to reduce our dependencies on python over time, and we already have all the infrastructure available to implement this in Rust using Hyper.

**Comment by bokuweb** [comment]
@ry Hi :) I would like to try this issue. So I have a question. How should I run `Rust http.server` from `tools/test.py` ? Specifically, what should I do now to run `hyper_hello` from `tools/test.py`?

**Comment by hermesespinola** [comment]
Hi! I see it's been over a year since the last comment, I would like to take this as my first issue if no one else is working on this :)

**Comment by bartlomieju** [comment]
Hey @hermesespinola I was supposed to work on that, but if you want to give it a try then go ahead! 

This issue is quite complex and I'd suggest tackling it in a few steps:
a) get simple server from `tools/http_server.py` ported as `warp` server (eg. `redirect_server`)
b) hook it up into `test_util::http_server()` so it's created along with servers from `tools/http_server.py`
c) port more servers from `http_server.py`
d) refactor `test_util::http_server()` to work in parallel

The very first PR should consist only of a) and b) - integration with `http_util::http_server()` might be hard, feel free to ping me

**Comment by hermesespinola** [comment]
@bartlomieju I would like to give it a try, thanks for the advice, I'll reach to you if I have any questions.

**Comment by humancalico** [comment]
@hermesespinola What's the status on this? If you're not working on it I'd like to give it a try

**Comment by bartlomieju** [comment]
@humancalico AFAIK no one is working on this problem and I planned to work on it this week. Reach me out on Discord if you want to discuss details.

**Comment by hermesespinola** [comment]
Hi @humancalico, sorry I've been working on other stuff since then, please, take it!
I have code for setting up the test_server with hyper, I can share it with you and explain my approach if you'd like.

**Comment by bartlomieju** [comment]
Done in https://github.com/denoland/deno/pull/6364
