### ISSUE TITLE
Add LSP configuration to deno.json(c)

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#14541]
Currently [`vscode_deno`](https://github.com/denoland/vscode_deno) uses `.vscode/settings.json` to enable Deno extension. The simplest configuration looks like so:
```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true
}
```

@ry proposed that we should replace this configuration with a new key in `deno.json(c)` file (`"lsp"`), that would allow to configure editors using a single file. That way, editors supporting LSP protocol could use `deno lsp` based on the configuration coming from Deno's config file. The above configuration would instead look like so:
```json
{
  "lsp": {
     "unstable": true,
     "lint": true
  }
}
```

Notice that `deno.enable` true is not specified here, as we believe that LSP should be activated automatically if config file is discovered.

CC @kitsonk

**Comment by kitsonk** [comment]
This is slightly incorrect. VSCode has multiple levels of configuration, of which the most specific, is stored in the `.vscode/setting.json`, this isn't something the extension controls, the extensions simply requests certain settings to be adjusted (or a user configures the setting themselves, either through the GUI or manually) and vscode stores them.

We should not interfere with that. Adding and "lsp" section to the deno.jsonc would make the whole thing a lot more confusing and less portable. Specifically with the vscode extension, the extension and the lsp have to be in sync, so that the lsp can provide diagnostics and that the client can "mute" the built in diagnostics. If they are out of sync, there are big usability issues. The only reliable way to do this is to have the client drive the enablement (as well as other adjustments to configuration of the lsp, as it is configuration of how the editor behaves).

Just because vscode stores workspace settings in the `.vscode/settings.json` should be immaterial to us, it stores "project" settings in a different way, and stores user level ones another different way. Both the client and the server are abstracted away from these, and simply using the configuration APIs provided by the editor.

**Comment by lucacasonato** [comment]
I agree with @kitsonk. An other issue is that deno.json is shared between developers, but not all developers likely want the same LSP configuration. LSP configuration is not just per project, but rather per developer per project.
