### ISSUE TITLE
Generated TypeScript definitions not compatible with Deno

### ISSUE THREAD

**Issue by tbranyen** [denoland/deno#14564]
I generate TypeScript definitions using `tsc --emitDeclarationOnly` and reference using triple forward slash.

_index.js_:

```js
/// <reference types="./index.d.ts" />
export * from './dist/es/index.js';
```
_index.d.ts_:

```js
import { __VERSION__ as VERSION } from "./version";
export { VERSION };
```

I import with:

```js
import { VERSION } from './index.js';
```

When I run this code with:

```
deno run --reload index.ts
````

I get the following error:

```
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member '__VERSION__'.
import { __VERSION__ as VERSION } from "./version";
```

If I manually edit the generated `index.d.ts` file and give the import an extension, denos runs without erroring.

```js
import { __VERSION__ as VERSION } from "./version.d.ts";
export { VERSION };
```

I can't find an option in `tsc` to generate definitions with extensions. Is this a bug in deno or should I raise the concern with TypeScript? I would expect Deno to be able to resolve sibling `d.ts` files without requiring a known extension.

**Comment by dsherret** [comment]
> I would expect Deno to be able to resolve sibling d.ts files without requiring a known extension.

Deno doesn't do any magic resolution on specifiers so it needs the extension. Additionally, `tsc`'s output is not compatible with Deno. Generally generating code with `tsc` for consumption with Deno is not a common pattern since TypeScript can just be imported.

That said, I would have thought tsc would maintain extensions in index.d.ts if the original file had extensions, but I guess not.
