### ISSUE TITLE
deno upgrade failed due to no write permission to "/usr/local/bin/deno" in macos 12.4

### ISSUE THREAD

**Issue by duke-git** [denoland/deno#14829]
When sudo to run deno upgrade in macos 12.4, It's still failed, cause no write permission to "/usr/local/bin/deno".
How could I set path "/usr/local/bin/deno" can be writable.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/5037603/172856687-876e11a3-4633-408b-bdfc-0e7aaf696cdd.png">

**Comment by shinshin86** [comment]
I also encountered the same message.
This never happened before, but I get this error when I run `deno upgrade`.

I don't know if this is caused by macOS side or deno side.

## My Environment
My macOS version is `11.6.7`.

The version of deno is as follows.

```sh
$ deno --version
deno 1.21.0 (release, aarch64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2
```

## Error message
I have not run it with `sudo`, but the message is the same.

```sh
$ deno upgrade
error: You do not have write permission to "/opt/homebrew/bin/deno"
```

## How it was solved
Fortunately I have succeeded in solving this problem.

It was an error related to permission, so I granted the permission and the problem was solved.

```sh
$ chmod 711 /opt/homebrew/bin/deno
```

In my case, this solved the problem.

```sh
$ deno upgrade
```

@duke-git  I don't know if this will solve your problem, but I hope it will be helpful.

**Comment by duke-git** [comment]
@shinshin86 Thanks a lot. I solved the problem by following your guide.

**Comment by tsx50** [comment]
In my case, I ran ”$ chmod 711 /usr/local/bin/deno” in a terminal and it worked.

Thanks!

**Comment by btoo** [comment]
if you dont want to worry about where/how you installed deno, use
```shell
chmod 711 $(where deno)
```

**Comment by HilmiZul** [comment]
> In my case, I ran ”$ chmod 711 /usr/local/bin/deno” in a terminal and it worked.
> 
> Thanks!

solved. thank you 🥳
