### ISSUE TITLE
lsp: warning messages may not be accurate due to caching

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#14933]
### Problem
If you don't specify the version of a dependency, deno lsp will warn you that you're *implicitly using the **latest** version* and it shows a version number, the problem is that the shown version is not really the latest version, its the latest version on the local system cache.

The actual latest version is 0.5.0 in this next example:
![image](https://user-images.githubusercontent.com/22427111/174908280-60d44e00-6cab-4ffe-81c8-e4d9329db828.png)

### Why this matters

The message is misleading and the user will rightfully think that hes using the latest version, this is not desirable and among other things it can lead to having vulnerable outdated dependencies.

### Suggestions

- Improve warning message which I think is located here https://github.com/denoland/dotland/blob/2b6850e057eabc85567f17e37c05327be90f1ccf/routes/x/module.tsx#L543 to something like `latest version in cahce`

- Add a new codelens action `update to latest version` which ignores the cache and check the version remotely

**Comment by sigmaSd** [comment]
Something I noticed in the above example I showed is that the 0.5.0 is actually already on my system cache but the warning still shows 0.2.0 as the latest version, this seems to indicate that the warning itself is cached.

**Comment by sigmaSd** [comment]
I think this is still relevant, the warning is misleading.

**Comment by sigmaSd** [comment]
I think just removing latest would fix this

**Comment by kitsonk** [comment]
The LSP reflects the `Deno-X-Warning` header as sent by a server, unmodified.  This means it is open for other registries/servers to provide different information if they wish.  The LSP also provides additional information, about what is actually being resolved to.

The CLI prints the warning one time at the point it is cached.

While I can understand it can be confusing, if modules were re-cached it would be true potentially again.  It is hard to get a balance between 100% accuracy in all situations and providing information to the user that is actionable.  Because the CLI displays it at the point of caching only once, I feel "latest" is the most informative and has been this way for an extended period of time.

So at this point in time I feel this issue is unactionable.
