### ISSUE TITLE
TS error on FFI imported functions since release 1.23.1

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#14963]
Types of functions parameters of imported ffi are always equals to ```...args: never``` no matter what type is specified. For instance:
```ts
const lib = Deno.dlopen(path, {
    add: {
        parameters: ['isize', 'isize'],
        result: 'isize'
    }
})

lib.symbols.add(40, 2)
```

In Deno 1.23.0
- ```deno check --unstable``` pass
- deno lsp on vscode show
```ts
(property) add: (...args: (number | bigint)[]) => bigint
```

In Deno 1.23.1
- ```deno check --unstable``` return ```error: TS2345 [ERROR]: Argument of type 'number' is not assignable to parameter of type 'never'.
lib.symbols.add(40, 2)```
- deno lsp on vscode return 
```ts
(property) add: (...args: never) => bigint
```

**Comment by sno2** [comment]
I saw this in Discord as a while a bit ago.  I'll fix this tonight.

**Comment by sno2** [comment]
@littledivy It seems https://github.com/denoland/deno/pull/14920 caused the error.

**Comment by sno2** [comment]
I have dug through the code and it looks like the issue is that we are falsely making the assumption that having a type parameter extend another type with default generic values would make TypeScript automatically infer the values of the generic values.  However, it eagerly downcasts the generics into the computed value with the default generics.  Here are some instances where this is incorrectly done:

1. `UnsafeCallback`
    - Def https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L543
    - Usage https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L559
2. `ForeignLibraryInterface`: this is the big one which basically just bubbles up and breaks all of the types
   - https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L430

**Comment by aapoalas** [comment]
If you put in `as const` for the definition  object that'll make the TS inference work, at least.

I'm not sure what exactly in my changes broke this from just being somewhat broken `(...args: number[])` to completely broken `never` for the non-const use case but sorry about that anyway :)

**Comment by aapoalas** [comment]
Also, I think this or something around it is probably what caused the change / break: https://github.com/aapoalas/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L433-L437

Here's the previous types: https://github.com/denoland/deno/blob/21dfeea3c48cf6101d71b39a1d2b0f9406818300/cli/dts/lib.deno.unstable.d.ts#L397-L413

The `StaticForeignFunctionParameters` does not offer a `never` option, so I think that here even though the type parameter given doesn't fit the definition of `ForeignFunction`, some sort of type inference happens anyway. Note that the `ForeignLibraryInterface` you linked to as the big one was not changed in the PR, and neither was any of the types "above" it. As such, I don't see how it could be the root cause.

So why would the type parameter given `StaticForeignFunctionParameters` fit the definition of `ForeignFunction`? It's because the types expects readonly arrays. So in eg.
```ts
const lib = Deno.dlopen(path, {
    add: {
        parameters: ['isize', 'isize'],
        result: 'isize'
    }
});
```
the `parameters` array is not readonly, from TS perspective it's okay to push and pop from it. As such, for TS it's an `"isize"[]` array and not an `["isize", "isize"]`.

Now, contrast this typing with the new parameters inference: https://github.com/denoland/deno/blob/main/cli/dts/lib.deno.unstable.d.ts#L379-L385
If the parameters array is readonly empty, then return an empty array. If the parameters array is a readonly array with one or more items, return the mapped type plus mapped rest. Otherwise, return `never`. I think this added `never` branch compared to the previous types is what you're seeing.

**Comment by piscisaureus** [comment]
The types in FFI are super complicated.
We should erase the exact type and replace it with a generic type that uses dynamic dispatch is where necessary.

**Comment by sno2** [comment]
I have fixed the issue but I'm going to build some tests into the types.
