### ISSUE TITLE
Flag --allow-env does not behave as expected

### ISSUE THREAD

**Issue by JLCarveth** [denoland/deno#15013]
When running a [Deno blog](https://github.com/denoland/deno_blog) using `deno task dev`, the user is given a prompt like the following:
![image](https://user-images.githubusercontent.com/23156861/176517777-7ea92746-c8fe-411c-b221-8535008db05a.png)

Appending the `allow-env` flag to the command does not infact bypass the prompt:
![image](https://user-images.githubusercontent.com/23156861/176517877-75dc2ae9-c65e-4edb-ab0e-03dab563e6c3.png)

Deno version being used is the following:
```
deno 1.23.1 (release, x86_64-unknown-linux-gnu)
v8 10.4.132.8
typescript 4.7.2
```

The blog was created with the following command:
`$ deno run --allow-read --allow-write https://deno.land/x/blog/init.ts ./directory/for/blog/`

**Comment by bartlomieju** [comment]
`--allow-*` flag need to be specified before the filename. I've mentioned it in https://github.com/denoland/deno_blog/pull/33 to add that flag.

**Comment by dsherret** [comment]
Appending `--allow-env` to the deno task will put it after the entrypoint of `main.ts` so `--alow-env` becomes part of the arguments for the script rather than deno's CLI. You'll need to update the deno task in the deno.jsonc file to have `--allow-env` before `main.ts`

Also, this issue is fixed in the latest deno blog https://github.com/denoland/deno_blog/pull/22 -- If you rerun the command specified in https://github.com/denoland/deno_blog#getting-started then it should create the deno task correctly, but it's probably easier to just update the deno task.
