### ISSUE TITLE
Completions for `--inspect-brk` cause an error in zsh

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#15223]
I have installed completions as described in [the manual](https://deno.land/manual/getting_started/setup_your_environment#zsh-example):
```
deno completions zsh > ~/.zsh/_deno
```
But whenever I try to complete a command with `--inspect-brk` I get
```
_arguments:463: command not found: PORT
```

For example:
```
deno run --insp
```
and then hit `tab`, completes into:
```
deno run --inspect-brk=
```
Then if you hit tab again you get
```
deno run --inspect-brk=_arguments:463: command not found: PORT
```

**Comment by jespertheend** [comment]
Fwiw, a workaround for now is to manually remove the `HOST` and `PORT` arguments from the generated completions file:
```diff
-'--inspect=[Activate inspector on host:port (default: 127.0.0.1:9229)]:HOST:PORT: ' \
-'--inspect-brk=[Activate inspector on host:port and break at start of user script]:HOST:PORT: ' \
+'--inspect=[Activate inspector on host:port (default: 127.0.0.1:9229)]' \
+'--inspect-brk=[Activate inspector on host:port and break at start of user script]' \
```

You may have to remove `~/.zcompdump`, run `compinit` and restart your shell.

**Comment by jespertheend** [comment]
I'm still running into this issue unfortunately, though the steps to reproduce seem to have changed a bit.

When typing `--ins` and then pressing tab a couple of times, it keeps cycling between `--inspect`, `--inspect-brk` and `--inspect-wait`.

The issue occurs when typing `--inspect-brk` causing that to be the only option to cycle through.

https://user-images.githubusercontent.com/2737650/210772696-21009c0c-8cce-4f73-94d5-a0f7b253f84d.mp4

**Comment by GJZwiers** [comment]
Thanks, I can reproduce it with `--inspect=` and `--inspect-wait=` as well. The problem seems to be that the placeholders in the completions file are delimited with colons and somehow having a colon in the name is not parsed correctly. Currently the line in the completions file for `--inspect` is:

`--inspect=[Activate inspector on host:port (default: 127.0.0.1:9229)]:HOST:PORT:`

Changing/escaping or removing the colon in `HOST:PORT` fixes it, e.g. `:HOST\:PORT:`. Ultimately I think this might be an issue in `clap` but Deno can probably fix it by using different placeholder values [in the clap args](https://github.com/denoland/deno/blob/main/cli/args/flags.rs#L1956)
