### ISSUE TITLE
This condition will always return 'false' since the types 'string | null' and 'number' have no overlap.deno-ts(2367)

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#15329]
Typescript says there is no overlap here, but that is wrong. `nationID` is a number and getItem will return a string or null. If it returns a string then `'4' == 4` would be true in javascript while `'4' === 4` would be false. Deno shouldn't be complaining about me trying to do the below.
```js
localStorage.getItem('id') == nationID
```

**Comment by nayeemrmn** [comment]
That's just a quirk of how that TS diagnostic is phrased. It won't be false because `'4' == 4` in JS but nevertheless TS doesn't want you to compare those two types. You should stringify `nationId` for sanity.

The error message being technically wrong is an upstream issue. There may be a past issue at https://github.com/microsoft/TypeScript.

**Comment by kitsonk** [comment]
As stated, this is just a [TypeScript diagnostic](https://www.typescriptlang.org/play?#code/DYUwLgBAdghmCWB7KBJAJhAvBALAbgCgDhEBjGYAZTEQCcYBzEAOibBTBAFsAKAcnho+ASizZYCZOkJA), not specific to Deno.  If you believe it invalid, you should open an issue with TypeScript.
