### ISSUE TITLE
allow starting a server by exporting a fetch function

### ISSUE THREAD

**Issue by slymax** [denoland/deno#15343]
cloudflare workers and bun now support (and recommend) this syntax for starting a server:

```js
export default {
  fetch(request) {
    return new Response("Hello World!");
  }
};
```

imho this is more convenient than importing the server module from the standard library and would ensure compatibility with other runtimes going forward.

**Comment by kitsonk** [comment]
We've discussed "declarative endpoints" such as this in the core team a few times and we have yet to arrive at a good workable solution.

Having explicit code without "magical" exports always wins. Because there are a whole host of use cases that quickly fall outside this, like how do you do testing, how do you do setup and teardown, how do you do you close a server. Theb it becomes layer after layer of special code. It also assumes that an HTTP server us the primary/only workload for Deno.

So for me, I am not in favour personally, but others might have different opinions.

**Comment by kidonng** [comment]
> more convenient than importing the server module from the standard library

If this is what you are going for, you can trivally [implement it in < 10 lines](https://gist.github.com/kidonng/77f7fb22c34e5136a3bca768fe0ac020):

```shellsession
$ deno install -n serve --allow-read --allow-net https://gist.github.com/kidonng/77f7fb22c34e5136a3bca768fe0ac020/raw/0437ff03934b6a9940ced971b9dea8861138ecef/serve.ts

$ cat handler.ts 
export default {
  fetch(request) {
    return new Response("Hello World!");
  }
};

$ serve handler.ts
Listening on http://localhost:8000/
```

**Comment by slymax** [comment]
> Having explicit code without "magical" exports always wins. Because there are a whole host of use cases that quickly fall outside this, like how do you do testing, how do you do setup and teardown, how do you do you close a server. Theb it becomes layer after layer of special code. It also assumes that an HTTP server us the primary/only workload for Deno.

yeah I was thinking of this mainly in the context of deno deploy where I think it could be useful. The issues you've raised make a lot of sense though (except that I don't see how this would interfere with projects that don't use an HTTP server).

> If this is what you are going for, you can trivally [implement it in < 10 lines](https://gist.github.com/kidonng/77f7fb22c34e5136a3bca768fe0ac020)

thanks for this. I was mainly bringing it up to see if this has been considered and if there's any interest for it.
