### ISSUE TITLE
 illegal hardware instruction on importing deleted file

### ISSUE THREAD

**Issue by hayd** [denoland/deno#1545]
Example:

```
 % cat bar.ts
import "./baz.ts";

 % cat baz.ts
console.log("hello");

 % ../deno/target/debug/deno bar.ts
hello
 % mv baz.ts baz.orig.ts
 % ../deno/target/debug/deno bar.ts
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DenoError { repr: Simple(NotFound, "Cannot resolve module \"./baz.ts\" from \"/Users/hayd/OSS/deno_std/bar.ts\"") }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

#
# Fatal error in v8::Isolate::Dispose()
# Disposing the isolate that is entered by a thread.
#

[1]    28433 illegal hardware instruction  ../deno/target/debug/deno bar.ts
```

**Comment by kevinkassimo** [comment]
The illegal hardware instruction happens when some unexpected panic happens.
https://github.com/denoland/deno/pull/1498#discussion_r248855334
I guess my original assumption here is not right...
Since the script for `bar.ts` is already compiled, the step for TS compiler dependency graph building is skipped. Thus, this `.unwrap` would explode:
https://github.com/denoland/deno/blob/d06c95637a2a19588fcb549ed7b760a916b3cbfd/src/isolate.rs#L406-L407

**Comment by kevinkassimo** [comment]
In comparison to what #1498 is trying to fix, we can deduce the location of the import using [`GetModuleRequestLocation()`](https://denolib.github.io/v8-docs/classv8_1_1Module.html#a323acfb19889ba4e16b81f1c3d89c2b9) and [`GetModuleRequestLocation()`](https://v8.paulfryzel.com/docs/master/classv8_1_1_module.html#a95b5467ac9bcfc120470b6944c7da111) to deduce the origin, create an exception, and handle as a JSError.
