### ISSUE TITLE
"deno bench" report should use same unit per group

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#15468]
Currently `deno bench` looks something like this:
```
cpu: Apple M1 Max
runtime: deno 1.24.2 (aarch64-apple-darwin)

file:///Users/ib/dev/deno/cli/tests/testdata/bench/pass.ts
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
bench0     487.82 ps/iter   (462.5 ps … 45.46 ns)    475 ps  516.7 ps  533.3 ps
bench1       4.31 ns/iter     (4.1 ns … 41.87 ns)   4.13 ns   6.06 ns   8.29 ns
bench2       4.19 ns/iter     (4.09 ns … 9.79 ns)   4.12 ns   5.81 ns   6.32 ns
bench3       4.18 ns/iter     (4.08 ns … 9.82 ns)   4.15 ns   5.41 ns   5.93 ns
bench4       4.38 ns/iter    (4.25 ns … 13.79 ns)   4.32 ns   5.96 ns   6.61 ns
```

@ry requested the output be changed in such a way, that all benches in the same group use the same unit. Which would render previous output like so:
```
cpu: Apple M1 Max
runtime: deno 1.24.2 (aarch64-apple-darwin)

file:///Users/ib/dev/deno/cli/tests/testdata/bench/pass.ts
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
bench0     487.82 ps/iter   (462.5 ps … 45.46 ns)    475 ps  516.7 ps  533.3 ps
bench1       4310 ps/iter     (4.1 ns … 41.87 ns)   4.13 ns   6.06 ns   8.29 ns
bench2       4190 ps/iter     (4.09 ns … 9.79 ns)   4.12 ns   5.81 ns   6.32 ns
bench3       4180 ps/iter     (4.08 ns … 9.82 ns)   4.15 ns   5.41 ns   5.93 ns
bench4       4380 ps/iter    (4.25 ns … 13.79 ns)   4.32 ns   5.96 ns   6.61 ns
```

**Comment by randomicon00** [comment]
I would like to work on it.

**Comment by bartlomieju** [comment]
@randomicon00 thanks, please do!

**Comment by paulmj7** [comment]
@bartlomieju could there be clarification on what "group" is? ex time, p75, p99 or bench0, bench1, bench2. Between the two examples, I see that "time (avg)" conforms to one unit, but p75 uses ps and ns. Perhaps I am looking at the wrong thing?

**Comment by bartlomieju** [comment]
@paulmj7 by group I mean [`group`](https://doc.deno.land/deno/unstable/~/Deno.BenchDefinition#group) option on the definition. However @randomicon00 already claimed this issue and is working on the fix, so if you are interested in working on it, I suggest to find some other unclaimed issue.

**Comment by psimk** [comment]
@bartlomieju 

I noticed that the issue hasn't been updated in more than a month, would it be okay, if I pick it up? I am looking for entry issues to get started with working on Deno.

---

I did some investigation into the issue, and it seems like we are using [evanwashere/mitata](https://github.com/evanwashere/mitata) for reporting the benchmark. The library itself decides ([evanwashere/mitata/src/lib.rs#L23](https://github.com/evanwashere/mitata/blob/master/src/lib.rs#L23)) which unit to use based on what precision time we pass to it . We would have to round all of the `time`s to be the same precision in order to get consistent units.  

There seems to be 2 approaches that we could take:

1. do the rounding ourselves, and pass the rounded values to the reporter
2. attempt to update [evanwashere/mitata](https://github.com/evanwashere/mitata) to support this behavior.

What do you think?

**Comment by randomicon00** [comment]
@psimk  The issue is not moving because we are stuck as we need to make changes to mitata. And if we do, we will be breaking the formatting as per mitata's main maintainer words.

**Comment by randomicon00** [comment]
If you want to start contributing to `deno`, a good first step is to join the Discord, if you haven't already.

**Comment by pancanin** [comment]
This should be a flag, for example, "-same-units", as it is IMO just a preference and not anything wrong with the metrics.
It's a bit tricky to figure out whether to upscale the units to the bigger one or downscale to the smaller, so maybe this should be configurable as well.

**Comment by bartlomieju** [comment]
I don't think we should implement this after all. It just complicates stuff and it's value is questionable.
