### ISSUE TITLE
deno doc error: Could not find module in store: file:///C:/Users/Administrator/$deno$doc.ts

### ISSUE THREAD

**Issue by masx200** [denoland/deno#15930]
```
 deno doc -- https://esm.sh/v95/@datastructures-js/binary-search-tree@5.0.2/index.d.ts
error: Could not find module in store: file:///C:/Users/Administrator/$deno$doc.ts
```
```
deno --version
deno 1.25.2 (release, x86_64-pc-windows-msvc)
v8 10.6.194.5
typescript 4.7.4
```

**Comment by brenelz** [comment]
So ended up debugging this for awhile but couldn't figure it out. Turns out the first time you run `deno doc` it works but the next time you do it doesn't. It has nothing to do with that specific package.

Simple repro:
```typescript
// test.ts
export function add(x: number, y: number): number {
  return x + y;
}
```

`deno doc test.ts` = Running it the first time equals success
`deno doc test.ts` = Running it the second time fails

Renaming the file and then rerunning works.

**Comment by dsherret** [comment]
@brenelz thanks for investigating that. This is the same issue as #15612
