### ISSUE TITLE
npm: Import map is not supported for "require()"

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#15948]
We have support for import map in case of ESM imports of npm: specifiers, but it's not supported if a module is `require`d. 

This might be a bit exotic, but I believe there are certain valid use cases for it.

Eg. I'm trying to run a Vite project, I did set up following import map:
```json
{
    "imports": {
        "@vitejs/plugin-vue": "npm:@vitejs/plugin-vue@3.0.3",
        "vite-plugin-deno": "./plugin.js",
        "vite": "npm:vite@3.0.7",
        "vue": "npm:vue@3.2.37"
    }
}
```

This works nicely, as long as there's a `package.json` file in the same directory like so:
```json
{
  "name": "my-vue-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.3",
    "vite": "^3.0.7"
  }
}
```

However as soon as I remove that `package.json` file, I'm no longer able to run `deno run -A --unstable npm:vite`, because I get following error:
```
failed to load config from /Users/ib/dev/my-vue-app/vite.config.js
error when starting dev server:
Error: Cannot find module 'vite'
Require stack:
- /Users/ib/dev/my-vue-app/vite.config.js
- /Users/ib/Library/Caches/deno/npm/registry.npmjs.org/vite/3.1.2/dist/node/chunks/dep-cff57044.js
    at Function.Module._resolveFilename (deno:ext/node/02_require.js:615:17)
    at Function.Module._load (deno:ext/node/02_require.js:447:29)
    at Module.require (deno:ext/node/02_require.js:658:21)
    at require (deno:ext/node/02_require.js:789:18)
    at Object.<anonymous> (file:///Users/ib/dev/my-vue-app/vite.config.js:31:19)
    at Object.<anonymous> (file:///Users/ib/dev/my-vue-app/vite.config.js:56:4)
    at Module._compile (deno:ext/node/02_require.js:719:36)
    at Object._require.extensions.<computed> [as .js] (file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/vite/3.1.2/dist/node/chunks/dep-cff57044.js:63489:24)
    at Module.load (deno:ext/node/02_require.js:636:34)
    at Function.Module._load (deno:ext/node/02_require.js:493:14)
```

If `require()` took into account import map file, just like ESM imports do, then we could remove `package.json` from the project altogether and instead replace it with `deno.json` + `import_map.json`.

**Comment by bartlomieju** [comment]
@guybedford I would appreciate your thoughts on this topic.

**Comment by cowboyd** [comment]
Potentially related, when loading plugins from a CLI, it would be nice to have more fine-grained control over how imports are mapped when using either ESM or CJS https://github.com/denoland/deno/issues/8655#issuecomment-1249502597

**Comment by guybedford** [comment]
@bartlomieju not sure I have much to add on this, but can share my thoughts certainly. In Node.js loader hooks are not currently supported for CommonJS require, so that a userland import map implementation will likely only apply to ESM as well although could hook into the require system using the standard monkey patching as well. Although the new loader work points in the direction of loaders being able to have more general hooks so that this might well be supported in future.

So it may well be possible, but yet to be seen if Node.js implementing import maps would also want to extend that to require. Typically Node.js does aim to support for CommonJS for new resolution features (like we did with "imports" and "exports").

In terms of CommonJS and ESM having different resolutions (`"import"` and `"require"` conditions), I've found in my own work that exact module scopes can allow supporting this for the most part, and have yet to hit up against a case of a single CommonJS module that does both `import('pkg')` and `require('pkg')` expecting both results. That would be an edge case to consider though.

So overall it seems useful to me, but it could be helpful to ensure it matches what Node.js does itself.

On a related note, has there been any discussion of supporting scoped maps for `npm:` specifiers? Either by scoping their final `file:///` URL or the `npm:` URL directly?

**Comment by bartlomieju** [comment]
@guybedford thank you for the time you took to respond. Since opening this issue we managed to overcome problems at hand and I no longer believe we should be adding import map support for `require()`.

> n Node.js loader hooks are not currently supported for CommonJS require, so that a userland import map implementation will likely only apply to ESM, although could hook into the require system using the standard monkey patching as well. The new loader work does point in the direction of loaders being able to have more general hooks so that this might be supported in future.

> So it may well be possible, but yet to be seen if Node.js implementing import maps would also want to extend that to require. Typically Node.js does aim to support for CommonJS for new resolution features (like we did with "imports" and "exports").

That makes total sense and is inline with browser behavior so I think we should keep it that way.

> In terms of CommonJS and ESM having different resolutions ("import" and "require" conditions), I've found in my own work that exact module scopes can allow supporting this for the most part, and have yet to hit up against a case of a single CommonJS module that does both import('pkg') and require('pkg') expecting different results. That would be an edge case to consider though.

Thanks for pointing this out, definitely something to keep an eye on, but again before this edge case is hit I think we should stay put.

> On a related note, has there been any discussion of supporting scoped maps for npm: specifiers? Either by scoping their final file:/// URL or the npm: URL directly?

Not yet, but I think this would be very useful for quickly patching dependencies locally. @dsherret any thoughts on this?
