### ISSUE TITLE
import() function does not work on compiled files

### ISSUE THREAD

**Issue by Sunf3r** [denoland/deno#16184]
When running a TypeScript file compiled by Deno, I got errors like "Module not found", but everything worked fine without compiling. I investigated the problem and found that the compiled files cannot import other files with the import() function, however if it is imported with "import from" there is no error.

Look at my tests:

Using import() function:
![image](https://user-images.githubusercontent.com/74569023/194439115-c7d0c52b-67fc-4b92-9617-2431e6e6737b.png)

Using import from:
![image](https://user-images.githubusercontent.com/74569023/194439295-78619659-885b-41be-8274-ad1797565baa.png)

I tried using the "--unstable" argument when compiling the file, but the result remained the same

**Comment by Seally** [comment]
Did you see the last part of the manual? 
https://deno.land/manual@v1.26.1/tools/compiler

Dynamic imports aren't supposed to work when compiled.

**Comment by Sunf3r** [comment]
Wow, I didn't really see that. I'm very sorry.

Are there plans for dynamic imports to be supported?

**Comment by andreubotella** [comment]
The idea with `deno compile` is that every module you import is already built into the executable, and you can't import anything else on demand. In order to enable dynamic import with `deno compile`, you'd need to have a list of modules that can be imported, and pass that as a flag when compiling. This is also why dynamic import doesn't work on Deno Deploy, since the edge servers that run your code don't know how to transpile Typescript or otherwise build a module graph.

As far as I know, there are no plans to do this. But the Deploy issue is a very common complaint (denoland/deploy_feedback#1), so it's probably somewhere on the Deno core team's todo list.

**Comment by Sunf3r** [comment]
Okay, thank you very much for your attention.
