### ISSUE TITLE
Type-only imports for importing definitions from semi-trusted sources

### ISSUE THREAD

**Issue by jeremyBanks** [denoland/deno#1628]
Motivating scenario: a service may automatically generate `.d.ts` definitions for its API. For a cool example see [this recent blog post about automatically generating TypeScript definitions for Rust Serde types](https://timryan.org/2019/01/22/exporting-serde-types-to-typescript.html). I am working on something similar for an internal project at work that generates `.d.ts` definitions for our RPC interfaces. Our users need to manually copy these `.d.ts` files into their projects, and make sure they stay in sync.

If the service exposes these `.d.ts` files alongside their API, such as `https://example.com/api/types.d.ts`, Deno lets us handle this in a more elegant way than other tools: we can import the types directly from the API server, right next to the code that makes requests to that API server. This seems like a very attractive pattern for safe API use.

```typescript
import {Post} from 'https://example.com/api/types.d.ts';

async function main() {
  const response = await fetch('https://example.com/api/posts/0');
  const post = await request.response() as Post;
  console.log(post.body);
}
```

However, this has the consequence that I'm importing and potentially evaluating code from every API that I depend on. For my internal use case, this is fine, but if I were integrating with several public APIs I would have some reservations. I can leave Deno's sandboxing enabled in some cases, but not all.

What I would like is the ability to indicate that these imports are intended to import types only, and throw an error if they would have any other effect. TypeScript automatically elides (removes) imports that are only used for types, so this wouldn't effect the behaviour of any allowed code, it would just disallow certain certain code.

---

I don't have a specific idea of what this should look like: perhaps it could automatically be applied for imports that end in `.d.ts`, or could be indicated with a URL pseudo-scheme, like `types:https://example.com/api/types.d.ts`. But it's a compelling pattern, and I'd like to be able to use it safely from Deno.

**Comment by kitsonk** [comment]
I am not sure this would be an issue.  While we need to do some work to support `.d.ts` files in general, they would now never end up in the sandbox, since we have split the compiler out of the runtime.  But even "if" we hadn't, `.d.ts` files wouldn't actually have any runnable code.

I would worry more about 3rd party imports from `.ts` files where the import is type only, but the file contains emittable runtime code.  Again, now that the compiler is split out, there is a clear segregation of duties between the compiler and the runtime.  The process works a bit like this:

- A TypeScript file is request to be run.
- The runtime request that module from Rust.
- Rust resolves the resource.  If it is a TypeScript file, and the output of the file is not cached, Rust sends a message to the compiler to compile a module (it is just the module specifier at this point).
- The compiler will check its in memory cache for the module, if it doesn't exist, it will request the module from Rust.
- Rust will again validate if it has already fetched the module (which it will have) and then return the module to the compiler (currently as a string).
- TypeScript will operate on the module as a string, resolving the types/etc, but not actually running any code.
- It will request additional modules it does not have in its in memory cache to complete the "type" picture of the file to be able to validate it and generated the emitted output.  This data is then sent back to Rust.
- Rust will then load the ESM module into the V8 runtime.
- V8 will do additional analysis of the module, determining any other dependencies, and request them from Rust.
- Wash and repeat the process above, until all the dependencies are resolved.
- Once the dependencies are resolved, V8 will start instantiating the modules (and thereby running code).

When we explicitly support `.d.ts` files, I cannot see a way they could compromise the runtime (or the compiler for that matter).

The only "risk" I see is that you are loading a remote `.ts` module of which you think you are only importing a type, but it doesn't elide, and then the whole transpiled module gets loaded into the runtime.  But that is really a more macro discussion about remote module integrity and verification.  I believe there was an issue discussing it, but I know that it continues to be in a lot of people's minds about how to best secure remote modules.

**Comment by jeremyBanks** [comment]
Thank you for the detailed explanation! My mental model of how Deno works what not complete.

I also didn't realize that the TypeScript compiler itself throws an error (statements "not allowed in ambient contexts") if there are non-type declarations in a `.d.ts` file.

It looks like I have nothing to worry about. 🙂
