### ISSUE TITLE
Upgrade Checker should not change output on `deno run`

### ISSUE THREAD

**Issue by j50n** [denoland/deno#16466]
Would it be possible to not have the upgrade checker write to output on `deno run`? This is an undesirable behavior in all cases when (1) deno is running in a container, or (2) when the deno version is being managed globally on a shared server. If there is no user to see a prompt - automation tasks - or if the user can't change the version themselves, this feature is at best useless, and possibly just annoying. At worst, it could change output in a tested environment in a way that breaks something.

This feature is changing process output on code that has been tested based on external changes outside the control of the developer. 

`deno check`, `deno lint`, `deno compile`, a dozen others - all fine for changing the output. `deno run` needs to produce the same output when given the same input. Every time. 

Put another way, this feature has the capacity to allow a bug to slip through CI/CD, since it guarantees a process output change at some point in the future, but is not opt-in (strictly opt out at this point). DENO_NO_CHECK_UPDATE=1 needs to be set in every docker definition or for every script. If I release code without it (let's say I forget), my code will get through CI/CD just fine and fail in production next week when a new patch release drops because something changed in the process output.

Put another way, arbitrarily altering the process output on a fixed version of Deno running fixed versions of code just seems like a bad idea to me. If Deno has not changed and code has not changed, I would expect the program to do *exactly* the same thing - forever. This feature seems to me to break that contract.

--- 

I am not sure if I can test with this behavior in place. There isn't a way to force Deno to output this message, so I have to wait for the next update. I am assuming that this is writing to `stderr`. For scripts that just use `stderr` as a garbage dump that is fine and probably won't cause too much of a problem (unless the script is being called a gazillion times - it happens). But `stderr` can't be assumed to be used that way in all cases. If it matters and I want to leave the default behavior in place, I need to test with different versions of Deno to verify that things still work (once 1.27.1 drops). So I am stuck with setting an environment variable everywhere, because I am not going to test like that. 

I hope there is a solution to this, or an evolution of the feature, or something that makes this more tidy.

---

Would it be possible to give this explicit command line support? Not just an environment variable.

**Comment by dsherret** [comment]
It won't output unless it's a tty. Did you experience otherwise?

**Comment by sigmaSd** [comment]
I also agree with this, I personally would've prefered that is at least opt in not opt out.

**Comment by sigmaSd** [comment]
Its especially weird for things I deno installed, it feels like there is a builtin ad that infected all deno scripts I have.

Does exe compiled from deno also shows this?

**Comment by dsherret** [comment]
> Does exe compiled from deno also shows this?

No, it doesn't because it uses a different code path.

> How does it treat ssh -t -t -o BatchMode=yes? That is mostly emulating a remote terminal.

In that case, you probably want to be using `--quiet` if you don't want any messages. Deno prints to stderr for things like downloading or if the registry for a module provides any warnings to display.

Anyway, please open an issue if this causes actual bugs in a real application. Again, I don't believe it should because of the check for if stderr is a tty.

**Comment by Timmmm** [comment]
I think this should be reconsidered.

> if this causes actual bugs in a real application

The actual bug *is* that it checks for updates and prints messages. I don't think it's reasonable for a user to expect that because

* It's confusing output - they might not even have heard of Deno, nor care if it is out of date.
* It unnecessarily accesses the network. Lots of people are overly paranoid about that but I still think it shouldn't do it by default.

As @j50n said, it's fine for basically every other `deno` command to do this check by default so I don't really see a downside to disabling it.
