### ISSUE TITLE
npm specifiers fail for submodules in import map

### ISSUE THREAD

**Issue by mrgrain** [denoland/deno#16476]
Given the following import map:
```json
{
  "imports": {
    "aws-sdk/": "npm:aws-sdk/"
  }
}
```

And `app.ts`:
```ts
import {S3} from "aws-sdk/clients/S3";
new S3({});
```

Deno fails with the following error:
```
> deno run -A --unstable app.ts
error: Failed to resolve the specifier ""aws-sdk/clients/S3"" as its after-prefix
            portion ""clients/S3"" could not be URL-parsed relative to the URL prefix
            "Url { scheme: "npm", cannot_be_a_base: true, username: "", password: None, host: None, port: None, path: "aws-sdk/", query: None, fragment: None }" mapped to by the prefix ""aws-sdk/""
    at file:///home/path/to/app.ts:1:18
```

**Comment by sinclairzx81** [comment]
Just to include another package that requires sub-module resolution.

```typescript
import { TypeCompiler } from 'npm:@sinclair/typebox/compiler'

console.log(TypeCompiler)

// Caused by:
//   Access is denied. (os error 5)
```
Not sure if there would be a way to hint to Deno of the sub modules existence, but do note that `esm.sh` currently has some strategy to resolve internal sub-modules that are not directly referenced by `package.json -> main`.

```typescript
import { TypeCompiler } from 'https://esm.sh/@sinclair/typebox/compiler'

console.log(TypeCompiler) // ok
```
Submitting for reference

**Comment by e1himself** [comment]
I still have this problem. 

The setup I have is a newly initialized Fresh framework repo:

_deno.json_:
```
{
   // ...
   "imports": {
      "react-icons/": "npm:@e1himself/react-icons/",
   }
}
```

_component.tsx_:
```tsx
import { IoCloseOutline } from "react-icons/io5";
```

The error (displayed in the CLI, and in VSCode too):
```
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 5 routes and 1 islands.
error: Uncaught (in promise) TypeError: Failed to resolve the specifier ""react-icons/io5"" as its after-prefix
            portion ""io5"" could not be URL-parsed relative to the URL prefix
            "npm:@e1himself/react-icons/" mapped to by the prefix "react-icons/"
    at file:///home/user/workspace/fresh/components/component.tsx:7:8
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
                    ^
    at async dev (https://deno.land/x/fresh@1.6.1/src/dev/dev_command.ts:38:21)
    at async file:///home/user/workspace/fresh/dev.ts:8:1
Watcher Process failed. Restarting on file change...
```

The issue only happens if there is an after-prefix portion after the import mapping prefix. Changing the imports mapping to this fixes the error:

```
{
   // ...
   "imports": {
      "react-icons/io5": "npm:@e1himself/react-icons/io5",
   }
}
```

I've traced the error message back to this import_mapping implementation code (which seems to be used by Deno internally):

https://github.com/WICG/import-maps/blob/abc4c6b24e0cc9a764091be916c5057e83c30c23/reference-implementation/lib/resolver.js#L61-L67

With the problem coming from the fact that `npm:package-name` specifiers are not valid URLs and cannot be used to resolve subpaths with the `new URL(afterPrefix, resolutionResult)` call.
