### ISSUE TITLE
Exposing internal APIs in runtime.

### ISSUE THREAD

**Issue by ssttevee** [denoland/deno#16545]
Has there been any consideration into allowing access to some useful internals from js?

I'm thinking specifically:
- [`tools::fmt::format_file`](https://github.com/denoland/deno/blob/1410e4adea5d399f9551ff04c6863862f169ee7a/cli/tools/fmt.rs#L251) for formatting at runtime without requiring run permission,
- [`tools::lint::lint_file`](https://github.com/denoland/deno/blob/1410e4adea5d399f9551ff04c6863862f169ee7a/cli/tools/lint.rs#L315) for linting at runtime without requiring run permission,
- typescript (i.e. the entire `ts` namespace) for parsing and printing ts code for removing net permission requirement for downloading + eval (maybe not important after microsoft/TypeScript#51387) and reducing memory footprint

Additionally, not what I'm looking for right now, but could be useful:
- `deno doc` that outputs to memory
- `deno bundle` that outputs to memory
- `deno compile` that outputs to memory
- `deno info` (would be useful for building a turborepo or nx clone)

`format_file` seems very straight forward and I can probably submit a pr within a day. Typescript seems very hard, considering that it seems to run in a completely different isolate. The others seems like it would be somewhere in between in due to serializations and writing accompanying type definitions.

This seems like it could be related to #1739, but also sounds different.

**Comment by dsherret** [comment]
Seems like #10731, which I don't think we'll ever do. We used to have an unstable `Deno.emit` and we removed that in favour of https://github.com/denoland/deno_emit

I don't think we'll support these APIs for formatting and linting because we'd rather distribute them as libraries for people to use and for the APIs to evolve with the features rather than being set in stone as runtime APIs.
