### ISSUE TITLE
npm:netlify-cli -> netlify-cli@12.2.4 did not have a 'bin' entry for netlify-cli in its package.json

### ISSUE THREAD

**Issue by juanfra684** [denoland/deno#16728]
Hi, the netlify client doesn't work with deno. I get the same error with stable 1.28.1 and 1.28.1+fedeea6.
```plain
$ deno run -A npm:netlify-cli help
error: package netlify-cli@12.2.4 did not have a 'bin' entry for netlify-cli in its package.json
```
I also tried with `--reload` and `--node-modules-dir`.

I've added `"netlify-cli": "./bin/run.mjs"` to `bin{}` in the file `package.json`, because they have `netlify` there but not `netlify-cli`. Now I get a different error:
```plain
$ deno run -A npm:netlify-cli help
error: Uncaught SyntaxError: The requested module 'process' does not provide an export named 'argv'
    at <anonymous> (file:///home/runner/.cache/deno/npm/registry.npmjs.org/netlify-cli/12.2.4/bin/run.mjs:3:10)
```
I'm reporting the problem because I would like to run the netlify client with deno but maybe the argv error is something different. I'm quite new to javascript.

**Comment by dsherret** [comment]
The package `netlify-cli` has a bin entry with the following:

```ts
"bin": {
  "ntl": "./bin/run.mjs",
  "netlify": "./bin/run.mjs"
},
```

Since there's no single entrypoint or one with the same name of the package, it doesn't know which one to use. So you can specify the binary entrypoint by doing:

```sh
deno run npm:netlify-cli/netlify help
```

Perhaps it could get a bit smarter and resolve ok if all the values in the bin entrypoints are the same.

I opened https://github.com/denoland/deno_std/issues/2917 about the issue you ran into running that.

**Comment by dsherret** [comment]
That's a good idea! I opened #16731. Let's track all this there and in the deno_std issue.
