### ISSUE TITLE
Support JSX in REPL

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#16771]

**Comment by rgbkrk** [comment]
For people wondering, this also affects the Jupyter kernel for deno. @bartlomieju and I talked on discord and zoom about a couple of approaches to support this in the notebook. Since the typescript compiler needs to know which `jsx` to use we either need to pick up Deno config (in the same directory) or a pragma:

```
/** @jsxImportSource https://esm.sh/preact */

export function App() {
  return (
    <div>
      <h1>Hello, world!</h1>
    </div>
  );
}
```

Rendering it, however, is a bit of a different issue as we either have to render to an HTML string and push it on `text/html` or use the VDOM spec (only supported in some environments). xref: https://github.com/rgbkrk/display.js/issues/5
