### ISSUE TITLE
Idea: use WebAssembly in core lib

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#1679]
We can port some functions (e.g. IsTTY) to C(++)/Rust and use them in WebAssembly instead of calling them in Rust core. Can be done after #1677

**Comment by kitsonk** [comment]
This doesn't make a lot of sense...  While WebAssembly gives a level of near native performance, it will break any sort of security we expect because it will run in the runtime, therefore breaking sandboxing.  Also, it isn't straight forward to author.  It would be authoring in some sort of 3GL language, like Rust, compiling to byte code and then loading that in an untrusted way into the runtime for what purpose?  Just because you can?  Doesn't seem very logical or practical.

**Comment by sh7dm** [comment]
ok
