### ISSUE TITLE
Space on website isn't distributed well

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#1690]
E.g. I've taken this 4K screenshot using Puppeteer:
![screenshot_1549385342926](https://user-images.githubusercontent.com/19504461/52289597-685cac00-297f-11e9-9280-f36a0a34bfeb.png)
Content is only in center, what is strange, it should be wider

**Comment by daynin** [comment]
I think it's ok for 4k resolution (without any scaling). Even if we change the container's width, it'll change nothing because of the content length (sentences, charts, etc). Moreover, we'll get loooong sentences which will look strange

**Comment by sholladay** [comment]
A simple solution could be to increase the root font size on large resolutions. Assuming everything else is using `em` or `rem`, it will scale well.

**Comment by Maxim-Mazurok** [comment]
@sholladay scaling is an option, but I think we should ask 4k monitor users how they like that idea because I can see why they might dislike it.

Our options that I currently see:
1. Make content wider
2. Create columns
3. Scale text

My opinion on each option:
1. We shouldn't make content too wide, because it will affect readability. I think it's fine as it is now.
2. I can't see any good reason to break the current site into columns, we're not [nytimes.com](https://www.nytimes.com/). Probably we could move the navigation links to the side-menu, maybe make columns from the last 6 blocks where we have charts. Not really sure if it's a good idea or not. Probably it's not worth development and maintenance tradeoffs. It has a good, simple and semantic layout, breaking it to columns might add some unnecessary complexity.
3. I imagine, that someone buys a nice new wide monitor, so he can fit a lot of stuff on it. And instead, we just scale everything, so he won't spot the difference, except that now he can read from the 1 feet distance. I don't think that we should really do that, let him have 100 lines of text instead of 50 lines. Maybe even fit a couple of chart on one screen, who knows. Besides that, there are a lot of options if a user prefers scaling. First, you can configure that system-wide (I've tried that on windows 4k laptop). Next, you can configure font-size in your browser. Also, you can just scale the specific website. So, I'm almost certain, that it is something that user should decide for himself and we shouldn't scale website for him.

So, I would recommend doing nothing in that case. Let me know what do you think about it?

P.S. Yeah, I'm following the same approach on [my own website](https://maxim.mazurok.com/) that I love and care about really much.

**Comment by bartlomieju** [comment]
This issue is stale. There had been some tweaks to site's CSS and it looks like there are no immediate plans for rewrite. 

Can this issue be closed? CC @ry
