### ISSUE TITLE
Cache invalidation when recompiling a module

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1692]
In discussion of a [StackOverflow question](https://stackoverflow.com/questions/54506135/how-is-deno-startup-fast-without-running-the-typescript-compiler-in-watch-mode/) it reminded me have a situation we don't handle well, which could result in runtime errors (or unexpected behaviour).

The scenario is as follows:

- There are two modules `a.ts` and `b.ts`
- `b.ts` exports a value that is consumed by `a.ts`, which is a "main" module
- Deno is run as `deno a.ts`
  - Both `a.ts` and `b.ts` are transpiled and cached
  - `a.js` and `b.js` are injected into the runtime
- Changes are made to `b.ts` that remove the export
- Deno is run as `deno a.ts` again
  - Deno invalidates the cache of `b.ts` and recompiles it
  - `a.js` and `b.js` are injected into the runtime
  - `a.js` fails at runtime because the export is no longer available in `b.js`

We need some sort of reverse dependency graph that we would need to persist along with the cached outputs, so we could determine if `b.ts` is invalidated that any modules that depend upon `b.ts` should also be invalidated.

This is a longterm issue to fix, not something that can be easily addressed, we still have some work to do in cleaning up the compiler and how we deal with modules, and how we cache modules before we would want to tackle this.  It is just a reminder to not forget it.

**Comment by mzdunek93** [comment]
TypeScript compilation can and needs to be optimized significantly. The issue is that currently, after a change of file in the dependency tree, it's recompiled along with all of its descendants in the tree, which is completely unnecessary - its ancestors, the files that depend on the modified one, should be the one to be recompiled. In order to mitigate that, we can use the TS compiler's option to perform incremental compilation - that way it saves a build info file with all the dependencies and their hashes, and the next time it only recompiles the necessary files. For this to work correctly, we have to always start compilation from the same file, instead of skipping the root if it's already in the cache. I have a prototype working locally, if anyone's interested I can improve it and make a PR.
