### ISSUE TITLE
Please explain...

### ISSUE THREAD

**Issue by metakeule** [denoland/deno#17]
Is it like nodejs but for TypeScript and with blocking IO  / without callback madness?

**Comment by kizerkizer** [comment]
I have a question as well. Is there a primary motivation behind the project? Of course, there needn't be one - the most common justification for coding (for me at least) is "just because".

I'm curious if there a specific aims. Could modification of the V8 engine to handle TS directly be on the roadmap? There would be obvious performance gains by executing TS directly.

**Comment by kizerkizer** [comment]
@metakeule I think asynchronicity is actually a feature of the deno, given that @ry mentions support for top-level await.
