### ISSUE TITLE
Deno doesn't support "allowSyntheticDefaultImports" compiler option which means a lot of npm dependencies that ship types won't typecheck properly

### ISSUE THREAD

**Issue by itsdouges** [denoland/deno#17058]
Hello! There's quite a few npm dependences that have typedefs for default exports that look like, well, a default export! Currently in Deno it results in the following error:

```
This expression is not callable.
```

As more folk start using Deno they're going to run into this problem, and it'll be a friction point that ideally shouldn't exist. 

Other related issues:

- https://github.com/denoland/deno/issues/16458
- https://github.com/denoland/deno/issues/16475
- https://github.com/denoland/deno/issues/16506

Can Deno support the `allowSyntheticDefaultImports` compiler option, or do something to transparently make this work?

**Comment by dsherret** [comment]
It's expected. We initially experimented with something to make this work, but now for node compat in Deno (which is always ESM) we decided to align with and follow the same rules that Node does in an ES module importing CJS. As I mentioned in the linked issues, those packages incorrectly have an `export = `, but then define that in their types as `export default`.

The bottom line is those packages need to fix their incorrect type declarations anyway if they want it to work when being imported by a Node ES module and then it will also work in Deno. I'd recommend if you come across a package like that to submit a pull request to their repo to correct their declarations and make it work correctly in both Node and Deno. In the meantime, you can write code like the following to "fix" the package's incorrect types:

```ts
import sizeofImport from "npm:object-sizeof@1.6.3";

const sizeof = (sizeofImport as any as typeof sizeofImport.default);

console.log(sizeof({}));
```

In TypeScript, the `allowSyntheticDefaultImports` works because it's not using ES modules under the hood and instead transpiling to `require` with some injected code.

**Comment by itsdouges** [comment]
Fair enough thanks for the context, I'll do that 😄. Might be worth putting something about this in the npm FAQ

**Comment by dsherret** [comment]
Opened https://github.com/denoland/manual/issues/496
