### ISSUE TITLE
Testing: Add Deno.test.ignore, Deno.test.only, t.step.ignore and t.step.only

### ISSUE THREAD

**Issue by mohsen1** [denoland/deno#17106]
[Similar to Jest](https://jestjs.io/docs/api#describeskipname-fn)

**Comment by bartlomieju** [comment]
This has been requested several times already. I was always a fan of this API - it's much more concise to add `.skip` (or actually it would be `.ignore` in Deno) that adding `{ ignore: true }` option.

I'm in favor of adding this. @dsherret thoughts?

**Comment by KyleJune** [comment]
The standard libraries `testing/bdd.ts` module has this. It has `.only` and `.ignore` on `describe` and `it`.

https://deno.land/manual@v1.29.1/basics/testing/behavior_driven_development#focusing-tests

One thing to consider with `step.only` is that currently the `TestStepDefinition` doesn't support the `only` option. So you'd need to figure out how you are going to want to implement that. It's easier to implement focusing subtests with a declarative approach than it is with the procedural approach deno uses since the test steps run when they are called and you can await for them to finish before registering other test steps.

https://deno.land/api@v1.29.1?s=Deno.TestStepDefinition

For `testing/bdd.ts`, all the tests are registered before they run. When a step in it is focused, all other tests that should be ignored just get ignored when registering them internally with `t.step`.

**Comment by marvinhagemeister** [comment]
I'd really like us to revisit this. I've been writing a bunch of extensive tests in a recent project and always having to add `{ only: true }` instead of `.only` when wanting to debug a single test file becomes annoying pretty quick. It's too much to type.

**Comment by KyleJune** [comment]
> I'd really like us to revisit this. I've been writing a bunch of extensive tests in a recent project and always having to add `{ only: true }` instead of `.only` when wanting to debug a single test file becomes annoying pretty quick. It's too much to type.

With the current design, that would only work with top level `Deno.test`. You wouldn't be able to do that with test steps, see my previous comment for the reason why. The only reason I can see for not adding it would be that it might cause confusion since users would assume they could do the same with steps too when they can't.

I'd personally recommend using `testing/bdd.ts` since it already has that ability for both top level tests and test steps. It's pretty easy to start using since the call signatures are almost the same and you can have a mix of both ways of registering tests, which mean you can incrementally switch over to using it rather than having to update all tests at once.

See the [manual](https://deno.land/manual@v1.36.4/basics/testing/behavior_driven_development) for more details about using `testing/bdd.ts`.

**Comment by marvinhagemeister** [comment]
@KyleJune I'm aware of the bdd API and used it in the past. To me the out of box experience should be good. I shouldn't have to reach to a library for that.

To me it's perfectly fine to only add that for `Deno.test` and not for steps. That's what I had in mind. Adding that to steps seems conceptually wrong, since the encompassing test might have local state variables where each step expects them to be in the state of the previous one. Whilst the issue title includes steps, I'd ignore these. I'm mainly interested in `Deno.test.only` and `Deno.test.skip`
