### ISSUE TITLE
Deno "strict mode" type checking doesn't seem to work

### ISSUE THREAD

**Issue by treuks** [denoland/deno#17155]
**Describe the bug:**
Deno doesn't seem to complain if you replace undefined in the global scope.

**To reproduce:**
Create a function called undefined, put whatever in it, and try to call it.

**Expected behavior:**
Deno should give you a typecheck error, `Declaration name conflicts with built-in global identifier 'undefined'.`

**Screenshots:**
![image](https://user-images.githubusercontent.com/18615981/208874144-e9d84bfc-9ada-4c0c-8a21-90348b4d0a92.png)

![image](https://user-images.githubusercontent.com/18615981/208873793-c2bfef6c-71bb-484f-a875-7e0a10cb1aeb.png)

**Versions:**

vscode: 1.74.2 (Universal) deno: 1.29.1 extension: v3.15.0

**Comment by treuks** [comment]
uhhhh 
![image](https://user-images.githubusercontent.com/18615981/208877639-05116121-c5d9-40af-b83c-80d527d9ff7c.png)

**Comment by dsherret** [comment]
The reason you get the type error in the editor is because that's a script and not a module. In Deno everything is a module. You can see that TypeScript does not complain about this in a module here: https://www.typescriptlang.org/play?#code/MYewdgzgLgBArmAJgUwGYEszMTAvDACgEo8A+GAbwCgYZRIQAbZAOkZAHMCAiAD0QGJuRANxUAvmKoIUGLImJTkvAA4gATrAqSgA

Also, this works at runtime, so it seems TypeScript is accurately reflecting what's allowed at runtime. Use `deno lint Untitlted-1.ts` for these kind of things.
