### ISSUE TITLE
`deno lint` exclude rule as CLI option does not take precedence if config file has it as include rule

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#17161]
While working on https://github.com/denoland/deno/pull/17008 I found a bug in how lint rules take precedence. In general the CLI flags take precedence over the config file but when linting, include rules in the config file also take precedence over exclude rules. However, when `--rules-exclude=<rule>` is used while the same rule is in the include field in the config file, the CLI flag does not take precedence.

Reproduction:

```ts
// main.ts
const foo = "bar";
```

```json
{
  "lint": {
    "rules": {
      "include": ["no-unused-vars"]
    }
  }
}
```

```
deno lint --rules-exclude=no-unused-vars

(no-unused-vars) `foo` is never used
const foo = 'bar';
      ^^^
    at C:\Users\GJZwiers\repos\repo\main.ts:1:7

    hint: If this is intentional, prefix it with an underscore like `_foo`    
    help: for further information visit https://lint.deno.land/#no-unused-vars

Found 1 problem
Checked 1 file
```

**Comment by kamilogorek** [comment]
CLI flag does take precedence here. The issue is that including both `include` and `exclude` will always prefer the `include` rule, no matter its content.

If you set:

```json
{
  "lint": {
    "rules": {
      "include": ["no-unused-vars"],
      "exclude": ["no-unused-vars"]
    }
  }
}
```

which is effectively what happens when you pass the CLI flag, it will still apply the rule.

I do believe, however, that `exclude` should take precedence, otherwise it's not easily possible to override flags via CLI.
We need to take into consideration the fact that when it's changed, the reverse will be impossible (which I believe is a way less common scenario).

Another possibility is to "prefilter" flags on the CLI side prior to handing it to `deno_lint`.

**Comment by kamilogorek** [comment]
Possible fix directly in `deno_lint` - https://github.com/denoland/deno_lint/pull/1104
