### ISSUE TITLE
npm import fails for package without any entrypoint

### ISSUE THREAD

**Issue by nikitavoloboev** [denoland/deno#17198]
Trying to import this package: https://www.npmjs.com/package/@raycast/api

I put in import: 

`import { Detail } from "npm:@raycast/api";`

Full code [here](https://github.com/nikitavoloboev/ts/blob/c462967ff49a1cf67124baad19a8309dc051fec5/raycast/test/src/index.tsx).

I get error trying to run the file:

```
❯ deno run -A raycast/test/src/index.tsx
error: Could not resolve 'npm:@raycast/api'.

Caused by:
    not found
```

Not sure what I am doing wrong, perhaps `@raycast`, the @ symbol is not supported?

I would like to have it run in deno as I want to [make raycast extensions](https://developers.raycast.com/basics/create-your-first-extension) in deno. Thanks.

**Comment by dsherret** [comment]
This is what I get trying to import this package in Node after using `npm install --ignore-scripts @raycast/api` because the post install script is a bash file, which fails on Windows:

```
> node main.mjs
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'V:\scratch\node_modules\@raycast\api\' imported from V:\scratch\main.mjs
```

This package has no entrypoints (bin/ray being a bash script):

![image](https://user-images.githubusercontent.com/1609021/211062524-f426dc3b-27a7-4d7c-b765-7e1293474559.png)

```
{
  "name": "@raycast/api",
  "version": "1.45.2",
  "description": "Build extensions for Raycast with React and Node.js.",
  "author": "Raycast Technologies Ltd.",
  "homepage": "https://developers.raycast.com",
  "repository": {
    "url": "https://github.com/raycast/extensions"
  },
  "license": "MIT",
  "types": "types/index.d.ts",
  "dependencies": {
    "@types/node": "18.8.3",
    "@types/react": "18.0.9",
    "react": "18.1.0",
    "react-reconciler": "0.28.0"
  },
  "peerDependencies": {
    "@types/node": "18.8.3",
    "@types/react": "18.0.9"
  },
  "peerDependenciesMeta": {
    "@types/node": {
      "optional": true
    },
    "@types/react": {
      "optional": true
    }
  },
  "scripts": {
    "postinstall": "bin/ray npm-post-install"
  },
  "bin": {
    "ray": "bin/ray"
  }
}
```

So for this one, follow #16164 for postinstall support.

Raycast could maybe get this to work by instead lazily initializing the package on first run in case the user skipped post install scripts. That said, to do that they'd have to ship some javascript in the package.
