### ISSUE TITLE
[fmt] Supporting remove semicolons

### ISSUE THREAD

**Issue by xieyuheng** [denoland/deno#17203]
The closing comment of this issue say: https://github.com/denoland/deno/issues/13616#issuecomment-1149836312

> This discussion is the perfect example why we will not be introducing additional options to the built in formatter. All source code written for Deno should use the same formatting options for consistency, and to reduce this kind of discussion. In our eyes ecosystem consistency is much more important than opinions of individuals. This is also why we limit configuration options of the runtime and type checker as much as we do.

But there are already many options:

```
--options-use-tabs
--options-line-width
--options-indent-width
--options-single-quote
--options-prose-wrap={always,never,preserve}
```

Beside the existing options, an option about semicolon is almost the only option that people want.

**Comment by qgustavor** [comment]
A few minutes ago I started working on a project, migrating an old Node project to Deno because I liked the idea of `deno compile`, how good it works, mostly because I had bad experiences in the past with pkg not working sometimes. While working on the project I noticed the issue above then added a note to future contributors "DO NOT use deno fmt: it does not have option to disable semicolons" followed by instructions about installing a linter using npm. I got curious about that, why? Then searched here for issues regarding when this feature will be implemented.

It was to my surprise that is not because Deno is "new" and because of that have few features, instead the formatter was made to force a specific style instead, one that I will not be using in my projects. Quite weird decision, reminds me of old [JSLint vs JSHint history](https://stackoverflow.com/a/10763615). I think way too inflexible tools might go in the way of JSHint: [a lot of people might still use it*](https://www.npmjs.com/package/jslint "I'm sure you know that npm downloads is not a good measure but, well, what I can do? It is just one I can cite to act as a reasonable acceptable proxy for the real number.") but most people will prefer [more flexible tools](https://www.npmjs.com/package/jshint) (not even talking about way more flexible [ESLint](https://www.npmjs.com/package/eslint), you can even find [people saying it being flexible is an advantage](https://medium.com/@sheldonled/from-jshint-to-eslint-8a0a135fa2bf)). I might be wrong, I can't predict the future, but I still quote “Those who cannot remember the past are condemned to repeat it.”

**Comment by xieyuheng** [comment]
If maintainers are not convinced that

> Beside the existing options, an option about semicolon is almost the only option that people want.

Please do not close and lock this issue like the old one,
and see how many people are searching for "semicolon" in the issue list.

I believe deno has a great team that cares about deno's user community :)

**Comment by lilnasy** [comment]
You can always use other formatting tools in deno projects.

**Comment by mattlucock** [comment]
I love Node, but I've just discovered Deno very recently, and would love to adopt it for personal projects. The fact that I somehow found this thread and am here commenting on it is proof of how signiciant of an issue this is. For JS devs like me who detest semicolons, being able to not use them is an order of magnitude more important than any of these other configuration options. It feels silly to me that there is an option for string quotes when it pales in comparison to an option for semicolons.

It doesn't help that the stated rationale for not supporting this doesn't seem to make sense, as @xieyuheng has identified. The argument essentially seems to be that there are all these discussions people would want to have about formatting rules, so these discussions should be precluded by there being a single, prescribed style.

The first issue is that, as also pointed out by @xieyuheng, semicolons is basically the only option missing from the current set of options. I don't think there's any reason to believe that this is some kind of slippery slope; `deno fmt` supports all the options I want, except for semicolons. That's literally it. The second issue is that, as others have pointed out, the line has already been drawn somewhere. The fact that options for indentation, line width, and string quotes already exist is itself an admission that one style does not fit all. If "ecosystem consistency" really is the singularly important goal, then the only logical conclusion is that these options should be removed. Why should individual developers be allowed to disagree about string quotes (realistically a minor issue) if ecosystem consistency is much more important than opinions of individuals?

As long as these options exist, no single, prescribed style exists. As long as these options exist, people will continue to re-open old issues, like this, asking for there to also be a semicolon option.

"Ecosystem consistency" is a noble ideal, and from my limited understanding, it seems like `deno lint` (which I note is also configurable) goes a long way to achieving that. Unfortunately, we are writing JavaScript.

**Comment by xieyuheng** [comment]
It is unlikely this will be supported by deno.

I just use prettier.

I apologize for opening this issue.

**Comment by dsherret** [comment]
Since people felt so strongly about this, Deno 1.30 has semicolon configuration https://deno.com/blog/v1.30#deno-fmt-supports-configuring-semicolons

**Comment by xieyuheng** [comment]
God bless Deno Community
