### ISSUE TITLE
`server.unref` (from `net.createServer`) does not throw "unstable required" error

### ISSUE THREAD

**Issue by hasezoey** [denoland/deno#17307]
i have noticed that `server.unref` (or specifically `TCP.unref`) is not throwing a `Requires --unstable` error and just throws a error that `unref` is not a function, but works when adding `--unstable` to the command

error:
```txt
error: Uncaught TypeError: this[#listener].unref is not a function
      this.#listener.unref();
                     ^
    at TCP.unref (https://deno.land/std@0.171.0/node/internal_binding/tcp_wrap.ts:236:22)
    at Server.unref (https://deno.land/std@0.171.0/node/net.ts:2395:20)
    at Server._setupListenHandle [as _listen2] (https://deno.land/std@0.171.0/node/net.ts:1955:10)
    at _listenInCluster (https://deno.land/std@0.171.0/node/net.ts:1676:12)
    at Server.listen (https://deno.land/std@0.171.0/node/net.ts:2165:9)
    at file:///mnt/projects/nodejs/mongoose/deno-test.js:31:8
```

script:
```ts
'use strict';

import { createRequire } from "https://deno.land/std/node/module.ts";

const require = createRequire(import.meta.url);

const net = require('net');

const server = net.createServer();

server.unref(); // without this it is running fine without "--unstable" and only works in "--unstable"

server.listen(9000, () => {
    console.log("server listening")
    server.close(() => {
        console.log("server closed")
    });
});
```

command:
```sh
deno run --allow-read --allow-net ./deno-test.js
```

versions:
```txt
deno 1.29.2 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by kamilogorek** [comment]
This is a known issue, see: https://deno.land/manual@v1.29.2/basics/standard_library#troubleshooting

**Comment by bartlomieju** [comment]
We should stabilize this API for v1.30

**Comment by hasezoey** [comment]
> This is a known issue, see: https://deno.land/manual@v1.29.2/basics/standard_library#troubleshooting

i know that his is currently a unstable API, but the issue is about that the error does not say so, example from the [link you provided](https://deno.land/manual@v1.29.2/basics/standard_library#troubleshooting):
```txt
TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
```
(note that this is a type error)

or a example from my previous issue (at #17297):
```txt
error: Uncaught TypeError: Requires --unstable
```
(note that this is a runtime error)

the error i have encountered:
```txt
error: Uncaught TypeError: this[#listener].unref is not a function
```
(note that this is a runtime error)

**Comment by kamilogorek** [comment]
Ah gotcha. You are correct, it's failing due to the fact, that `Deno.listen` returns a `Listener` which `unref` method is unstable - https://deno.land/api@v1.29.2?s=Deno.Listener&unstable=
It's called indirectly through node's `net` package, and the check there in TCP is only done for `listener` existence, not method existence like it's done in other places - https://github.com/denoland/deno_std/blob/06bec6012ab6fb3dbda539e4c51c531e5501f30a/node/internal_binding/tcp_wrap.ts#L234-L238
eg. https://github.com/denoland/deno_std/blob/06bec6012ab6fb3dbda539e4c51c531e5501f30a/node/net.ts#L1953-L1957 or https://github.com/denoland/deno_std/blob/06bec6012ab6fb3dbda539e4c51c531e5501f30a/node/net.ts#L1103-L1105
