### ISSUE TITLE
ffi:The type of pointer should depend on the system bit width, not the size of the pointer's value

### ISSUE THREAD

**Issue by tianxiadys** [denoland/deno#17316]
The return result of `Deno.UnsafePointer.of` is Number or BigInt, which should depend on whether I'm running on a 32-bit system or a 64-bit system, not on whether a 32-bit length can accommodate a pointer

For example, this is an important function in the Windows system
```
typedef struct tagWNDCLASSEXW {
  UINT      cbSize;
  UINT      style;
  WNDPROC   lpfnWndProc;
  int       cbClsExtra;
  int       cbWndExtra;
  HINSTANCE hInstance;
  HICON     hIcon;
  HCURSOR   hCursor;
  HBRUSH    hbrBackground;
  LPCWSTR   lpszMenuName;
  LPCWSTR   lpszClassName;
  HICON     hIconSm;
} WNDCLASSEXW, *PWNDCLASSEXW, *NPWNDCLASSEXW, *LPWNDCLASSEXW;
ATOM RegisterClassExW(
  [in] const WNDCLASSEXW *unnamedParam1
);
```

When I tried to call it using ffi

```
let a1 = new Uint8Array(100)

//copy L"DemoWndClass" into a1 here
//Neither deno nor js seems to provide such a function, and I need to do it myself through a loop

let a2 = Deno.UnsafePointer.of(a1)//a2 is a Number, not a BigInt
let b1 = new Uint8Array(96)
let b2 = new DataView(b1.buffer)

//cbSize=96
b2.setUint32(0, 96, true)
//lpszClassName=L"DemoWndClass"
b2.setBigUint64(0, a2, true)//error: Uncaught TypeError: Cannot convert 2314604269232 to a BigInt

//ffi call here

```

**Comment by tianxiadys** [comment]
sorry The first argument of calling the setBigUint64 function was written incorrectly, it should be 88

**Comment by tianxiadys** [comment]
sorry, The first argument of calling the setBigUint64 function was written incorrectly, it should be 80

**Comment by aapoalas** [comment]
1. Deno is currently only supported on 64-bit systems, so presumably you're also running on a 64-bit system. If you're not, please let the Deno folks know what sort of patches you needed to setup to get Deno to build on a 32-bit system as I'm not sure anyone has done that before.

2. There is indeed a method to copy data through a pointer into a JS buffer, it is this one: https://deno.land/api@v1.29.2?unstable=&s=Deno.UnsafePointerView#method_copyInto_0

So you could do the copying to `a1` like this:
```ts
const a1 = new Uint8Array(100);
const view = new Deno.UnsafePointerView(demoWndClass);
view.copyInto(a1);
```

3. The `setBigUint64` API needs to be called with a BigInt. Regardless of if Deno gives you a pointer number as a JS Number or BigInt, you can safely convert to BigInt by simply calling `BigInt(value)`. So here you'd call:

```ts
b2.setBigUint64(80, BigInt(a2), true);
```

Currently the returning of pointer numbers as `number | bigint` is done for performance reasons, but this may change in the near future with some changes coming to V8's Fast API. At that point it might indeed be so that Deno chooses to fully use BigInts as pointers. Then, if Deno eventually gains support for 32-bit environments, the pointer number type for 32-bit environments may become `number` instead. A secondary reason for the `number | bigint` type is that it's not expected that pointer arithmetic would commonly be done in JS side, meaning that it's unlikely that a user will need to actually do anything more than pass a pointer as an opaque parameter in JS. Your use case of emplacing in an array / DataView is the one common enough exception, but it is also luckily easily handed using the above-mentioned `BigInt(pointerNumber)` conversion.

**Comment by tianxiadys** [comment]
1. I'm also running on a 64-bit system, but I think it's reasonable to use the number type on a 32-bit system, so I mentioned that
2. copy string to ArrayBuffer with wide char encoding, I'm using this function to do it now, It contains a 0 terminator
```
function stringToBuffer(input) {
    let result = new Uint16Array(input.length + 1)
    for (let index = 0; index < input.length; index++) {
        result[index] = input.charCodeAt(index)
    }
    return result.buffer
}
```

**Comment by tianxiadys** [comment]
I've got the answer I want, thank you very much
