### ISSUE TITLE
feature request: prompt to add import map entry if deno finds bare import.

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#17344]
This proposal tries to improve the usability of `npm:` compat feature.

---

If the module resolver finds a bare specifier (and it can'be resolved using import maps), then prompt the user to add import map entry of the form `"foo": "npm:foo@[latest-version-of-foo]"` (or `"foo": "npm:foo@^[latest-version-of-foo]"`) and if the user answers 'yes', then keep resolving it using the updated import map.

(If there's no import map applied, then CLI automatically creates it and specify it in `deno.json`'s `importMap` entry. If `deno.json` doesn't exist, then CLI also automatically create it.)

---
Example:

If the user runs the below script:

example.js
```ts
import express from 'express';
const app = express();
app.listen(3000, () =>
  console.log('Example app listening on port 3000!'),
);
```

Then, it prompts like:

```shellsession
$ deno run example.js
⚠️  ┌ Deno tries to import from "express" (example.js:1:22)
   └ Do you want to map "express" to "npm:express@^4.18.2"? [y/n] (y = yes; n = no) >
```

If the user answers 'yes', the code runs using the 'npm:' dependency:

```shellsession
$ deno run example.js
✅ Added mapping from "express" to "npm:express@^4.18.2" in "path/to/import_map.json".
Example app listening on port 3000!
```

**Comment by albnnc** [comment]
It feels like Deno shouldn't advertise NPM too much, since it is, as far as I know (or want to think), stays ESM-oriented anyway (I mean, not package-oriented). _Please, correct me if I'm wrong._

Moreover, bare specifiers aren't NPM-specific, so it's completely OK to use them without NPM even for backend development. Proposed feature will probably make these use-cases much harder and inconvenient to handle for developer – why would anyone want to select "no" multiple times?

To be honest, this feature would make me kinda sad, since I mostly want to abstract away from NPM but still using bare specifiers with import maps and URL-based CDNs like deno/x.

By the way, even deno.json auto creation is some sort of too opinionated thing to do. Prompts are not like project starters and boilerplates – if someone prefers not to use deno.json and use import map via CLI option, this action would be very unhandy.

**Comment by kt3k** [comment]
The prompt only happens when the bare specifier can't be resolved using import maps. You can still use bare specifier that is mapped to `deno.land/x/*` (or any urls), and they don't prompt the above question (I updated the original issue comment to clarify it).

The point is when the user uses bare specifiers without corresponding import map entries, then the intention may be npm modules (because that's how people use npm modules in Node now). This feature tries to help the users from npm ecosystem start up on Deno project smoothly

**Comment by kt3k** [comment]
Closing this as the situation around bare specifiers will be significantly changed by https://github.com/denoland/deno/issues/17475
