### ISSUE TITLE
Do not permission prompt for statically analyzable dynamic imports

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#17697]
Statically analyzable dynamic imports are part of the graph on startup and are inspectable in the code similarly to any regular import declaration. They also show up in `deno info`. Perhaps we should not bother requiring `--allow-net` when they load?

Related: #14877

**Comment by Mehrbod2002** [comment]
@dsherret Can i work on it ?

**Comment by dsherret** [comment]
@Mehrbod2002 sure! This issue is just a suggestion, but I’m pretty sure it’s going to be done. Just note it’s for 2.0 so if you work on it then the branch might live for a bit longer than usual.

**Comment by Mehrbod2002** [comment]
@dsherret 
Great , I am going forward with it .
Thanks

**Comment by nayeemrmn** [comment]
Should this be done for a minor version rather than 2.0? These imports are fetched statically so as it stands, Deno prompts for a permission which it won't use / act upon. That's bordering on a bug. Net permissions for dynamic imports guard runtime-gathered user data which might be exfiltrated in the module request URL, not third party code execution (which would be redundant).

If anything, the runtime is less secure as long as this use case requires granting more permissions than what should be necessary.

**Comment by aapoalas** [comment]
Agreed. IMO this is simply a bug.

**Comment by jtoppine** [comment]
This difference of statically analyzable imports vs plain dynamic imports seems pretty surprising to me. If the behaviour is considered part of the public API, that's weird, magical one. 

Although the behaviour might be desireable in most cases, it may be causing confusion in other cases, like catching edge cases and permission issues during testing and development. Should the developer know that  `import("./foo/bar.ts")` has completely different behaviour to `import("./foo/" + "bar.ts")`, permissions-wise?

This certainly has implications on permissions. But does a statically analyzable import also mean they are parsed and loaded on startup regardless of them being actually ever used? If so, it might be also undesireable if the dynamic import mechanism is used for lazy loading, to improve startup performance.

> If anything, the runtime is less secure as long as this use case requires granting more permissions than what should be necessary.

I agree, a fair point.

Personally I believe dynamic imports should always work the same statically analyzable or not. Any change in behavior should have explicit API.

An example use case: Say, I have code for rendering a bunch of different file types, like office documents and different image types. It has a mechanism to dynamically import support for a given mimetype the first time such a file is encountered.  For safety/sandboxing reasons, this file rendering code is run in a deno subprocess with very limited permissions. 

It can be tricky to make sure the code is able to do the dynamic imports it needs, but anything else is denied. For testing this it is a bit weird/surprising if a statically analyzable import behave somehow differently to an actually dynamic dynamic import. 

I feel like any API should be more explicit than formatting strings to try and make sure they are/are not statically analyzable. You can now kinda whitelist modules by statically importing files to ensure it is available for dynamic import later without permission issues. But they won't be lazy-loaded anymore, making the dynamic import kinda pointless. Would be nice to be able to statically "preload" a file that might possibly be dynamically imported later..

Went on a tangent here, sorry folks :)

**Comment by jespertheend** [comment]
> But does a statically analyzable import also mean they are parsed and loaded on startup regardless of them being actually ever used?

It seems like that's the case. When you do something like
```js
console.log(performance.now());
if (false) await import("./path/to/module/with/large/tree.js");
```
It logs a much higher value than when the import is not statically analyzable.

Making the import not statically analyzable would be a good workaround if it weren't for the fact that this completely removes types. For instance:
```js
const {puppeteer} = await import("https://deno.land/x/puppeteer@16.2.0/mod.ts" + "");
puppeteer; // any
```
You might think you'd be able to work around this by casting the import, but this requires the same import again and thus would still slow down startup time. Even when `--no-check` is used.

**Comment by nayeemrmn** [comment]
> This difference of statically analyzable imports vs plain dynamic imports seems pretty surprising to me. If the behaviour is considered part of the public API, that's weird, magical one.

I also used to think the same, but it's essentially a given due to how TypeScript supports typings for statically analyzable dynamic imports. Stemming from there it becomes a requirement to preload such imports, which results in things like `write("foo.ts"); await import("./foo.ts")` being quirky. And it follows that the runtime net access doesn't occur so it shouldn't prompt.

Basically this ship has sailed from the perspective of build tools / static analysis. At this point I think it's viable to carry forward with these behaviours and suggest that users do `const s = "./foo.ts"; await import(s)` where they want to opt out.

**Comment by jtoppine** [comment]
> I also used to think the same, but it's essentially a given due to how TypeScript supports typings for statically analyzable dynamic imports. 

Okay, thank you for the explanation! I personally only use JS, so these TS related quirks/compromises are alien to me. But sounds like valid reasoning..

**Comment by nayeemrmn** [comment]
> > At this point I think it's viable to carry forward with these behaviours and suggest that users do `const s = "./foo.ts"; await import(s)` where they want to opt out.
> 
> But that suffers from the issue where it completely makes the imports type unsafe. Would it not be possible to to ignore type imports and dynamic imports, unless a command is used that needs type checking?

Two things to note are that what we're talking about is the current behaviour irrespective of this issue, and that users haven't suffered any from this even if it seems surprising on paper. Consider that if a user is writing a file before importing it, the code would naturally look like this in the first place:
```ts
const path = "./foo.ts";
await Deno.writeTextFile(path, "// content...");
await import(path);
```
And if the imported path or content is dynamic, there are no typings to correctly infer. I suspect it's rare to extract a specifier variable for other reasons while still expecting typings (since pretty much nobody complains).

**Comment by jespertheend** [comment]
Ah apologies, I was referring to the slow startup time. I suppose a separate issue should be opened for that.
The reason why I'm addressing this is because, aside from the startup time, I'm also running into many issues caused by seemingly unrelated dynamic/type imports, many of which I think would be fixed if type imports and dynamic imports were ignored.

**Comment by NfNitLoop** [comment]
Copy/pasting from [this comment][1], since the concern is relevant to the proposed solution here:

[1]: https://github.com/denoland/deno/issues/18514#issuecomment-1492752907

> If https://github.com/denoland/deno/issues/17697 only relaxes permissions for statically-analyzable dynamic imports (SADIs), then if I deno install a program with SADIs, deno run is still going to try to fetch them from the network each time.
> [...]
> [That] means a malicious actor could change the code of the dynamic import after I've done a `deno install`.

IMO, that's a regression on Deno's permission checking.  If I haven't specified `--allow-net`, I don't expect a `deno install`ed program to be able to change its behavior on different runs depending on the status of network resources.

(Unless `deno install` is (or will be) caching the statically-analyzed dynamic import? Is that part of this proposal? IMO it should be to avoid this security regression.)

**Comment by davidbludlow** [comment]
This is deployed!

Unfortunately, the documentation of this isn't complete (as far as I know), so I am finding differing and disturbing answers to the question "Are statically-analyzable dynamic imports always fetched at program start (unless already cached)?" The [blog post about the release of this feature](https://deno.com/blog/v1.33#fewer-permission-checks-for-dynamic-imports) seems to sorta imply that the answer to that question is "no" which would be a HUGE SECURITY hole. (If you want an explanation of why that is a security hole, just ask.)

@jespertheend said that [it seems like the answer to that question is "yes"](https://github.com/denoland/deno/issues/17697#issuecomment-1486509016) which would mean there is no security issue, but if that is true, then shouldn't that be in some official documentation?

Sorry, I don't have the Rust knowledge to figure out the answer to this question myself. I just want to be able to securely run black-box programs with Deno.

Side Note: @dsherret, I am a fan of your work on various projects. Keep it up!

**Comment by nayeemrmn** [comment]
> "Are statically-analyzable dynamic imports always fetched at program start (unless already cached)?" The [blog post about the release of this feature](https://deno.com/blog/v1.33#fewer-permission-checks-for-dynamic-imports) seems to sorta imply that the answer to that question is "no"

I think you're talking about the claim of having improved startup time from 'conditional loading'. Rest assured that this refers to the 'load' from the host graph storage into V8 as an instantiated script (as well as the evaluation). Not download.

**Comment by davidbludlow** [comment]
Thanks for that answer!
