### ISSUE TITLE
Nix version is outdated

### ISSUE THREAD

**Issue by ConProgramming** [denoland/deno#17726]
The version of deno in nix is outdated. This especially effects replits.

**Comment by levex** [comment]
Hey @ConProgramming, deno in nixpkgs-unstable is now 1.32.3, see this tracker: https://nixpk.gs/pr-tracker.html?pr=221462

**Comment by levex** [comment]
1.32.4 can be tracked via https://nixpk.gs/pr-tracker.html?pr=226158
PR https://github.com/NixOS/nixpkgs/pull/226158

**Comment by 06kellyjac** [comment]
Since the packaging of deno is not part of denoland done in https://GitHub.com/nixos/nixpkgs please raise issues there in the future & cc me (@06kellyjac) for visibility.

Thanks

---

Ive not cross-referenced this issues creation against what version was in nixpkgs but the recent delays to updating deno were due to delays getting rust 1.68 through our staging process which was required for compiling newer deno.
