### ISSUE TITLE
Disabling test sanitizers causes test steps to not be logged in time.

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#17788]
Whenever a test gets stuck, it's very difficult to figure out at which step it keeps hanging.

Here's a reduced test case:
```js
import {serve} from "https://deno.land/std@0.177.0/http/mod.ts";

// Start a server to keep the process running without
// 'Promise resolution is still pending but the event loop has already resolved.'
serve(() => new Response("hello"));

Deno.test({
	name: "hanging step",
	sanitizeOps: false,
	sanitizeExit: false,
	sanitizeResources: false,
	async fn(ctx) {
		await ctx.step("Step 1", async (ctx) => {
			await ctx.step("Step 2", async (ctx) => {
				// A promise that never resolves
				await new Promise(r => {});
			});
		});
	}
});
```

Then run with `deno test --allow-net the.test.js`.

For me this keeps hanging without ever logging the steps. Enabling either one of the three disabled sanitizers fixes the issue.

I've been getting a flaky e2e test that I suspect is hard to debug because of this. Though for some reason in that case the name of the test itself isn't being logged either. I think my workaround for now will be to replace all test steps with `console.log`.

**Comment by kamilogorek** [comment]
This is the check that prevents printing in this specific case, as it detects that there are no sanitizers for the test-case.

https://github.com/denoland/deno/blob/f8435d20b0e9408e50bfb24793becc0e476cc285/cli/js/40_testing.js#L448-L451

Although I'm not sure if that's necessary, as `preValidation` already does all the heavy lifting here and it should be safe to remove the `canStreamReporting(desc)` check.

**Comment by nayeemrmn** [comment]
It's sort of intentional,
- Steps aren't reported live if they may be running concurrently
- Steps may only run concurrently if test sanitizers are off
- Therefore test sanitizers being off disables steps being reported live

This doesn't account for users who turned off sanitizers for separate reasons and still want live reporting, though. It also resulted in some confusing internal code as hinted above.

[2.0 change] We should probably have a separate `TestStepDefinition::parallel` option, that would 1) solely gate whether a test step can be run alongside others, 2) implicitly turn sanitizers off and 3) disable live reporting. Note that it would break existing parallel steps.

We should also have an interrupt handler that prints off the list of pending tests before exiting, that should help a lot in your case.

**Comment by jespertheend** [comment]
Ah I see, that makes sense.
I moved away from using steps for the time being and I'm now simply logging events using a basic logger. This also made it a lot easier to work around #14635.
