### ISSUE TITLE
Dynamic npm module imports should be able to fail individually #17770

### ISSUE THREAD

**Issue by bershanskiy** [denoland/deno#17802]
This is split away from #17770 

#17770 fixes crash on some module imports. Namely, after #17770 the following lines no longer crash deno:
```js
import("npm:ws:")
import("npm:wss:")
```
However, that PR did not fix module resolution. In particular:

Module resolutions are still bundled and failure of dynamic import will fail resolution of static modules too
```js
import a from "npm:ok-module";
try {
  await import("npm:bad-module");
} catch (e) {
  console.log("This should print");
}
console.log("This should print");
```

Failure of one dynamic import will fail import of other dynamic imports:
```
$ rm -rf ~/.cache/deno/npm/registry.npmjs.org/semver/
$ deno
Deno 1.30.3+0aeb8bc
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> const a = import("npm:" + "aefsfddsadv"); const b = await import("npm:" + "semver"); console.log("123")
Uncaught TypeError: Could not resolve 'npm:semver'.
  Caused by:
    could not find npm package directory for 'semver'
    at async <anonymous>:3:11
> const s = await import("npm:semver")
undefined
> s
Module {
  Comparator: [Class: Comparator],
  Range: [Class: Range],
  SEMVER_SPEC_VERSION: "2.0.0",
  SemVer: [Class: SemVer],
...
```

**Comment by dsherret** [comment]
This is specific to npm specifiers and will work fine otherwise. The support for npm specifiers with dynamic imports is limited at the moment (for example, we don't support non-analyzable dynamic imports). For handling this scenario, I'm not entirely sure we want to have them work this way because it would mean essentially doing an npm install for these imports at runtime instead of always having them prepared on startup as they're done now. That said, it would align more with the way dynamic imports are supposed to work, but at the same time code being able to dynamically install npm packages sounds sketch on the surface... perhaps it would need permission to do that, but I haven't thought about it much.

**Comment by aapoalas** [comment]
Non-analysable dynamic NPM imports actually do work.

**Comment by dsherret** [comment]
I believe they only work if they've been analyzable before (ex. loaded from lockfile or some other import)

**Comment by dsherret** [comment]
I just realized my upcomming deno graph refactor should make it work this way. It does the analysis ahead of time then errors later when the dynamic import gets executed.

That said, I'm not sure this would fix it for the repl. The repl has separate handling of npm specifiers compared to when you actually run code.

**Comment by tmcw** [comment]
I'm not sure about the status of this - assuming that the graph refactor hasn't landed yet? Right now if you do a bad import or transitive import of something that fails the module name parsing, it becomes no longer possible to use dynamic import() against anything for the rest of the time that process is running.
