### ISSUE TITLE
Deno 1.31.0 downloads Node modules without being asked to

### ISSUE THREAD

**Issue by MKRhere** [denoland/deno#17928]
Consider this situation:

```shell
$ ls
node_modules
package-lock.json
package.json
update-list.ts
...

$ cat package.json
{
  "dependencies": {
    "typescript": "^4.9.5"
  }
}

$ cat update-list.ts
console.log("test");

$ deno run update-list.ts
# downloads typescript from package.json dependencies
```

Deno has no need to look into Node modules here, since `update-list.ts` is its own standalone Deno script. However in this case, it still installs `typescript` first. This is unnecessary. Is this intentional? Is there going to be no way to have Deno scripts in an otherwise Node project?

**Comment by dsherret** [comment]
I'm thinking we should do the following:

1. If no npm dependencies are found, it will not run an npm install.
2. On the first npm dependency encountered, it will install all the package.json dependencies.

We need to install package.json dependencies ahead of time before other npm dependencies so that it works similarly to how npm installs.

**Comment by MKRhere** [comment]
Sounds good!
