### ISSUE TITLE
Allow Comments in package.json

### ISSUE THREAD

**Issue by machineghost** [denoland/deno#18044]
It's always struck me as a major flaw that you can't document your `package.json` file, but there's no technical reason it needs to be that way.  Deno should correct Node's mistake, and allow comments in that file.

**Comment by petamoriken** [comment]
I think that is a issue of whether Node.js allows `package.jsonc` or not, not a Deno issue.

**Comment by machineghost** [comment]
Right, but Deno could simply parse comments out before processing the file, allowing Deno users to comment their `package.json` (or `package.jsonc`, if Deno supported it).

**Comment by dsherret** [comment]
I don't think we should allow this because many tools read a package.json file and once people start adding comments to a package.json then those other tools will break. Also, the package.json only exists in deno for compatibility reasons. I'd recommend migrating to a deno.jsonc file which supports comments instead.

**Comment by dsherret** [comment]
I'm going to decline and close this one. Again, I recommend using a deno.jsonc file instead, which supports comments.

**Comment by Delapouite** [comment]
It looks like they decided to do it in Bun land : https://bun.sh/blog/bun-v1.1.5#package-json-with-comments-and-trailing-commas
