### ISSUE TITLE
TypeScript errors when accessing DenoError

### ISSUE THREAD

**Issue by ry** [denoland/deno#1810]
The following crashes in v0.3.0:
```ts
const { DenoError } = Deno;
const e = {};
e as DenoError;
console.log("ok");
```
With the following error
```
> deno tests/deno_error.ts
Compiling file:///Users/rld/src/deno/tests/deno_error.ts
/Users/rld/src/deno/tests/deno_error.ts:3:6 - error TS2304: Cannot find name 'DenoError'.

3 e as DenoError;
       ~~~~~~~~~
```

cc @kitsonk 
ref https://github.com/denoland/deno_std/pull/205

**Comment by j-f1** [comment]
This is because `const` pulls the value `DenoError` out, but not the corresponding type. You’d have to do `type DenoError = Deno.DenoError` or `e as typeof DenoError` instead.

**Comment by ry** [comment]
But the following works:

```ts
// x.ts
import { C } from "./c.ts";
const x = {};
x as C;
console.log("ok");
```
```ts
// c.ts
export class C { }
```

```
> deno x.ts
Compiling file:///Users/rld/x.ts
ok
```

**Comment by kitsonk** [comment]
When importing the local type scope matches the variable scope, so `import { DenoError } from "deno";` works.  That is because there is an implied import/export of the type scope with `import`.  When you are destructing variables, the type scope isn't changed, so when using in a type position it would either be:

```ts
e as Deno.DenoError;
// or
type DenoError = Deno.DenoError;
```

While I don't know the whole reasoning, is if the type scope changed every time you created a variable, the type scope would become unwieldy.  I haven't looked to see if there is an issue for this in TypeScript, but I suspect they wouldn't have a good reason to change that behaviour though.

**Comment by bartlomieju** [comment]
`DenoError` has been replaced with specified error classes in #3936 so this issue is no longer valid.
