### ISSUE TITLE
`node:path` module contains non-node symbols

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#18177]
Namely exports from https://deno.land/std@0.179.0/path/glob.ts, https://deno.land/std@0.179.0/path/separator.ts and some others. Also missing circular references like `path.posix.posix === path.posix`.
```ts
import path from "node:path";
console.assert(path.SEP === undefined);
console.assert(path.SEP_PATTERN === undefined);
console.assert(path.fromFileUrl === undefined);
console.assert(path.globToRegExp === undefined);
console.assert(path.isGlob === undefined);
console.assert(path.joinGlobs === undefined);
console.assert(path.normalizeGlob === undefined);
console.assert(path.toFileUrl === undefined);
console.assert(path.posix.fromFileUrl === undefined);
console.assert(path.posix.toFileUrl === undefined);
console.assert(path.win32.fromFileUrl === undefined);
console.assert(path.win32.toFileUrl === undefined);
console.assert(path.posix.posix === path.posix);
console.assert(path.posix.win32 === path.win32);
console.assert(path.win32.posix === path.posix);
console.assert(path.win32.win32 === path.win32);
if (Deno.build.os == "windows") {
  console.assert(path === path.win32);
} else {
  console.assert(path === path.posix);
}
```

**Comment by andrewnester** [comment]
@bartlomieju if my understanding correct, removing listed function from the module export will be a breaking change, f.e. I see `fromFileUrl ` being used across Deno codebase and thus potentially by other users

**Comment by bartlomieju** [comment]
It appears most of uses of `fromFileUrl` can simply be replaced with `new URL()`. If these symbols are not supposed to be exported then we should removed them. It won't be a breaking change, because Node.js doesn't export these symbols and thus this is a bug on our side.

**Comment by RyanClementsHax** [comment]
I'm looking to pick this one up. What exactly does this entail? What exactly are the non-node symbols being exported? Is it all of https://deno.land/std@0.179.0/path/glob.ts, and https://deno.land/std@0.179.0/path/separator.ts?

**Comment by andrewnester** [comment]
@RyanClementsHax methods and constants listed in example below, such as SEP, fromFileUrl and etc. are not part of NodeJS path module specification and thus should not be exported.

Essentially, you can use the above example as a test case which passes

**Comment by RyanClementsHax** [comment]
Thanks! I'll take a crack at it

**Comment by andrewnester** [comment]
@RyanClementsHax it actually should be changed in NodeJS polyfills module, for example, here SEP and SEP_PATTERN is wrongly exported

https://github.com/denoland/deno/blob/686fe477496cf6eee398eb8ac195692528d3f427/ext/node/polyfills/path/mod.ts#L32

**Comment by RyanClementsHax** [comment]
Oh my bad. I'll make the changes there instead.

**Comment by RyanClementsHax** [comment]
Isn't there still the issue of fromFileUrl or do we want to tackle that in a separate PR?

**Comment by ayame113** [comment]
`fromFileUrl` could be replaced with `pathFromURL` in `ext/web/00_infra.js`.

https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/web/00_infra.js#L444

> Keep in sync with `fromFileUrl()` in `std/path/win32.ts`.
> https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/web/00_infra.js#L394

**Comment by RyanClementsHax** [comment]
Thanks for the help. I plan on looking at this this week

**Comment by RyanClementsHax** [comment]
Is there a reason we had two separate functions? I'm just looking to be careful in light of [Chesterton's fence](https://thoughtbot.com/blog/chestertons-fence#:~:text=Chesterton's%20Fence%20is%20a%20principle,why%20it%20was%20put%20up.)

**Comment by bartlomieju** [comment]
@RyanClementsHax probably no particular reason. Feel free to remove one of them.

**Comment by RyanClementsHax** [comment]
After doing some research, I found the following.

`fromFileURL` as defined in [node/polyfills/path/_posix.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/_posix.ts#L488) and [node/polyfills/path/_win32.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/_win32.ts#L964) has the following files depending on it
- [child_process_unref.js](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/cli/tests/unit_node/testdata/child_process_unref.js#L5)
- [deno_workspace.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/tools/release/deno_workspace.ts#L9)
- [win32.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/win32.ts#L13)
- [posix.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/posix.ts#L13)
- [polyfills/path/mod.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/mod.ts#L31)
- [_win32.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/_win32.ts#L964)
- [_posix.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/path/_posix.ts#L488)
- [_fs_writeFile.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_writeFile.ts#L3)
- [_fs_utimes.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_utimes.ts#L4)
- [_fs_truncate.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_truncate.ts#L3)
- [_fs_symlink.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_symlink.ts#L3)
- [_fs_rename.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_rename.ts#L2)
- [_fs_readlink.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_readlink.ts#L9)
- [_fs_readFile.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_readFile.ts#L9)
- [_fs_link.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_link.ts#L3)
- [_fs_exists.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/_fs/_fs_exists.ts#L2)
- [process.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/node/polyfills/process.ts#L16)

[pathFromURL](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/web/00_infra.js#L444) has the following files depending on it
- [path_from_url_tests.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/cli/tests/unit/path_from_url_test.ts#L6)
- [00_ffi.js](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/ffi/00_ffi.js#L36)
- [30_fs.js](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/fs/30_fs.js#L27)
- [10_permissions.js](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/runtime/js/10_permissions.js#L5)
- [40_process.js](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/runtime/js/40_process.js#L21)

> There are lots of other usages of `fromFileURL` but they come from [deno_std/path/posix.ts](https://github.com/denoland/deno_std/blob/c9af8416de2c344329c8e9df979bd542152652d0/path/posix.ts#L459) and [deno_std/path/win32.ts](https://github.com/denoland/deno_std/blob/c9af8416de2c344329c8e9df979bd542152652d0/path/win32.ts#L918)

The goal here seems two-fold
1. Get rid of `fromFileURL` from `node/polyfills/path` since it technically isn't part of node's api
2. Converge all usages of `pathFromURL` and `fromFileURL` to one implementation since they do the same thing

The first part seems straightforward to do since it is just deleting code. I see a few options for the second one. Keep in mind that I'm new to deno so I'm probably missing context here.
1. Replace all usages of `fromFileURL` to `pathFromURL`
2. Replace all usages of `pathFromURL` to `fromFileURL` and move `fromFileURL` to `00_infra.js` (or some other file)
3. Replace all usages of `pathFromURL` and `fromFileURL` to `fromFileURL` as defined in `deno_std`

`pathFromURL` seems to be [marked for internal usage only](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/ext/web/00_infra.js#L459) as well as something that needs to be in sync anyway with `fromFileURL` as mentioned above. Maybe 2 sounds more appealing than 1 then?

Both 1 and 2 duplicate the logic between deno core and deno std but avoid bringing in code from std whereas 3 keeps the implementation in one place, but forces some files to bring in code from deno std.

Here are some questions for those with more context before I blindly make changes.
- Is there a preferred strategy?
- Is using the implementation in deno std possible for all of these files? I'm not sure if all internal files can depend on std
- Do we not want to make any of these changes in std? Diverging the two seems like it might be a source of confusion, but the two seem to have different purposes anyway so maybe that's not a bad thing. Maybe keeping core code in sync with the std side would make the code easier to maintain?

**Comment by RyanClementsHax** [comment]
Also feel free to assign me this issue :)

**Comment by bartlomieju** [comment]
@RyanClementsHax 

> Is there a preferred strategy?

I would suggest to keep `pathFromURL` and remove `fromFileURL`

> Is using the implementation in deno std possible for all of these files? I'm not sure if all internal files can depend on std

Unfortunately that's not possible.

> Do we not want to make any of these changes in std? Diverging the two seems like it might be a source of confusion, but the two seem to have different purposes anyway so maybe that's not a bad thing. Maybe keeping core code in sync with the std side would make the code easier to maintain?

I'm not sure I follow here - the function in the deno repo is completely standalone and doesn't share any code with the one in `deno_std`. Are they diverging in behavior right now?

**Comment by RyanClementsHax** [comment]
Ok, I'll remove `fromFileURL` and keep `pathFromURL`.

> Are they diverging in behavior right now?

No. I just noticed they were very similar and wanted to see if this was duplicated code that should be consolidated.

**Comment by RyanClementsHax** [comment]
Mind if I bother for direction on how to import stuff from the `ext` crate within tests for the `cli` crate?

I see an example where we grab a reference to the deno internals directly off of the `Deno` namespace like in [path_from_url_tests.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/cli/tests/unit/path_from_url_test.ts#L6) (`const { pathFromURL } = Deno[Deno.internal];`), but is this the right way to do it?

When I try to import it like `import { pathFromURL } from "ext:deno_web/00_infra.js";`, I get the following error.

```
vscode ➜ /workspaces/deno (main) $ ./target/debug/deno test cli/tests/unit_node/child_process_test.ts 
error: Unsupported scheme "ext" for module "ext:deno_web/00_infra.js". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
    at file:///workspaces/deno/cli/tests/unit_node/child_process_test.ts:15:29
```

I've also tried to import it like `import { pathFromURL } from "../../../ext/web/00_infra.js";`, but that leads to the following error.

```
vscode ➜ /workspaces/deno (main) $ ./target/debug/deno test cli/tests/unit_node/child_process_test.ts 
error: Unsupported scheme "ext" for module "ext:deno_url/00_url.js". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
    at file:///workspaces/deno/ext/web/00_infra.js:37:30
```

Looking at the chain of the `ext:` import format, it seems like I'm not thinking about the problem properly. What is the clean way to import `ext` code into a test file like this?

**Comment by kt3k** [comment]
Let's use `fromFileUrl()` from `test_util/std/path/mod.ts` in unit tests. JS unit tests already heavily depends on `std` and it should be ok.

> I see an example where we grab a reference to the deno internals directly off of the Deno namespace like in [path_from_url_tests.ts](https://github.com/denoland/deno/blob/041d1e093bcac9a834afa1a2a036d07aef0ad1b2/cli/tests/unit/path_from_url_test.ts#L6) (const { pathFromURL } = Deno[Deno.internal];), but is this the right way to do it?

I don't think it's a good idea.

**Comment by RyanClementsHax** [comment]
Thanks for the guidance. I'll get to work on that!

**Comment by kt3k** [comment]
@RyanClementsHax 

> toFileURL is used in [ext/node/polyfills/worker_threads.ts#L57](https://github.com/denoland/deno/blob/348287825cdefecdd6dda6ce5c8652fdfc69837c/ext/node/polyfills/worker_threads.ts#L57) and [ext/node/polyfills/worker_threads.ts#L61](https://github.com/denoland/deno/blob/348287825cdefecdd6dda6ce5c8652fdfc69837c/ext/node/polyfills/worker_threads.ts#L61) exclusively. Is it preferred to create a separate function like pathFromURL within 00_infra.js or inline the needed logic into worker_threads.ts. Personally I'm leaning towards the former, but just wanted maintainer input before I go ahead.

I prefer the 2nd option. `ext/web/00_infra.js` is utility for implementing Web platform APIs (`Event`, `AbortController`, etc). If `toFileURL` is only used in `worker_threads.ts` (`ext/node`), it doesn't make much sense to move that to `ext/web`.

> Also, what are expectations for tests regarding the invariants I fixed in the first PR? I see some integration tests, but no dedicated test file for node/path. Was this intentional? I an add a test file and put tests in it that verify the invariants I fixed.

Does this mean things like the below?:
```js
if (Deno.build.os == "windows") {
  console.assert(path === path.win32);
}
```
if so, the test exists here, but disabled https://github.com/denoland/deno/blob/d32287d2111ec7b845e09c7cfe6a5d779c5f3bd1/cli/tests/node_compat/test/parallel/test-path.js#L77-L81

Can you try enable them?

**Comment by kt3k** [comment]
@RyanClementsHax Thank you for working on this long time!

**Comment by RyanClementsHax** [comment]
No prob :) thanks to y'all of being patient
