### ISSUE TITLE
Share objects with C?

### ISSUE THREAD

**Issue by AlbertShown** [denoland/deno#18227]
What is the safest way to share `objects` with `C` using Deno FFI?

The TypeScript Code:

```javascript
    let bool_test : Boolean = false;
    let number_test : Number = 0;
    let string_test : String = "";

    console.log("bool_test = " + bool_test); // "false"
    console.log("number_test = " + number_test); // "0"
    console.log("string_test = " + string_test); // ""

    // void my_c_function(bool* bool_test, unsigned int* number_test, char** string_test);
    my_lib.symbols.my_c_function(bool_test, number_test, string_test);

    console.log("bool_test = " + bool_test); // "true"
    console.log("number_test = " + number_test); // "123"
    console.log("string_test = " + string_test); // "Hello From C Buffer"
```

The C Code

```c
void my_c_function(bool* bool_test, unsigned int* number_test, char** string_test) {

    *bool_test = true;
    *number_test = 123;

    char* buf = (char*) malloc(32);
    sprintf(buf, "Hello From C Buffer");
    *string_test = buf;
}
```

**Comment by aapoalas** [comment]
Depends on what you mean by `objects`.

If you mean a JavaScript object then the answer is "you do not". A JavaScript object at the native level is a complex collection of heap allocated memory slices and pointers between them, allocated and handled by V8.

If you mean object-like native data, like C structs, then the answer is pretty much: Heap allocate and pass a pointer.

For your specific case here, you're trying to get data assigned into parameters. Your C-side code is logical, you're taking mutable (non-const) pointers to what are essentially memory slices containing given data types: A memory slice containing a boolean first, then a memory slice containing a 32-bit unsigned integer second, and finally a memory slice containing a pointer (64-bit size integer).

Your Deno side, however, is not quite correct. You can take a look at how TS-side types map to C types [here](https://deno.land/manual@v1.31.3/runtime/ffi_api). I would quote from there but I realize it's missing the `bool` type. So, quoting only the second and third parameter, and filling in the data for the boolean from memory:

> | FFI type | Deno | C |
> | --- | --- | --- |
> | `bool` | `boolean` | `bool` |
> | `u32` | `number` | `unsigned int` |
> | `pointer` | `{} \| null` | `void *` |
> | `buffer` | `TypedArray \| null` | `uint8_t *` |

You're passing a boolean and a number into your FFI call. For this to be correct, your C side call should look like this:
```c
void my_c_function(bool bool_test, unsigned int number_test, char** string_test);
```

But now obviously you cannot assign to these parameters, right?

Your C code contains the keys to solving this case: Your C code expects pointers, so you need to pass pointers from Deno side. Deno has two pointer types, the `pointer` and `buffer`. The `"pointer"` type is mostly meant for passing pointers where the memory is owned by foreign code (ie. C calls malloc and returns a `"pointer"`).

So, for our case here we'll want to use `"buffer"`. We'll need to prepare memory buffers that are large enough to contain the data that will be assigned into them:

```ts
const boolBuffer = new Uint8Array(1); // A bool is 1 bit but the smallest we can allocate is a single byte.
const u32Buffer = new Uint8Array(4); // 4 bytes make 32 bits
const u64Buffer = new Uint8Array(8); // 8 bytes makes 64 bits

mylib.symbols..my_c_function(boolBuffer, u32Buffer, u64Buffer);

console.log("bool_test =", boolBuffer[0] === 1);
console.log("number_test =", new Uint32Array(u32Buffer.buffer)[0]); // Extract the u32 from the buffer: This does not make a copy / do any more extra allocations
const charPointer = Deno.UnsafePointer.create(Number(new BigUint64Array(u64Buffer)[0])); // Extract the u64 from the buffer, again without extra allocations. Then, turn that bigint into Number for minor performance reasons and create a pointer object from that u64.
console.log("string_test =", Deno.UnsafePointerView.getCString(charPointer); // Read and create a JavaScript string from the `char *` pointer.
```

Two things to notice above:
1. I'm using `Uint8Array` even though later I then have to do `new Uint32Array` and `new BigUint64Array`. This is needlessly complicated in a minimal example like this, but in large scale using `Uint8Array` enables the FFI calls to be made much faster.
2. I'm doing three allocations with three different `new Uint8Array` calls.

The latter could be improved with eg.
```ts
const buffer = new Uint8Array(13);
const u64Buffer = buffer.subarray(0, 8);
const u32Buffer = buffer.subarray(8, 12);
const boolBuffer = buffer.subarray(12);
```
Now we allocate once and just take subarrays from it to get the proper sized and properly aligned slices of it without making extra copies.

Alternatively, your C function might take a struct pointer:
```c
struct my_struct {
  bool bool_test,
  unsigned int number_test,
  char *string_test,
};

void my_c_function(struct my_struct *my_struct);
```

Now your Deno side function would just pass `buffer` as the only parameter. Note that in this case it would probably be necessary to call `new Uint8Array(16)` as I think the size of `my_struct` is 16 bytes instead of the "packed" size of 13.

**Comment by AlbertShown** [comment]
I enjoyed asking you those questions and genuinely appreciate your time and effort in explaining and commenting. I started to be more familiar with Deno FFI now :)

However, I guess because of the [Breaking change](https://deno.com/blog/v1.31#breaking-change-in-ffi-api) in FFI API in Deno v1.31, `getCString()` expect `PointerObject` instead of `PointerValue`, so I get warning in VSCode: `Argument of type 'PointerValue' is not assignable to parameter of type 'PointerObject'`. But no runtime error. It's working fine.

I got `Uncaught TypeError: Cannot mix BigInt and other types, use explicit conversions`, and I fixed it by changing `BigUint64Array(u64Buffer)` to `BigUint64Array(u64Buffer.buffer)`.

Again, Thank you so much @aapoalas
