### ISSUE TITLE
`TextEncoder.encodeInto` may produce wrong result for one-byte non-ASCII characters

### ISSUE THREAD

**Issue by lideming** [denoland/deno#18255]
`TextEncoder.encodeInto` may produce wrong result for one-byte non-ASCII characters (code point range 128 - 255).

To reproduce the bug:

```ts
import { assertEquals } from "https://deno.land/std@0.180.0/testing/asserts.ts";

const encoder = new TextEncoder();

// Looping required (maybe because of V8 optimizations)
for (let tries = 0; tries < 10000; tries++) {
  const str = String.fromCodePoint(200);
  
  const expected = encoder.encode(str);

  const buffer = new Uint8Array(expected.byteLength);
  const { written } = encoder.encodeInto(str, buffer);
  const actual = buffer.subarray(0, written);

  assertEquals(actual, expected);
}
```

Error:

```diff
    [Diff] Actual / Expected


+   Uint8Array(2) [
+     195,
+     136,
-   Uint8Array(1) [
-     200,
    ]
```

The issue was introduced in `v1.31.2` (I have tested `v1.31.1` - `v1.31.3`).

I might be wrong, but it seems to be PR #17996, which [assumes](https://github.com/denoland/deno/pull/17996/files#diff-3ac03efc3001cfd7af76671890f379aa91cd124b120693718247406354f35226R359-R361):

> Since `input` is already UTF-8, we can simply find the last UTF-8 code
> point boundary from input that fits in `buffer`, and copy the bytes up to
> that point.

Maybe `input` is not always UTF-8?

cc @littledivy

**Comment by andrewnester** [comment]
I was looking into it a bit and it seems the problem comes from fast version of encode function https://github.com/denoland/deno/blob/3487fde236d0852a8b0672c293fa41a741f471e8/ext/web/lib.rs#L371 and (potentially) from `SeqOneByteString` optimisation. If I look at the value of `input.as_bytes()` inside this function for provide example it equals to `[200, 0]` instead of `[195, 136]`

Not entirely sure why it happens though, any ideas? @littledivy

**Comment by njhanley** [comment]
Small correction to @andrewnester: `input.as_bytes()` returns `[200]` for the example.

`input` *should* be valid UTF-8 as guaranteed by `str`; the fact that it isn't points to unsound `unsafe` code.

The problem is that [`FastApiOneByteString.as_str()`][1] assumes V8's various `OneByteString`s are UTF-8 when they are actually ISO-8859-1 (see [2], [3], [4], `git -3 -i -e Latin-1 -e ISO-8859-1`). Adding UTF-8 validation in `rusty_v8` with the following patch causes a panic when the example is run.

```diff
diff --git a/src/fast_api.rs b/src/fast_api.rs
index e4ac272..8c64c1a 100644
--- a/src/fast_api.rs
+++ b/src/fast_api.rs
@@ -221,10 +221,10 @@ impl FastApiOneByteString {
   pub fn as_str(&self) -> &str {
     // SAFETY: The string is guaranteed to be valid UTF-8.
     unsafe {
-      std::str::from_utf8_unchecked(std::slice::from_raw_parts(
+      std::str::from_utf8(std::slice::from_raw_parts(
         self.data,
         self.length as usize,
-      ))
+      )).unwrap()
     }
   }
 }
```

[1]: https://github.com/denoland/rusty_v8/blob/a07c222ae3d7593e7b8d1248263355b962c72518/src/fast_api.rs#L222-L228
[2]: https://github.com/v8/v8/blob/d191292845d0345c59a10085b98050a372d71f53/include/v8-primitive.h#L327-L335
[3]: https://github.com/v8/v8/blob/d191292845d0345c59a10085b98050a372d71f53/include/v8-primitive.h#L146-L158
[4]: https://github.com/v8/v8/blob/d191292845d0345c59a10085b98050a372d71f53/include/v8-primitive.h#L430-L434
