### ISSUE TITLE
"deno cache --reload <package_name>" reloads all dependencies in Node project

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#18605]
I created a new `next.js` project like so:
```
$ deno run -A npm:create-next-app@latest next-app
$ next-app
```

I tried `deno task dev` but got following error:
```
error: Could not find npm package '@types/node' matching 18.15.11. Try retrieving the latest npm package information by running with --reload
```

`deno cache --reload npm:@types/node` fixed the problem, but it reloaded all the dependencies specified in `package.json` in the current working directory.

**Comment by dawidcyron** [comment]
I had a quick look at the issue in the morning, and I think you might have used the command incorrectly. If you want to reload a specified npm dependency, try using ```deno cache --reload=npm:@types/node``` instead.

**Comment by dsherret** [comment]
In this case it still shouldn't cause an npm install with `deno cache --reload npm:@types/node` because it didn't match that specifier via a bare specifier. This is caused by this todo here:

https://github.com/denoland/deno/blob/df72420d723affb780c0c388b7d704985288f801/cli/resolver.rs#L209-L219

**Comment by dawidcyron** [comment]
> In this case it still shouldn't cause an npm install with `deno cache --reload npm:@types/node` because it didn't match that specifier via a bare specifier. This is caused by this todo here:
> 
> https://github.com/denoland/deno/blob/df72420d723affb780c0c388b7d704985288f801/cli/resolver.rs#L209-L219

Sorry if that's a stupid question, but I'm new to deno, and trying to understand this issue, as I would love to dive into the code and possibly fix it. What should be the behaviour of the ```deno cache --reload npm:@types/node``` command in this case?

**Comment by dsherret** [comment]
> Sorry if that's a stupid question, but I'm new to deno, and trying to understand this issue, as I would love to dive into the code and possibly fix it. What should be the behaviour of the deno cache --reload npm:@types/node command in this case?

In this case it shouldn't install the packages in the package.json. It should only redownload the `@types/node` package information and then download the tarball of the latest version.

I wouldn't recommend it as a first issue. It's a hard issue to fix because it requires some refactoring in [deno_graph](https://github.com/denoland/deno_graph) in order to allow the CLI to say if a specifier was resolved from a package.json file or not. We could do a quick workaround fix, but I don't think we should because it doesn't fully resolve the todo.
