### ISSUE TITLE
subsequent `execute_script_static` of deno_core is 10x slower

### ISSUE THREAD

**Issue by xiaoas** [denoland/deno#18698]
This is a slightly modified version of `deno_core` example:
```rust
use std::time::Instant;

use deno_core::v8;
use deno_core::JsRuntime;
use deno_core::RuntimeOptions;

fn main() {
    let mut runtime = JsRuntime::new(RuntimeOptions::default());

    // Evaluate some code
    let code = "let a = 1+4; a*2";
    for _ in 0..10 {
        let instant = Instant::now();
        runtime.execute_script_static("<anon>", code);
        println!("{:?}", instant.elapsed());
    }
}
```
Which outputs the following:
```
28.809µs
321.455µs
181.944µs
132.383µs
128.343µs
121.826µs
119.734µs
114.393µs
131.579µs
162.282µs
```
The second run is observably slower.

**Comment by lakshayHQ** [comment]
The second run is likely slower due to JIT (Just-In-Time) compilation. V8, the JavaScript engine used by Deno, employs JIT compilation to improve the performance of JavaScript code. When a piece of JavaScript code is executed for the first time, V8 compiles it to machine code before executing it. The machine code is then cached so that subsequent executions of the code can skip the compilation step and directly execute the cached machine code.

The first time the loop runs, the code has not been executed before, so V8 compiles it to machine code before executing it. The subsequent iterations of the loop execute the cached machine code, which is faster than re-compiling the code every time. However, after some time, the cached machine code may be evicted from the cache to free up memory, or the runtime may decide to recompile the code using different optimization settings. In either case, the next execution of the code will require recompilation, which takes additional time and may cause a slowdown.

In this case, the observed slowdown may be due to V8 recompiling the code with different optimization settings or evicting the cached machine code from the cache.

**Comment by xiaoas** [comment]
Cannot reproduce on latest deno_core
