### ISSUE TITLE
Deny permissions

### ISSUE THREAD

**Issue by levex** [denoland/deno#18804]
Right now I run trusted scripts using `deno run -A` but since the list of permissions in the future may change, it may be beneficial to do something like `deno run --allow-all --deny-env` to allow the script to do everything we normally allow it to do but not let it access the environment.

**Comment by levex** [comment]
cc @bartlomieju @ry for feedback

**Comment by iuioiua** [comment]
How funny, I thought of this just the other day. I'd be happy to work on this if the functionality is desired, as I have a little experience with the permission system.

**Comment by bartlomieju** [comment]
> I do wonder whether this functionality is worth the added complexity, though.

Besides some CLI arg munching there shouldn't be a lot of added complexity.

>  For example, do allow or deny permissions take precedence?

`--deny-*` flags should have precedence over `--allow-*` flag (ie. `deno run --allow-env --deny-env` should deny the permissions).

> How often would such functionality be used? The current permission system may be sufficient.

So we discussed it during some meeting and we think this is desirable as it gives more flexibility to the permission system.
Currently it's hard (maybe impossible) to give read access to all file system, but `/etc/hosts` file, with this change it would be `deno run --allow-read --deny-read=/etc/hosts`

**Comment by nayeemrmn** [comment]
After discussing with @iuioiua I came up with a spec for this. I thought it would be a breaking overhaul of our current semantics but fortunately it seems like it doesn't change any behaviour absent of `--deny-perm` flags.

-  Discard the constraints written in https://deno.com/manual@v1.33.2/runtime/permission_apis#permission-strength.
- ```rust
  parseFlags(flags):
    if flags.has(--deny-perm) {
      denied_list.insert(GLOBAL_DESC_FOR_PERM);
      return;
    }
    denied_list.extend(flags.values_from(--deny-perm=...));
    if flags.has(--allow-perm) {
      granted_list.insert(GLOBAL_DESC_FOR_PERM);
    }
    // We want to include these even if global `--allow-perm` was passed, so revocations can be granular.
    granted_list.extend(flags.values_from(--allow-perm=...));
  ```
- Add a third list `UnaryPermission::no_prompt_list`. This is used to store declined requests, while `denied_list` is now used for `--deny-perm` flags. Their recursing semantics work in different directions.
- In an actual implementation, each list might need an accompanying boolean to indicate if it contains the global desc. Similar to what `UnaryPermission::global_state` currently accomplishes. But in this write-up, the lists are modelled such that they can contain a global desc. Or maybe we CAN implement it like that and performantly?
- ```rust
  // Returned by `Deno.permissions.query()`.
  pub enum UnaryPermissionState {
    Granted,        // js: { state: "granted" }
    GrantedPartial, // js: { state: "granted", partial: true } (new)
    Prompt,         // js: { state: "prompt" }
    Denied,         // js: { state: "denied" }
  }
  ```
- ```rust
  check(desc):
    match query(desc) {
      UnaryPermissionState::Granted | UnaryPermissionState::GrantedPartial => Ok(())
      UnaryPermissionState::Prompt | UnaryPermissionState::Denied => Err(PermissionError)
    }
  ```
- ```rust
  query(desc):
    if denied_list.any(|d| d >= desc) || no_prompt_list.any(|d| desc >= d) {
      UnaryPermissionState::Denied
    } else if granted_list.any(|d| d >= desc) {
      if denied_list.any(|d| desc >= d) { // opt: Don't bother checking this case if this is called by `check()`.
        UnaryPermissionState::GrantedPartial
      } else {
        UnaryPermissionState::Granted
      }
    } else {
      UnaryPermissionState::Prompt
    }
  ```
- ```rust
  request(desc):
    let status = query(desc);
    match status {
      UnaryPermissionState::Prompt => {}
      _ => return status,
    }
    match prompt(desc) {
      Yes => {
        granted_list.insert(desc);
        UnaryPermissionState::Granted
      }
      No => {
        no_prompt_list.insert(desc);
        UnaryPermissionState::Denied
      }
    }
  ```
- ```rust
  revoke(desc):
    granted_list.retain(|d| !(d >= desc));
    query(desc)
  ```
- `desc1 >= desc2` means that `desc1` is _stronger than_ `desc2` (non-strict):
  ```js
  { name: "read" } >= { name: "read", path: "/foo" }
  { name: "read", path: "/foo" } >= { name: "read", path: "/foo/bar" }
  { name: "read", path: "/foo" } >= { name: "read", path: "/foo" }
  { name: "net", host: "127.0.0.1" } >= { name: "net", host: "127.0.0.1:8000" }
  ```

**Comment by bartlomieju** [comment]
Thanks for the write-up @nayeemrmn. A few questions:

- What is `GLOBAL_DESC_FOR_PERM` you're suggesting?

> Add a third list UnaryPermission::no_prompt_list. This is used to store declined requests, while denied_list is now used for --deny-perm flags. Their recursing semantics work in different directions.

I don't see that function. Could you clarify here?

> // Returned by `Deno.permissions.query()`.
pub enum UnaryPermissionState {
  Granted,        // js: { state: "granted" }
  GrantedPartial, // js: { state: "granted", partial: true } (new)
  Prompt,         // js: { state: "prompt" }
  Denied,         // js: { state: "denied" }
}

I believe this makes it a breaking change, because now we have a new variant that was not present before and might give false-positive to currently existing and working code (maybe that's okay though?).

**Comment by iuioiua** [comment]
> * Add a third list `UnaryPermission::no_prompt_list`. This is used to store declined requests, while `denied_list` is now used for `--deny-perm` flags. Their recursing semantics work in different directions.

Must deny permissions from both flags and requests work in different recursive directions? Removing this requirement might simplify things if I understand correctly. I'd prefer `denied_list` to work as one would expect it to - where to deny permissions from both flags and requests are stored. Such a change may be breaking, but Deno v2 is dropping soon, so now might be a good time.

**Comment by nayeemrmn** [comment]
> Must deny permissions from both flags and requests work in different recursive directions?

The reason the current denied state recurses upwards is because if the user said no to granting `--allow-read=/foo/bar`, then of course they're going to say no to granting `--allow-read=/foo` which implies the former, and so that should also act as denied. But we don't know if they're averse to granting `--allow-read=/foo/bar/baz` which is a smaller ask, so that should stay as prompt. This logic should be preserved or there would be no point in having the denied state at all as opposed to prompt.

The `--deny-read=/foo/bar` flag is very different from that. Its intended meaning is to downward-recursively block off a subspace of a permission that might be granted like `--allow-read=/foo`.

These two sets have in common that they represent an ungranted permission which may not be prompted for, but otherwise are completely different.

> I believe this makes it a breaking change, because now we have a new variant that was not present before and might give false-positive to currently existing and working code (maybe that's okay though?).

That's part of why I chose `{ state: "granted", partial: true }` instead of `{ state: "granted-partial" }`. It's probably fine for most purposes that partial granted is just treated like granted, if not they should analyse to the `partial` field.

**Comment by nayeemrmn** [comment]
I just remembered, it's imperative that things like `Deno..remove("foo/", { recursive: true })` and `Deno.watchFs("foo/")` check that the permission is non-partial, they need blanket access.

**Comment by iuioiua** [comment]
Ok. I'll give your suggested API a crack 👍🏾

**Comment by iuioiua** [comment]
Sorry to continue the discussion. I have an alternative that's worth considering. Instead of explicitly denying permissions, one could instead deny all permissions that have not been allowed via a new `--deny-default` or another flag. In other words, the script exits with a permission denied error instead of prompting for permission when this new flag is provided.

This would take care of almost all cases where permissions need to be denied, except for a few edge cases that require very specific deny permissions. However, this would be a significant reduction in added complexity but a minor reduction in added granularity compared to the current proposal for the permission system as a whole, which is more worth it, IMO.

What do you guys think?

**Comment by jsejcksn** [comment]
@iuioiua That behavior is already part of Deno CLI — the `run` argument name is `--no-prompt`:

```
% deno help run

---snip---

Usage: deno run [OPTIONS] [SCRIPT_ARG]...

Arguments:
  [SCRIPT_ARG]...
          Script arg

Options:

---snip---

      --no-prompt
          Always throw if required permission wasn't passed

---snip---
```

**Comment by iuioiua** [comment]
🤣 🤣 🤣

**Comment by cderv** [comment]
Sorry for asking in a closed thread, however it is directly related to OP here

> it may be beneficial to do something like deno run --allow-all --deny-env to allow the script to do everything we normally allow it to do but not let it access the environment.

It does seems lik `--deny-*` takes precedence over `--allow-*` counterpart, but `--allow-all` still gets precedence over everything - This is by design ? 

@levex does the `--deny-*` flag introduction solved it for your use case ? 

Thanks
