### ISSUE TITLE
Empty lock file doesn't have any hashes written to it after running deno vendor

### ISSUE THREAD

**Issue by taoeffect** [denoland/deno#18830]
on macOS, Deno 1.32.4, I just created a simple project with the following source in `main.ts`:

```ts
import blake from 'https://esm.sh/blakejs@1.2.1'
import multihash from 'https://esm.sh/multihashes@4.0.3?bundle'

export function blake32Hash (data: string | Uint8Array): string {
  const uint8array = blake.blake2b(data, undefined, 32)
  return multihash.toB58String(multihash.encode(uint8array, 'blake2b-32', 32))
}
if (import.meta.main) {
  console.log("Add 2 + 3 =", blake32Hash('asdf'))
}
```

I then run:

```
$ deno vendor -f main.ts
$ deno cache --lock deno.lock --lock-write main.ts
```

And an empty `deno.lock` is generated:

```json
{
  "version": "2",
  "remote": {}
}
```

What to do? How do I generate this file? The documentation [seems to say](https://deno.com/manual@v1.32.5/getting_started/configuration_file#lock) that `deno cache` is the way to generate, but although the file is created, it isn't populated.

**Comment by dsherret** [comment]
If you've vendored then there won't be any remote files and so there's nothing to hash.

**Comment by taoeffect** [comment]
For example, right now I'm running into an issue where myself and a coworker are getting different hashes for the same dependency. I'm guessing it might be related to this issue since we have a lock file but also vendored dependencies. It might be the case that the lock file got generated before the vendoring, and now is no longer being updated, but still exists and is causing conflicts. If the lock file worked even in the case of vendoring, it would make it easier to figure out what's going on (since we could compare the actual files being hashed), and also avoid situations where the lock file gets out of sync with the code.

**Comment by dsherret** [comment]
> For example, right now I'm running into an issue where myself and a coworker are getting different hashes for the same dependency.

Are you checking the vendored files into source control? If so then it shouldn't be an issue. If not, then consider not vendoring. When updating the vendored dependencies maybe try running with the `--reload` flag to fetch the latest data. Also, maybe try deleting the lockfile and recreating it.

> Or does it make sense to add hashes even in the case of vendored dependencies?

No, because once they're vendored then they're considered local files and there's no need to hash them at that point since you have the contents locally.

**Comment by taoeffect** [comment]
@dsherret I've noticed a bunch of weird behavior when using `deno vendor`...

- The line `"importMap": "./vendor/import_map.json",` is needed in `deno.json`, without it the `deno.lock` file gets recreated
- Running `deno vendor` seems to result in different files getting downloaded on different machines. This non-determinism is scary and also I guess points to an incompatibility with `deno.lock`. Ideally, there should be no issue with having a `deno.lock` file while using vendoring, because the exact same dependencies get downloaded on all machines. But there's weird stuff going with URLs getting changed, I guess because there are multiple ways to import files from URLs and they aren't very deterministic. [This PR is an example of a whole bunch of stuff changing that shouldn't](https://github.com/snowteamer/chel/pull/1/files)

**Comment by dsherret** [comment]
`deno vendor` isn't a great user experience. If you want deterministic behaviour when you vendor, then in your situation you will need to provide an import map that maps `"https://deno.land/std/io/util.ts": "https://deno.land/std@0.144.0/io/util.ts"` otherwise it will pull in the latest std version since miniexec@1.0.0/deps.ts has an unversioned import to `https://deno.land/std/io/util.ts` (you may want to try opening a PR to that repo to fix that or just fork it, fix it, then link directly to the raw github contents of your fork). Additionally, esm.sh often makes changes so you can pin your build versions of esm.sh in your deps.ts (see "Pinning Build Version" at https://esm.sh/#docs)

The main issue here is the remote dependencies are changing.

> Ideally, there should be no issue with having a deno.lock file while using vendoring, because the exact same dependencies get downloaded on all machines.

A lockfile doesn't help here because it would just error when the remote dependencies change—it would not ensure all machines get the same dependencies. The best thing to do is to pin the esm.sh build versions and the deno.land/std version.

> The line "importMap": "./vendor/import_map.json", is needed in deno.json, without it the deno.lock file gets recreated

If an import map is not specified in the deno.json then it won't be automatically used so the `deno.lock` file gets recreated because it's using the remote dependencies without that entry and not the vendored dependencies.

**Comment by taoeffect** [comment]
Thanks so much @dsherret for taking the time to explain that! 🙇
