### ISSUE TITLE
What happens to https://deno.land/x/aws_sdk

### ISSUE THREAD

**Issue by solepole** [denoland/deno#18877]
What happens to the AWS SDK lib on deno at https://deno.land/x/aws_sdk@v3.32.0-1. It's now 404 Not Found. It was working last month.

**Comment by ayame113** [comment]
When I access https://deno.land/x/aws_sdk@v3.32.0-1/client-s3/mod.ts from the browser, 404 Not Found is displayed, but when I access it from the CLI, I can get the content normally.

```shell
PS C:\Users\ayame> curl https://deno.land/x/aws_sdk@v3.32.0-1/client-s3/mod.ts
export * from "./S3Client.ts";
export * from "./S3.ts";
export * from "./commands/AbortMultipartUploadCommand.ts";
export * from "./commands/CompleteMultipartUploadCommand.ts";
export * from "./commands/CopyObjectCommand.ts";
export * from "./commands/CreateBucketCommand.ts";
...
```

As far as I know, the 3 modules  `aws_sdk`, `masto`, `react_icons` are no longer accessible from the browser due to website performance issues. (ref: https://github.com/denoland/apiland/pull/86/files#diff-0f333eea5d2787b19b89ca1e52a1d009170cb0ce2adb68a68c7090678fa41175)

In my opinion, when people see 404 Not found when accessing these modules, it gives them the illusion that they have been removed from deno.land. I wish I could see the message "Document rendering was skipped due to performance issues".

**Comment by solepole** [comment]
That's so good to know! Thanks for providing the information. Hopefully, the website performance issues can be fixed soon.
