### ISSUE TITLE
[test runner]: Error messages not printed to terminal

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#18910]
I ran into an admittedly weird bug while working on https://github.com/denoland/fresh/pull/1139 . For some reason when _both_ an `npm:` prefixed import and a spawned child process is present, any uncaught error messages are not printed to the terminal in our test runner. The odd thing is that the npm import doesn't even have to be used and can have no side effects. Running the code without the test runner shows the error message as expected.

source:

```ts
// Commenting this unused import that has no side effects somehow
// fixes the missing error message in the test output.
// import * as kl from "npm:kolorist";

Deno.test("Foo", async () => {
  // Commenting either this or the `kolorist` import makes the
  // error message show up, but when both are present it somehow
  // doesn't print the error message
  new Deno.Command(Deno.execPath(), {
    args: ["run", "-A", "server.ts"],
    stdin: "null",
    stdout: "inherit",
    stderr: "inherit",
  }).spawn();

  // This error message isn't printed to the terminal
  throw new Error("This message should be printed to the terminal");
});
```

**Steps to reproduce:**

1. Clone https://github.com/marvinhagemeister/deno-test-uncaught-error-bug
2. Run `deno test -A foo.ts`

**Actual terminal output:**

Note how it just says "FAILED" but doesn't print the error message at all.

```sh
Check file:///Users/marvinhagemeister/dev/test/deno-bugs/test-console/foo.ts
running 1 test from ./foo.ts
Foo ... FAILED (12ms)
------- output -------
Server running: http://localhost:8300/
Listening on http://localhost:8300/
```

**Expected terminal output:**

```sh
$ deno test -A foo.ts
Check file:///Users/marvinhagemeister/dev/test/deno-bugs/test-console/foo.ts
running 1 test from ./foo.ts
Foo ... FAILED (13ms)

 ERRORS

Foo => ./foo.ts:5:6
error: Error: This message should be printed to the terminal
  throw new Error("This message should be printed to the terminal");
        ^
    at file:///Users/marvinhagemeister/dev/test/deno-bugs/test-console/foo.ts:16:9

 FAILURES

Foo => ./foo.ts:5:6

FAILED | 0 passed | 1 failed (29ms)

error: Test failed
```

**Comment by nayeemrmn** [comment]
This is caused by this handler: https://github.com/denoland/deno/blob/10ae5ee26557107b22524b1a84ebb56ed7d23fb4/ext/node/polyfills/process.ts#L736-L742
At the end of the test run, it's true that there is more work in the event loop because the child process is still open. But for normal test runs we don't attempt to run the event loop unless a JS `beforeunload` handler calls `e.preventDefault()` (which the Node compat layer does I assume for good reason). This is kind of strange.

We should either attempt to complete the event loop before dispatching `beforeunload` no matter what, or be ruthless and not allow the user to keep a worker alive once the tests from that module are finished i.e. ignore the `defaultPrevented` for `beforeunload` in test runs. I'm strongly leaning to the latter.

**Comment by marvinhagemeister** [comment]
@nayeemrmn your analysis is spot on! Removing the `e.preventDefault()` call in the `beforeunload` handler resolves the issue. I'm not sure what the better option to solve it is, as I'm not familiar (yet?) with how the node compat layer and deno coordinate all things surrounding the event loop.
