### ISSUE TITLE
Unable to import npm package's ES6 (?) default export

### ISSUE THREAD

**Issue by mashirozx** [denoland/deno#18966]
In the npm package, it export default modules with `exports.default` ([for real example](https://cdn.jsdelivr.net/npm/megalodon@6.0.1/lib/src/index.js))

```js
// npm:some_module@1.0.0/index.js
var MyModule = 'xxx'
exports.default = MyModule;
```

And It's type declearation:

```ts
// npm:some_module@1.0.0/index.d.ts
declare const MyModule: string
export default MyModule;
```

But I can't import it in Deno:

```ts
import MyModule from "npm:some_module@1.0.0/index.js";
// also tried
import { default as MyModule } from "npm:some_module@1.0.0/index.js";
```

What is the correct way to import it?

Deno 1.32.5 (release, aarch64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3

For real test, you may try this package: https://www.npmjs.com/package/megalodon, and this is its files:
https://cdn.jsdelivr.net/npm/megalodon@6.0.1/lib/src/

Related #15865 #16506

**Comment by marvinhagemeister** [comment]
Took a quick look and note that with `npm:`-prefixed imports you don't need to specify the full file path. It can be shortened to `npm:some_module`. But back on topic.

The `megalodon` package is published as a CommonJS module and it looks like deno doesn't yet support the `__esModule` convention. To make it possible to load CommonJS modules in ES modules via the `import` statement and more specifically to support something like a `default` import, tools have introduced the convention of setting `__esModule` to true on `exports` inside a CommonJS module. Otherwise the `exports.default` property is treated as a generic named export.

```js
// Tell the importing module that this CommonJS module has an `exports.default` property
// and that that can be used for default imports.
Object.defineProperty(exports, "__esModule", { value: true });
 ```

There is more information about this convention in the [TypeScript docs under the `esModuleInterop` section](https://www.typescriptlang.org/tsconfig#esModuleInterop).

**Comment by bartlomieju** [comment]
@dsherret please take a look

**Comment by dsherret** [comment]
You will need to import it like so:

```js
import megalodon from "npm:megalodon@6.0.1";
console.log(megalodon.default); // use the default property here
```

This works the same as Node when importing from ESM:

```js
// main.mjs
import megalodon from "megalodon";
console.log(megalodon.default); // works the same
```

https://arethetypeswrong.github.io/?p=megalodon%406.0.1

> The CJS module resolved at the package under contains a simulated export default with an `__esModule` marker, but no top-level module.exports. Node does not respect the `__esModule` marker, **so accessing the intended default export will require a `.default` property access in Node from an ES module**.
