### ISSUE TITLE
Move web assembly lib to assets.ts

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#1930]
From #1854 

> Actually thinking about `lib.web_assembly.d.ts`, we should inline it in `assets.ts` and include it in the `lib: [ "esnext", "web_assembly" ]` in our configuration for the `compiler.ts`.  We would then replace it with the official one when/if the issue gets resolved.

**Comment by bartlomieju** [comment]
@kitsonk I took a stab at it, here's what I found:
1. `lib: [ "esnext", "web_assembly" ]` - this is illegal now, TS compiler accepts `lib` values listed [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
2. We can safely move `lib.web_assembly.d.ts` to `assets.ts`, the only difference I found is that `deno --types` will no longer show WebAssembly declarations (which is expected AFAICT, since they are part of global TS declaration after moving to assets)

Do you still want to proceed with this issue?

**Comment by bartlomieju** [comment]
Stale and severly outdated
