### ISSUE TITLE
Expose dprint options to deno fmt

### ISSUE THREAD

**Issue by PodaruDragos** [denoland/deno#19806]
Hello guys,

Is is possible to expose the options that `dprint-typescript` has to `deno fmt` ? 
I would like to be able to use some of the options there.

I saw in `cli/cargo.toml` the definition for `dprint-plugin-typescript = "=0.85.0"`.

Is this something feasible/considerable ?

**Comment by albnnc** [comment]
As far as I understand the idea of `deno fmt`, this tool was meant to be opinionated (kind of like `go fmt`), which contrasts with configurable `deno lint` a bit actually. Thus, it would be interesting to see the team response (again?).

In case this functionality is going to be added, I request to expose not only `dprint-typescript` options, but whole `dprint` configuration (reduced probably) – this would be handy in order to handle unsupported languages via [exec plugin](https://dprint.dev/plugins/exec/) (e.g. YAML).

**Comment by dsherret** [comment]
Please open specific issues about specific configuration needs. dprint-plugin-typescript's configuration is too experimental to expose everything.

**Comment by PodaruDragos** [comment]
@dsherret fair enough, thanks for replying.

I would really like this 2 options exposed, introduced into [PR](https://github.com/dprint/dprint-plugin-typescript/pull/376)

**Comment by Stokestack** [comment]
Any status on this? I just found that I can't stop deno fmt from messing up my braces and flow-control statements, but Dprint offers the exact options I want and they work fine in their playground. Those options are:

	"bracePosition": "nextLine",
	"nextControlFlowPosition": "nextLine"

but I don't think a piecemeal approach makes sense here. Why can't we just pass any Dprint-supported options?
