### ISSUE TITLE
Accessing .url on cloned request throws in new Deno.serve API

### ISSUE THREAD

**Issue by florian-imi** [denoland/deno#19818]
Minimal example:

```ts
Deno.serve((req) => new Response(req.clone().url));
```

Request:
```
curl http://localhost:8000
```

Trace:
```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.url (ext:deno_fetch/23_request.js:182:32)
    at Request.get url (ext:deno_fetch/23_request.js:446:33)
    at file:///Users/qwtel/GitHub/tmp/index.ts:1:38
    at ext:deno_http/00_serve.js:530:28
    at ext:deno_http/00_serve.js:730:29
    at eventLoopTick (ext:core/01_core.js:183:11)
```

Screenshots:
<img width="503" alt="Screenshot 2023-07-13 at 15 50 14" src="https://github.com/denoland/deno/assets/108846768/9bd1bbe2-c835-4e71-9ca3-abfb29a2ba7a">

Version:
```
deno 1.35.1 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```

**Comment by fbaltor** [comment]
The log message states that the problem occurs when we call the [`url` getter](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_request.js#L182) of the [`innerRequest` instance](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_request.js#L158) of the cloned request, more specifically in line 182, when we try to access the property **`urlListProcessed`**:

```js
/**
 * https://fetch.spec.whatwg.org/#concept-request-clone
 * @param {InnerRequest} request
 * @param {boolean} skipBody
 * @returns {InnerRequest}
 */
function cloneInnerRequest(request, skipBody = false) {
  const headerList = ArrayPrototypeMap(
    request.headerList,
    (x) => [x[0], x[1]],
  );

  let body = null;
  if (request.body !== null && !skipBody) {
    body = request.body.clone();
  }

  return {
    method: request.method,
    headerList,
    body,
    redirectMode: request.redirectMode,
    redirectCount: request.redirectCount,
    urlList: request.urlList,
    urlListProcessed: request.urlListProcessed,                         // Line 178
    clientRid: request.clientRid,
    blobUrlEntry: request.blobUrlEntry,
    url() {
      if (this.urlListProcessed[0] === undefined) {                     // Line 182
        try {
          this.urlListProcessed[0] = this.urlList[0]();
        } catch {
          throw new TypeError("cannot read url: request closed");
        }
      }
      return this.urlListProcessed[0];
    },
    currentUrl() {
      const currentIndex = this.urlList.length - 1;
      if (this.urlListProcessed[currentIndex] === undefined) {
        try {
          this.urlListProcessed[currentIndex] = this.urlList[currentIndex]();
        } catch {
          throw new TypeError("cannot read url: request closed");
        }
      }
      return this.urlListProcessed[currentIndex];
    },
  };
}

```

But this is very weird since this property is supposed to have been setted just above, in [line 178](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_request.js#L178), where the `request` used to do so is an instance of the `InnerRequest` from the original (not cloned) request. This led me to think that this property was never setted in this original request, which indeed is the case. 

After debugging the code with help of the Chrome DevTools I found that during the handling of a request the [code calls a `new InnerRequest(...)`](https://github.com/denoland/deno/blob/3c8bbc434d32ad75097647b0cdbc9ea1b0ad2645/ext/http/00_serve.js#L527) and uses it to create the proper request with [`fromInnerRequest(...)`](https://github.com/denoland/deno/blob/3c8bbc434d32ad75097647b0cdbc9ea1b0ad2645/ext/http/00_serve.js#L528). But both the constructor of `InnerRequest` and the function `fromInnerRequest` never set the property `urlListProcessed`, causing the issue.

I found that the the `urlListProcessed` property seems to be correctly set in [the function `newInnerRequest`](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_request.js#L92-L152) which is called by the [constructor of `Request`](https://github.com/denoland/deno/blob/21c2c01ebed902c70763bb9319c3ec48c4cb5284/ext/fetch/23_request.js#L301), but I don't know the best way to fix or reconcile these codes.

I saw that some recent refactoring was made in #18619 so I think @mmastrac could point out the best path here.

**Comment by aaronhuggins** [comment]
I hate this workaround, but I needed to functionally clone requests in my app. A getter can be forcefully defined on the clone by `Object.defineProperty`. A hack, but it works in production (so far).

```TypeScript
  const clone = originalRequest.clone();
  Object.defineProperty(clone, "url", {
    configurable: true,
    enumerable: true,
    get: () => {
      return originalRequest.url;
    },
  });
```
