### ISSUE TITLE
`node:zlib` fails to decompress brotli data larger than 4096 bytes

### ISSUE THREAD

**Issue by honnip** [denoland/deno#19816]
## Steps to reproduce
```js
import { brotliCompressSync, brotliDecompressSync } from "node:zlib";

const a = "a".repeat(4097);
const compressed = brotliCompressSync(a);
const decompressed = brotliDecompressSync(compressed); // error: Uncaught TypeError: Failed to decompress
```
This works with `"a".repeat(4096)`

## version 
```shell
$ deno -V
deno 1.35.0
```

**Comment by lachrimae** [comment]
I have determined why this happens. The Rust code FFIs out to [this C function](https://github.com/google/brotli/blob/c1bd196833e4ce05ef49b82ec5e124bb79e095ff/c/dec/decode.c#L2264). On line 2283, you can see that all non-success results are coerced to the same generic error code. On the Rust side, we [only attempt to double the buffer size](https://github.com/denoland/deno/blob/d104a09f796d3176ccd73a24906da87073cab85f/ext/node/ops/zlib/brotli.rs#L237) when we get a `BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT` result from the C code. But as mentioned, that result is always coerced away to the generic case.

Possible solutions are to upstream a change to `google/brotli` that stops coercing errors to the same generic case. Or to use `CBrotliDecoderDecompressStream`, which does not perform this error-coercing step.

**Comment by lachrimae** [comment]
Upstreaming seems like a bad idea, this has been the API for 8 years ago and it's documented, so not a mistake.

When I rewrite `brotli_decompress` as
```rust
fn brotli_decompress(buffer: &[u8]) -> Result<ToJsBuffer, AnyError> {
  let mut output = Vec::with_capacity(4096);
  let mut decompressor = Decompressor::new(buffer, buffer.len());
  decompressor.read_to_end(&mut output)?;
  Ok(output.into())
}
```
it passes the test in this issue. @littledivy is there a reason you wrote new unsafe FFI code here instead of using the Rust API in the `brotli` crate?

**Comment by lachrimae** [comment]
This is the PR where this code was introduced by the way: https://github.com/denoland/deno/pull/19223

**Comment by lachrimae** [comment]
Okay I have looked a little bit more closely into the `brotli` crate being used, and I realized it's actually Dropbox's `rust-brotli` library. The `rust-brotli` crate provides a C FFI interface, allowing `rust-brotli` to replace `google/brotli` as a drop-in replacement. What we are doing here in Deno is calling into the `rust-brotli` C FFI layer, which is immediately calling back into Rust. Everything I said about error types being coerced is true, but it's happening [here in `rust-brotli`](https://docs.rs/brotli-decompressor/2.3.2/src/brotli_decompressor/ffi/mod.rs.html#144-149).

We should definitely switch this over to the Rust API because the unsafe C API is just a layer of indirection on top of Rust.
