### ISSUE TITLE
Vendoring doesn't copy over existing import map aliases

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#19841]
Noticed that vendoring doesn't copy over existing import map definitions. This makes it not possible to run the code via the vendored import map. A workaround is to copy over the imports from `deno.json` into the vendored import map.

## Steps to reproduce

1. Run `deno run -Ar https://fresh.deno.dev` (press Enter to go through the wizard)
2. Run `cd fresh-project`
3. Run `deno vendor dev.ts`
4. Run `deno run -A --no-remote --import-map vendor/import_map.json dev.ts`

Error:

```sh
error: Uncaught (in promise) TypeError: Relative import path "$fresh/server.ts" not prefixed with / or ./ or ../ and not in import map from "file:///Users/marvinh/dev/test/fresh-jsx-runtime/main.ts"
    at file:///Users/marvinh/dev/test/fresh-jsx-runtime/main.ts:9:23
  await import(entrypoint);
  ^
    at async dev (file:///Users/marvinh/dev/test/fresh-jsx-runtime/vendor/deno.land/x/fresh@1.2.0/src/dev/mod.ts:140:3)
    at async file:///Users/marvinh/dev/test/fresh-jsx-runtime/dev.ts:5:1
```

**Comment by dsherret** [comment]
The way to make this work is to include `main.ts` when vendoring as well:

```
deno vendor main.ts dev.ts
```

The reason this is necessary is because `dev.ts` does a dynamic import of `main.ts` that is not statically analyzable.

If someone just does `deno vendor dev.ts`, we could maybe copy over import map entries from the original file that aren't in the vendored import map, but it wouldn't use the vendored code for everything in that case, which might lead to surprises.

**Comment by marvinhagemeister** [comment]
Closing as the `deno vendor` command was removed in favour of setting `"vendor": true` in `deno.json` which doesn't have the described issue.
