### ISSUE TITLE
deno support for import assertions?

### ISSUE THREAD

**Issue by uriva** [denoland/deno#19850]
the popular webtorrent lib has lines like this:

```js
import json from "./MyJSON.json" assert { type: "json" };
```

when imported as `npm:webtorrent` this improt trips deno's compiler and a very cryptic hard to debug error message is output:

```
error: Uncaught SyntaxError: Unexpected token 'i', "import {cr"... is not valid JSON
```

is this feature supported in deno? why is the error message not with file and line numbers?

is there some solution to this?

thanks

Related #19834

**Comment by petamoriken** [comment]
Import Attributes (ex-Import Assertions) are Stage 3 now. We should wait for ECMAScript progress.

related: #17944

**Comment by andreubotella** [comment]
Deno has supported import assertions and JSON modules since 1.17.0. (In fact, recently the import assertions proposal was renamed to import attributes and the `assert` keyword changed to `with`, and Deno's support of `assert` means it will have to continue shipping that keyword for at least some time.)

The reason your import is failing seems to be because the JSON file you're importing isn't valid JSON syntax, but seems to be JS or TS.

**Comment by uriva** [comment]
https://github.com/webtorrent/webtorrent/blob/master/index.js#L20

https://github.com/webtorrent/webtorrent/blob/master/package.json

seems like valid json

**Comment by uriva** [comment]
@ThaUnknown maybe you'll have an idea?

**Comment by ThaUnknown** [comment]
my idea is that webtorrent doesn't support deno, as I've already told you once before

**Comment by sigmaSd** [comment]
it seems like the node compat doesn't support npm packages that have import assertion

this fails the same way `import "npm:@sigmasd/a/a.js";`  where a.js only have this
```js
import b from "./b.json" assert { type: "json" };
console.log(b);
```

**Comment by fushihara** [comment]
Around 2021, Deno will support json import. I saw an article that said that Deno will support json import around 2021, but I wonder if this means that it is not currently supported.
