### ISSUE TITLE
Upgrading deno_std to v0.3.4 fails

### ISSUE THREAD

**Issue by ry** [denoland/deno#1988]
https://github.com/denoland/deno_std/pull/297

It hangs after 19 minutes and prints "WARNING the sharedQueue overflowed" 
(The warning isn't necessarily a bad thing but is perhaps a hint)

**Comment by bartlomieju** [comment]
I've just encountered the same error when running `deno --fmt`, it hangs during compilation of `prettier/main.ts`.

**Comment by bartlomieju** [comment]
@ry after some debugging I found that:
https://github.com/denoland/deno/blob/efe9c18b459dbec71b213e8dc87e2e1b02477139/core/isolate.rs#L393
`poll` is not called again after we hit `overflow_response`. 

So we're left in situation where there is 1 pending op but it's not resolved because `poll` is not called again.

Could you point me where should I dig further?

**Comment by bartlomieju** [comment]
It seems that adding `self.polled_recently = false;` to `unsuccessful_push` branch resolves this issue.

```rust
if !successful_push {
  // If we couldn't push the response to the shared queue, because
  // there wasn't enough size, we will return the buffer via the
  // legacy route, using the argument of deno_respond.
  overflow_response = Some(buf);
  self.polled_recently = false;  // change
  break;
}
```

**Comment by ry** [comment]
Sounds like you figured it out! Try resetting polled_recently for that op. 
Would be great to get a small test case that demoed this bug in core/isolate.rs test section.
