### ISSUE TITLE
Potential bug: Inability to access Deno.openKv function

### ISSUE THREAD

**Issue by EthanThatOneKid** [denoland/deno#19992]
### Description

Upon executing a clean `deno run -A -r https://fresh.deno.dev` command, I encountered a `TypeError: Deno.openKv is not a function` when setting up a `Deno.openKv` expression in the `routes/index.tsx` file and running `deno task start`. It appears that Deno's KV API is inaccessible by default due to restricted access from unstable APIs.

### Steps to reproduce

1. Ensure a clean environment.
2. Execute `deno run -A -r https://fresh.deno.dev`.
3. Set up a `Deno.openKv` expression in the `routes/index.tsx` file.
4. Run `deno task start`.

### Expected results

The application should run without errors, allowing expected access to the `Deno.openKv` function.

### Actual results

The application throws a `TypeError`, indicating that the `Deno.openKv` function is not recognized due to restricted access from Deno's unstable APIs.

### Possible solutions

1. **Modify boilerplate code:** Review the relevant section of the [init.ts](https://github.com/denoland/fresh/blob/430be774e21b98225bd23d9b7807ed11e8aa9bdc/init.ts#L539C13-L539C55) boilerplate code to enable access to all unstable APIs, thereby resolving the issue.
2. **User confirmation:** Consider adding a confirmation step during project initialization to allow users to enable or disable access to unstable APIs, such as `Deno.openKv`, for convenient access.
3. **Documentation**: Revise the getting started guide or documentation to provide clear instructions on working with Deno's unstable APIs, including `Deno.openKv`, effectively.

### Impact

The inability to access Deno.openKv may slightly affect the experience for beginners using the framework. However, this issue does not pose any critical or urgent concerns and can be considered a non-urgent, quality of life improvement. 🍋

**Comment by marvinhagemeister** [comment]
Moving this to the Deno tracker as this is not Fresh specific.

**Comment by lucacasonato** [comment]
You can update your "start" script in deno.json to `"start": "deno run -A --watch=static/,routes/ --unstable dev.ts"`

**Comment by EthanThatOneKid** [comment]
> You can update your "start" script in deno.json to `"start": "deno run -A --watch=static/,routes/ --unstable dev.ts"`

Is this information worth adding as a note in <https://fresh.deno.dev/docs/getting-started/create-a-project>?

**Comment by marvinhagemeister** [comment]
I'm hesitant to add it there as Deno KV is unrelated to Fresh.

**Comment by marvinhagemeister** [comment]
Closing as we added a bit regarding KV to our docs.

**Comment by algoflows** [comment]
Getting the same error.... on the latest canary.

Watcher Process started.
error: Uncaught (in promise) TypeError: Deno.openKv is not a function
      const kv = await Deno.openKv();

**Comment by bartlomieju** [comment]
You need to run with `--unstable-kv` flag

**Comment by iensu** [comment]
I was running into this issue with Deno Fresh v2.1.

In my deno.json I had `"dev": "vite"`, so I tried running `deno run --unstable-kv dev`, but the option had no effect. 

Changing the script to `"dev": "deno run --unstable-kv vite"` solved the issue and running `deno run dev` works as expected.

In hindsight it seems pretty obvious, but if you're coming from node it can be bit confusing since `deno run` works both as `npm run x` and `node x` depending on what you're executing.

**Comment by zvigrauer** [comment]
I only have access to the Playground GUI API. I get the error message on the build attempt, with the suggestion "Run again with `--unstable-kv` flag to enable this API"

No idea where to stick this "--unstable-kv" flag (please no extraneous suggestions). Any field (in the GUI) I tried causes something else to fail. I doubt I should try to download DENO and run from the terminal on my computer, if this is even allowed, since this is part of a course and the autograder would expect me to run the API.

Any suggestions would be welcomed.
