### ISSUE TITLE
Changing version of npm package to a more inclusive one does not use the latest version

### ISSUE THREAD

**Issue by mhanuszh** [denoland/deno#20008]
How to reproduce:
- Stage 1
  - Create a `deno.json` file
  - Create a `test.ts` file with the content `import handle from "npm:handlebars@4.7.6";`
  - Run `deno run test.ts`
  - Now a `deno.lock` file is generated, containing:
  ```json
      "specifiers": {
        "handlebars@4.7.6": "handlebars@4.7.6"
      },
  ```
- Stage 2
  - Update the `test.ts` file to `import handle from "npm:handlebars@4";`
  - Run `deno run test.ts`
  - Now the `deno.lock` contains this:
  ```json
    "specifiers": {
      "handlebars@4": "handlebars@4.7.6",
      "handlebars@4.7.6": "handlebars@4.7.6"
    },
  ```

My assumption was that by changing the version to `4` (based on [Deno's semver docs](https://deno.land/std@0.196.0/semver/mod.ts), 1 := 1.x.x := >=1.0.0 <2.0.0), Deno will use / lock the latest version in the same major version (4.x.x)

One example of this would be that you could receive patch level updates automatically.

More over, this can create a special case when the same, self contained script behaves differently in different projects:
A project can contain an already locked dependency. Copying a file form an other project, that has the same package, but only specifies the the major version, but depends on a feature that is not present in the minor version of the locked package. Obviously, the developer is at fault here, they should have specified the minimum minor version, but I don't think it's that uncommon to think that depending on the major version only, gives you the latest version in the specified major group.

I think this way of using the already pinned package can be confusing, so if this is the intended behavior, some kind of feedback would be nice. For example the VSCode extension could warn about this, or at least when running the `deno cache` command a warning could be printed in the console:
```
Version `4.7.6` (not the latest) will be locked for the package `npm:handlebars@4`
```
Or something like this, just to make sure that its explicitly stated

The version selection / locking mechanism should be stated in the [docs](https://deno.land/manual@v1.35.3/basics/modules/integrity_checking)

**Comment by dsherret** [comment]
> My assumption was that by changing the version to 4 (based on [Deno's semver docs](https://deno.land/std@0.196.0/semver/mod.ts), 1 := 1.x.x := >=1.0.0 <2.0.0), Deno will use / lock the latest version in the same major version (4.x.x)

Not exactly. The constraint `handlebars@4` means "give me a version that's greater than or equal to 4.0.0 and less than 5.0.0". It doesn't mean "give me the latest version in that range". Additionally, the lockfile is used to inform npm resolution based on past resolutions. So it sees `handlebars@4.7.6` previously resolved in the lockfile and uses that in order to prevent duplicate dependencies.

> One example of this would be that you could receive patch level updates automatically.

With a lockfile, it won't automatically upgrade you to the latest version if a previous version matches what's found in the lockfile. If you want that behaviour, then not using a lockfile would provide that.

> More over, this can create a special case when the same, self contained script behaves differently in different projects:

A script with a lockfile is no longer self contained.

> A project can contain an already locked dependency. Copying a file form an other project, that has the same package, but only specifies the the major version, but depends on a feature that is not present in the minor version of the locked package.

If a script only specifies the major version (ex. `@4`), but depends on a feature only present in a minor version (ex. `4.2`), then the version constraint specified in the script is incorrect—it should also specify the minimum minor version it depends on (ex. `@^4.2`). In this example, it shouldn't say that it's also compatible with `4.0` and `4.1` when it's not.

> I think this way of using the already pinned package can be confusing, so if this is the intended behavior, some kind of feedback would be nice. For example the VSCode extension could warn about this, or at least when running the deno cache command a warning could be printed in the console:

I'd recommend running the `deno info main.ts` command to see what the resolved dependencies are or hovering over the module specifier. I think it would get very noisy to output all that information.

**Comment by mhanuszh** [comment]
Hmm... Yes, it looks like my assumption was incorrect.

And thanks for the `deno info`. It's really useful!
