### ISSUE TITLE
request and info are undefined in `Deno.serve` when using rest parameters

### ISSUE THREAD

**Issue by lunsdorf** [denoland/deno#20054]
I was trying to delegate all arguments of a `Deno.ServeHandler` to a child handler like `(...args) => otherHandler(...args)` and discovered, that `args` is an empty array. Switching to explicit arguments like `(requst, info) => otherHandler(request, info)` works.

Minimal broken example:
```ts
Deno.serve(
  { port: 8080 },
  (...args) => new Response(JSON.stringify(args))
);

// responds with '[]'
```

Minimal working example:
```ts
Deno.serve(
  { port: 8080 },
  (request, info) => new Response(JSON.stringify([request, info]))
);

// responds with '[{},{"remoteAddr":{"transport":"tcp","hostname":"127.0.0.1","port":60795}}]'
```

- deno 1.35.3 (release, aarch64-apple-darwin)
- v8 11.6.189.12
- typescript 5.1.6

**Comment by ayame113** [comment]
It seems that `info` is undefined even if the callback argument is partially a rest parameters.

```ts
Deno.serve(
  { port: 8080 },
  (request, ...args) => new Response(JSON.stringify([request, ...args]))
);
// responds with '[{}]'
```

**Comment by mmastrac** [comment]
Unfortunately there is a pretty significant performance hit when generating all the args for handlers that don't need them. For delegation, we recommend requesting the args directly and forwarding those, rather than using arguments or rest params.

If we can come up with a way to avoid the expense of generating the arguments when unused, but also support variadic arguments, we can revisit this issue, but for now our hands are somewhat tied.
