### ISSUE TITLE
perf(kv): `list` of 20k+ items takes 34+ seconds

### ISSUE THREAD

**Issue by skoshx** [denoland/deno#20218]
Is it meant to be that the performance of `list` is ~linearly correlated with the amount of items with the `prefix`?

So if there would be 40k items, it would take over a minute.

Is this expected speeds?

Edit: Clarifying, the `list` operation takes 34+ seconds on the edge (locally it's much faster)

**Comment by skoshx** [comment]
@exside Wow, quite the comprehensive review, maybe this will help the Deno team, but in my case, the slow speed takes place on the edge.

Basically the 34+ seconds is benchmarked from live example deployed to the edge.

**Comment by losfair** [comment]
Locally I'm not seeing slow `list()` operations. Testing with the script:

```ts
const kv = await Deno.openKv("./test.db");

const start1 = Date.now();
for (let i = 0; i < 400; i++) {
  const op = kv.atomic();
  for (let j = 0; j < 100; j++) {
    op.set([`key${i * 100 + j}`], `value${i}-${j}`);
  }
  await op.commit();
}
const end1 = Date.now();

console.log(`write: ${end1 - start1}ms`);

const start2 = Date.now();
let count = 0;
for await (const _it of kv.list({ prefix: [] })) {
  count += 1;
}
const end2 = Date.now();

console.log(`read: ${end2 - start2}ms, count: ${count}`);

```

gives:

```
write: 957ms
read: 165ms, count: 40000
```

On Deno Deploy, @skoshx can you try setting the `batchSize` parameter to 1000, like:

```ts
db.list({ prefix: ["a"] }, { batchSize: 1000 });
```

**Comment by skoshx** [comment]
@losfair My benchmark was run with `batchSize` of `500`, because the Deno unstable lib docs stated (maybe I have an outdated version) "The maximum value for this option is 500. Larger values will be clamped."

Tested with `batchSize` of `1000` and now fetching 26K items takes 5.5s - 6.5s. A large improvement, but still unusable in production, since there is no way we can expect users to wait around for such a long time.

On a personal note, the time it takes also causes my Discord slash commands to time out, because Discord slash commands require the request to return quite quickly.

**Comment by skoshx** [comment]
Okay, thanks for clearing that up, didn't understand that that is how it works...

My usecase is tracking the time users are online on Discord (we use it internally for performance monitoring), and those 26K items are the entries of "online", "offline" etc. Even if we need just the entries of this day, we need to fetch them all to be able to filter by `createdAt`.

I completely understand that my usecase probably would be better served by a traditional relational database like Postgres, but I just wanted to use Deno KV since Deno KV + Pentagon is my favorite for persistence on the edge, because it's so simple and Just Works(tm)...

I guess I was expecting Deno KV to magically work with the same performance as other relational databases, but I understand that the edge has its own pros & cons.

**Comment by nberlette** [comment]
@exside Just at a quick glance, I think the blazing fast speed in Firefox might be due to the record count being an order of magnitude lower than the tests ran in Chrome and Safari. I'd wager ~300k records in Firefox would put it somewhere in the range of ~500ms, essentially on par with Chrome and Safari.

> Ran the same snippet in Firefox:
> 
> <img alt="image" width="450" src="https://user-images.githubusercontent.com/445501/266180800-ded60291-0a74-4fb9-923b-6998351e6b7f.png">
> and Chrome (wow? I'd take that performance any day 🤣 ):
> 
> <img alt="image" width="408" src="https://user-images.githubusercontent.com/445501/266181483-8c139e13-7c56-4c24-913f-0284b29835b4.png">
> and Safari (also good, even faster than Chrome below 100k entries, then it evens out a bit):
> 
> <img alt="image" width="442" src="https://user-images.githubusercontent.com/445501/266182206-2b4d1a3a-c9d0-422f-9f65-5803bcf98f2b.png">

**Comment by cknight** [comment]
@skoshx Could you add `createdAt` to your key allowing you to filter during your query (using [list](https://deno.land/api@v1.36.4?s=Deno.Kv&unstable=&p=prototype.list) range or prefix capabilities) rather than after?

E.g.
```ts
kv.list({start: ["users", 1694044800], end: ["users", 1694131200]});
```
will fetch users data for today (1694044800 is the unix time for start of today).

**Comment by skoshx** [comment]
@cknight Hello, didn't know you can specify a range in the `list` function, thanks for that!

I guess I knew there were workarounds, I just was hoping that this was some problem upstream. I'm using [Pentagon](https://github.com/skoshx/pentagon) and don't want to start making massive changes to how the keys are stored...

**Comment by anywhichway** [comment]
@skoshx Although being tied to Pentagon may make this suggestion moot, I have written an indexing and query wrapper around Deno KV to address the kind of issue you are running into, https://github.com/anywhichway/denodata.

**Comment by skoshx** [comment]
@anywhichway Looks interesting! Could you elaborate a bit on how denodata could be used? I read the README but I was a bit overwhelmed by the code examples :D

**Comment by anywhichway** [comment]
@skoshx Denodata can automatically index any object across all properties. Or, you can create indexes as collections like in MongoDB. Typically your collections will exactly parallel JavaScript classes. Then you can search by just providing a pattern, e.g. db.find({name:"joe"}) would return all objects with the property 'name' having value 'joe' as an iterable. In your case, you would split the `createdAt` date into month, day, and year properties or so each could be searched separately or provide a range query. I have actually toyed with auto-splitting dates for indexing. 

Probably best to create an issue on my GitHub site https://github.com/anywhichway/denodata with the title "Simpler Documentation!" rather than pollute the Denoland issue repository. I will then provide more updates in the issue you create and use that to drive simpler documentation. Make sense?

**Comment by skoshx** [comment]
@anywhichway Yeah interesting, I'm curious though, do the automatic indexes refer to some "document ID" which is then used to actually find the "real" value of that document, or does it create duplicate content for all the indexes?

**Comment by anywhichway** [comment]
The indexes refer to an ID which is used to retrieve the document. Indexes are actually arrays used as Deno KV keys (which Deno KV can range search very efficiently). In Denodata, the last value in the array is the document ID to make things even more efficient. The Indexes are automatically managed as documents are modified and deleted. It is pretty obscure, but the index structure is documented late in the README.


________________________________

**Comment by skoshx** [comment]
Ok, cool approach! Will take a deeper look when I have time :)

**Comment by skoshx** [comment]
Closing, as this isn't a problem with Deno KV.
