### ISSUE TITLE
Suggestion:  Look into porting to Rust and using Tokio

### ISSUE THREAD

**Issue by brucod** [denoland/deno#205]
Alex Crichton, from the Rust Core team, gave a great presentation on Concurrency in Rust with Async I/O using [Tokio](https://tokio.rs/) at [code::dive 2017](https://www.youtube.com/watch?v=SiUBdUE7xnA).  As soon as I watched your Deno talk, I thought about his.  It is long, but I highly recommend watching it.

From his talk:  Using a [simple hello world benchmark](https://www.youtube.com/watch?v=SiUBdUE7xnA&feature=youtu.be&t=2104), they achieved almost 2mil req/sec - nearly 250k more than the next best implementation and 500k more than Go's fasthttp. Out of the box, [Tokio supports](https://youtu.be/SiUBdUE7xnA?t=2672) 'TCP, UDP, Unix sockets, Named pipes, processes, signals, http, http2, web sockets, ...'

Some observations (Some may be wrong and definitely missing some :smiley:):
- [Mio](https://github.com/carllerche/mio) crate handles all the OS async abstractions for you for each major platform bundled into Tokio.  No re-inventing the wheel.
- They don't use callbacks like Node but futures and task-scheduling.
- Actual threadsafe concurrent/multi-threaded async operations and servers.  See [Rayon](https://github.com/rayon-rs/rayon) as well
- Async/await Rust syntax that might map well to V8/JS's async/await implementation.
- Rust is already poised for WebAssembly.  Writing Deno in Rust, developers won't have to know Go as well.
- Rust is young but growing - voted most loved language for third year in a row Stack Overflow's yearly survey
- Tokio's thoughtful design appears to lend to extensible use cases and crates.
- Tokio is written and supported by members of the Rust Core team.
- No garbage collection

Thanks for the cool, new project and your time

Edit: Forgot to include no GC

**Comment by arjunyel** [comment]
One block is Deno uses Protobufs for communication but they are not officially [supported in Rust](https://developers.google.com/protocol-buffers/), There are third party libraries tho.

I think Rust would be a great fit, it seems Mozilla is putting [a lot of work into WebAssembly](https://hacks.mozilla.org/2018/03/making-webassembly-better-for-rust-for-all-languages/) 😄

**Comment by FrankFang** [comment]
https://github.com/ry/deno/issues/208#issuecomment-395739171

**Comment by fluxxu** [comment]
I am a huge Rust fan, and I agree with the advantages you listed. But I don't think now is the best time to invest to Futures/Tokio, considering
- `Future`  has some [difficult ergonomics problems](https://boats.gitlab.io/blog/post/2018-01-25-async-i-self-referential-structs/) now.
- `Future` and task system were just merged into `std` 2 days ago.
  https://github.com/rust-lang/rust/pull/51263#issuecomment-395233182
- async/await is not implemented now. I know the design work is [almost done](https://github.com/rust-lang/rust/issues/50547). And there is a prototype [futures-await](). But it takes time to settle all the details.
- [Rust 2018](https://blog.rust-lang.org/2018/03/12/roadmap.html) is expected to release in September. I am not saying it will break everything, but some major refactoring is foreseeable.

These are not deal breakers, and Rust core team is resolving them quickly. It's just sensible to add these complexities to deno now, which itself an experimental project.
I think the better approach is to implement low-level modules using C++ now, and later port them to Rust after Rust's async io story settled.

**Comment by matiasinsaurralde** [comment]
I've been playing around with Rust and wrote this wrapper of `libv8worker2`, might not be useful but I wanted to explore some of the language capabilities for this: https://github.com/matiasinsaurralde/rust-v8worker2

**Comment by alexhultman** [comment]
Sounds like a good idea. But just to be clear: these hello world pipelining benchmarks are highly inaccurate and 2 million req/sec is not even that good of a result. I have servers doing 5 million req/sec for those cases. In any case - anything is better than where Node.js performs today (capping at 60k req/sec with pipelining).

Japronto, lwan, "uws" all perform better than tokio for these pipelined hello world cases.

**Comment by alexhultman** [comment]
The biggest problem is not going to be making the native part of deno fast - there are tons of fast native servers. Where everything is going to be determined is how lightweight the JS wrapper of this server will be. Clearly Node.js completely failed at this, even though their native components are not all that slow.

**Comment by alexhultman** [comment]
What I would like to see as a highly prioritized item on the agenda is a benchmark of Deno as is, with Golang. Because if Deno cannot properly retain even the perf. of the built-in Golang HTTP module then it will make no difference at all spending a lot of time rewriting the native parts in Rust. We really need to see a benchmark of Deno in action as soon as possible. This should be priority nr. 1 before every other decision really.

**Comment by matiasinsaurralde** [comment]
@alexhultman I've been running a few benchmarks on `deno` with Go and also extended the profiling options in order to make it easier to find potential bottlenecks (#193). The Go profiling tools provide a great overview and you can visualize stuff like this:
<img width="1053" alt="captura de pantalla 2018-06-07 a la s 11 05 19" src="https://user-images.githubusercontent.com/20110/41383530-3ead3348-6f3f-11e8-9aa8-8a9bc9e1f5a1.png">
I've been working with Go interop for around two years, integrating Python, Lua and other runtimes with a HTTP server (actually an API gateway that people use to handle many requests) and I would say that the overhead of `cgo` calls is pretty big.
I think that the @ry minimal V8 bindings are pretty good and helps on keeping this overhead as low as possible, at the same time I've been hacking around Rust (and also learning it!) and recently ended up [porting this component](https://github.com/matiasinsaurralde/rust-v8worker2). I've also started to hack on a minimal `deno` port that uses `std::sync::mpsc` (have also tried `crossbeam`, really exciting stuff) in order to be able to benchmark and potentially compare both implementations. From my Rust experiments it seems that interop is lighter here and this could represent a big performance gain.
You may also find [these benchmarks interesting](https://github.com/ry/deno/pull/209#issuecomment-395716893), of course this is experimental and I'm sure there are many ways to optimize this.

**Comment by ry** [comment]
@alexhultman Removing Go is to avoid a double GC - which I think everyone can appreciate. And we're experimenting with interfaces - first pass implementations like the HTTP patch let us test. No one is claiming any release or interface commitment.

**Comment by alexhultman** [comment]
So are you prepared to put your foot down and **reject** solutions with bad performance or are you just looking to fall in the same pits like with Node.js? Obviously you can't just let anyone write up anything and just hit merge.

**Comment by matiasinsaurralde** [comment]
@brandonros I haven't implemented the HTTP module yet, there are many options for this. I've been doing some quick benchmarks with this system call `readFileSync` (calling this 5000 times).

1) Running the Deno version that uses Go:
```
% ./deno readfile.ts 
elapsed =  190 ms
```
2) Running `reno` using a `debug` build:
```
% ./target/debug/reno readfile.ts 
elapsed =  250
```
3) Running `reno` using a `release `build:
```
% ./target/release/reno readfile.ts 
elapsed =  140
```
4) NodeJS:
```
% node readfile_node.js 
elapsed =  77
```
The main advantage of Rust in this scenario is that we can interact directly with the C data structures, etc.
I've been trying to measure the overhead of using Protocol Buffers as described in #269 and started to migrate our Protocol Buffers definition to Cap'n Proto, implemented the Rust side of it but got stuck trying to parse these messages on the V8 side, found issues with the Cap'n Proto TS library that require some serious debugging.

**Comment by brandonros** [comment]
@matiasinsaurralde If you had to estimate, do you have faith that switching to Cap'n Proto will bring the elapsed time down from 140, close to Node's 77?

For perspective, it might make sense to show how long the pure C/pure Rust version of the same benchmark would take?

**Comment by alexhultman** [comment]
> For perspective, it might make sense to show how long the pure C/pure Rust version of the same benchmark would take?

For HTTP Deno would currently be about 13x off.

**Comment by ssokolow** [comment]
> Running reno using a releasebuild:
> 
> ```
> % ./target/release/reno readfile.ts 
> elapsed =  140
> ```
> 
> NodeJS:
> ```
> % node readfile_node.js 
> elapsed =  77
> ```

NPM encountered something similar to this during a reliability-oriented rewrite of one of their components and wound up discovering that a surprising amount of the difference was down to how much optimization effort had been put into Node.js in areas you'd underestimate the impact of, like default buffer sites.

**Comment by kentonv** [comment]
@matiasinsaurralde Can you tag me on any capnp-ts issues you're running into? I can't make any promises but I'm trying to make some time to play with it myself soon and I hope to help fix issues while I'm at it. (I created Cap'n Proto and the C++ reference implementation but not capnp-ts.)

**Comment by alexhultman** [comment]
I just wanted to insert a few points.

It's easy to "dislike" comments that goes against ones gut feeling and fanatism. However disliking someone's comments does not make any change on reality, just because you don't want to accept reality for what it is. You can't pull the plug on reality and the reality as in, what's measurable with scientific methods shows a very clear picture.

If a project stems from the acknowledgement of prior mistakes in Node.js but still clings to it as the only source of reference then you're not going to get any further than a few baby steps past.

Crystal, Golang, Rust, Swift - they all have servers that outperform Node.js by multiple significant times over. You really need to stop comparing with Node.js and raise the stakes if you want to get anywhere real.

I have actual code running inside of reality in this very moment doing about 6x of Node.js, inside of Node.js via V8 native addons. It properly communicates with JavaScript callbacks and methods, has proper URL routing and SSL. It does about 1.5x of Crystal and Golang's fasthttp.

My point is that solely comparing with, and settling for, Node.js is only going to lead you to yet another Node.js. Clearly it is possible to raise performance up to Golang levels from inside V8, just do it already. Comparing with Node.js and accepting even a 4/5th the perf. is simply unacceptable.

Can we please start comparing with Golang's fasthttp or similar?

**Comment by matiasinsaurralde** [comment]
@kentonv Sure, I will continue my experiments this week and will be able to report the detailed issues on the repo. Thanks.

**Comment by brandonros** [comment]
> I have actual code running inside of reality in this very moment doing about 6x of Node.js, inside of Node.js via V8 native addons. It properly communicates with JavaScript callbacks and methods, has proper URL routing and SSL. It does about 1.5x of Crystal and Golang's fasthttp.

Link to said code? How does it compare to Rust?

**Comment by alexhultman** [comment]
You always pay a quite hefty (but still somewhat acceptable) fine calling JS functions from C++. So of course it is impossible to measure up all the way to a native-only implementation. I lose about 30% req/sec when running inside of Node.js compared to as a stand-alone C++-only build.

Still, 70% of a good C++ implementation is enough to measure up to the fastest available for Golang.

**Comment by brandonros** [comment]
@alexhultman I want to learn Rust. Let's work together on what you think this project should be. I've tried e-mailing you but you never wrote back.

**Comment by alexhultman** [comment]
I don't know a single line of Rust though, so I can't help

**Comment by brandonros** [comment]
@alexhultman 

1. You ignored my comment about the e-mail

2. You ignored my comment about the link to your code that is 1.5x as fast as fasthttp.

3. It sounds like you are saying protocol buffers/Cap 'n Proto are the wrong thing to do... proven by your fast JavaScript code, which uses callbacks and methods and native modules? If you remove node.js out of the picture and take the v8 runtime by itself, how would you compile native modules that hook into the v8 runtime but are still callable by Javascript?

**Comment by robbym** [comment]
I've been watching this project since Ryan gave the talk, and have been wanting to contribute. I'm fairly familiar with Rust, but not with V8, Cap'n Proto or protobufs (I get the concept though). Is someone taking the helm on the Rust experiment and needs help?

**Comment by alexhultman** [comment]
Dude, all of this is already done. No need to post basic V8 samples here. Ryan wrote Node.js. He already knows about V8 and so does all Node.js core devs. Also, this project deno is not mine, I don't decide anything here. And finally that repo is not FFI and completely useless. Of course you can run C code free of perf. cost from Rust. This is not a hello world introduction to neither Rust nor V8.

**Comment by robbym** [comment]
@brandonros Looking at the roadmap, it seems like the portion that will be interacting with the VM, called libdeno, will be written in C++, which will expose a C api so that Rust can bind to it. The beginnings of it are here: https://github.com/ry/deno/blob/master/src/main.rs

As far as the messaging protocol you are mentioning, they already decided to use protobuf (Cap'n Proto in future?) and pub/sub.

**Comment by Azareal** [comment]
I would be careful about hello world benchmarks, they're notoriously... Useless lol
I suppose, they are alright as a rough indicator, but I wouldn't read into them too much.
In practice, it's largely how well optimised the application is rather than the stack below it.

Go seems to have a fair bit of room for improvement, at-least as far as performance is concerned (there's always some new idea bouncing around their Github), but the GC is probably always going to be a problem lurking round the corner.
The best you can probably get on that front is probably to reuse memory across requests ala fasthttp, I believe one thing fasthttp recommended there were the sync.Pools.

There are a couple of proposals including a [percpu sharded value proposal](https://github.com/golang/go/issues/18802#issuecomment-396811877) which might also help with performance in some areas, but I'm not sure how much momentum it has behind it.

And there are ideas being bounced around to drastically reduce allocations in Go 2 (e.g. the conversions between []byte and string which can sometimes be costly), although I can't really say much on that, as the details seem a little vague and I'm not sure when it may be released.

**Comment by alexhultman** [comment]
> I would be careful about hello world benchmarks, they're notoriously... Useless lol
I suppose, they are alright as a rough indicator, but I wouldn't read into them too much.
In practice, it's largely how well optimised the application is rather than the stack below it.

What is a "hello world benchmark" to you? If we're talking about HTTP pipelining of the string "hello world" then I can easily outperform Node.js by 80x. That's unlikely to ever be a useful number though. The 6x comes from a far more useful case and is not a "hello world" benchmark. Or maybe you suggest we all go write our servers in Ruby on Rails? Then what was the point of Node.js in the first place?

**Comment by alexhultman** [comment]
Yeah those 2 mil are complete nonsense. They are achieved using HTTP pipelining which basically only benchmarks the parser/formatter. I get 5 million req/sec in my implementation when I do that.

**Comment by ry** [comment]
Yes we will likely use Tokio. It's about to land in #434

**Comment by dmayerdesign** [comment]
@alexhultman Prove you're not just a troll and post some code!
