### ISSUE TITLE
Add style guide for commit messages

### ISSUE THREAD

**Issue by ry** [denoland/deno#2075]
Our commit message formatting is all over the place. Now that Deno is a bit more mature we should try to nail this down. Ideally we'd have some sort of lint for commit messages as well (for example, the first line of commit end in a period, CI should reject such messages)

https://golang.org/doc/contribute.html#commit_messages
https://github.com/golang/go/wiki/CommitMessage

**Comment by zekth** [comment]
Agreed. Also it would be nice to work on the style guide of Issues and PR using the github templates.

**Comment by sh7dm** [comment]
IMHO good for that are commitizen + commitlint.

**Comment by j-f1** [comment]
If you’re mainly committing via PRs, I’d suggest instead linting PR titles using a GitHub App instead, since those are much easier to edit and the “squash and merge” feature pretty much obliterates the commit messages anyway. This could work hand-in-hand with requiring CI to pass before merging, effectively blocking commits from being pushed to `master` directly.

**Comment by kitsonk** [comment]
This has largely been done in the [PULL_REQUEST_TEMPLATE.md](https://raw.githubusercontent.com/denoland/deno/master/.github/PULL_REQUEST_TEMPLATE.md), though `docs/contributing/` could of course be more explicit, but closing for now.
