### ISSUE TITLE
Uncaught SyntaxError: The requested module './deno.json' does not provide an export named 'imports'

### ISSUE THREAD

**Issue by sant123** [denoland/deno#20774]
Related with https://github.com/denoland/deno/issues/18614

Currently trying to import a JSON module like this causes a SyntaxError:

```ts
import { imports } from "./deno.json" with { type: "json" };

console.log(imports);

```

![image](https://github.com/denoland/deno/assets/7959437/34818567-1ec4-43ab-83fd-c4292cb63de7)

Should the LSP or TypeScript hint this is not supported? Or may this import like be supported in a future?

Thanks.

**Comment by dsherret** [comment]
The same thing happens in vanilla TypeScript with Node with import assertions:

```shellsession
> cat other.json
{
  "imports": {}
}
> cat main.mts
import { imports } from "./other.json" assert { type: "json" };

console.log(imports);
> cat tsconfig.json
{
  "compilerOptions": {
    "target": "es2022",
    "module": "NodeNext",
    "resolveJsonModule": true
  }
}
> npx tsc
> node main.mjs
file:///V:/scratch-npm/main.mjs:1
import { imports } from "./other.json" assert { type: "json" };
         ^^^^^^^
SyntaxError: The requested module './other.json' does not provide an export named 'imports'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1
```

So I don't think this issue is worth tracking in this repository.

I would recommend reopening this issue if:

1. TypeScript 5.3 is released (as I mentioned here: https://github.com/denoland/deno/issues/18614#issuecomment-1745533077)
2. The above example fails for `tsc`

Once TS 5.3 is released, if this still occurs with import attributes then I'd recommend opening an issue in the TypeScript repo with the above example if you'd like to see this fixed.
