### ISSUE TITLE
Implement `node:tty`

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#20855]
All of these reports below are blocked on `node:tty` support.

- https://github.com/denoland/deno/issues/20611
- https://github.com/denoland/deno/issues/6529#issuecomment-1432690559
- https://github.com/denoland/deno/issues/6529#issuecomment-1522059006
- https://github.com/denoland/deno/issues/6529#issuecomment-1695803570
- https://github.com/denoland/deno/issues/20336
- https://github.com/denoland/deno/issues/17248
- https://github.com/denoland/deno/issues/20890

**Comment by ulken** [comment]
@littledivy Not sure where to post this, but `node:tty` doesn't seem completely implemented. I'm try to using [term.ink](https://term.ink) and it crashes with:

```sh
  ERROR  unreachable

 ext:deno_node/_util/asserts.ts:16:9

 - unreachable (ext:deno_node/_util/asserts.ts:16:9)
 - TTY.ref (ext:deno_node/internal_binding/handle_wrap.ts:38:5)
 - ReadStream.ref (node:net:658:20)
 ...
 ```

More specifically, it fails [here](https://github.com/vadimdemedes/ink/blob/168244470cd3e4b85e19b968a55938d013232761/src/components/App.tsx#L166).

The problem seems to be `ref()` not being implemented in `net.Socket`. But that confuses me, since [std / node / net.ts > Socket#ref](https://deno.land/std@0.158.0/node/net.ts?s=Socket&p=prototype.ref) suggests that is indeed implemented?

Thoughts?

**Comment by littledivy** [comment]
@ulken Yes, not all of it is implemented yet. In this case, `Socket#ref` for TTY handles is unimplemented. 

Can you open an issue? Thanks

**Comment by ulken** [comment]
@littledivy sure thing. I suppose [this](https://github.com/denoland/deno/issues/21024) is part of the issue?

> During the implementation of node:tty we had to make a tradeoff wherein tty.ReadStream and tty.WriteStream were made to extend a Duplex instead of a net.Socket because it introduced circular dependencies at snapshot-time

I'm still confused by the docs I referenced above, it seem to suggest that is indeed implemented. How am I suppose to read it?
