### ISSUE TITLE
Support import node modules (commonjs modules)

### ISSUE THREAD

**Issue by julianreyes25** [denoland/deno#20887]
I think that this issue can be solved doing that the node module can be imported with `import { foo } from 'module' with { type: 'node' }`
Example:
```ts
// module.cjs
exports.foo = 'bar';

// main.js
// old way: import { createRequire } from 'node:module'
// const require = createRequire(import.meta.url);
// const { foo } = require('./module.cjs');
import { foo } from './module.cjs' with { type: 'node' }
console.log(foo) // bar
```

**Comment by julianreyes25** [comment]
.

**Comment by dsherret** [comment]
The way to do this is as you mentioned with `createRequire`.

We really don't want to increase the complexity in Deno by having yet another way of importing CJS modules. ESM is the future.

(side note: I deleted a noisy blank comment in this thread so that's why there's the "deleted a comment" message above)
