### ISSUE TITLE
Deno advantages and potential

### ISSUE THREAD

**Issue by cllty** [denoland/deno#2107]
Hi everyone this is a question not an issue.

I have a seen similar issue like https://github.com/denoland/deno/issues/245 already but haven't fully grasped what advantages deno bring compared to nodejs (or any other language if that matters) in terms of robustness, scale, or performance. Also is deno just a runtime to prototype with, thus with no regards to performance? I have seen issues like https://github.com/denoland/deno/issues/1205 although not the best which mentions some performance issues with deno, but I'd like to get a clear and better picture hopefully.

**Comment by kitsonk** [comment]
The issue tracker really isn't a good place for something like this.  The home page (https://deno.land/) provides a collection of information of the purpose and intent of Deno.  General discussion occurs on Gitter (https://gitter.im/denolife/Lobby).

**Comment by ry** [comment]
@cllty This is an experimental project exploring how the JS runtime/ecosystem could be improved/simplified and what kind of tooling is enabled by modern infrastructure. [I discuss this in some detail in a recent talk.](https://www.youtube.com/watch?v=z6JRlx5NC9E)

**Comment by leodutra** [comment]
Hey guys, I am in the process of growing some love to Deno and I have something which is bothering me.

I know Ryan likes TypeScript. But will Deno have any real benefit from using it at the core?
I mean, will the runtime use raw TypeScript to squeeze performance, maybe passing types somehow to V8 or another underlying component, providing better performance than just JS?

I think this should be taken into consideration, of course, not because of my preferences but because JS community is used to optimizations (because of the times of IE and the culture of V8 vs SomeMonkey). We also see some runtimes almost reaching Java on some algorithm benchmarks and the contrary could be seen as a kind of regression, maybe, IMHO.

The point is: is Deno really focusing on some Unix-y light, fast, optimal approach or this is not one of the main guidelines, if not **the** main guideline?
