### ISSUE TITLE
`os.freemem()` pollyfill is not compatible with Node.js

### ISSUE THREAD

**Issue by roj1512** [denoland/deno#21148]
https://github.com/denoland/deno/blob/9f2e56ba96b847d6275ac26656d9d522fca252f7/ext/node/polyfills/os.ts#L161-L162

Here, `Deno.systemMemoryInfo().free` is the amount of **free** memory in bytes, which is incompatible with what `os.freemem()` returns in Node.js, the amount of **available** memory in bytes.

![Frame 1](https://github.com/denoland/deno/assets/49933115/019d9f72-e9a8-4407-b7c2-cfc6168426c0)

**Comment by lino-levan** [comment]
What's the difference between free memory and available memory in this context?

**Comment by tannal** [comment]
OS will use most available memory to buffer I/O which make I/O faster.
The free memory is almost always very low.
Node users typically use this API to decide whether the machine has enough memory to launch their apps/programs.
That means available memory is more useful than free memory for users.

libuv/libuv#3351
nodejs/node#31243

So they change uv_get_free_memory to return available memory.

But I don't know why they don't add a get_available_memory api and tell users use this.
Apparently they can not switch it back now, because that would break users' code.

Because deno is working on node compat, the only thing we can do is do what node do.
