### ISSUE TITLE
http/server: ERR_CONNECTION_RESET when responding without request body consumed

### ISSUE THREAD

**Issue by jespertheend** [denoland/deno#21209]
**Describe the bug**

**Steps to Reproduce**

1. Create `main.ts`:

```ts
async function post() {
	const fileInput = document.getElementById("fileInput") as HTMLInputElement;
	if (!fileInput.files || fileInput.files.length != 1) {
		alert("Please select a file");
		return;
	}
	const file = fileInput.files[0];
	const response = await fetch("/post", {
		method: "POST",
		headers: {
			"content-type": "application/zip"
		},
		body: file,
	});
	alert(await response.text());
}

Deno.serve(async (req: Request) => {
	const url = new URL(req.url);
	if (url.pathname == "/") {
		return new Response(`
<!DOCTYPE html>
<html>
	<body>
		<script>
			${post.toString()}
		</script>
		<input type="file" id="fileInput" />
		<button onclick="post()">POST</button>
	</body>
</html>`, {
			headers: {
				"content-type": "text/html"
			}
		})
	} else if (url.pathname == "/post") {
		console.log("/post received");
		// Uncomment this to fix the issue:
		// const buffer = await req.arrayBuffer();
		return new Response("OK");
	}
	return new Response("Not found", {
		status: 404,
	})
})
```

2. Run `deno run --allow-net main.ts`
3. Visit `http://localhost:8000/`
4. Select a large file (in my case I'm using [dist.zip](https://github.com/denoland/deno_std/files/9390192/dist.zip))
5. Open the network panel in the browser inspector
6. Click 'POST'.

**Expected behavior**

The request responds with 'ok'

**Actual behavior**

The request fails with ERR_CONNECTION_RESET.
Note that the deno console doesn't show any errors and the `console.log("/post received");` line is being run.
If you uncomment the `await req.arrayBuffer()` line, the issue is fixed.

**Environment**

- OS: macOS 12.5 (21G72)
- deno version: `1.38.1`

**Comment by lucacasonato** [comment]
I am going to classify this is as "working as intended". The server is closing the connection after the response body has been entirely sent, to prevent resource leaks. You did not read the entire request body in the server, which means that the client may not have sent the entire request body and thus is still trying to write it. While the client is doing this, the server closed the connection because the request is done. The client notices this and errors out because it was unable to fully send it's request body.
