### ISSUE TITLE
Different behavior deno vs deno eval

### ISSUE THREAD

**Issue by cybor0** [denoland/deno#2132]
run deno then 
```
$ deno
> Deno = 'a'
a
thread 'tokio-runtime-worker-0' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', ../../core/isolate.rs:486:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
==================================================================

./target/debug/deno
> eval("var a =12; console.log(window.a)")
12
undefined

./target/debug/deno eval "var a =12; console.log(window.a)"
undefined

**Comment by ry** [comment]
Weird. Thanks.

**Comment by kevinkassimo** [comment]
This is due to we have an async function wrapper around the code when doing `deno eval` (to allow `await`s):

https://github.com/denoland/deno/blob/0796a8f2f75005df95ef6115a4bdf6dd66e58dc3/cli/main.rs#L163-L183

I don't think we should fix this. Using non-strict mode in such ways should be discouraged.

The `window.Deno` assignment problem could be addressed though.

**Comment by ry** [comment]
Fixed in https://github.com/denoland/deno/pull/2153
