### ISSUE TITLE
Website does not feel authentic

### ISSUE THREAD

**Issue by szmarczak** [denoland/deno#21831]
It feels like the design was copied from https://upstash.com/ or https://supabase.com/

Sudden change of the color scheme to green gives it straight away as it does not follow previous grayish (or blue) theme Deno had used.

It is definitely "inspired" (influenced) by some other website.

**Comment by josh-collinsworth** [comment]
Hi @szmarczak. I'm Josh, and I'm the frontend developer who implemented the new homepage of the website. I've been with Deno since August, and I was involved in most of the redesign discussions. I know seeing a new version of something familiar is always challenging, especially when there's not a lot of transparency to the reasons and process behind those choices. So hopefully I can help with the feeling of "inauthenticity" a little bit by adding some of that missing transparency.

For what it's worth, Deno engaged a third-party design firm for this redesign, and it's something the team at Deno (including myself, to some extent) have been working on and thinking about since at least last summer. A lot went into it, and there's still a good deal more to come. This is just a first step, which is part of why we've been pretty quiet about it for the time being, and I think it'll make a bit more sense further down the road, with more of the pieces in place. (Even the homepage itself isn't 100% yet.)

While we recognize there are similarities to a number of other tech sites (even beyond those named above), that's more to do with current design trends than imitation. We certainly weren't trying to copy anyone, and we don't believe the very capable and talented designers we worked with did so either. I think it's just a somewhat trendy look. But more importantly: it's a look we felt suited where Deno is currently.

The old, familiar Deno homepage was indeed much more colorful. It's definitely a strong contrast to the current redesign (although in fairness, the homepage has been both dark and green for a good while now, albeit a different green). You might pick up hints as you look around the site that this is because we're beginning to use color to differentiate Deno, the free and open-source runtime (green) from other products, like Deno Deploy (blue).

In any case: that original design felt like a great fit for what Deno was at the time, but as Deno has matured and grown from its humble origins into the very powerful suite of tools it is today, we felt the design of the site should be a better reflection of its current status as an increasingly polished, professional, and capable product, and of its continuing evolution.

We know this is a big change, and we most certainly don't want to lose sight of where we've come from. We have conversations about that very frequently. But for now at least, we feel it fits current Deno; modern, powerful, and sharp. Deno will continue to grow, and I have no doubt our website will evolve alongside it, in both content and design. But for the time being, we're proud of what our partners in design have produced, and we look forward to carrying that design further.

I hope that explanation helps, and I hope it is indeed apparent the care and thought that went into this redesign as more of it is unveiled. In the meantime, we're always happy to hear from our community and to help address any issues or concerns we can.

**Comment by nhrones** [comment]
Why so much DEAD space?  On my laptop, there are areas of full-black-screen as I scroll down?  It seems to take forever to traverse the complete page top-to-bottom?

**Comment by nhrones** [comment]
Also, navigating from the home page to -> Moules -> Standard Library, is a jarring, blinding experience.  When will these pages have common dark theme?

**Comment by szmarczak** [comment]
Thanks for your reply @josh-collinsworth, I appreciate it. You are probably familiar with the [*Linear effect*](https://twitter.com/namyakhann/status/1692469183060078889). 

>  that's more to do with current design trends than imitation. We certainly weren't trying to copy anyone

It's like saying the design is indeed based on (copied from) other website(s) without actually saying it but rather using the word *trend* (because that's what people currently do - imitate). The new website is definitely intriguing and looks cool (however it's much less readable than the previous versions).

Many CTAs now have a glow/texture effect:
- https://chrisnicholas.dev/blog/a-new-blog-for-2024
- https://rauno.me/craft

Cubes are also a popular concept. The Big Green Button? I'm pretty sure I've seen it as well.

It's just that these little things pile up and give this "woah, I've seen this one before!" impression. 

> we don't believe the very capable and talented designers we worked with did so either. I think it's just a somewhat trendy look.

No doubt in talent. In fact, talent has nothing to do with being authentic. Often people create a better version of something else.
And often people recall something but they're not sure they have remembered it so they think they're being authentic, while in fact they're not.

**Comment by josh-collinsworth** [comment]
We're getting into design theory territory here. There seems to be an assumption that any design should be wholly original—not reminiscent of anything—and that's a deep theoretical topic in itself (not to mention something many in design would argue is either impractical, impossible, or both. After all, if you make a button unlike anything anybody's seen before, how will they know it's a button?)

I don't mean to dismiss these points as wholly invalid or impractical. They're not. You have a valid point. But I _do_ want to emphasize it's very easy to critique a new design without being privy to the myriad decisions that went into it, and the countless tradeoffs that were evaluated along the way. Uniqueness is just one of many, many concerns that have to be evaluated and balanced, and one that comes with its own costs and benefits.

There's a very strong psychological reaction against the new, and so I think it's fairer and more productive to at least live with the change until after the initial adjustment period, and to consider what tradeoffs might be inherent in other directions.

We don't by any means think of this redesign to be perfectly final or beyond improvement. We'll doubtlessly iterate on it. There are plenty of valid critiques that can be made, and I'm sure we'll address many of them. Others, we might consider worth the tradeoff.

Design is always a moving target. This is just our best step at this moment towards where we feel we ought to be.

**Comment by szmarczak** [comment]
> We're getting into design theory territory here. There seems to be an assumption that any design should be wholly original—not reminiscent of anything—and that's a deep theoretical topic in itself

No. Copying a single part (or a dozen) does not make you inauthentic. Copying a hundred parts - does. The same applies to all subjects in existence.

> There's a very strong psychological reaction against the new
> [...]
> We don't by any means think of this redesign to be perfectly final or beyond improvement.

I never said that a website should not iterate.

> This is just our best step at this moment towards where we feel we ought to be.

Maybe! I believe you're right. I'm sure this wasn't a 1-person decision (don't take this issue personal).
I just hope the final version happens to be more original than it is now.

Thank you for discussing this important topic.

**Comment by szmarczak** [comment]
Hey @josh-collinsworth congrats on the Deno 2 website launch! I'd like to provide additional feedback.

[The Deno 1.0 website](https://web.archive.org/web/20200531030042/https://deno.land/) was very minimalistic. And [it stayed like that](https://web.archive.org/web/20221113214615/https://deno.land/) for a while.
It was good at that moment, however as Deno improved indeed it was too simple.

[The blue version of the website](https://archive.is/txxyz) was definitely too overwhelming to read.
[The first green one](https://archive.is/jZhAm) was a little bit better than the blue version, however still too overwhelming.

I really loved [this version](https://archive.is/LlYOv) of Deno Deploy. I think something between the current version of deno.com and that would be best.
There are several issues with the current website:
- too much spacing,
- the blue gradient is warm, maybe make it colorful [like this](https://web.archive.org/web/20221113214615/https://deno.land/),

![image](https://github.com/user-attachments/assets/44d6f598-a214-44cd-a96f-1aa1b9358e11)
- remove black border
- make terminal look like terminal
- vertical-align: middle to the copy button
- also the `Install Deno` section is so small, maybe it should be integrated into the `Uncomplicate JavaScript` section?
- the green contrasts too much
- the loading hover button animation is weird
- the dropdown menu animation is unnecessary
- `Deno for enterprise` could be a navbar link with a different color
- `Native TypeScript support` section is too big
- `Built on web standards` is also too big
- `Batteries included` is also too big
- `Secure by default` :heart: perfect

![image](https://github.com/user-attachments/assets/f7d2a9c3-7b2d-4d4f-a274-efdc874d7733)

this `Get started` button redirects to `/` so it's useless. Also the statistics could be this so the entire section is useless:

![image](https://github.com/user-attachments/assets/5f1f50cd-167e-4e2c-8fd9-8aac7309320a)

![image](https://github.com/user-attachments/assets/d10f1125-5160-4642-9eb6-c2e4a5353947)

The graphs should be more compact:

![image](https://github.com/user-attachments/assets/03fc5968-4923-428e-b5d1-50c68fe8c66b)

- the `Built for the cloud` section should be positioned higher

**If you were to print the website, it would be 23 pages long.** Either this is a powerpoint presentation, or a website. It cannot be both.

As per the logo font, I think https://fonts.google.com/specimen/Fredoka?preview.text=deno would suit better.
