### ISSUE TITLE
Deno.listen() does not properly check the port parameter

### ISSUE THREAD

**Issue by hwcwy** [denoland/deno#21896]
Version: Deno 1.39.2

Deno.listen() does not check the availability of the port and can even accept a string without throwing an error.
However, the boolean value 'true' can still throw an error as expected.

![image](https://github.com/denoland/deno/assets/74729240/1f5c960d-55be-4f3b-8b97-692fb95b4573)

**Comment by hwcwy** [comment]
![image](https://github.com/denoland/deno/assets/74729240/7286f22e-321e-44bb-aec8-cc5de1b25c2c)

**Comment by marvinhagemeister** [comment]
We should definitely validate the port argument. It seems like we're casting any value to a number which can lead to unexpected values somewhat working due to JS casting rules as demonstrated in this issue.

https://github.com/denoland/deno/blob/f45ceb23206b4aaeca123c06bd3d59770f728468/ext/net/01_net.js#L468

**Comment by crisadamo** [comment]
Hi @lucacasonato I would love to give it a try. Seems to be quite doable as an initial contribution.
