### ISSUE TITLE
Implement sendFile()

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#2190]
Essentially http://man7.org/linux/man-pages/man2/sendfile.2.html. Windows seems to also have [`TransmitFile()`](https://docs.microsoft.com/en-us/windows/desktop/api/mswsock/nf-mswsock-transmitfile). Probably could have an interface
```ts
async function sendFile(inRid: number, outRid: number, offset: number, count: number): Promise<number>;
```

I'm not so sure why Node.js removed this feature in the early days. Is there any special reason that this is not included?

(It seems that `fs.copyFile()` in Node on linux [would try to use `sendfile` internally](https://github.com/nodejs/node/issues/23824#issuecomment-432642148))

**Comment by mikeal** [comment]
was just wondering about this today. i don’t know why this was removed in the early days but maybe @ry remembers.

i actually really want this for a database that i’m building, it’s just absurd that I have to copy data from a file into memory in order to put it in another file when there’s a way to do it without leaving the kernel.

**Comment by ry** [comment]
It was removed because our abstractions didn't mesh well with sendfile. It induced a lot of exceptions in the APIs - and ultimately was considered to be too much complexity for the optimization.

**Comment by littledivy** [comment]
This has been implemented internally in the HTTP server and `copyFile` API. Deno will use sendfile automatically where it can be instead of exposing a new API.
