### ISSUE TITLE
Import map expansion doesn't work in LSP

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#22270]
```json
{
  "imports": {
    "preact": "npm:preact@10.5.13"
  }
}
```

```ts
import * as preact from "preact";
import * as hooks from "preact/hooks"; // error only in lsp

console.log(preact, hooks);
```

Version: Deno 1.40.3

**Comment by lucacasonato** [comment]
It also doesn't work in `deno publish` I think

**Comment by guybedford** [comment]
If the import map is defined only for `preact`, expansion / inference of `preact/hooks` seems to violate the import maps spec? Or is the idea to bend the semantics to better support packaging workflows in this way?

**Comment by dsherret** [comment]
Sorry, wasn't clear in the issue. This is only for the import map in deno.json (not if referenced via "importMap": "..."), which is an extension to the import map spec. It only occurs for jsr and npm imports because it was an annoyance to have two entries (https://github.com/denoland/deno/pull/22087)

**Comment by guybedford** [comment]
Thanks for sharing the context, I missed that. I guess this only makes sense because the targets are not so much final URLs as they are intermediate package specifiers which then get further resolution processing applied. If browsers were ever to adopt the same pattern they would effectively rely on `/dir` serving the main entry point and `/dir/module` serving submodules, while while very unlikely to ever be viable, doesn't seem entirely unreasonable either, so it seems an interesting extension to explore. I would be careful of extending the spec much further at all though, effectively these are already two extensions which simply won't be supported by Node.js (partial resolution into intermediate specifier targets and automatic subpathing expansion).

**Comment by dsherret** [comment]
@nayeemrmn I'll take this one on by making this happen at a lower level.
