### ISSUE TITLE
Direct execution of file excluded from testing, `No test modules found`

### ISSUE THREAD

**Issue by kamekyame** [denoland/deno#22351]
Direct execution of file excluded from testing in `deno.json` will result in **"No test modules found"**.

As far as I can tell, this bug seems to have occurred between v1.39.2 and v1.39.3.

## Reproduce code

- deno.json
```json
{
  "test": {
    "exclude": ["test.ts"]
  }
}
```

- test.ts
```ts
Deno.test("test", () => {
  return;
});
```

- **Command**
```console
> deno test test.ts
```

<hr>

```
deno 1.40.4 (release, x86_64-pc-windows-msvc)
v8 12.1.285.6
typescript 5.3.3
```

**Comment by dsherret** [comment]
There was some inconsistencies around this that was resolved by making all the sub commands act the same way. See https://github.com/denoland/deno/issues/21658

As part of this, if you have a file excluded in your config file, then it will be excluded. The reason is people often do stuff like `deno test **/*.ts`, which expands to files being specified explicitly. So for example, if you had a `test.ts` file only in that directory, then it would expand in the shell to `deno test test.ts`. At this point, people would complain that `test.ts` was run when it's excluded in the config file.

Additionally, some people use stuff like pre-commit hooks for different tasks, which also explicitly specify files on the command line.

So overall, if you specify a file as being excluded from testing in the config file, then it will be excluded from testing if that config file is loaded (can be not loaded with `--no-config`).

**Comment by kamekyame** [comment]
I see ... It's not a bug.

From a usability point of view, I wanted to prevent `test.ts` from being executed when a user who does not know anything (not even `deno task`) executes the `deno test` command (with no arguments). (I would like to run `test.ts` from ci, however.)

I did not envision a usage like `deno test **/*.ts`. Given this, I consider this specification natural!

Thanks for your reply.
