### ISSUE TITLE
TC39 stage 3 decorators do not work with bundle or compile

### ISSUE THREAD

**Issue by tdillon** [denoland/deno#22419]
$ deno --version
deno 1.40.4 (release, x86_64-pc-windows-msvc)
v8 12.1.285.6
typescript 5.3.3

The TC39 stage 3 decorators sample provided by https://deno.com/blog/v1.40#decorators does not work with `bundle` or `compile`.  Given `bundle` has been deprecated 😢 I can understand why it wouldn't matter too much, but I assume decorators should still work with `compile`.  The `compile` command successfully creates an executable, but an error occurs when running the executable.

```
$ ./sample.exe
error: Uncaught SyntaxError: Invalid or unexpected token
  @trace
  ^
    at <anonymous> (file:///C:/.../sample.ts:10:3)
```

**Comment by cleverplatypus** [comment]
Same issue here. I haven't been able to deploy to Deno Deploy anymore in the past few days. It took some effort to figure out that the problem was the use of decorators, which my app relies heavily on. 
On a side note, Deno Deploy has the horrible "habit" of truncating stack traces, so I wasn't even able to figure out what the offending line was.

My deno.jsonc contains the experimental config setting.

```jsonc
{
//...
 "compilerOptions": {
    "experimentalDecorators": true
  }
//...
}

Indeed running `deno compile src/server.ts` I get the same error, so, I guess deno deploy compiles the app in the same way.

<img width="722" alt="image" src="https://github.com/denoland/deno/assets/1626868/19a95cdb-365b-4c67-ab86-90fe37fd21e9">

**Comment by lucacasonato** [comment]
This is now fixed for `deno compile`.
