### ISSUE TITLE
Disable test sanitizers when using `node:test`?

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#22473]
For better Node compat, perhaps the test sanitizers should be disabled when using `node:test` since `node:test` doesn't have this behaviour?

https://github.com/denoland/deno/issues/22471

**Comment by mmastrac** [comment]
I think this makes sense.

**Comment by 77it** [comment]
I'm writing code on Deno that can work also with Node, but I dislike the idea of having tests working differently under Deno just because I use `node:test` instead of `Deno.test()`. I could understand a switch/option or whatever makes explicit the difference and leave me choice. I like the strictness of Deno, when is needed/useful to produce better code.

**Comment by dsherret** [comment]
> but I dislike the idea of having tests working differently under Deno just because I use node:test instead of Deno.test()

I think a bigger problem is having `node:test` work differently under Deno than Node unfortunately.

> I'm writing code on Deno that can work also with Node

You may wish to create your own test function that calls `Deno.test` in Deno and then `node:test` in Node.
