### ISSUE TITLE
.jsonc doesn't work for external import_map.jsonc, but works for deno.jsonc

### ISSUE THREAD

**Issue by librejutsu** [denoland/deno#22535]
Version: Deno 1.41.0

**Issue:** 
If an external `import_map.jsonc` file is used instead of  `import_map.json`, Deno will throw an error if any comment is inserted in file, even though comments will work fine if the base deno file is used for imports instead as `deno.jsonc`

**Error:** 
```
error: Unable to load 'file:///home/user/project/import_map.jsonc' import map

Caused by:
    key must be a string at line 12 column 92
```

**Desired:**
Desired behavior would be for external `import_map.jsonc` files to work and support comments, just as a `deno.jsonc` file can.
Thanks.

**Comment by dsherret** [comment]
The file specified via "importMap" must conform to the import map standard, which doesn't support jsonc. If you want to use jsonc then you need to put it in a deno.jsonc.

The reason it's that way is so that if you go to use the import map in something like a browser, then you'll know it will work in the browser if it works in the import map file in Deno.
