### ISSUE TITLE
Bug: import reads '\r' as a '\n' character

### ISSUE THREAD

**Issue by javihernant** [denoland/deno#22575]
**Description**
`import`ing a file containing a carriage return ('\r') doesn't work as expected. `import` transforms the carriage return ('\r') into a newline ('\n'). This should be addressed because snapshot testing depends on this functionality to work. Take a look at denoland/deno_std/issues/4226.

**Steps to reproduce**
I made a repro at [https://github.com/javihernant/deno_import_test](https://github.com/javihernant/deno_import_test)
`deno run import.ts` will import the `snapshot.ts` file and then print the object created by `await import`. There you'll see a string containing a '\n' instead of a '\r', that is what the `snapshot.ts` contains.

**Deno version**
Version: Deno 1.41.0

**Comment by dsherret** [comment]
Taking the code, renaming to a .js file, and modifying it to this:

```ts
export const snapshot = {};

snapshot[`test 1`] = `"
bye"`;
console.log(snapshot)
```

...while ensuring that a \r newline is still used in the template literal.

![image](https://github.com/denoland/deno/assets/1609021/67a5f2e8-aa99-44f6-9486-ffd7b7b77c00)

Deno, Node, and Chrome all output `\n` in this scenario. I'm not sure what the correct behaviour is, but if all three of those do the same thing then maybe this is v8 behaviour and I'm not sure if we should or can do anything here. Overall, it's probably not worth any additional effort because people shouldn't be using `\r` line endings these days.

**Comment by OzzieOrca** [comment]
If it's the case that `\r` shouldn't be used, should Deno's std/csv `stringify` function stop using the CRLF format as its newline output? https://github.com/denoland/deno_std/blob/main/csv/stringify.ts#L318 Or is that still needed for some systems/CSV programs.

I first noticed this issue when trying to snapshot the output of csv stringify. Maybe an alternative would be for `assertSnapshot` to strip `\r` from the actual input before trying to compare to the imported version. That makes `assertSnapshot` less strict and would succeed silently if someone was trying to care about a `\r` existing. But an error and no way to make the snapshot succeed (aside from manually stripping `\r` chars before) seems worse.

**Comment by lucacasonato** [comment]
I think this behaviour is correct. std should generate snapshot files that do not end with `\r` in a string on a line.
