### ISSUE TITLE
`npm:create-docusaurus` ReferenceError: require is not defined

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#22732]
```
$ deno run -A npm:create-docusaurus@latest my-website classic
[INFO] Creating new Docusaurus project...
[INFO] Installing dependencies with npm...
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
error: Uncaught (in promise) ReferenceError: require is not defined
if (require.main !== module) {
^
    at file:///home/divy/.cache/deno/npm/registry.npmjs.org/shelljs/0.8.5/src/exec-child.js:1:1
[ERROR] Dependency installation failed.
[INFO] The site directory has already been created, and you can retry by typing:

  `cd my-website`
  `npm install`
```

**Comment by lucacasonato** [comment]
This still happens.

**Comment by kt3k** [comment]
The below snippet looks like a smaller reproduction of the same issue:

```js
import shelljs from "npm:shelljs";
shelljs.exec("echo 1")
```

`shelljs.exec` tries to call `child_process.execFileSync` with `shelljs/src/exec-child.js` as an entrypoint, and it seems handled as ESM instead of CJS.
https://github.com/shelljs/shelljs/blob/8a960da8383666024bfdb2eff709a4fdf66333ee/src/exec.js#L100

The issue seems disappearing if I use byonm settings (with package.json and node_modules)

**Comment by kt3k** [comment]
`in_npm_package` check of `ManagedCliNpmResolver` seems returning false in the above case.

In that check function, `root_dir_url` becomes `file:///Users/kt3k/Library/Caches/deno/npm/registry.npmjs.org/shelljs/0.8.5/node_modules/` in the above situation, and that directory doesn't exist. So this check never returns true for any specifier in the above invocation..
https://github.com/denoland/deno/blob/9f27bf9144b114bc4d7d9da77f7d55486e3d2c78/cli/npm/managed/mod.rs#L556
