### ISSUE TITLE
jsr: no slow types requirement might be dangerous to long term type quality

### ISSUE THREAD

**Issue by bjesuiter** [denoland/deno#23127]
Hi There! 

Some time ago we had some discussion in the twitter/youtube/twitch dev community about 
"inferred types vs. explicit types". 

I was on the "explicit types are better" camp first. 
But then I saw this video by @t3dotgg: [Be Careful With Return Types In TypeScript](https://www.youtube.com/watch?v=I6V2FkW1ozQ) and after that I was convinced that explicit return types can be really harmful, especially when editing a codebase with multiple people who aren't able to correctly type most functions yet, since they're too fresh in TS for that. 

I'm worried that this requirement might lead to a lot packages with wrongly exported typings which don't match the real implementation of functions.

**Comment by 0f-0b** [comment]
I disagree with all major points against explicit type annotations mentioned in that video.

> Point 1: Type annotations may be imprecise.
>
> ```ts
> type Result<T> =
>   | { status: "ok"; value: T }
>   | { status: "error"; error: Error };
>
> function contrivedStrict(): Result<string> { // with explicit return type
>   return Math.random() > 0.5
>     ? { status: "ok", value: "yay" }
>     : { status: "error", error: new Error("oopsies") };
> }
>
> const resultStrict = contrivedStrict();
> if (resultStrict.status === "ok") {
>   resultStrict.value;
>   //           ^?  string, instead of the more precise "yay"
> }
>
> function contrivedAsConst() { // without explicit return type
>   return Math.random() > 0.5
>     ? { status: "ok", value: "yay" } as const
>     : { status: "error", error: new Error("oopsies") } as const;
> }
>
> const resultAsConst = contrivedAsConst();
> if (resultAsConst.status === "ok") {
>   resultAsConst.value;
>   //            ^?  "yay"
> }
> ```

What if a future version of `contrivedAsConst` returns a string other than `"yay"`? The maintainer would possibly fail to notice that the inferred return type had changed (it is not even written in the source code) and forget to increment the major version. Downstream code, having been relying on `value` being `"yay"` since it had been part of the return type, would break.

Had the return type been explicitly annotated as in `contrivedStrict`, such a compatibility hazard would not have been introduced. The return type is the perfect place to document what properties of the returned value can be relied upon.

> Point 2: Type annotations may be incorrect.
>
> ```ts
> type User = {
>   username: string;
>   email: string;
> };
>
> const getUserStrict = (): User => {
>   const user = {
>     username: "user",
>     email: "fake@mail.com",
>     password: "PLS_DONT_LEAK_ME",
>   };
>   return user;
> };
>
> const userStrict = getUserStrict();
> userStrict.password;
> //         ^?  Property 'password' does not exist on type 'User'.
> ```

It is not incorrect. In TypeScript's [structural type system](https://github.com/microsoft/TypeScript/wiki/FAQ#what-is-structural-typing), a value has type `{ username: string; email: string }` if it has properties named `username` and `email` with `string` values. Nothing about the presence or absence of `password` is said. One can still access `password` if they prove that the property exists.

```ts
if ("password" in userStrict && typeof userStrict.password === "string") {
  userStrict.password;
  //         ^?  string
}
```

> Point 3: Overloads are broken.
>
> ```ts
> type User = {
>   role: "user" | "admin";
> };
>
> export function getUserOverrides(id: string, role: "user"): { role: "user" };
> export function getUserOverrides(id: string, role: "admin"): { role: "admin" };
> export function getUserOverrides(
>   id: string,
>   role: "user" | "admin",
> ): User | null {
>   if (role === "user") return { role: "admin" };
>   if (role === "admin") return { role: "user" };
>   return null;
> }
>
> const userOverride = getUserOverrides("1", "user");
> userOverride.role;
> //           ^?  "user", should be "admin"
> ```

This is a point against overloads, not type annotations.

**Comment by lucacasonato** [comment]
Let's continue this discussion on discord. This is not a good place for long form discussions like this. https://discord.gg/deno
