### ISSUE TITLE
deno compile: weird race conditon ?

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#23136]
deno 1.42.0+bca0fe1 (canary, x86_64-unknown-linux-gnu)

Compiling a fresh project:
- doesn't work if used with  permissions set in the cli (like--allow-all)
- but works if I don't set permission on the cli, and just hit yes to all permissions at runtime

The problem seems to happen when running esbuild

To reproduce:
- deno run -A  https://fresh.deno.dev/
- cd fresh-project

This loads the page, but some js scripts don't load so there is no interactivity
- deno compile -A  main.ts && ./fresh-project 

This works as expected, but you have to accept all permission prompts
- deno compile main.ts && ./fresh-project  

Demo
[Screencast from 2024-03-30 06-38-44.webm](https://github.com/denoland/deno/assets/22427111/c7ee229b-958a-4b71-a52b-d4fa1c7d8971)

**Comment by lucacasonato** [comment]
This is because `fresh` shells out to `esbuild` and `deno` binary if `--allow-run` is given (this improves performance). If `--allow-run` is not given explicitly, we fall back to using a WASM build of esbuild, and an in memory loader.

The shelling out to `deno` when using `--allow-run` is not passed does not work for `deno compile`.

I suggest you open an issue on fresh. This is not a Deno bug.
