### ISSUE TITLE
LSP: Formatting ignores passed formatting options

### ISSUE THREAD

**Issue by mkhl** [denoland/deno#23257]
Version: Deno 1.42.0

When the Deno LSP receives a `textDocument/formatting` request, it receives an optional set of formatting options with that request, see [DocumentFormattingParams](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentFormattingParams) and [FormattingOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions) in the LSP spec.

The request gets handled by [the formatting function](https://github.com/denoland/deno/blob/f9f37963b70948f51334ded1657546e614cfa0a6/cli/lsp/language_server.rs#L1479), and it receives the DocumentFormattingParams but only handles the contained reference to the text document and ignores the formatting options, instead generating its own formatting options for the document.

The expected behavior should be that it instead respects the received formatting options and formats the document according to them, falling back on defaults it provides itself.

**Comment by heygarrett** [comment]
Expanding on my comment [here](https://github.com/denoland/vscode_deno/issues/1140#issuecomment-2481453680), the editor settings taking priority over the project configuration feels backwards. When I use Prettier or Biome, my editor formats according to the project configuration, and I'm sure most people would expect deno to function similarly. Otherwise, one would need to manually change their editor settings to match the project configuration for _each_ project they're working on.
