### ISSUE TITLE
Deno running typescript error Module not found file:///var/lib/snapd/void/file.ts

### ISSUE THREAD

**Issue by mrgebra1** [denoland/deno#23286]
Version: Deno 1.40.3

I am new deno user but I got an error when run typescript file with deno.

I installed deno on ubuntu 22.04 via snap

``deno run file.ts``

`` error: Module not found "file:///var/lib/snapd/void/class.ts" ``

my TS file is on /var/www/html/typescript-OOP/class.ts but why the error is on /var/lib/snapd/void/class.ts

this my testing code in  ``/var/www/html/typescript-OOP/00class.ts ``

```
class Animal {

}


const fish = new Animal();
const bear = new Animal();

console.log(fish);
console.log(typeof Animal);
```

**Comment by jsejcksn** [comment]
@lucacasonato It would benefit the community if a dialog were opened with Luke, the publisher of the snap package, so that it can either be removed from the snap store or — if possible — fixed to work according to expectations.

Refs:

- Snap store URL: https://snapcraft.io/deno
- Associated repository: https://github.com/Lukewh/deno-snap
- Publisher info:
  - Snapcraft: https://snapcraft.io/publisher/lukewh
  - GitHub: https://github.com/Lukewh
