### ISSUE TITLE
`--doc` option seems disabling type checking

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#23430]
Save the below script as `test.ts`, and then `deno test` throws type error at `const a`, but `deno test --doc` doesn't throw type error.

```ts
/**
 * ```ts
 * ```
 */
function foo() {}

const a: string = 1;
```

If I remove the code block part in the jsdoc, then this issue doesn't happen.

Version: Deno 1.42.4

**Comment by crowlKats** [comment]
After some searching, we found out that the issue is a regression from https://github.com/denoland/deno/pull/22854. This is because of https://github.com/denoland/deno/blob/b3d7df55357ea6fc6f5141b64a9638ddb39b0f63/cli/module_loader.rs#L116, and because the `prepare_module_load` function is called twice, once for doc files and once for actual files, it does not type check because on second call `has_type_checked` is true.
