### ISSUE TITLE
[discussion] Deno.Open('/dev/urandom')

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2352]
As `everything is a file` in Linux when we want to read `/dev/urandom` we need to grant permission to it. Which in a case fits the philosophy of Deno, but in another case is problematic because reading `urandom` does not make a security breach. Same for `/dev/null`. Which i faced in : 
https://github.com/denoland/deno/pull/2152

What's your thought about it?

**Comment by rsp** [comment]
Making random (no pun intended) exceptions for certain paths like /dev/urandom which happen to be safe to open on some systems can be problematic if hardcoded in `deno` itself.

E.g. writing to /dev/null on Windows would mean that programs could write a file and fill up the hard drive because this is not a special file there. When we add /dev/urandom then someone could want real random numbers from /dev/random and reading it could exhaust the system entropy and DoS the system.

It would be hard to have a set of permissions that is good once and for all, but having a possibility to do something like this seems like a useful feature.

But maybe instead of hardcoding the permissions (hard to make it universal enough to make everyone happy plus someone would want a switch to turn it off) maybe a switch like `--perms=@file.txt` where the contents of file.txt would be:
```
--allow-read=/dev/urandom
--allow-read=/dev/null
--allow-write=/dev/null
--allow-read=/dev/fd
... other common things you need ...
```
(just normal command-line options would mean no new syntax but of course it could be a yaml or json or whatever just as well)

This could be a general `--options=@file` to get command line options from a file.

Then you could have your own favorite set of options to use in your projects, you could have it on GitHub, other people could share it, modify it for their own use, without imposing those permissions on anyone else.

(the '@' is just an example, inspired by `curl` to read data from a file for some options)

**Comment by zekth** [comment]
> E.g. writing to /dev/null on Windows would mean that programs could write a file and fill up the hard drive because this is not a special file there. When we add /dev/urandom then someone could want real random numbers from /dev/random and reading it could exhaust the system entropy and DoS the system.
> 

Equivalent of `/dev/null/` on windows is `NUL` which works perfectly.

But i agree with you about issues with hardcoded permissions. Also if not implemented on some systems, we can do like some functions in `deno_std`: use `unimplemented()`

having `--perms=@file.txt` sets could be replaced by having aliases for example.

**Comment by zekth** [comment]
Closing as it stales
