### ISSUE TITLE
Finalization not working

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#23533]
I can't get the gc to run a destructor..
At first I thought that I'm making some kind of mistake here.. 

I was trying to make a Drop trait
```ts

abstract class Drop {
    #registry=new FinalizationRegistry((_)=> this.drop());
    constructor() {
        this.#registery.register(this, "");
    }
    protected abstract drop(): void;
}

class Foo extends Drop {
    protected drop(): void {
        console.log("Foo was dropped");
    }
}

const _foo=new Foo();

```

Then I tried to copy some code that seemed to work from a conf and also mdn but the destructor was never called..

```ts

const obj={ xd: "xd" };

const registry=new FinalizationRegistry (heldValue=> console.log(`${heldValue} was dropped`));

registery.register(obj,obj.xd);
```

**Comment by dsherret** [comment]
Garbage collection is not guaranteed to run and there's no reason for it to run for this program that barely uses any memory and then exits. I would recommend not relying on the finalization registry (see the ["Avoid where possible" section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry#avoid_where_possible)) and instead use explicit resource management: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management

**Comment by andreubotella** [comment]
In fact, it's not only that GC is not guaranteed to work -- in this example it will *never* work. GC only happens when an object has no remaining references left, and `() => this.drop()` keeps a reference to the object alive.

In fact, `FinalizationRegistry` callbacks will only be called *after* the object is GC'd and destroyed, so you can't possibly call a method of the object at that point.

**Comment by kakashi-69-xd** [comment]
> In fact, it's not only that GC is not guaranteed to work -- in this example it will *never* work. GC only happens when an object has no remaining references left, and `() => this.drop()` keeps a reference to the object alive.
> 
> In fact, `FinalizationRegistry` callbacks will only be called *after* the object is GC'd and destroyed, so you can't possibly call a method of the object at that point.


Would it work if I use a `WeakRef`?

**Comment by andreubotella** [comment]
> Would it work if I use a `WeakRef`?
> 
> please explain..

No, it wouldn't. A `WeakRef` would keep a reference to the object that would not keep it from being GC'd. However, *once the object is GC'd, you cannot access it*. Calling `deref()` on the weakref at that point would return `undefined`, *because the object no longer exists*.

Simply put, there's no 100% equivalent to a C++ destructor or a Rust `Drop` trait in JS. The closest you can get is the new [`using` proposal (a.k.a. explicit resource management)](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#using-declarations-and-explicit-resource-management), but you could have code outside of the scope that could still have access to the object after the "destructor".

**Comment by kakashi-69-xd** [comment]
> > Would it work if I use a `WeakRef`?
> > please explain..
> 
> No, it wouldn't. A `WeakRef` would keep a reference to the object that would not keep it from being GC'd. However, _once the object is GC'd, you cannot access it_. Calling `deref()` on the weakref at that point would return `undefined`, _because the object no longer exists_.
> 
> Simply put, there's no 100% equivalent to a C++ destructor or a Rust `Drop` trait in JS. The closest you can get is the new [`using` proposal (a.k.a. explicit resource management)](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#using-declarations-and-explicit-resource-management), but you could have code outside of the scope that could still have access to the object after the "destructor".

I tried this and this one just works but it looks really gross.. any suggestions?

```ts
const globalRegistry=new Map<number,FinalizationRegistry<void>>();

abstract class Drop {
  constructor() {
    const id=globalRegistry.size;
    const dropRef=new WeakRef(this.drop);

    const registry=new FinalizationRegistry(()=> {
      globalRegistry.delete(id);
      dropRef.deref()!();
    });

    registry.register(this,undefined);
    globalRegistry.set(id,registry);
  }

  protected abstract drop(): void;
}

class XD extends Drop {
  protected drop(): void {
    console.log("XD was dropped");
  }
}

for(let i=0;i<100000;i++) {
  const xd=new XD();
  console.log(xd);
}

```

**Comment by dsherret** [comment]
It only "works" because because `this.drop` is a reference to the function on the prototype since it's doing `new WeakRef(this.drop)`. If you try using `this` in the `drop` method it won't be the `XD` instance.

Highly recommend just using explicit resource management.

**Comment by kakashi-69-xd** [comment]
> It only "works" because because `this.drop` is a reference to the function on the prototype since it's doing `new WeakRef(this.drop)`. If you try using `this` in the `drop` method it won't be the `XD` instance.
> 
> Highly recommend just using explicit resource management.

you don't use the `using` just to initialize a `Vec`
