### ISSUE TITLE
Deno hangs after succesfully executing npm-package library call

### ISSUE THREAD

**Issue by aukeroorda** [denoland/deno#23727]
```sh
> deno --version
deno 1.41.3 (release, x86_64-apple-darwin)
v8 12.3.219.9
typescript 5.3.3
```

### MRE
Can be found at: https://github.com/aukeroorda/mre-deno-hang/tree/main

1. Verify the contents of the repo
2. Install the `paper-js` library as specified in the package file:
    ```sh
    npm install
    ```
3. Run deno:
    ```sh
    deno run mre.ts
    ```
4. Allow reading of `node_modules`: `y`
5. Observe that code executes to the end of the `mre.ts` script, but Deno hangs.

__Note__: 
Deno doesn't hang anymore if the following lines 20 and 21 are commented out: https://github.com/aukeroorda/mre-deno-hang/blob/6c3d8d0f313141bff39ffc0906780189668b055d/mre.ts#L20-L21

### Inspecting using chromium
I've tried to inspect what is going on with this library call using the chromium debugger, but I can't really see much, as the call gets 'hijacked' by a call to `node:timers` `setInterval()` function, and I lose the trace of the library function call here.

**Comment by lucacasonato** [comment]
I presume this is related to NAPI, as paper uses `node-canvas`.

**Comment by kt3k** [comment]
Deno fails to simulate Node.js in paper.js because it uses `self` global variable to detect Node.js https://github.com/paperjs/paper.js/blob/92775f5279c05fb7f0a743e9e7fa02cd40ec1e70/src/init.js#L32

(In Deno, `paper.agent` becomes `{ platform: undefined }`, in Node.js it is:

```js
{
  platform: 'mac',
  mac: true,
  version: '20.15.0',
  versionNumber: 20.15,
  name: 'node',
  node: true
}
```

If the platform is not Node.js, `view._autoUpdate` becomes true:

https://github.com/paperjs/paper.js/blob/92775f5279c05fb7f0a743e9e7fa02cd40ec1e70/src/view/View.js#L120

If `view._autoUpdate` is true, it calls `view.requestUpdate` method:

https://github.com/paperjs/paper.js/blob/92775f5279c05fb7f0a743e9e7fa02cd40ec1e70/src/item/Project.js#L97

Which calls polyfilled version of `requestAnimationFrame` in Deno:

https://github.com/paperjs/paper.js/blob/92775f5279c05fb7f0a743e9e7fa02cd40ec1e70/src/view/View.js#L225

Which internally calls `setInterval`, which is never cleared.

https://github.com/paperjs/paper.js/blob/92775f5279c05fb7f0a743e9e7fa02cd40ec1e70/src/dom/DomEvent.js#L120

One of workarounds is deleting `globalThis.self` before importing `paper`:

```ts
delete globalThis.self;
const paper_import = await import("paper");
const paper = paper_import.default;
globalThis.paper = paper;
paper.setup();
const pathdata = "M 0 0 C 0 10 10 10 10 0 z"; 
const path = new paper.Path(pathdata);
console.log({ path }); 
console.log(paper.agent);
```

The above script exits immediately and prints `paper.agent` with `node` field set to `true`.

**Comment by kt3k** [comment]
One solution might be hiding `globalThis.self` while evaluating npm packages. WDYT?

**Comment by bartlomieju** [comment]
Seems like a reasonable solution, `self` is not defined in Node.js

**Comment by aukeroorda** [comment]
Hi - 
Just running this again, but on my end it still hangs after execution, using the same MRE as stated earlier. This is using the updated deno version:
```
> deno --version
deno 1.43.5 (release, x86_64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5
```
so I'm not sure if the PR to fix this issue actually fixes it.

Using `delete globalThis.self;` before the import does fix it in the MRE though!

**Comment by marvinhagemeister** [comment]
@aukeroorda Deno `v1.43.5` is a bit older. The latest version at the time of this writing is `v1.45.5`

**Comment by aukeroorda** [comment]
Thanks for informing me! I thought I updated recently, but apparently not that recently! It is indeed solved.
Thanks
