### ISSUE TITLE
Deno Node Compatibility WebSockets Not Working

### ISSUE THREAD

**Issue by phant0m2290** [denoland/deno#23959]
Versions:
- deno 1.43.6 (release, x86_64-pc-windows-msvc)
- v8 12.4.254.13
- typescript 5.4.5
- npm:discord.js 14.15.2

When trying to log my discord bot in using the discord.js npm package it returns the following error:
```
error: Uncaught (in promise) SyntaxError: Invalid protocol value.
    at new WebSocket (ext:deno_websocket/01_websocket.js:203:13)
    at WebSocketShard.internalConnect (file:///C:/Users/titul/AppData/Local/deno/npm/registry.npmjs.org/@discordjs/ws/1.1.0/dist/index.js:675:24)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

When trying to log my bot in using node it works fine. seems like something with the websocket client from node not working in deno.
ive tried changing a bunch of things and adding the `--allow-all` parameter but nothing helped

**Comment by Iuriiiii** [comment]
Do you have a code example or something to use as a ref?

**Comment by phant0m2290** [comment]
> Do you have a code example or something to use as a ref?

My issue is in the title and not hard to understand how to recreate it. But here you go

Import `npm:discord.js`
Create a bot on https://discord.con/developers
Create an instance of the Client class imported from discord.js
add at least one intent. For example as argument `{intents:["Guilds"]}`

And run the `login` function on the client instance using the bot token generated at https://discord.con/developers as the argument

**Comment by guy-borderless** [comment]
Unsure if related. 
I also get a lot of instability with puppeteer.connect()
Code is essentially 
```javascript 
import puppeteer from "puppeteer-core" // npm:puppeteer-core

const BROWSER_WS =
    "wss://...@brd.superproxy.io:9222"

  const browser = await puppeteer.connect({
    browserWSEndpoint: BROWSER_WS,
  })
```
This usually fails with 'tcp connect times out'
It mostly hangs on `.connect()`, sometimes on following calls, and rarely it works. Works fine on node-js.

**Comment by kt3k** [comment]
The same issue was reported here https://discord.com/channels/222078108977594368/1237471430887604375/1239037602699546645 (needs discord.js server invite to see it https://discord.gg/djs)

and it seems fixed by this PR on d.js side https://github.com/discordjs/discord.js/pull/10271

@phant0m2290 Can you test your script again with the latest discord.js version?

Note: Discord.js switch to `fetch` and `WebSocket` globals for Deno compat. https://github.com/discordjs/discord.js/pull/9683 https://github.com/denoland/deno/issues/19766#issuecomment-2312378129 I don't think node compat is involved with discord.js compatibility anymore.

**Comment by phant0m2290** [comment]
Yes, ive been successfullly working with discord.js since a few weeks now
