### ISSUE TITLE
Access-Control-Allow-Methods not reflected on the response header when integrated with Hono

### ISSUE THREAD

**Issue by hh54188** [denoland/deno#24086]
Version: Deno 1.43.6 (release, aarch64-apple-darwin)

My application was written with Hono and I want to manage CORS config with Hono cors middleware. Here is my major code:

```javascript
const app = new Hono()

app.use('/api/*', cors({
    origin: '*',
    allowMethods: ['GET', 'POST']
}))

Deno.serve({ port: Deno.env.get("PORT") }, app.fetch)
```

However, only access-control-allow-origin shown in the response header, Access-Control-Allow-Methods is missing

**Comment by marvinhagemeister** [comment]
This is not an issue with Deno. Hono only sets those headers when an `OPTIONS` request is made, see their code https://github.com/honojs/hono/blob/a036d7030710b75464fe5d56d52809c56287134a/src/middleware/cors/index.ts#L103-L112 

```sh
$ curl -i -X OPTIONS http://localhost:4000/api/foo
HTTP/1.1 204 No Content
access-control-allow-methods: GET,POST
access-control-allow-origin: *
date: Mon, 03 Jun 2024 08:02:30 GMT
```

Please file issues and usage questions about Hono in [Hono's issue tracker](https://github.com/honojs/hono) instead of here in the Deno issue tracker in the future.
