### ISSUE TITLE
Improvements to installation script (`https://deno.land/install.sh | sh`) for Deno 2.0

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#24157]
See title - I'm worried about breaking changes where people have used the install command in their bash scripts. It probably makes sense to have a new URL for for v2 - e.g. 
```
curl -fsSL https://deno.land/install-v2.sh | sh
```
That said, a disadvantage of this is that there are questions/docs/etc. all over the internet which use the original URL.

A couple of tangential asides:
 * Currently the installation page doesn't show how to download a specific version of Deno. It looks like I need to first install the latest version, then 'upgrade' back to an older version. This makes scripts slower than if there were a way to directly install a specific version.
 * This is probably already the case, but the default install location should also always be kept backwards compatible - again, for scripts.

**Comment by lucacasonato** [comment]
Thanks for raising this. We're not sure yet about what we'll do here.

**Comment by josephrocca** [comment]
No problem - also, if changes are being made here, then I think it'd be a great time to add this change too, so that the install process is as simple as Bun/Rust/etc:

* https://github.com/denoland/deno/issues/22451

**Comment by bartlomieju** [comment]
We discussed this with @lucacasonato and @dsherret, here's what we agreed on:
- The install script will keep installing the latest stable version - which will be Deno v2.0 once it is released
- The script accepts and argument that allows to install a concrete version (eg. `curl -fsSL https://deno.land/install.sh 1.46.2 | sh`) so that doesn't require to download the latest to then downgrade. We can think about integrating it into https://deno.com (CC @josh-collinsworth @donjo).
- We can definitely improve the script to output relevant lines to `.bashrc`.

**Comment by ericlery** [comment]
> Thanks for raising this. We're not sure yet about what we'll do here.

Like mention in #25749 and related issues, the install script could leverage full semver notation to download the desired version.

The current script could end at Deno v1.* to keep compatibility of existing scripts as some form of `latest` but only for v1. Generally `latest` is bad for scripting that are not monitored frequently so it better end there.

We could then ask for `curl -fsSL https://deno.land/install.sh?version=^2 | sh` for 2.0.0 to <3.0.0

**Comment by bartlomieju** [comment]
I consider this issue completed now; @nathanwhit has added automatic update of shell profile files so for most cases manual intervention shouldn't be needed.
