### ISSUE TITLE
Can't make requests to Deno.serve in Jupyter from outside of notebook context

### ISSUE THREAD

**Issue by tlockney** [denoland/deno#24421]
Version: Deno 1.44.4+3324d72

Tested this against the latest canary build after @bartlomieju's latest [changes](https://github.com/denoland/deno/pull/24373) got merged with the hope that it would fix things. But sadly, it didn't. I've got a [full example shown in this gist](https://gist.github.com/tlockney/b3197ab22771ddaeb8bdc384c7873132). But for a brief description of the problem, when I run `Deno.serve` within a Jupyter notebook, I can call it just fine from within the notebook. Even from a curl command running thrugh `Deno.Command` within the notebook. But if I try the exact same command from my shell on the same machine running Jupyter, it just hangs. 

For additional context, I'm running my Jupyter instance under Pipx, but not in a docker container or anything else that I would expect to get in the way of any local network requests. Happy to provide any more details if helpful and happy to run any additional tests that might help debug the underlying issue.

**Comment by bartlomieju** [comment]
The problem at hand is that the "repl session" that the Jupyter kernel is using is not running in the background. We only spin the event loop when there are messages being exchanged. 

We need to have a tight loop like in the `cli/tools/repl/mod.rs`:
https://github.com/denoland/deno/blob/9776a13e33bc371a67f0d44925e2bf04dca159f1/cli/tools/repl/mod.rs#L101-L140
instead of only reacting to messages received from the notebook frontend here:
https://github.com/denoland/deno/blob/9776a13e33bc371a67f0d44925e2bf04dca159f1/cli/tools/jupyter/mod.rs#L351-L400
