### ISSUE TITLE
LSP doesn't resolve npm:stable-hash default export type  

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#24451]
Version: Deno 1.44.4

see the [example](https://github.com/guy-borderless/lsp-bug2) here
![1720244517](https://github.com/denoland/deno/assets/100129659/ac14fdfe-c081-4127-b9d0-991f2344d20d)
when go-to-definition on the function I see
```typescript
export default function stableHash(arg: any): string;
```
![1720244527](https://github.com/denoland/deno/assets/100129659/d61a72c5-9e0d-42e7-b8d0-2333f030430a)

**Comment by dsherret** [comment]
Part of the problem with this package is the types are wrong: https://arethetypeswrong.github.io/?p=stable-hash%400.0.4

**Comment by nayeemrmn** [comment]
https://github.com/denoland/deno/issues/25359#issuecomment-2335048531

If you add `{ "type": "module" }` to `package.json` and use the following tsconfig:
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.2.7"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18"
  }
}
```
You'll see the same diagnostics, and the same inconsistency with emit / runtime behaviour due to the incorrect types of `npm:stable-hash`. You can access the actual function with `stableHash.default` but that will give a false diagnostic unfortunately. Closing for now.
