### ISSUE TITLE
[bug] deno compile package.json file handling behavioral change on 1.45.0

### ISSUE THREAD

**Issue by jerome-benoit** [denoland/deno#24537]
Version: Deno 1.45.0

cli.js:
```js 
import { readFileSync } from 'node:fs'
 
const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url)))
```

`deno compile --allow-read --allow-sys --output=cli ./cli.js`

`./cli`

`error: Uncaught (in promise) NotFound: path not found: readfile '/tmp/deno-compile-tatami/tatami-ng-git/package.json'`

**Comment by dsherret** [comment]
In Deno <1.45.0, it would embed the absolute file paths into the binary. So say the file you have there is at the following path:

```
/home/david/my-project/cli.js
/home/david/my-project/package.json
```

Then you run `deno compile cli.js`. That will embed `/home/david/my-project/cli.js` into the binary in Deno < 1.45.0. That means, the code in the compiled binary in Deno <1.45 is essentially the following:

```ts
import { readFileSync } from 'node:fs'
 
const pkg = JSON.parse(readFileSync(new URL('./package.json', "file:///home/david/my-project/cli.js")))
```

So, it only works if that file exists on the target system like that, which isn't great. Now, `deno compile` doesn't store absolute paths in the binary and so relative to the fake paths it uses in a temp directory, it can't find that file anymore.

Instead of using `import.meta.url`, use `Deno.execPath()` instead to read files relative to the binary.

**Comment by dsherret** [comment]
Note for others: if you want to embed the package.json into the binary intself, you can use a JSON import:

```json
import pkg from "./package.json" with { type: "json" };
```

**Comment by jerome-benoit** [comment]
Then `deno compile` has a serious design issue: they're no way to specify a list of file expected to be streamlined in the resulting native OS binary. 

There's legitimate use of non JS code files required to run JS code.

**Comment by dsherret** [comment]
By "design issue" I think you mean "not implemented feature". Follow https://github.com/denoland/deno/issues/20885 for updates.
