### ISSUE TITLE
deno workspace: --filter or -r (recursive)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#24991]
With pnpm / bun workspace, there is a way to use --filter to select multiple packages or to select all packages `bun --filter '*'` or `pnpm -r` to run a task in all of them, typically `dev`, `build` or `start`.

Also, the -r flag is super convenient in `pnpm update -r -i` for recursively making interactive dependency updates across the entire workspace.

**Comment by iceglober** [comment]
I second this. I'm finding myself either having to create redundant tasks at the root level, or cd'ing into my packages for running tasks.

**Comment by birkskyum** [comment]
A good test for this functionality would be moving the repo below from pnpm workspace to npm workspace, building all the packages and running an example:
https://github.com/histoire-dev/histoire

**Comment by shanipribadi** [comment]
# Run tasks/scripts in specific package in a workspace
1. `pnpm  --filter pkgA run command
2. `npm run command --workspace=pkgA`
3. `yarn workspace pkgA run command`
4. `bun --filter pkgA run command`

# Run tasks/scripts in all packages under the workspace
1. `pnpm run command -r`
2. `npm run command --workspaces`
3. `yarn workspaces foreach run command`
4. `bun --filter ‘*’ run command`

# Run tasks/scripts in multiple selected packages under the workspace
1. `pnpm run command -r --filter <pattern>
2. `npm run command --workspace=pkgA --workspace=pkgB`
3. `yarn workspaces foreach --from <pattern> run command`
4. `bun --filter <pattern> run command`

Summary
1. bun follows pnpm approach of using `filter`, yarn also has glob pattern support using the `from` arg
2. npm have explicit workspace arg selection that support multiple args
3. yarn execute commands in order of dependencies, couldn't find docs for execution order for bun/pnpm/npm

**Comment by wjutsum** [comment]
Having come from heavily using yarn workspaces, this would be very useful.  

This would probably fix an issue I'm having at the moment whereby the `.env` file for the deno process needs to be in the directory from which I am running the command. This means that if I have multiple apps needing to use the same environment variable, I have to duplicate the .env rather than have one in the root of the project.

**Comment by shanipribadi** [comment]
@wjutsum for your use case I don't think this particular issue is really meant to solve your issue with .env placement,

so, for npm, pnpm, bun and yarn, when you run `npm run  --workspaces command` (or the respective commands for each tools)
the actual command is executed with the CWD in the individual workspace/package directory.

hence .env file will still need to be in the workspace/package directory, rather than putting it in the root workspace directory.

I'm assuming the main reason these tools switch their working directory to the commands in the individual pkgs is because many js libraries/frameworks "scripts"/tasks have the assumption that they're being run from within that particular package's directory.

workflow-wise I personally follow two approaches for dotenv in a workspace
1. root level .env, symlinked to various packages/pkgX/.env if I can share a common .env file for those packages
2. having unique packages/pkgX/.env for when certain package need it's own .env file config.
