### ISSUE TITLE
fetch doesn't follow redirects

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#2513]
Currently `fetch` doesn't support redirects - eg:
```ts
// current behavior
const response = await fetch("https://deno.land/std/colors/mod.ts")
response.status // 302
response.redirected // false
await Deno.readAll(response.body) // Uint8Array [] - empty!

// expected behavior
const response = await fetch("https://deno.land/std/colors/mod.ts")
response.status // 200
response.redirected // true
await Deno.readAll(response.body) // Uint8Array [...snip...] - should be filled with data

```

I did quick research and it seems that hyper client doesn't support redirects. I found this extension: https://github.com/srijs/rust-follow-redirects, but it's not very popular so I guess we'll need to handle that ourselves.

This feature is needed for installer denoland/deno_std#471.

**Comment by Fenzland** [comment]
As I see, check response.status and refetch manually is better than auto follow.

**Comment by bartlomieju** [comment]
My bad - of course you can configure fetch to either follow redirects or not with `fetch(url, {redirect: "follow"});` - but still Deno does not support this option now.

**Comment by TonyLianLong** [comment]
The `redirected` is unimplemented as in https://github.com/denoland/deno/blob/master/js/fetch.ts#L246. I can have a try at implementing this these two weeks when I'm free. This is a huge workload since `redirected` depends on unimplemented feature such as `type` and implementing `redirected` also requires the implementation of these features.
