### ISSUE TITLE
Bug: Types cannot call function in `@preact/preset-vite`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25529]
## Steps to reproduce

1. Run `deno init`
2. Run `deno install @preact/preset-vite`
3. Replace contents in `main.ts` with this:
  ```ts
  import preact from "@preact/preset-vite";
  console.log(preact());
  ```
4. Run `deno check main.ts`

Output:

```sh
$ deno check main.ts
Check file:///Users/marvinh/dev/test/deno-callable/main.ts
error: TS2349 [ERROR]: This expression is not callable.
  Type 'typeof import("file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/@preact/preset-vite/2.9.0/dist/types/index.d.ts")' has no call signatures.
console.log(preact());
            ~~~~~~
    at file:///Users/marvinh/dev/test/deno-callable/main.ts:2:13
```

Contents of the resolved definition file:

```ts
declare function preactPlugin({ devtoolsInProd, devToolsEnabled, prefreshEnabled, reactAliasesEnabled, prerender, include, exclude, babel, jsxImportSource, }?: PreactPluginOptions): Plugin[];
export default preactPlugin;
export { preactPlugin as preact };
```

So it's definitely typed as a function.

Version: Deno 2.0.0-rc.1+ce1d668

**Comment by dsherret** [comment]
This isn't a bug. The same thing happens when calling from ESM in Node.

```
> cat tsconfig.json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "skipLibCheck": true
  }
}
> cat main.mts
import preact from "@preact/preset-vite";
console.log(preact());
> npx tsc
> npx tsc
main.mts:2:13 - error TS2349: This expression is not callable.
  Type 'typeof import("V:/scratch/node_modules/@preact/preset-vite/dist/types/index")' has no call signatures.

2 console.log(preact());
              ~~~~~~


Found 1 error in main.mts:2
```

The problem here is that the package is sharing its ESM and CJS types in a separate types directory where the types are defined as CJS based on its closest package.json. So TypeScript from ESM detects these are CJS types and requires accessing it on the `default` property.

To fix the issue, the package should have separate typescript declarations for CJS and ESM. (See how the types for ESM are masquerading as CJS https://arethetypeswrong.github.io/?p=%40preact%2Fpreset-vite%402.9.0)
