### ISSUE TITLE
deno bundle doesn't work with import.meta

### ISSUE THREAD

**Issue by ry** [denoland/deno#2553]
```
~/src/deno_std> deno bundle test.ts

file:///Users/rld/src/deno_std/archive/tar_test.ts:91:11 - error TS1343: 
The 'import.meta' meta-property is only allowed using 'ESNext' for 
the 'target' and 'module' compiler options.

91 runIfMain(import.meta);
             ~~~~~~~~~~~

```

**Comment by kitsonk** [comment]
Yeah, I am not sure of an easy way around that, because any bundle is not going to be an ESM module.  We could "ignore" the TypeScript error when doing the bundle, but then would a bundled version have the right behaviours. Hmmm... 🤔

**Comment by kt3k** [comment]
What is the expected behavior for this?

Should we replace `import.meta` with something like the below?

```ts
({ url: "file:///path/to/file.js", main: false })
```

**Comment by kitsonk** [comment]
Hmmm... Possibly...  Just checking with recent versions of TypeScript and `import.meta` works under SystemJS modules, and that is the module format we are going to have to move to for bundling in order to support TLA (because AMD is likely to never support it).  It might "just work" but our SystemJS loader will need to supply it base on what the down-emit look like.

**Comment by kitsonk** [comment]
So this:

```ts
declare function runIfMain(arg: any): void;

runIfMain(import.meta);
```

Emits as this for System, which I already have a branch where I am trying to move bundling to System and supply the context, so just need to supply the right value:

```js
System.register([], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            runIfMain(context_1.meta);
        }
    };
});
```
