### ISSUE TITLE
Worker.onmessage overriding `this`

### ISSUE THREAD

**Issue by notroid5** [denoland/deno#25564]
Version: Deno 1.46.3

`main.ts`
```typescript
class Class {
    worker: Worker

    constructor() {
        this.worker = new Worker(import.meta.resolve('./worker.ts'), { type: 'module' })
        this.onmessage()
        this.worker.onmessage = this.onmessage
    }

    onmessage() {
        // console.log({ this: this })
        this.test()
    }

    test() {
        console.log('success')
    }
}

const test = new Class()

```

`worker.ts`
```typescript
(self as unknown as Worker).postMessage('message')
```

Expected result:
```
success
success
```
Actual result:
```
success
error: Uncaught TypeError: this.test is not a function
        this.test()
             ^
    at Worker.onmessage (file:///[redacted]/main.ts:12:14)
    at Worker.wrappedHandler (ext:deno_web/02_event.js:1401:12)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
    at invokeEventListeners (ext:deno_web/02_event.js:801:5)
    at dispatch (ext:deno_web/02_event.js:658:9)
    at Worker.dispatchEvent (ext:deno_web/02_event.js:1043:12)
    at Worker.#pollMessages (ext:runtime/11_workers.js:253:12)
    at eventLoopTick (ext:core/01_core.js:175:7)
```
If a method is called by the `onmessage` event, it overrides `this` from `Class`to `Worker`.
This can be seen by logging `this` within `onmessage`.
Same error if you comment `this.onmessage()` and add the parameter `_event: MessageEvent` to the `onmessage` method.
It does not depend on the method names.

**Comment by notroid5** [comment]
Apparently, it works if you replace the assignment with the actual code (but it cannot be reused like this):
```typescript
    this.worker.onmessage = () => {
        // console.log({ this: this })
        this.test()
    }
```
Or if the method is called within the event:
```typescript
    this.worker.onmessage = () => {
        this.onmessage()
    }
```

**Comment by lucacasonato** [comment]
This is expected behaviour for web event handling. When you assign a function to a `on*` event callback, the callback is called with `this` set to the event target that fired the event (in your case `Worker`). This is how events behave in browsers too: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#the_value_of_this_within_the_handler.

The behaviour that you want, is to bind `this` to the current `Class`. You can do this using the `Function.prototype.bind` method, like this:

```diff
-        this.worker.onmessage = this.onmessage
+        this.worker.onmessage = this.onmessage.bind(this)
```

This will ensure that the onmessage callback is always called with the `Class` as `this`, instead of the `Worker`.
