### ISSUE TITLE
LSP: `textDocument/completion` hangs starting in version 1.43

### ISSUE THREAD

**Issue by aaronhuggins** [denoland/deno#25610]
Version: Deno 1.43, 1.44, 1.45, 1.46

Prior to version 1.43, the following code worked as expected and provided a completion response. Starting at 1.43, the response for a `textDocument/completion` just hangs, holding up the parent process.

This code snippet is for reproduction purposes.

```typescript
import * as rpc from "npm:vscode-jsonrpc@8.2.1/node.js";
import { Readable, Writable } from "node:stream";

const uri = "file:///stub.ts";
const text = "console.";
const languageId = "typescript";
const command = new Deno.Command(Deno.execPath(), {
    args: ["lsp"],
    stderr: "null",
    stdin: "piped",
    stdout: "piped",
});
const process = command.spawn();
const connection = rpc.createMessageConnection(
    new rpc.StreamMessageReader(Readable.fromWeb(process.stdout as any)),
    new rpc.StreamMessageWriter(Writable.fromWeb(process.stdin)),
);

connection.listen();

const res = await connection.sendRequest("initialize", {
    processId: Deno.pid,
    capabilities: {},
    rootUri: null,
    clientInfo: {
        name: "example",
        version: "0.10.11",
    },
    locale: "en",
    initializationOptions: {
        enable: true,
    },
});

console.log(res);

await connection.sendNotification("textDocument/didOpen", {
    textDocument: {
        uri,
        text,
        version: 1,
        languageId,
    },
});

const res2 = await connection.sendRequest("textDocument/completion", {
    textDocument: { uri },
    position: { line: 1, character: 8 },
    context: { triggerKind: 1 },
});

console.log(res2);

connection.end();
process.kill();
```

**Comment by nayeemrmn** [comment]
You have to send the [`initialized`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialized) notification after receiving the response to `initialize`. This unblocks the rest of the language server. We do this because the proper pull-based configuration (though it's not really applicable to your client) cannot be fetched until the `initialized` handler and we want to make sure it's incorporated before processing other requests. See https://github.com/microsoft/language-server-protocol/issues/567#issuecomment-2085131917.

Working as intended.

**Comment by aaronhuggins** [comment]
Thanks, Nayeem! This appears to be a gap in the protocol docs, as the
language for the client sending initialized notification is “may” and not
“must”. I’ll follow up there for clarification.
