### ISSUE TITLE
suggestion: please crib ideas or code from mdrb for markdown execution

### ISSUE THREAD

**Issue by andrewbrey** [denoland/deno#25747]
I just read the Deno 2.0 RC announcement post and I was so stoked to see the execution of code blocks in Markdown files. I wrote a Deno cli called **mdrb** (https://github.com/andrewbrey/mdrb) which provides this functionality with a handful of other niceties on top. I would be honored if you "stole" some of my ideas or implementation to bring into Deno!

The goals of my project and what Deno want's may not be exactly the same, but I wanted to make the existence of this project known to the Deno authors in case it could provide inspiration or, maybe just maybe, some free code :)

Thanks and congrats on Deno 2!

Also, feel free to close this issue - I know I didn't ask for anything particular or necessarily immediately actionable in here :)

**Comment by magurotuna** [comment]
@andrewbrey Thank you for the great suggestion! mdrb looks a very nice and sophisticated tool. What's particularly appealing to me is that dax is automatically available in snippets - this should be quite useful, though I don't think this idea is not something that the builtin `deno test --doc` could adopt because adding a dependency on an external library would result in circular dependency and make maintenance harder. 
Another feature that we could imitate is the "single" mode. Concatenating code blocks into one before execution would be convenient when we want to write, for example, all the needed `import` statements in the first code block, so that the rest blocks don't need to import them. 

Closing this issue for now, but we'll definitely acknowledge you when we implement a new feature based on your project. Thanks again!
