### ISSUE TITLE
`import { createServer } from "npm:http"` fails in a strange way

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#25925]
Version: Deno 2.0.0-rc.7

```ts
import { createServer } from "npm:http"
```

```
$ deno run main.ts
error: Could not resolve 'npm:http@0.0.1-security'.

Caused by:
    [ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/ib/Library/Caches/deno/npm/registry.npmjs.org/http/0.0.1-security/index.js' imported from 'file:///Users/ib/dev/scratchpad2/foo.ts'
```

This is really strange, because https://www.npmjs.com/package/http is just a "placeholder" package that contains only `package.json` file. I've no idea how Deno appends `-security/index.js` to the package specifier to import it.

**Comment by marvinhagemeister** [comment]
The latest version on npm of that package is tagged `0.0.1-security`. So it's their pre-release tag. The `index.js` is probably appended because the `package.json` has neither an `exports` property or a `main` property. I think in node this works because you'll write an unprefixed import like:

```ts
import { createServer } from "http"
```

...which will then automatically fall back to `node:http` internally.

**Comment by bartlomieju** [comment]
Discussed with @dsherret and there is nothing actionable for us to do. We considered special casing `npm:http` but decided not to as it's a very exotic use case.
