### ISSUE TITLE
`deno test --doc`: test don't compile if a named export is also the default export

### ISSUE THREAD

**Issue by lowlighter** [denoland/deno#26009]
deno 2.0.0-rc.9 (release candidate, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

```ts
/**
 * ```ts
 * console.log(Foo)
 * ```
 */
export class Foo {}
export default Foo
```

```
vscode ➜ /workspaces/deno $ deno test --doc test.ts 
Check file:///workspaces/deno/test.ts
Check file:///workspaces/deno/test.ts$2-5.ts
error: TS2300 [ERROR]: Duplicate identifier 'Foo'.
import Foo, { Foo } from "file:///workspaces/deno/test.ts";
       ~~~
    at file:///workspaces/deno/test.ts$2-5.ts:1:8

TS2300 [ERROR]: Duplicate identifier 'Foo'.
import Foo, { Foo } from "file:///workspaces/deno/test.ts";
              ~~~
    at file:///workspaces/deno/test.ts$2-5.ts:1:15

Found 2 errors.

**Comment by magurotuna** [comment]
Thanks for reporting. This is a good edge case that I didn't think about when I was implementing it. I think in that case we should prioritize named export over default export. I believe this should be a simple fix

**Comment by MohammadSu1** [comment]
@lowlighter Hi, I believe this issue is related to Deno 2.0.0 because I didn't encounter it in the previous version. I created a workaround to address it. First, I made a file using the same example you provided (export.ts, in my case). Then, I created a separate file to test whether it runs correctly (export_testing.ts). The key point is in importing the two exports from the export.ts file, which were imported using two different names. It works, as you can see in the following figures.
![export](https://github.com/user-attachments/assets/273d8bbf-98df-4bdd-b7b0-02cd5d52ff39)
![export_test](https://github.com/user-attachments/assets/3aa552ca-f8b3-4752-844e-6b7bb06228bc)
![test_pic](https://github.com/user-attachments/assets/65b81b5e-c8ea-4cd1-8dde-6c2265d4f8f2)

**Comment by MohammadSu1** [comment]
@lucacasonato Hi Luca, could you give me a hint on where to start solving this issue?

**Comment by magurotuna** [comment]
@MohammadSu1 FYI I've just started working on fixing this issue.
