### ISSUE TITLE
bug: `deno test --coverage` produces new files each time

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#26015]
```
deno 2.0.0-rc.10 (release candidate, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

`deno test --coverage` keeps producing more and more `.json` files with each execution. This seems to sometimes cause the `deno coverage --html` command to not display the correct data, getting confused with older files.

**Comment by lucacasonato** [comment]
This is expected. `deno test --coverage` generates new files every time, so that you can get coverage results even if your test suite is invoked as multiple `deno test` commands.

You either need to manually clear the `coverage/` directory before every run, or run `deno test --coverage --clean` (which will do the same thing).
