### ISSUE TITLE
Svelte `preview` server crashes when running in Deno

### ISSUE THREAD

**Issue by ylor** [denoland/deno#26115]
```
$ deno --version
deno 2.0.0 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```

`deno run dev` works as expected but when running `deno run build && deno run preview` it fails with `ERR_EMPTY_RESPONSE`. Works as expected in both node and bun.

Please let me know if you have any questions or need further info. Thanks to the devs for all their hard work!

Minimal sample repro project: https://github.com/ylor/deno-repro-svelte

**Comment by marvinhagemeister** [comment]
Can reproduce. These are the full steps:

1. Clone  https://github.com/ylor/deno-repro-svelte
2. Run `deno install --allow-scripts`
3. Run `deno run build && deno run preview`

**Comment by sspilleman** [comment]
Is this being worked on? I have the feeling the solution is to force "every package" to comply with the "node:" or "npm:" specifiers because deno needs it... It simply doesn't feel like "deno can be used as a drop-in replacement for node/bun" as stated in the "deno 2 release video/notes/etc." ... I'm ok with having issues, no probs at all... I like deno a lot, switched completely from nodejs and never looked back  I'm used to having issues with a lot of npm packages, been there, done that at all.... Just don't state node compat if it requires the node ecosystem to change their code...

**Comment by bartlomieju** [comment]
Yes, we reviewed it today during the meeting and will prioritize fixing Svelte compatibility.
