### ISSUE TITLE
node_modules installs to wrong directory in monorepo

### ISSUE THREAD

**Issue by cam-mcevenue** [denoland/deno#26126]
Version: Deno 2.0.0

I have a simple monorepo setup with two folders

deno.json
deno.lock
packages/some-package
apps/web

```jsonc
// deno.json
{
  "nodeModulesDir": "auto",
  "workspace": ["./packages/some-package", "./apps/web"]
}
```

The web directory contains a single package.json that looks like this

```jsonc
// package.json
{
    "name": "web",
    "version": "0.0.1",
    "scripts": {},
    "devDependencies": {
        "vite": "^5.0.3"
    },
    "type": "module"
}
```

When I cd into `apps/web` and run `deno install` the node_modules directory is created in the root directory of the project instead of in the `apps/web` directory.

If I remove "workspace" from the deno.json config, and run deno install in the `apps/web` directory, node_modules is created in the `apps/web` directory as expected.

is this expected behaviour?

**Comment by marvinhagemeister** [comment]
Yes, this is the expected behaviour, unless it caused an error in your application. The idea behind workspaces is that shared dependencies can be hoisted to the workspace root. This saves lots of disk space in bigger projects. It's similar how other package managers like pnpm work.

**Comment by manzt** [comment]
> This saves lots of disk space in bigger projects. It's similar how other package managers like pnpm work.

My understanding is that with pnpm, it installed the packages in to the workspace root, but then also creates a `node_modules` for each workspace package with hard links to the root `node_modules`. Certainly saves disk space, but the presence of the per-package `node_modules` is important.

**Comment by BastiDood** [comment]
Hi @marvinhagemeister, I'm requesting that we reopen this issue because I am indeed running into compatibility issues with this design decision.

My use case: I have a SvelteKit project workspace member that contains a `svelte-check` task. Due to how `svelte-check` resolves modules (haven't gotten to the bottom of this yet), running `svelte-check` from the workspace root with `--recursive` results in an unresolved module error.

```
TypeError: Import "@sveltejs/adapter-static" not a dependency and not in import map from "file:///{REDACTED}/svelte.config.js"
  hint: If you want to use a JSR or npm package, try running `deno add jsr:@sveltejs/adapter-static` or `deno add npm:@sveltejs/adapter-static`
    at file:///{REDACTED}/svelte.config.js:2:21
```

Based on the stack trace, my hunch is that `svelte-check` dynamically imports `svelte.config.js` at runtime, but fails because the `node_modules` does not exist in the workspace member's directory (which as you mentioned is by design). This is quite an unfortunate blocker for me.

For context: this works totally fine in `pnpm` (as @manzt mentioned) because it installs the `node_modules` within each workspace member. The workaround is the use of file system hard links to deduplicate the bloat, which already works and scales in practice (speaking as a long-time `pnpm` user).

I propose that we at least provide a compatibility flag in `deno.json` that enables localized installations of `node_modules` per workspace member.

**Comment by bartlomieju** [comment]
@BastiDood it would be a lot better to open a new issue about your problem.
