### ISSUE TITLE
Rust library with batteries included

### ISSUE THREAD

**Issue by s-panferov** [denoland/deno#2633]
In #1209 you introduced a deno crate which allows creating and working with a basic Isolate. This is definitely usable, but it would be very helpful to have the ability to "turn on" Deno's standard library from the cli package to be available in the deno crate along with maintaining the ability to get an "empty" `Isolate` as it is now. For some cases you need a standard library, for some you don't.

---

My use case: I'm trying to build a FaaS on top of Deno, and I would like to have some parts of the cli package available in deno crate:

- The TypeScript compiler
- Fetch API
- Timers
- Dynamic module import

But it would be useful to be able to turn on everything else selectively too.

**Comment by ry** [comment]
Yes I agree - it would be nice to have such a crate. We want to fix some performance issues before we release a full framework around d TS - but it’s a goal. Thanks for the feedback.

**Comment by norman784** [comment]
I also have interest in using this as a dependency of my project, I don’t care if is unstable yet, because I’m not doing something that will be finished any time soon, but want to start working on it ASAP.

So my question is, it is possible to use as a dependency from the master branch? If so can you give some hints if there’s any gotcha or tricky part to make it work. 

Thanks

**Comment by lucacasonato** [comment]
Update:

- Things like the fetch API and timers are going to be modularized through op crates (#2180). @bartlomieju has started on this work (#6906).
- @kitsonk is working on splitting the TypeScript compiler into its own crate (#6894)

**Comment by bartlomieju** [comment]
The main runtime is now available as a Rust library crate: https://crates.io/crates/deno_runtime
