### ISSUE TITLE
Panic on file change

### ISSUE THREAD

**Issue by lexuzieel** [denoland/deno#26541]
I'm trying to migrate existing node project to deno. I've been using `tsx --watch src/index.ts` for development. When I ran `deno run --watch src/index.ts`  it complained that the module from a local file is not found. Here is the import:

```
import OkoCRM from "./okocrm-api/okocrm.js";
```

I used .js because typescript was nagging about it.

When I appended `file:` to that line deno crashed (I am yet to read how to include local files, but that was just what I intuitively did since deno uses `npm:` and `node:`)

Here is the message:

```
Watcher File change detected! Restarting!

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.34.1
Args: ["C:\\Users\\Aleksei\\AppData\\Local\\Microsoft\\WinGet\\Links\\deno.exe", "run", "--watch", "src/index.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\watcher.rs:92:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by catuhana** [comment]
You're using very old version of Deno, `1.34.1` vs `2.0.3`. You should also prefer using Deno's official installed script instead of WinGet or any other sources, since Deno has a built-in version checking and upgrading.

The reason LSP is warning about the import is *most probably* because you're not using Deno LSP instead of built-in TypeScript one. In my experience, I've had issues with Deno LSP and Deno linter not being automatically enabled, even though they're supposed to be via the extension.

**Comment by bartlomieju** [comment]
Please upgrade to the latest Deno (2.0.3), the problem should be gone there.
