### ISSUE TITLE
Progress bar shows percent-encoded `npm:` dependencies

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#26576]
Downloading npm packages that get percent encoded (eg. having `/` in the name) are badly printed:

https://github.com/user-attachments/assets/c08d7d82-edd2-4a50-829a-1070950a4cca

Most likely caused by https://github.com/denoland/deno/pull/26390

**Comment by SaiThanushreddy** [comment]
@bartlomieju Can i work on this?

**Comment by marvinhagemeister** [comment]
Looking into this the issue occurs because we're passing only the resolved URL to the progress bar here https://github.com/denoland/deno/blob/3a306c450ce99067c4322720792d909afaf78841/cli/util/progress_bar/renderer.rs#L196-L199

The check for the `npm:` specifier is hard coded for the public npm registry and won't work with private registries either. I'm not sure if wiring up the npmrc information to this place would be a good fix. It feels like the original specifier should be passed to the progress par instead.
