### ISSUE TITLE
vite still can't resolve local module in deno workspace

### ISSUE THREAD

**Issue by umajho** [denoland/deno#26721]
Version: Deno 2.0.4

This is a continuation of #26138 that has been closed. It seems that the problem described in that issue still exists.

I have made two reproductions:
- the 1st one is based on the reproduction for the issue mentioned before (using SvelteKit), 
- the 2nd one is the minimum reproduction of what I have encountered originally (using SolidJS).

Here is the repository: https://github.com/umajho/deno-vite-monorepo-reproductions

---

There is also an issue reported to [denoland/deno-vite-plugin] that seems to describe the same problem:
- https://github.com/denoland/deno-vite-plugin/issues/19

[denoland/deno-vite-plugin]: https://github.com/denoland/deno-vite-plugin

**Comment by ali-issa** [comment]
Hello @bartlomieju and @marvinhagemeister,

I see that the issue has been assigned, which is great. Since our project depends on this feature, I wanted to ask if there’s an approximate timeline for when it might be addressed. If it’s likely to take some time, we’re considering alternative setups as an interim solution.

Thank you for any updates you can share!

**Comment by ali-issa** [comment]
> Hey @ali-issa, sorry I missed your comment. We'll try to fix it in the next week.

No worries, @marvinhagemeister! Thanks for the update, and I appreciate the effort!

**Comment by bartlomieju** [comment]
I managed to reproduce both issues. It appears to me the problem lies with `@deno/vite-plugin`, but I need to confirm me. Will get back to you soon.
