### ISSUE TITLE
fmt Astro: incorrect formatting when code comments contain links

### ISSUE THREAD

**Issue by quadratz** [denoland/deno#26786]
#### Component.astro:
```astro
---
/** https://example.com */
const foo = "bar"
---
<p>Hello world</p>
```

#### Cmd:
```sh
deno fmt --unstable-component Component.astro
```

#### Output:
```astro
---

---

```

#### Version:
Deno 2.0.5+637b1d5 (canary, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

**Comment by HasanAlrimawi** [comment]
@g-plane 
I believe this issue could be fixed if `fn format_script` in `markup_fmt/src/ctx.rs`
![image](https://github.com/user-attachments/assets/0f47a59a-50c7-422b-a667-37ece513dfe1)
would pass the complete self.source to the external formatter, since the already applied logic will pass the source code in an altered state mostly composed from whitespaces. 'At least for this case'

**Comment by g-plane** [comment]
Fixed in upstream.

**Comment by g-plane** [comment]
This can be closed since markup_fmt was upgraded.

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/deno/pull/27164
