### ISSUE TITLE
Unable to resolve dev dependencies from private npm registry

### ISSUE THREAD

**Issue by lethanhan97** [denoland/deno#26892]
Version: Deno 2.0.6

# Problem Description

We have a private repository hosted on gitlab. In `.npmrc`, we have the following

```
@prefix:registry=https://gitlab.private.whatever
```

In a deno project using `Deno 2.0.6`, I install the private `sample-lib` module like so

```
deno install npm:@prefix:sample-lib
```

The installation works as expected

`sample-lib` has a dependency on `protobufjs`, which has a dependency on `minimal`

When running the app, I'm faced with the error

```
[ERR_MODULE_NOT_FOUND] Cannot find module 'file:///Users/my-user/Library/Caches/deno/npm/registry.npmjs.org/protobufjs/7.4.0/minimal' imported from 'file:///Users/my-user/Library/Caches/deno/npm/gitlab.private.whatever/api/v4/packages/npm/@prefix/sample-lib/5.3.62/dist/esm/index.js'
```

Note that this lib has been long running and working fine with `npm` and `.npmrc` setup

What could be causing this problem here? Judging from the error message, seems like deno di not install `sample-lib`'s dependencies?

Thank you guys in advance 🙇

**Comment by marvinhagemeister** [comment]
You listed running `deno install npm:@prefix:sample-lib` to install it. Is the colon a typo and you used a `/`?

```diff
- deno install npm:@prefix:sample-lib
+ deno install npm:@prefix/sample-lib
```

**Comment by marvinhagemeister** [comment]
Closing as we haven't heard back.

**Comment by hammamabughali** [comment]
Our company wanted us to switch from nodejs to deno2, but unfortunately deno2 isn't ready yet when it comes to its own npm gitlab registry, you simply can't import via deno install or deno add and all the solutions for it don't work and all their solutions that you can find on the net don't work 

C:\kr3m\test\deno2-projects\demo>deno add  npm:@kr3m/kr3m           
Add npm:@kr3m/kr3m@23.6.0
error: Failed caching npm package '@kr3m/kr3m@23.6.0'

Caused by:
    Could not find npm package tarball at: https://gitlab.kr3m.com/api/v4/projects/82/packages/npm/@kr3m/kr3m/-/@kr3m/kr3m-23.6.0.tgz

C:\kr3m\test\deno2-projects\demo>deno add  npm:@kr3m/kr3m
Add npm:@kr3m/kr3m@23.6.0
error: Failed caching npm package '@kr3m/kr3m@23.6.0'

Caused by:
    Could not find npm package tarball at: https://gitlab.kr3m.com/api/v4/projects/82/packages/npm/@kr3m/kr3m/-/@kr3m/kr3m-23.6.0.tgz

C:\kr3m\test\deno2-projects\demo>deno add  npm:@kr3m/kr3m
Add npm:@kr3m/kr3m@23.6.0
error: Failed caching npm package '@kr3m/kr3m@23.6.0'

Caused by:
    Could not find npm package tarball at: https://gitlab.kr3m.com/api/v4/projects/82/packages/npm/@kr3m/kr3m/-/@kr3m/kr3m-23.6.0.tgz

C:\kr3m\test\deno2-projects\demo>deno info @kr3m/kr3m    
Download ⣟ [00:00] 0/2
 - https://gitlab.kr3m.com/api/v4/projects/82/packages/npm/@kr3m/kr3m/-/@kr
3m/kr3m-23.6.0.tgz
 - npm:@types/node/-/node-18.19.73.tgz

dependencies: 17 unique
size: 1.96MB

npm:/@kr3m/kr3m@23.6.0 (unknown)
├─┬ npm:/@types/node@18.19.73 (unknown)
│ └── npm:/undici-types@5.26.5 (71.34KB)
├── npm:/autobind-decorator@2.4.0 (24.09KB)
├─┬ npm:/mysql2@3.12.0 (495.66KB)
│ ├── npm:/aws-ssl-profiles@1.1.2 (222.76KB)
│ ├── npm:/denque@2.1.0 (29.65KB)
│ ├─┬ npm:/generate-function@2.3.1 (8.82KB)
│ │ └── npm:/is-property@1.0.2 (13.26KB)
│ ├─┬ npm:/iconv-lite@0.6.3 (340.35KB)
│ │ └── npm:/safer-buffer@2.1.2 (41.31KB)
│ ├── npm:/long@5.2.4 (116.11KB)
│ ├── npm:/lru.min@1.1.1 (32.76KB)

C:\kr3m\test\deno2-projects\demo>
