### ISSUE TITLE
Wasm modules are missing non-function exports

### ISSUE THREAD

**Issue by dsherret** [denoland/deno#26986]
Surfacing this here for visibility.

https://github.com/denoland/deno_core/issues/974

Version: Deno 2.1.1

**Comment by korywka** [comment]
@dsherret can you tell please if `import * as wasm from "./exports.wasm";` should work for files like:

https://cdn.jsdelivr.net/npm/@imagemagick/magick-wasm@0.0.31/dist/magick.wasm

or

https://unpkg.com/@ffmpeg/core-mt@0.12.6/dist/umd/ffmpeg-core.wasm

because i got

```
TypeError: Relative import path "a" not prefixed with / or ./ or ../ and not in import map from
```

errors for both. Does it mean that both libs don't compatible with Deno imports? 🙏

**Comment by dsherret** [comment]
@korywka sorry, that error message is not good. There's an open issue here: https://github.com/denoland/deno/issues/26953

If you run the following code:

```ts
const module = new WebAssembly.Module(Deno.readFileSync("magick.wasm"));

console.log(WebAssembly.Module.imports(module));
```

You'll see that the magick.wasm module has many imports like: `{ module: "a", name: "a", kind: "function" }`

To get it to work, you need to map the `"a"` specifier to point to a module, which can be done with an import map: https://docs.deno.com/runtime/reference/wasm/#overriding-import-specifiers or by rewriting the wasm module to instead use a relative import.

After you have it importing from a JS module, you'll need to export all the imports that it requires. So overall, it's a lot of work and generally this step should be done by an automated tool when building the Wasm module.

**Comment by korywka** [comment]
Thank you for clarification. Subscribed to the issue 🙏
