### ISSUE TITLE
HMR not working in deno-vite-solidjs

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#27148]
[스크린캐스트_20241129_231210.webm](https://github.com/user-attachments/assets/38292c8f-a864-4ee2-b182-588dcf96fdf5)

Version: Deno 2.1.2

## to reproduce

1. run `deno run -RWE npm:create-vite-extra@latest`
2. setup deno-solid
3. run `deno task dev`
4. despite on vite hmr isn't working.

**Comment by marvinhagemeister** [comment]
Looks like an upstream issue in either `solidjs` or `vite` itself. I can't get HMR working in Node either. When I click the counter and change something else, the counter is always reset in Node. Same is true for the normal solidjs preset for Node.

Closing because it's not an issue with Deno, but an upstream issue.

**Comment by scarf005** [comment]
oh, yeah looks like solidjs has no way of preserving state between hmr according to https://github.com/solidjs/vite-plugin-solid/issues/42
could you close it as not planned instead?

**Comment by marvinhagemeister** [comment]
sure
