### ISSUE TITLE
--allow-read and --allow-write whitelists broken

### ISSUE THREAD

**Issue by qwerasd205** [denoland/deno#2718]
The issue:
```js
const passwd = Deno.readFileSync('./../../../../../../etc/passwd');
console.log(new TextDecoder().decode(passwd));
```
successfully reads `/etc/passwd` when run with `--allow-read=./` because [the whitelist check](https://github.com/denoland/deno/blob/master/cli/permissions.rs#L484) does not first [canonicalize](https://doc.rust-lang.org/std/path/struct.PathBuf.html#canonicalize.v) the path.

While I discovered this issue, it was @nayeem-rahman who pointed out the cause when I brought up the bug in [the gitter chat](https://gitter.im/denolife/Lobby). I figured I should make an issue for it so that it could be tracked properly, especially considering it's a fairly major issue (Untrusted code that is meant to have access to only one directory has access to the whole file system).

**Comment by nayeemrmn** [comment]
Sorry, that was just a throwaway unresearched statement on my part.

See:
https://github.com/denoland/deno/blob/e9908453df970b1cdf90483892bc9e794382fccc/cli/fs.rs#L142-L153

I think the problem is that the normalisation method used here resolves `.`s but not `..`s.
```rust
fn main() {
    let path = std::path::Path::new("/a/..");
    let normalized_path = url::Url::from_file_path(&path).unwrap().to_file_path().unwrap();
    dbg!(&path, &normalized_path);
}
```
```
[src/main.rs:4] &path = "/a/.."
[src/main.rs:4] &normalized_path = "/a/.."
```
Maybe some dedicated library should just be included for this.
