### ISSUE TITLE
Consider `reqwest` as internal HTTP client

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#2720]
Currently we use `hyper` as internal HTTP client for Deno.

It is used to download remote modules as well as implement `fetch`.

There are several problems with this approach:
- no proxy support (#1960)
- no compressions (#1533)
- ~~no TLS (#1568)~~

When talking with @mhvsa we started with [hyper_proxy](https://docs.rs/hyper-proxy/0.5.0/hyper_proxy/) to implement proxy support in Deno, but that would still leave compression issue unaddressed.

So I'd like to propose to use [reqwest](https://docs.rs/reqwest/0.9.19/reqwest/) as an internal HTTP client. It can use [system TLS](https://docs.rs/reqwest/0.9.19/reqwest/#tls), supports [proxies](https://docs.rs/reqwest/0.9.19/reqwest/#proxies), as well as [gzip](https://docs.rs/reqwest/0.9.19/reqwest/struct.ClientBuilder.html#method.gzip). 

Seems like a quick win to solve a few issues.

**Comment by ry** [comment]
Looking at its dependencies it seems to sit on top of hyper and tokio. So that works with our infrastructure fine. I’m open to the change.

One particularly annoying thing about hyper’s client is that it starts 3 threads for DNS resolution. I’d be very happy if reqwest could use tokio-dns or other asynchronous DNS methods.

**Comment by bartlomieju** [comment]
@ry `reqwest` uses [trust-dns](https://github.com/bluejekyll/trust-dns). I'll get the PR going and let's see how it plays out.
