### ISSUE TITLE
Incorrect Binary Architecture When Adding npm:@pnpm/core on macOS ARM64

### ISSUE THREAD

**Issue by LeoMartinDev** [denoland/deno#27231]
**Description**

I ran into an issue while trying to add the npm package @pnpm/core using Deno on my Mac with an ARM64 chip (Apple Silicon). Instead of downloading the correct binary for my architecture, Deno attempts to fetch a binary for x64, which causes an error.

**Steps to Reproduce**

1. On a Mac with Apple Silicon, run:

`deno add npm:@pnpm/core`

2. You’ll get the following error:

```
❯ deno add npm:@pnpm/core
Add npm:@pnpm/core@1000.0.0
error: Could not find npm package '@reflink/reflink-darwin-x64' matching '0.1.18'.
```

**What I Expected**

I expected Deno to fetch the correct binary for macOS ARM64.

What Actually Happened

Deno tried to fetch a binary for the x64 architecture (@reflink/reflink-darwin-x64), which is incompatible with my system, leading to the error.

The binary for arm64 architecture is available for the package [@reflink](https://github.com/pnpm/reflink):
![CleanShot 2024-12-04 at 18 28 19@2x](https://github.com/user-attachments/assets/879388e2-ff2b-4154-aaf8-c4c67661e4ec)

**System Details**

	•	OS: macOS 15.1.1 (ARM64 / Apple Silicon)
	•	Deno Version: 2.1.2
	•	npm:@pnpm/core Version: 1000.0.0 (default version added by deno add)

**Additional Notes**

It seems like there’s an issue with how Deno determines the architecture when handling npm packages, as it doesn’t recognize the need for an ARM64 binary on macOS.

**Comment by dsherret** [comment]
What's happening here is Deno is attempting to get the package information for the dependency `"@reflink/reflink-darwin-x64": "0.1.18"` in `@reflink/reflink` in order to read the architecture, but that package doesn't exist due to https://github.com/pnpm/reflink/issues/15

That said, Deno should not error here because it's an optional dependency. The root cause is outlined in https://github.com/denoland/deno/issues/27232 so lets track this in that issue.
