### ISSUE TITLE
node compat: fs.access/fs.promises.access seems broken

### ISSUE THREAD

**Issue by thautwarm** [denoland/deno#27405]
- Platform: Windows 10
- Current Behavior: `await fs.promises.access("/path/to/existing/executable", fs.constants.X_OK)` throws `Uncaught Error: EACCES: permission denied, access ...`.
- Expected Behavior: `await fs.promises.access("/path/to/existing/executable", fs.constants.X_OK)` returns `undefined`, which aligns with Node.js.

Note that `fs.access` and `fs.promises.access` used to work on Windows at least in a few versions around v1.42, however it seems that the behavior has changed since about v2.

**Comment by filipstev** [comment]
I can reproduce the issue on a Windows 11 machine. Note that it seems as per Node documentation `X_OK` has no effect on Windows and will behave as `F_OK`. When I tried the same code sample with `F_OK` instead of `X_OK`, I did get `undefined`. I'll be happy to look into this a bit further!

<img width="1166" alt="Screenshot 2024-12-17 at 22 15 10" src="https://github.com/user-attachments/assets/f6608bc7-7146-4e6d-94e5-7e356a9465c5" />
