### ISSUE TITLE
Typescript for deno

### ISSUE THREAD

**Issue by johnsoncodehk** [denoland/deno#2772]
Hello everyone! I have done some deno support on the basis of TypeScript. If there is something missing, please let me know, I will add it to the list, and I will implement it soon if it is not too difficult.

Repo: https://github.com/johnsoncodehk/TypeScript/tree/deno

## Features

- [x] Import module with extension - https://github.com/johnsoncodehk/TypeScript/commit/30295395d6735d71effa342300742e7c83f62947
- [x] Import module by URL - https://github.com/johnsoncodehk/TypeScript/commit/5aaa36d5fb0648b50b35ec742f273f7fcd25ac13
- [x] Top-level await - https://github.com/johnsoncodehk/TypeScript/commit/200b47ff48bdc851f2c5b7a02d26022710e400a7
- [x] Auto reference DENO_DIR/deno.d.ts - https://github.com/johnsoncodehk/TypeScript/commit/7299e31b9e9a9d3c8b811d51527ebb464e55cdd2

## Using

Install from npm
```console
$ npm install --save-dev typescript-deno
```

If use VSCode, setting ```./.vscode/settings.json``` and select TypeScript version to workspace in editor
```json
{ "typescript.tsdk": "./node_modules/typescript-deno/lib" }
```

Set up tsconfig.json
```json
{
  "compilerOptions": {
    "moduleResolution": "deno" // This may change
  }
}
```

**Comment by kevinkassimo** [comment]
Hi, thanks for posting the project.

We also have a Deno chatroom at https://gitter.im/denolife/Lobby . Do you mind sharing it there? Since issue thread is mostly about tracking bugs and feature requests, while in the chatroom there are quite a few people working on Deno and Typescript stuff and would also allow easier discussion. Thanks!
