### ISSUE TITLE
Reverse flow of messages

### ISSUE THREAD

**Issue by s-panferov** [denoland/deno#2777]
Hello, I'm trying to use Deno core in my project and I have a use case when I need to have a script constantly running in "idle" state and I want to be able to push some work to it from the app. You can see it like a "hook" that a user defines to amend a system behavior in some way.

I don't see any way to make it work using the public API, because we don't have an analog of `dispatch` function in Rust exposed. 

Currently, all I can do is to:

1. recreate an Isolate every time to force the script to "ask" for a job 
2. evaluate small fake on-demand scripts with instructions I need using the `execute` method, but I have to String-serialize everything this way
3. constantly "poll" jobs from the script

Neither of these seems to be a perfect solution

**Comment by ry** [comment]
Your JS should "ask" for new work. This is forced by design. We do not want to allow the JS to be exposed to an unbounded stream of events. By asking for new work, you ensure proper back pressure.

So you should implement an async dispatch op, and setup an infinite loop which dispatches to Rust to ask for more work.

**Comment by s-panferov** [comment]
Ok, thanks, that makes sense
