### ISSUE TITLE
"deno test" failure

### ISSUE THREAD

**Issue by ry** [denoland/deno#2948]
```
> ./target/debug/deno test js/version_test.ts
Download https://deno.land/std@06958a4/testing/runner.ts
Compile https://deno.land/std@06958a4/testing/runner.ts
Download https://deno.land/std@06958a4/fs/mod.ts
Download https://deno.land/std@06958a4/testing/mod.ts
Download https://deno.land/std@06958a4/fs/empty_dir.ts
Download https://deno.land/std@06958a4/fs/ensure_dir.ts
Download https://deno.land/std@06958a4/fs/ensure_file.ts
Download https://deno.land/std@06958a4/fs/ensure_link.ts
Download https://deno.land/std@06958a4/fs/ensure_symlink.ts
Download https://deno.land/std@06958a4/fs/exists.ts
Download https://deno.land/std@06958a4/fs/move.ts
Download https://deno.land/std@06958a4/fs/copy.ts
Download https://deno.land/std@06958a4/fs/read_file_str.ts
Download https://deno.land/std@06958a4/fs/write_file_str.ts
Download https://deno.land/std@06958a4/fs/read_json.ts
Download https://deno.land/std@06958a4/fs/write_json.ts
Download https://deno.land/std@06958a4/fs/eol.ts
Download https://deno.land/std@06958a4/fs/utils.ts
Found 4 matching test files.
Compile file:///Users/rld/src/deno/js/version_test.ts
error: Uncaught SyntaxError: Unexpected token ':'
► file:///Users/rld/src/deno/target/debug/.deno_test/gen/file/Users/rld/src/deno/js/version_test.ts.js.map:1:11

1 {"version":3,"file":"version_test.js","sourceRoot":"","sources":["file:///Users/rld/src/deno/js/version_test.ts"],"names":[],"mappings":"AAAA,OAAO,EAAE,IAAI,EAAE,MAAM,EAAE,MAAM,gBAAgB,CAAC;AAE9C,IAAI,CAAC,SAAS,OAAO;IACnB,MAAM,OAAO,GAAG,iBAAiB,CAAC;IAClC,MAAM,CAAC,OAAO,CAAC,IAAI,CAAC,IAAI,CAAC,OAAO,CAAC,IAAI,CAAC,CAAC,CAAC;IACxC,MAAM,CAAC,OAAO,CAAC,IAAI,CAAC,IAAI,CAAC,OAAO,CAAC,EAAE,CAAC,CAAC,CAAC;IACtC,MAAM,CAAC,OAAO,CAAC,IAAI,CAAC,IAAI,CAAC,OAAO,CAAC,UAAU,CAAC,CAAC,CAAC;AAChD,CAAC,CAAC,CAAC"}
            ^
```

**Comment by bartlomieju** [comment]
This issue is related to denoland/deno_std#576 - it looks like your `DENO_DIR` is set to `target/debug/.deno_test`. It's in the same directory as you're running test runner. So it indeed walks through the whole directory and `version_test.ts.js.map` matches the default regex for test file (Regexes have `g` flag, so `.js.map` ending is matched).

We definitely need to rethink how test runner discovers files. It'd probably be a good idea to skip directories listed in `.gitignore` as well and try to partially match directories to avoid expensive walking over big directories as suggested in denoland/deno_std#576

**Comment by nayeemrmn** [comment]
@bartlomieju
> Regexes have `g` flag

Hmm, why?

Also, I'm concerned that the default globs for can't be used in practice. You'd normally try to run `deno test src` precisely to avoid things like `node_modules` and `deno_dir`, but then you lose the globs and it matches everything in `src`. I crashed into this my first time trying it. I think any directory arguments should have some kind of default globs applied to them.

**Comment by bartlomieju** [comment]
> > Regexes have `g` flag
> 
> Hmm, why?

TBH I don't remember, I introduced it in https://github.com/denoland/deno_std/pull/574 so it was probably not working properly without it. Upgrades welcome

**Comment by nayeemrmn** [comment]
This is fixed by https://github.com/denoland/deno_std/pull/604 (when integrated), in that `//js/version_test.ts` is the only matched file.

Not sure if you what you were expecting but no tests would be run anyway since they're declared using the `test()` in `//js/deps/https/deno.land/std` whereas `deno test` uses https://deno.land/std@06958a4.
