### ISSUE TITLE
Any plans to use multithreading on Deno server?

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#3003]
Ecma has made some advances in making Javascript better suitable for multithreading(webworkers) for quite a while now. Would there be any plans to take advantage of this and perhaps a little of Rust vast power to make Javascript Achilees heel(horrible concurrency) less of a problem?

**Comment by kevinkassimo** [comment]
Deno already have `Worker`s fyi. I don't think I fully understand your implication of "Rust vast power" here. Do you have a good example to demonstrate this (that could not be resolved with Workers)?

**Comment by Soremwar** [comment]
I was thinking on Rust multithreading instead of native JS multithreading.

Running multiple instances of Rust Deno runtime to boost execution time on high demanding JS processes.

Just an idea, though.

**Comment by kitsonk** [comment]
Rust side processes take advantage of that, as well as the way V8 handles what it can handle, but there isn't a lot you can do with JavaScript because of the need to have a main event loop.  Multi-threading is more than just going faster, you have to have you memory access thread safe as well, and code has to be written to be aware of that, and there is no way to do such a thing outside of web workers in JavaScript, which Deno supports.

**Comment by Soremwar** [comment]
Ok guys, :(

**Comment by frank-dspeed** [comment]
@ry but when you do that please don't do that for workers as i can then not expect anymore what is going on when my workers start to create addition th's
