### ISSUE TITLE
The command `cargo build -vv` fails to build deno

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#3072]
The command `cargo build -vv` fails to build deno

Instructions followed from https://deno.land/manual.html#buildfromsource
The output with `RUST_BACKTRACE=full` attached: [build.backtrace.log.txt](https://github.com/denoland/deno/files/3693934/build.backtrace.log.txt)

* OS version: Ubuntu 18.04.3 LTS
* rust: rustc 1.37.0 (eae3437df 2019-08-13)

**Comment by trivikr** [comment]
Related issues based on warnings displayed while building deno:
* https://github.com/unicode-rs/unicode-normalization/issues/41
* https://github.com/denoland/deno/issues/3073
* https://github.com/bluss/either/issues/41
* https://github.com/SergioBenitez/version_check/issues/10

**Comment by ry** [comment]
There are some dependencies that are fetched during download - from first scan of your output it looks like that downloaded failed for whatever reason. Is the failure repeatable?

I don’t think the issues you linked to are related. Deno doesn’t have any outstanding compiler warnings afaik.

**Comment by trivikr** [comment]
> From first scan of your output it looks like that downloaded failed for whatever reason. Is the failure repeatable?

I just ran `cargo build -vv` ten times, it failed each and every time.

> I don’t think the issues you linked to are related

Yup, they're not related to this issue. The warnings are in dependencies.
I removed the "related" word from my comment and marked it as offtopic

**Comment by ry** [comment]
The pertinent bit of the output is this

“””
Traceback (most recent call last):
  File "./tools/setup.py", line 185, in <module>
    sys.exit(main())
  File "./tools/setup.py", line 29, in main
    third_party.download_gn()
  File "/home/trivikr/workspace/deno/tools/third_party.py", line 242, in download_gn
    download_from_cipd("gn/gn/", "152c5144ceed9592c20f0c8fd55769646077569b")
  File "/home/trivikr/workspace/deno/tools/third_party.py", line 227, in download_from_cipd
    ], env=google_env())
  File "/home/trivikr/workspace/deno/tools/util.py", line 63, in run
    rc = subprocess.call(args, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
thread 'main' panicked at 'assertion failed: status.success()', core/build.rs:94:9
“””

cargo is calling tools/setup.py and setup.py is trying to download the “gn” executable. It’s odd that the failure message is “no such file or directory” that doesn’t fit with the download error theory. Are the git submodules synced? Is third_party an empty directory? If so run “git submodule update”.

If it is an internet download problem after all maybe it’s because you’re behind a firewall or having dns issues? We should have a better error message on a download failure in any case...

**Comment by trivikr** [comment]
> Are the git submodules synced?

Ran the following commands:
```console
$ git clean -dfx
Removing target/
Removing tools/third_party.pyc
Removing tools/util.pyc

$ git remote show upstream | grep Fetch
  Fetch URL: git@github.com:denoland/deno.git

$ git fetch upstream
$ git rebase upstream/master
Current branch master is up to date.
```

The log is attached: [build.log.txt](https://github.com/denoland/deno/files/3693969/build.log.txt)
Do I need to run some other commands?

> Is third_party an empty directory?

Yup, as the following command doesn't show any files
```console
$ ls third_party
```
After running `git submodule update` the third_party directory is still empty

**Comment by kt3k** [comment]
I think `--init` is needed for the first time updating submodules, like `git submodule update --init`.

**Comment by trivikr** [comment]
> I think `--init` is needed for the first time updating submodules, like `git submodule update --init`

I'm able to successfully build deno after running `git submodule update --init`
This was added in [build instructions](https://deno.land/manual.html#buildfromsource) in PR https://github.com/denoland/deno/pull/3078
