### ISSUE TITLE
Merge deno_install repo into deno repo

### ISSUE THREAD

**Issue by ry** [denoland/deno#3166]
It's not helpful to have a one-off side repo with it's own CI setup.
https://github.com/denoland/deno_install

Probably best placed in /std/install ?

**Comment by bartlomieju** [comment]
> Probably best placed in /std/install ?

This will lead to even more confusion between `deno_install` and `deno install`... We should rename one of another

**Comment by nayeemrmn** [comment]
Also `deno fmt` and `std/fmt` :(

**Comment by MarkTiedemann** [comment]
> This will lead to even more confusion between `deno_install` and `deno install`... We should rename one of another

Now that there's `deno upgrade`, `deno_install` could be renamed to `deno_bootstrap`.

**Comment by crowlKats** [comment]
or denoup or smth like that (following Rust's style)

**Comment by MarkTiedemann** [comment]
Or maybe just `install_deno`. I think that kind of makes the distinction between installing Deno and installing something using Deno more obvious.

**Comment by nayeemrmn** [comment]
Why should this go into `std`? This was most likely suggested for publishing convenience, this was around the time that the manual was moved into `std` for seemingly that reason.

If this needs to go into the deno repo, `https://deno.land/install.sh` should be the URL and the site ought to be able to map that to a file in the repo, instead of needing to treat it like an `/std/` or `/x/` module. As we should do with the manual.

cc @lucacasonato

**Comment by lucacasonato** [comment]
I agree - I think the installer should move to `https://deno.land/install.sh` and not piggyback off `/x/`. Same goes for the manual.

**Comment by ry** [comment]
Retracting this. Seems to work fine how it is.
