### ISSUE TITLE
Std release cycle

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#3167]
- deno@v0.21.0 released in last weekend but std not yet? 
- v0.21.0 is still using old std release for subcommands (fmt, test, install) and latest fixes in those modules are not available in this version.
- How std will be released with single repository?

**Comment by ry** [comment]
Since deno_std is now part of deno it will share tags. This was a major reason for merging the repos.

The actual website http://deno.land/std/ has still been pointing to the old repository until just a few minutes ago... I just made this change:
https://github.com/denoland/registry/commit/7fd99c2ec09d929afce2096231caa12388865e69

Tangentially related: I'm also working a new implementation of the website which hopefully will be easier for others to participate and understand: https://github.com/denoland/deno_website2
