### ISSUE TITLE
Import Json is not exposing properties as exports

### ISSUE THREAD

**Issue by zekth** [denoland/deno#3171]
Importing Json files only works this way:
```Json
{
  "foo": "bar"
}
```
this works:
```javascript
import file from './foo.json'
console.log(file.foo)
```
this does not
```javascript
import { foo } from './foo.json'
console.log(foo)
```

**Comment by kitsonk** [comment]
Why you say "does not work", what sort of error message do you get?

**Comment by kevinkassimo** [comment]
This is because our current json import is through a wrapper looking like
```ts
export default { "your_json_field": 1 };
```

**Comment by zekth** [comment]
> This is because our current json import is through a wrapper looking like
> 
> ```ts
> export default { "your_json_field": 1 };
> ```
> 
> A problem that might arise if we somehow allow `import { prop_name } from "./file.json"` is that `prop_name` might be a reserved word or contains space.

Agreed but rollup / webpack for example does not care of this for example. The output will crash and that's normal. But the output error might be odd.

**Comment by kitsonk** [comment]
> Agreed but rollup / webpack for example does not care of this for example.

They also don't output ESM.  They output a script bundle.  ES modules don't have an "export assignment" operator.  There is no clean way to write it so that the whole of the JSON structure is made available.  It is unlikely that rollup or webpack would just throw, because they don't have the same challenge, because they write it out in a special bundle format that isn't ESM and then wrap that in some sort of loader mechanism.

I don't think "just failing" would be a good idea.  All the following are valid `.json` that we would expect to be able to import:

```js
[ "foo", "bar" ]
```

```js
"foo"
```

```js
1
```

```js
true
```

While the primitives are unlikely, I don't think it is safe to assume an array at the top level would be unlikely, and it would be bad to not support that.  So while I _hate_ default exports, they are actually the only safe way to expose JSON as an ES module.

**Comment by zekth** [comment]
@kitsonk i get your point about those case you mention. So assuming that the loading method for Json files is using only default exports, this might need to be documented. Like i said, other projets don't have the same implementation, so it could be confusing for users.
