### ISSUE TITLE
Support for deno eval interactive option

### ISSUE THREAD

**Issue by BrunnerLivio** [denoland/deno#3173]
Deno should provide an equivalent functionality of [`node -e <CODE> -i`](https://nodejs.org/api/cli.html#cli_i_interactive) that allows the user to evaluate code through the Deno CLI but also attach REPL in the context of the given code. 

**Expected behavior**
```bash
deno eval "const hello = 'world'" -i
# Automatically starts REPL
> console.log(hello)
world
undefined
>
```

**Comment by kevinkassimo** [comment]
Current REPL logic involves creating a module for the evaluated code. I'll investigate if there is a way we could restore to the context of the module for REPL.

**Comment by kevinkassimo** [comment]
It seems very hard to access the lexical scope of the module. `Deno.core.evalContext()` currently evaluates results in a scope that is a different one from the module itself. A reasonable compromise I can think of atm is that REPL would automatically import the module evaluated.

This is different from Node's behavior since Node evals code as a script, so later REPL can also creates more scripts of same origin to access other variables in the same lexical scope. A problem of this is that the code evaled would not be able to use static imports.

**Comment by dsherret** [comment]
I think this should probably be a flag on `deno repl`. It would allow people an easy way to define repls already setup for a certain environment.

Example from #7425:

```
deno repl --eval "import * as calc from './scripts/calc.ts';"
```

**Comment by dsherret** [comment]
I opened #11317 with this proposed approach.
