### ISSUE TITLE
wanted: tutorial/demo of using firebase in a server-side deno process

### ISSUE THREAD

**Issue by ry** [denoland/deno#3177]
The client side firebase code ought to work out-of-the-box on Deno.

If not we should address whatever issues arise.

**Comment by lucacasonato** [comment]
So I tried to get this working, but its pretty difficult - `@firebase/app` is no problem as it is on pika.dev.

`@firebase/database` and `@firebase/firestore` both are not easily doable because they aren't on pika.dev and I have not found any other easy way to import them.

`@firebase/storage` is on pika and can be imported, but it requires XMLHttpRequest to do anything useful so it doesn't work either.

`@firebase/auth` does not make sense in deno as it requires a DOM (or at least window.open). Also it doesn't really make sense server side. Same with these packages: `@firebase/analytics`, `@firebase/preformance` and `@firebase/remote-config`.

The Firebase JS Client SDKs are pretty unusable in deno atm. I don't think they should be the target anyway - it should be `firebase-admin` because that is the SDK meant for server side applications. The problem with that: it is very node dependent to run - so nothing for now. I am pretty sure it also uses a native module so that will be fun.

While trying this out I also realized that we should focus on having good tooling for all of the major editors (VS Code, vim, sublime, ect.). Currently none of them support the `// @deno-types` syntax which makes development very cumbersome for packages which ship with TS support, as I usually can't just import .ts files as no packager outputs .ts files and pika.dev only serves js and d.ts files.

**Comment by matey-jack** [comment]
@ry any idea on how to break this is up into pieces? any specific use-case to try first? One approach I see is to first patch up the libraries so they can be imported and used and then use the learnings from this to either code up some polyfills, propose upstream changes, or some combination of things that results in having Deno-importable @firebase/ libraries published at some URL.

**Comment by bershanskiy** [comment]
@matey-jack 
> first patch up the libraries

The proper way to patch up the libraries is just to export them with ES Modules syntax instead of CommonJS `require()`. This is something the upstream developers would need to do. Another approach is to make a tiny libraries that use the RESTful API provided by Firebase. Also, it's probably possible to make a polyfils that wrap around `require()` (albeit that would probably defeat all optimizations but into ES Modules).

**Comment by matey-jack** [comment]
I dived a bit deeper into @firebase/storage. It looks like the entire Firebase SDK is meant to be used on Browsers: not only does it use XHR, but they also offer rollups as ESM module, even a version for ES2017. For NodeJs they seem to recommend the full Google Cloud / Storage SDK, but this thing has a lot of dependencies on other NPM modules... which might be why we want to go for Firebase first.
I could have a closer look at the use-case "deploy a static Browser app to Google Cloud Storage Webhosting" if that would go into the direction intended by @ry ? I also wanted to look into doing the same for AWS S3 (where I am hosting an app) as part of moving my frontend-dev-toolstack to Deno.

**Comment by QuantumInformation** [comment]
This is how I use firebase, albeit in node functions

https://github.com/QuantumInformation/svelte-fullstack-starter

**Comment by GideonMax** [comment]
the server-side SDK seems to be dependent on Node, but the source code is in typescript and it uses import/export, it shouldn't be that hard to port it over to Deno, though it will probably take some time as it is quite a lot of code.

**Comment by pandakub** [comment]
If I was able to put together a basic deno fire-base server, maybe someone could clean it up. Firebase & Deno make a great team.

**Comment by arthurkhlghatyan** [comment]
In case this can be helpful I just published a [demo](https://github.com/arthurkhlghatyan/deno-firebase-demo/tree/master/server) using firebase with deno. There's also a simple [wrapper](https://github.com/arthurkhlghatyan/deno-firebase-demo/blob/master/server/src/firebase.ts) around rest API which worked really good for my case.

**Comment by gugahoi** [comment]
Just thought I'd check in as there is not a lot of information regarding using the Firebase admin SDK in Deno. Is it possible today? If so, how can we go about it? Below was a naive attempt:

```ts
import { createRequire } from "https://deno.land/std/node/module.ts";

const require = createRequire(import.meta.url);
const admin = require("firebase-admin");

console.log(admin);
```

Below is the error:

```
[I] ➜ deno run --unstable --allow-read main.ts
error: Uncaught Error: Cannot find module 'http'
Require stack:
- /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/utils/api-request.js
- /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/credential/credential-internal.js
- /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/firebase-app.js
- /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/firebase-namespace.js
- /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/default-namespace.js
- /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/index.js
- /Users/guga/Projects/joinflux/firestorectl/main.ts
    at Function._resolveFilename (https://deno.land/std@0.99.0/node/module.ts:273:19)
    at Function._load (https://deno.land/std@0.99.0/node/module.ts:380:29)
    at Module.require (https://deno.land/std@0.99.0/node/module.ts:133:21)
    at require (https://deno.land/std@0.99.0/node/module.ts:1158:16)
    at Object.<anonymous> (file:///Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/utils/api-request.js:36:12)
    at Module._compile (https://deno.land/std@0.99.0/node/module.ts:168:36)
    at Object.Module._extensions..js (https://deno.land/std@0.99.0/node/module.ts:1109:10)
    at Module.load (https://deno.land/std@0.99.0/node/module.ts:147:34)
    at Function._load (https://deno.land/std@0.99.0/node/module.ts:413:14)
    at Module.require (https://deno.land/std@0.99.0/node/module.ts:133:21)
```

**Comment by jthegedus** [comment]
There is a new version of the Admin SDK in alpha which *should* be more compatible with ESM.

**Comment by j-mendez** [comment]
WIP for deno firestore, https://github.com/j-mendez/dfirestore / https://deno.land/x/dfirestore@v0.0.9. Need to improve the docs a bit, add pagination for document query, and some other minor task. Hope this helps!

**Comment by j-mendez** [comment]
> Just thought I'd check in as there is not a lot of information regarding using the Firebase admin SDK in Deno. Is it possible today? If so, how can we go about it? Below was a naive attempt:
> 
> ```ts
> import { createRequire } from "https://deno.land/std/node/module.ts";
> 
> const require = createRequire(import.meta.url);
> const admin = require("firebase-admin");
> 
> console.log(admin);
> ```
> 
> Below is the error:
> 
> ```
> [I] ➜ deno run --unstable --allow-read main.ts
> error: Uncaught Error: Cannot find module 'http'
> Require stack:
> - /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/utils/api-request.js
> - /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/credential/credential-internal.js
> - /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/firebase-app.js
> - /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/firebase-namespace.js
> - /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/default-namespace.js
> - /Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/index.js
> - /Users/guga/Projects/joinflux/firestorectl/main.ts
>     at Function._resolveFilename (https://deno.land/std@0.99.0/node/module.ts:273:19)
>     at Function._load (https://deno.land/std@0.99.0/node/module.ts:380:29)
>     at Module.require (https://deno.land/std@0.99.0/node/module.ts:133:21)
>     at require (https://deno.land/std@0.99.0/node/module.ts:1158:16)
>     at Object.<anonymous> (file:///Users/guga/Projects/joinflux/firestorectl/node_modules/firebase-admin/lib/utils/api-request.js:36:12)
>     at Module._compile (https://deno.land/std@0.99.0/node/module.ts:168:36)
>     at Object.Module._extensions..js (https://deno.land/std@0.99.0/node/module.ts:1109:10)
>     at Module.load (https://deno.land/std@0.99.0/node/module.ts:147:34)
>     at Function._load (https://deno.land/std@0.99.0/node/module.ts:413:14)
>     at Module.require (https://deno.land/std@0.99.0/node/module.ts:133:21)
> ```

WIP for deno firestore, https://github.com/j-mendez/dfirestore / https://deno.land/x/dfirestore@v0.0.9. Need to improve the docs a bit, add pagination for document query, and some other minor task. Hope this helps!
