### ISSUE TITLE
[cli] Remove URL dependencies of std for subcommands

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#3201]
Currently some subcommands (`fmt`, `test`, `install`) depends on remote codes on https://deno.land/std. These commands don't work if site is down or wrongly serve files. Actually I met this situation recently. 

It is strange and undesirable. As I commented on https://github.com/denoland/deno/pull/3168 , There may be no way to use latest std codes for the latest cli release with tag. 

So I think remote dependencies for std should be removed from cli. One possible solution is including subcommand codes in cli release. Is it  possible?

**Comment by kitsonk** [comment]
I believe it was a very intentional decision to not bloat the binary.  In particular `fmt` is a rather huge situation.  Personally I would want us to enhance the experience versus bloating the binary with some of these things.  A subcommand that would ensure that all subcommands are available locally and don't require subsequent network requests, would be my suggestion of a next step.  As well as failing in an informative way.

**Comment by keroxp** [comment]
Anyway we should investigate how will the binary get huge by bundling those codes. If difference is around 2~3MB, we can accept changes. Especially it is strange that the latest release is not using the latest std code for subcommands even though they had been merged.

**Comment by andyfleming** [comment]
I agree it's nice for the binary to be small, but I'd be curious as to what the size cost is of including the subcommands. It seems strange for them to not ship with them included.

**Comment by bartlomieju** [comment]
Done in #3818, #3850 and #3865
