### ISSUE TITLE
Switch from permissive to free software license

### ISSUE THREAD

**Issue by jhabdas** [denoland/deno#3261]
Hello friends. Hopefully this is a no-brainer, but please for version 1.0 switch to a freedom-respecting software license such as AGPL or SSPL. If you cannot switch to a free software license, please indicate why for the benefit of [the community](https://github.com/zloirock/core-js/issues/635#issuecomment-549183827) considering shifting away from NPM.

For a gentle introduction to the free software movement please read this short, informative and recent article from James Halliday titled [Open Source is Not Enough] (https://notesfrombelow.org/article/open-source-is-not-enough).

**Comment by rsp** [comment]
Deno is **already** released under a **free software license**.

You seem to be confusing a free software license with a copyleft license.

All MIT/BSD/X11/Expat etc. licenses are not only considered free software licenses by the Free Software Foundation, but they are also explicitly listed as **GPL-compatible** licenses by the Free Software Foundation. For more info, see: https://www.fsf.org/licensing

In short, Deno is licensed under a license that is:

- open source
- free software
- OSI-certified
- FSF-approved
- DFSG-compliant
- GPL-compatible

It basically means that what you are asking for is already true. You can take all Deno and act as if it was licensed under a copyleft license of your choice if you wish so. If, on the other hand, Deno was explicitly licensed under one of the copyleft licenses, then **you would not be free** to combine it with software released under an incompatible copyleft license, thus your freedom would be largely restricted (see for example why ZFS has not been integrated in Linux yet - not for technical reasons and not for the lack of will to do it, but exactly because those two free software projects have incompatible licenses and the mechanism to "enforce the freedom" is indeed restricting the freedom to use both of the projects together - thankfully Deno did not make this mistake).

**Comment by rsp** [comment]
Just to get you some more context:

Deno complies with all 4 of the Essential Freedoms defined in The Free Software Definition of the Free Software Foundation:

- https://www.gnu.org/philosophy/free-sw.en.html

And it complies with all 10 points of The Debian Free Software Guidelines from the Debian Social Contract:

- https://www.debian.org/social_contract

It also complies with all 10 points of The Open Source Definition by the Open Source Initiative:

- https://opensource.org/osd

It cannot really be more "free software" (and "open source" if you will) than that, at least in my estimation. But if you are concerned about not having some of the freedoms explained by FSF/DFSG/OSI then please be more specific.

**Comment by ry** [comment]
We are sticking with MIT. Being able to link to Deno in commercial software is an important use case.

**Comment by jhabdas** [comment]
First of all thank you for taking the time to respond to this important issue. It's clear license discussions are not what gets most of us out of bed in the morning. When leading a community project please consider prose and form in accepting contributions on GH such as this issue. The BDFL style issue close wasn't necessary and shutting the DOOR on discussion without hearing others out shows close-mindedness.

That said, I'd like to take this opportunity to bring what I've learned of the MIT to the community's attention in hopes of opening some eyes:

- MIT was not designed for community projects. It's an academic license and [assumes](https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html) one institution holds the copyright – almost never the case with projects like Deno.
- There is no express patent grant. In other words, if someone wants to sue later MIT leaves the door open as a result of its ambiguous language. Why settle for that ambiguity when clarity can be had in not using a 30 year-old academic license for a community project like Deno?
- MIT is an attribution landmine. It expects no contributions from the community and what ends up happening is the license, as simple as it [appears to be](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html), often gets lost or munged the moment someone wants to copy a small piece of the project and not carry around a whole license for that, or doesn't want to contribute back as we often see in proprietary software. I'm sure many of you have seen this if not made the same mistake yourselves in the past. 
- MIT may be compatible with GPL but it [limits freedom](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses) to incorporate freedom-respecting software. In other words, no GPL software may be used inside Deno while it's under MIT. And while this may seem OK right now it inhibits the usefulness of this software long-term. Why not address that now rather than later?

Last thing I want to mention right now (I'm typing this from a mobile screen) is @ry stated he wants to link Deno in commercial software later. That's great if later you plan on limiting freedom by closing the source code but there are more apt licenses for that such as Apache 2 (compatible with AGPL) and the LGPL itself.

I encourage contributors to this project to open your minds a bit more and think about these important facts as using MIT with this project is almost certainly a mistake and there's still time to correct it with the right mindset.

Cheers.
