### ISSUE TITLE
Discussion: Partial permissions

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#3302]
With the current API, we can't partially request the permissions like "net permission for example.com". Though we have whitelist for `net` `read` `write` permissions, they are fixed at the start up time and we can't add or remove items to/from them.

This causes unnecessarily dangerous situation because whenever the program needs the access to path/url which is not listed in the whitelists, the program have to request the entire net/read/write permissions.

I think the program should be able to request partial permissions like "net permission for example.com", "read permission to $HOME", "write permission to $HOME/.cache", etc.

**Comment by nayeemrmn** [comment]
What about partially revoking permissions? Could Deno be able to support arbitrary sets of fs locations as specified by trees of blacklists on whitelists and vice versa? I would imagine there exists some applicable data structure.

A use case would be denying access to a subdir of an otherwise required directory. Plus this is the only way to correctly respect `PermissionDescriptor`s.

**Comment by kt3k** [comment]
#7074 implemented what I tried to do with this issue. Thank you for the great work @nayeemrmn !
