### ISSUE TITLE
Aliasing Imports and Modules

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#3311]
This has probably cross your mind while in the early stages of development in Deno, but what about an alias standard for packages?

If I wanna import say React into most of my files I may not wanna write its url into each one(gotta admit it's kinda ugly), so why not reference it once into a file that act as a synonim of it so i can use it into my project?

First thoughts were something like this (not that it is any prettier but will do)

![image](https://user-images.githubusercontent.com/42647963/68537684-332e2180-0336-11ea-80aa-d756dce013c2.png)

This isn't really a feature but more of a standard for Deno development to maybe be included into the documentation now that 1.0 is coming close.

**Comment by nayeemrmn** [comment]
@Soremwar Read https://deno.land/std/manual.md#linking-to-third-party-code. It's already there.

**Comment by rsp** [comment]
@Soremwar a canonical way to do it is to use a single `deps.ts` file with all imports in one place (instead of one per dependency like in your example) and in other files import everything from there:

```ts
import { serve } from './deps.ts';
import { somethingElse } from './deps.ts';
```

Or you can use import maps like I [explained here](https://github.com/denoland/deno/issues/3268#issuecomment-551859728) to have:
```ts
import { serve } from 'std/http/server.ts';
```
or:
```ts
import { serve } from 'http/server.ts';
```
or whatever prefix you use in your mappings.

**Comment by nayeemrmn** [comment]
@ry Can this be closed?

**Comment by ry** [comment]
Yea. Also importmaps work in deno.
