### ISSUE TITLE
Feature Request: Support external versions of TypeScript tsc

### ISSUE THREAD

**Issue by yoav-lavi** [denoland/deno#3323]
Supporting an external version of `tsc` would allow to use the most updated version of TypeScript without waiting for a Deno update and to use beta TypeScript versions. Since the two are different tools from different teams it may make sense to allow decoupling them. The default would still be the internal version so it'd still be "batteries included".

**Comment by kitsonk** [comment]
This is non-trivial, as often upgrades of TypeScript require upgrades of some of the internal code.  Especially because the TypeScript team do breaking changes in the compiler APIs without notice (3.6 had one for example).  Plus there are often changes to the library files, not only the content, but also the names of the files, and those are statically baked into the binary.  Retooling to be able to get all that stuff externally is complex and likely not worth the effort.

I think once we get more mature, we could consider having a "nightly" release of Deno that includes the nightly release of TypeScript would make sense, as we can get early visibility of any breakage.

**Comment by yoav-lavi** [comment]
I understand, my assumption was that you transpile to JS at compile time by running tsc itself. A nightly release would probably be a good idea in the future, although it wouldn't specifically  solve the case where TypeScript releases a stable version that's ahead of the internal Deno version. In that case I assume we'd be forced to transpile existing code. Adding Deno (as in TS to JS) as a Babel / Parcel / Rollup configuration target might be a good workaround

**Comment by ry** [comment]
We will not support using an external tsc. We'll be upgraded to 3.7 very soon.

(We do weekly-ish releases - there's no need for a nightly at this point.)
