### ISSUE TITLE
Add --no-remote to disable remote module resolution

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3384]
The behaviour of `--no-fetch` is to fail to resolve remote modules unless they are already in the cache.

A ~`--no-remotes`~`--no-remote` flag that simply disabled remote module resolution would be more useful and reasonable while not conflicting with Deno's philosophy any more than `--no-fetch` does already.

**Comment by ry** [comment]
Sounds reasonable to me

**Comment by bartlomieju** [comment]
Please wait until I finish #3383

**Comment by kevinkassimo** [comment]
`--no-remote` sounds better to me (don't like remembering "s" 😅)

**Comment by bartlomieju** [comment]
> The behaviour of `--no-fetch` is to fail to resolve remote modules unless they are already in the cache.
> 
> A ~`--no-remotes`~`--no-remote` flag that simply disabled remote module resolution would be more useful and reasonable while not conflicting with Deno's philosophy any more than `--no-fetch` does already.

@nayeemrmn can you show example of usage of `--no-remote` flag? 
I can see value in having `--no-fetch` flag - ie. you fetch and cache all dependencies during CI and then running in production you specify `--no-fetch` to fail if any of dependencies are missing. 
But preventing remote modules entirely? So you add a remote import somewhere in your code and then run it with `--no-remote` so it prevents you from using this module? 
I'd like to see some argument before we replace `--no-fetch` with `--no-remote` - after all I think it would make more sense to have both of them rather than replacing, but there is very intrinsic distinction between the two.

**Comment by nayeemrmn** [comment]
@bartlomieju 

> specify `--no-fetch` to fail if any of dependencies are missing

What else would happen if dependencies are missing?

I could use `--no-remote` if I'm vendoring all 3rd party code and want to find and remove any remote imports (without depending on whether or not the target happens to already be in the cache).

Or I could wrap it to create a strictly traditional package management experience (which, no matter where anyone stands on this, shouldn't made unnecessarily difficult with this awkward `--no-fetch` behaviour).

**Comment by hayd** [comment]
These commands seem independently useful. Specifically the current --no-fetch is useful.

However `deno fetch` is a confusing verb for what it's doing... Which is compile. Semantically `deno compile --no-fetch` and `deno compile --no-remote` makes much more sense.

**Comment by nayeemrmn** [comment]
> > specify `--no-fetch` to fail if any of dependencies are missing
> 
> What else would happen if dependencies are missing?

The answer is download the dependencies now, duh! Sorry I got confused.

You're right about `--no-fetch` being a meaningful flag. (Also if the point is to catch missing deps at `run`time then I understand why it wouldn't apply to `fetch`.) Thinking more clearly, it's completely unrelated to the proposed feature.

@ry What do you think about separately adding `--no-remote` regardless? I gave some use-cases in https://github.com/denoland/deno/issues/3384#issuecomment-559523590. It would be a quick adjustment to #3417.
