### ISSUE TITLE
Inconsistent behavior mixing promise and setTimeout

### ISSUE THREAD

**Issue by Nicify** [denoland/deno#3432]
```javascript
const promise = new Promise(r => {
    let i = 100
    while (i--) { }
    r()
})

setTimeout(() => promise.then(() => console.log('no')))

setTimeout(() => console.log('de'))
```
same code different output

`node` and `deno`
![](https://i.loli.net/2019/12/02/p2ElmhZqVO96cdS.png)

browser
![](https://i.loli.net/2019/12/02/gjI56kczrVJ2uhA.png)

**Comment by kevinkassimo** [comment]
I believe the reason of our behavior here is due to `setTimeout` itself being internally implemented as microtask. Node.js and in browsers the microtask queue could be depleted before moving onto next task.

With Deno timers, however, once a `setTimeout` callback is triggered, all callbacks that have their timers expired (actually there is always only a single global timer used) would be triggered one by one before microtasks are run again. I don't think this is the correct behavior though, we might need to fix it.
