### ISSUE TITLE
Add documentation in std/manual.md about plugins

### ISSUE THREAD

**Issue by ry** [denoland/deno#3449]
The folder test_plugin/, while showing an example, is not mentioned anywhere in the manual, and is not easy to find (since the name does not indicate it also being an example)

This could be a good first issue.

**Comment by ajeetshergill** [comment]
I'm like super new to open source. Got a question, like is this issue open (as in still needs resolving) or closed? 
You mention that #3895 is closed. But this post (i don't know what to call it) is under open and good first issue. SO IDK :| 
Also if it's closed, how do I find easy open issues I can start contributing to.

**Comment by sciepsilon** [comment]
Hi ajeetshergill! Yes, this issue is open, so feel free to contribute! 

None of the linked issues was actually *resolved* when it was closed. #3895 and #4212 were closed as a duplicates of this issue. #3901 is a pull request, not an issue, and it was closed without merging the PR, because the PR was rejected as insufficient to solve the problem. So someone still needs to do add documentation in std/manual.md about plugins.

**Comment by nayeemrmn** [comment]
This can be closed in favour of #6844.
