### ISSUE TITLE
Implement WHATWG Streams

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#3494]
We should implement the [Streams API](https://streams.spec.whatwg.org/) in Deno and utilise it appropriately in other APIs, where things like back pressure are needed/useful.

More easy to understand information is [available on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API).

**Comment by ry** [comment]
Unfortunately you're probably right... I think the Stream API is unnecessarily complicated. I've presented my alternative version of streaming by porting Golang's I/O system, which include things like `Deno.copy`. That said, users don't care, they just want browser-like...

**Comment by rsp** [comment]
Might [deno-streams](https://github.com/keroxp/deno-streams) by @keroxp be useful here?

The WHATWG Streams API feels more like nothing more to add rather than nothing left to take away, very Java-like and verbose but certainly powerful. A port of Golang's I/O might be more elegant but if Deno needs to support WHATWG Streams anyway for browser compatibility then the question is if it makes more sense to use a better streams API where there is no need for WHATWG streams (having two APIs, maybe one built on top of the other) or to use one API everywhere (which couldn't be something not compatible with WHATWG Streams, unfortunately).

**Comment by kitsonk** [comment]
I think this has been largely implemented now.

**Comment by alisabzevari** [comment]
I needed some of the `fetch` and `Body` methods that are related to streams and saw them as not-implemented (`getIterator` and `getReader` specifically). I would like to give it a try and implement them.

Would it make sense to reuse the [reference implementation](https://github.com/whatwg/streams/tree/master/reference-implementation) of whatwg streams and reuse them to implement `Body` stream related methods?

**Comment by kitsonk** [comment]
fetch is being rewritten to align to the standards.

**Comment by alisabzevari** [comment]
How can I help? Is there an issue?

**Comment by kitsonk** [comment]
Not easily right now, as it is also an experiment on how to structure operations in the internals of Deno.  I am afraid it is best to just hold tight at the moment on fetch.

**Comment by elazutkin-dynata** [comment]
> I've presented my alternative version of streaming by porting Golang's I/O system, which include things like `Deno.copy`

@ry, do you happen to have it anywhere accessible?
