### ISSUE TITLE
ServerRequest.respond() is easy to misuse

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3555]
As this has happened once before with our own benchmark code, `ServerRequest.respond()` returns a promise that people might be incorrectly waiting for, thus making request handling effectively synchronous.

```ts
const s = serve({ port: 80 });
for await (const req of s) {
  // This `await` makes next request only responded after previous is done,
  // thus rendering response synchronous.
  await req.respond({ body });
  // The correct way is to drop this `await`.
}
```

It is possible that we can rename it to `ServerRequest.respondAsync(...)` (see below about naming issue) and make `ServerRequest.respond(...)` simply returning `void`, while internally calling `ServerRequest.respondAsync(...)` without `await`ing (we need to find a way to catch and save the error though. Since we have `ServerRequest.done` exposed, it could be used to notify user that an error might be available to read)

(`.respondAsync()` is also a strange name actually, since it creates the false impression that `.respond()` is fully sync, while it is nothing more than just a wrapper that does not directly expose the promise to wait for. Needs a better name)

**Comment by nayeemrmn** [comment]
Found some related discussion here: https://github.com/denoland/deno_std/issues/386.
- https://github.com/denoland/deno_std/issues/386#issuecomment-498055833
- https://github.com/denoland/deno_std/issues/386#issuecomment-501070772

**Comment by sholladay** [comment]
As you mentioned, error handling is problematic with any wrapper that doesn't return the promise.

I think I would end up only ever using `respondAsync` so that I can `.catch()` it, which seems silly and kind of defeats the purpose of renaming it because I still wouldn't want to `await` the result inside of the loop in most cases.

My suggestion is to leave `respond()` the way it is and instead focus on improving the abstractions around it. For example, `listenAndServe()` is an interesting function because even if your handler does `await request.respond()`, it won't actually block the request loop since the handler itself is not awaited.

I think `listenAndServe()` could be improved further, maybe renamed, and then used more prominently in examples as the recommended high-level way to use the server API.

In terms of how to improve `listenAndServe`, I'm thinking the handler should be able to `return response` instead of it calling `request.respond(response)` directly. Then we just need a way to provide a callback for error handling and it will be very pleasant to use.

**Comment by rsp** [comment]
@kevinkassimo, about the naming of `.respond()` vs `.respondAsync()`
\- maybe `.respond()` and `.responded()` if there needs to be two of them?

It will be common to handle errors:

`req.respond({ body }).catch(err => console.log(err));`

so it would be good to have a nice name not only for those who ignore errors ;)

Alternatively, `.respond()` might return an object instead of a bare promise, so maybe something like this could be more explicit:

- `await req.respond({ body }).result`
- `await req.respond({ body }).finish()`
- `await req.respond({ body }).finished`
- etc.

If the idea is to make it less confusing for people who are likely to misuse the for-await loop, then maybe a hint in the property/method name of the returned object would be a better indicator of what is going on than the `Async` suffix?

Also as a bonus if an object is returned then there will be no harm in `await`ing on it by accident:

- `await req.respond({ body })` (await is a no-op if `.respond()` doesn't return a thenable)

**Comment by sholladay** [comment]
Personally, I don't think `req.respond({ body }).finish()` makes it any clearer that we should not `await` in the loop.

The fact that we shouldn't `await` in the loop is an outgrowth of the desire for concurrency. It kind of feels like there is a need for new language syntax, wherein the inside of the loop is allowed to `await` but the iteration happens without awaiting. It would be pretty similar to this common pattern...

```js
Promise.all(foos.map(async (foo) => {
    // Allowed to await, but does not block the iteration of map()
    await doSomeStuff(foo);
}));
```

**Comment by rsp** [comment]
@sholladay I'm not convinced with the `req.respond({ body }).finish()` name either, but then again the current behavior of `req.respond({ body })` is fine with me.

As for your `for-async` loop:

> ```ts
> for async (const foo of foos) {
>    // Allowed to await, but does not block the iteration of foos
>    await doSomeStuff(foo);
> }
> ```

I usually do it like this:
```ts
for await (const foo of foos) (async () => {
    // Allowed to await, but does not block the iteration of foos
    await doSomeStuff(foo);
})();
```

or just use `.then()` instead of await:

```ts
for await (const foo of foos) {
    doSomeStuff(foo).then(async (x) => {
        // Allowed to await, but does not block the iteration of foos
        await someMoreStuff(x);
    });
}
```
but I **really** like your `for-async` loop, even if it would just desugar to `for await (const foo of foos) (async () => { ... })();` it would be very useful and elegant.

**Comment by dd-pardal** [comment]
Might be an unpopular opinion, but I think this is not a good use for `for await ... of`.  was made for iterating over things that can be iterated over (normally lists). And a server is not really something that can be iterated over. I think a callback (like `listenAndServe()`) is a better fit for this use case .

*`for await ... of` wasn't made for replacing callbacks completely.*
