### ISSUE TITLE
discussion: Cache .d.ts files during compilation

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3564]
This idea popped up in my head several times, so I'm writing it down to get some feedback. I believe we might further speed up TS compilation by caching type declaration files alongside compiled JS and source maps. 

We already support stubbing out files with `.d.ts` files using `@deno-types` directive and use it for `prettier` to greatly speed up its compilation (https://github.com/denoland/deno/issues/2490#issuecomment-530097749). 

Going a step further we might stub out as many source files as possible with type declaration which could be emitted during compilation process to speed up subsequent compilation.

So idea is as follows:
1. during compilation of `some/file.ts` check if in TS cache there's corresponding `.d.ts` file that is valid
2. if there is suitable `.d.ts` use this file to do type check (as if `@deno-types` was explicitly used)
3. if there is no `.d.ts` file compile the same way as now
4. during caching of `.js` and `.map` file cache `.d.ts` file alongside them
5. on subsequent compilation `.d.ts` file is available and can be stubbed to perform type check

This solution requires to emit type declaration alongside compiled output, but I think it should be trivial.

CC @kitsonk for opinion

**Comment by kitsonk** [comment]
I doubt you will get a perf performance if the original source is `.ts` files.  The only reason we got the performance improvement with prettier is because TypeScript was parsing the whole of `prettier.js` instead of just using the `.d.ts` file.  In fact I would expect it would actually be slightly slower, because we would have to write out the `.d.ts` files, which would be a minor overhead on the compiler as well as the infrastructure.

Are there performance issues you are currently seeing?  I suspect cache hits of this type would be very low, because a compilation of something else would likely only cause the compiler to acquire the imports of that something else to understand the types that it depends on.

I still think the biggest performance improvement is to warm up the compiler in some fashion.  I still have ideas on that and really need to get around to do it.  Then if we still have a performance problem, this _might_ be worth pursuing, but I still doubt it.
