### ISSUE TITLE
DenoAsyncWrite must do implicit flush during write()

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#3565]
During upgrade to Tokio 0.2 I had to add implicit `flush` during `write()` op.

https://github.com/denoland/deno/blob/46d76a7562025374600a7f866dfc68c1b7e268e9/cli/ops/io.rs#L231-L234

https://github.com/denoland/deno/blob/46d76a7562025374600a7f866dfc68c1b7e268e9/cli/ops/io.rs#L361-L380

I had no problems without `flush` locally, failures occurred during CI runs ([especially on Ubuntu](https://github.com/denoland/deno/runs/364286737)) and appeared in various tests. 

The reasons for why that situation happens are not really known and current solution with `flush` should be treated as a band-aid. 

Eventually we need to figure out what's happening and remove calls to flush (or make it explicit op `flush()`).

Ref #3418

**Comment by kevinkassimo** [comment]
Is this `flush` causing a performance hit to `deno_tcp`, benchmrk of which seems to degrade after Tokio 0.2 upgrade?

**Comment by bartlomieju** [comment]
> Is this `flush` causing a performance hit to `deno_tcp`, benchmrk of which seems to degrade after Tokio 0.2 upgrade?

Most likely

**Comment by caspervonb** [comment]
Been a while, so checked if this is still the case, it is and still cannot reproduce locally.
The problem here seems just be that stdout is buffered on CI so, what if we add flush ops and expose them to Deno.Writer implementations?

**Comment by bartlomieju** [comment]
@piscisaureus PTAL

**Comment by canonic-epicure** [comment]
I've just stumbled upon this issue. My program is using only `Deno.stdout.writeSync()` calls. At the end of it, I'm calling `Deno.exit()` to provide an exit code. And.. some of the output is not printed on the screen! If I remove the `Deno.exit()` call, the output is printed (but then, how do I provide an exit code?)

Can the "flush" call on the `stdout` object be exposed to the user?
Or, can Deno provide the facility for setting a "delayed" exit code? (similar to Node's `process.exitCode = value`, which provides the code to be set, when process exits)

Both would work for me.

Please advise, as a user (programmer) I'm finding this experience quite unpleasant.

**Comment by bartlomieju** [comment]
@canonic-epicure it seems like a separate issue. I never had problem with synchronous writing. Could you open a new issue and provide reproduction code?

**Comment by piscisaureus** [comment]
self ping @piscisaureus

**Comment by canonic-epicure** [comment]
@bartlomieju I tried to create a minimized reproduction code, but all seems to work in it. Putting my ego aside, its probably something in my app (async gap somewhere). And I guess it works in Node, because Node is doing soft-exit. I'll be checking this.

Sorry for the hassle.

**Comment by piscisaureus** [comment]
> @canonic-epicure it seems like a separate issue. I never had problem with synchronous writing. Could you open a new issue and provide reproduction code?

Agree, if @canonic-epicure's issue is reproducible, it'd warrant a separate issue.

**Comment by piscisaureus** [comment]
On the original issue:

The need to call `flush()` arises naturally from the fact that `async fn write()` is really just a convenience wrapper around [`poll_write()`](https://docs.rs/futures/0.3.19/futures/io/trait.AsyncWrite.html#tymethod.poll_write). `poll_write()` can only return `Poll::Pending` (aka "I did nothing, try again later maybe?") or `Poll::Ready(..)` (aka "I did what you asked me to do, no further action needed").

If for whatever reason the AsyncWrite-able thingie needs to do some internal buffering, it is possible that neither `Ready` nor `Pending` are super appropriate for `poll_write()` to return. 
It might have done something with your data (e.g. compressed it into a buffer) so it can't return `Pending`; if it did, it would be ok for you to change your mind and call poll_write with some other data. 
At the same time it might have to do some more work to finish processing (e.g. send the compressed data to a socket) so returning `Ready(..)` also doesn't seem right. The AsyncWrite contract says that in this case `poll_write()` should return `Ready(..)` anyway, and it is the caller's responsibility to call *some* `poll_xxx()` function again after that. 

Very often this `poll_xxx()` like function that ensures that written data gets processed completely is the next `poll_write()` call. Sometimes it is `poll_shutdown()`. But if there is no more data to write and no desire to shut down, the only way to ensure that `poll_write()` data gets fully processed is by calling `poll_flush()`.

That's the only semantic `poll_flush()` has; it does not evict caches or make `fdatasync()` syscalls or such.

Many if not most AsyncWrite types implement `poll_flush()` as a no-op, when it is not it'll do work that otherwise gets done by the next `poll_write()` call. Therefore,

> During upgrade to Tokio 0.2 I had to add implicit flush during write() op.

I think this is more correct than it was before, and I don't believe that it has any performance impact.
