### ISSUE TITLE
Why is hyper still required as a dependency (in Errors)?

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#3607]
I came across this question while going through the deno codebase.
* reqwest was added an an http client in https://github.com/denoland/deno/pull/2822 (to replace hyper)
* however, hyper still is used in deno_error.rs https://github.com/denoland/deno/blob/76e44ddfd0d286335107de28bae06c6f962abf13/cli/deno_error.rs#L219-L229

Why is this dependency on hyper required?

**Comment by bartlomieju** [comment]
We use `reqwest` for our HTTP client which relies on `hyper`. [`reqwest::Error`](https://docs.rs/reqwest/0.10.1/reqwest/struct.Error.html) does not contain a lot of useful information but we can downcast it to underlying `hyper` error to get that info. Unfortunately `reqwest` does not reexport any types from `hyper` so we need explicit dependency on it. I guess it doesn't matter much because it's already used by `reqwest` anyway.

This bring another topic which is https://github.com/denoland/deno/issues/2635 quick grep through a code base does not yield a single usage of:
- `HttpUser`
- `HttpClosed`
- `HttpCanceled`
- `HttpParse`
So we should consider removing them and rename `ErrorKind.HttpOther` to `ErroKind.Http`.

CC @ry

**Comment by bartlomieju** [comment]
Fixed in #3662
