### ISSUE TITLE
Translate all the documentation into Spanish

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [denoland/deno#3803]
Hello, I would like to be able to translate all the documentation into Spanish, could you take that task?

**Comment by Soremwar** [comment]
I would be glad to colaborate into this as well, however I think this is an issue for the Deno webpage rather than Deno crate

**Comment by ry** [comment]
Thank you for the offer, it would certainly be helpful for spanish-language users. That said, we're early in development and maintaining just the english documentation is a struggle. I also don't speak Spanish, so wouldn't be able to properly review changes. That's all to say, please go for it, but it should be done in a separate repository. Let us know if this happens! I'm closing this issue, since it's not something we will take on.

**Comment by kitsonk** [comment]
The community does a decent job of making information available in other languages.  A list can be seen here: https://github.com/denolib/awesome-deno#resources-in-other-languages and I am sure contributions in Spanish would be very welcome there.
