### ISSUE TITLE
Deno.run rename args to cmd

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#3891]
From the code:
UNSTABLE: Maybe rename args to argv to differentiate from Deno.args Note the first element needs to be a path to the binary.

I would suggest `cmd` over both options. This makes it more clear that you are specifying both the binary command and its arguments. This should help remove confusion over Deno.args.

**Comment by PandawanFr** [comment]
Wouldn’t “cmd” imply a string to represent the entire command rather than an array of strings for each argument? 

I’m not saying it’s a bad idea, just that I find it weird for the API to expect an array of strings if you’re essentially just sending one command. (That might need to be a separate Issue/Feature Request, but allowing for multiple commands, or with &&, would be great).

**Comment by brandonkal** [comment]
Perhaps. But the way I see it is that the array contains the command + args.
So args alone is a bit odd.
Another option is `exec`.

`&&` is a shell feature. So you can already do `args: ['sh', '-c', 'echo hello && echo goodbye']`

**Comment by ry** [comment]
I think "cmd" is a good name...
When making this change we ought to provide an error message for people using "args" and the API should remain unstable.

**Comment by humancalico** [comment]
@bartlomieju Can I work on this?

**Comment by ry** [comment]
@humancalico go for it

**Comment by ry** [comment]
fixed in https://github.com/denoland/deno/pull/4444 by @humancalico (thanks!)
