### ISSUE TITLE
Use null instead of Deno.EOF for read return types

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#3932]
Throughout `cli/js` and `std`, there are return types that look like `number | Deno.EOF`, `Uint8Array | Deno.EOF`, `ServerRequest | Deno.EOF`. These are a pain to use and force a proprietary type for no reason. With `null` we can use JS's null checking syntaxes to extract the important type.

**Comment by kevinkassimo** [comment]
Past discussions: https://github.com/denoland/deno_std/pull/444
(There was quite a bit discussion on `null`)

**Comment by kitsonk** [comment]
Also, I believe we could add `assertNotEOF()` in order to narrow types to remove it I believe.

**Comment by nayeemrmn** [comment]
I also want to point out that `null` just became a lot more powerful with nullish coalescing etc.

I think a custom null symbol is only needed for unions with generic types: `T | NULL_SYMBOL` where the lib needs to be able to tell apart `NULL_SYMBOL` from a possibly nullable user-supplied type. `Deno.EOF` just seems redundant, and Deno is supposed to avoid proprietary stuff like this.

https://github.com/denoland/deno_std/pull/444#issuecomment-496841065:

> Using `null` is useless in non-strict mode.

This is the only counter-argument I could glean. Is it still relevant, and will we be strict by default any time soon?

**Comment by kitsonk** [comment]
Ok, I have a slightly stronger opinion on this now... `fetch()` returns a `Response::body` and `Body::read()` returns a `Promise<number | Deno.EOF>`... This leaks the Deno namespace into non "standards" based code which is bad, because workers do not include the Deno namespace, but do include `fetch()` according to our typings, and that means they would have no way in theory of checking for `Deno.EOF`.

I have no problem with `Deno.EOF` for other `Deno` APIs, but it certainly should leak into other things.

cc/ @bartlomieju

**Comment by nayeemrmn** [comment]
Wait, why is there a `Body::read()`? That's not standard.

https://github.com/denoland/deno/blob/87c329c45ac0e3382c115793094317df15cbe5bf/cli/js/fetch.ts#L38?

**Comment by bartlomieju** [comment]
@kitsonk @nayeemrmn that's interesting topic, just yesterday I talked with @ry about it. 

I'm not sure that `fetch` should return a body that is a resource in the first place. This leads to the fact that you need to consume body or else it will leak (https://github.com/denoland/deno/issues/3982). Does it work like that in the browser?
As for `null` instead of `Deno.EOF` I guess it makes sense given the example presented.

**Comment by nayeemrmn** [comment]
@ry Thoughts on this? Not much time left to make the change.

**Comment by ry** [comment]
@nayeemrmn I'm working on it.

**Comment by bartlomieju** [comment]
Discussed this issue yesterday - we have a sentiment to remove `Deno.EOF` however it might cause more harm than good. Namely: if we remove `Deno.EOF` in favor of `null` then there are 2 very distinct "falsy" values returned from `Deno.read()` - `null` and `0` - this might lead to unexpected behavior if conditional check is sloppy:
```
const nread = Deno.readSync(10, buf);

// bad:
if (!nread) { // both `null` and `0` will pass this conditional

}

// good:
if (typeof nread !== "number") {}

if (nread === null) {}
```

**Comment by kitsonk** [comment]
> this might lead to unexpected behavior if conditional check is sloppy

As in the problem with all of JavaScript, right?  The problem is that it makes it really hard to provide spec compliant features with the current behaviour.
