### ISSUE TITLE
Expose fetch related types in the global scope

### ISSUE THREAD

**Issue by dstaley** [denoland/deno#3974]
It'd be nice to have the following types from `__domTypes` exposed in the global scope:

- `HeadersInit`
- `RequestMode`
- `RequestInit`

(I'm sure there's more types, but these are the ones that I ran into that weren't exposed like they are in TypeScript.)

**Comment by bartlomieju** [comment]
Makes sense, this will require changes to `cli/js/lib.deno.shared_global.d.ts`. A test case presenting those types are exposed is highly desired

**Comment by timonson** [comment]
I just found myself in the need of this as well.

At the moment, when somebody wants to make a client library - meaning for both deno and the browser - this person can't use one universally compatible type because deno uses `__domTypes.RequestInit` and TypeScript uses `RequestInit`.

If there is another simpler way of doing this, please let me know.

**Comment by kitsonk** [comment]
No, there isn't a simpler way.  These just need to be exposed like some other ones already are.

**Comment by dstaley** [comment]
I believe this can be closed! Looks like it was fixed in https://github.com/denoland/deno/pull/4687
