### ISSUE TITLE
Problems with using async interators for HTTP server in std

### ISSUE THREAD

**Issue by dd-pardal** [denoland/deno#4029]
Why is an async iterator used instead of a listener for the API for (https://deno.land/std@v0.30.0/http/server.ts)? It can cause problems, for example:

```ts
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  const data = await fetchDataFromSomewhere();
  req.respond({ body: data });
}
```

This code was adapted from the [README example](https://deno.land/std@v0.30.0/http/README.md). It seems right, however there's one big problem: the fetching of data will block all requests coming in. In other words, the next request will only be processed when and if the data arrives. Some solutions are:

```ts
for await (const req of s) {
  fetchDataFromSomewhere().then( data => {
    req.respond({ body: data });
  });
}
```
```ts
for await (const req of s) {
  (async function() {
    const data = await fetchDataFromSomewhere();
    req.respond({ body: data });
  })();
}
```

These aren't pretty. I'm sorry if I'm missing some obvious better solution.

It also seems counter-intuitive to me. There's no list of requests to iterate, only connections to react to.

I would prefer something like this:

```ts
import { serve } from "https://deno.land/std/http/server.ts";
const s = serve({ port: 8000 }, req => {
 const data = await fetchDataFromSomewhere();
 req.respond({ body: data });
});
console.log("http://localhost:8000/");

```

I understand that this is due to TCP conections also being handled this way, which also doesn't make sense to me.

Please correct me if I'm wrong and sorry for my bad(?) English.

**Comment by nayeemrmn** [comment]
I like them because they have very transparent semantics that belong directly to the language and provide much more control. I think this is just the more idiomatic way of doing it now. Why implement our own listener registries and things like that instead of doing async the JS way?

If preferable it's easy to adapt an async iterator to a callback API, but the same can't be said of the reverse. This is the more minimal choice in a sense.

It's true that doing things like this will require getting used to being careful about what's blocking what. Ref #3555. FWIW, your second solution would normally be written by actually extracting a non-anonymous async function and calling it without `await`.

```js
async function respond(req) {
  const data = await fetchDataFromSomewhere();
  req.respond({ body: data });
};

for await (const req of s) {
  respond(req);
}
```

**Comment by kevinkassimo** [comment]
@dd-pardal There is another API you could use: [listenAndServe](https://deno.land/std/http/server.ts?doc#listenAndServe)

**Comment by dd-pardal** [comment]
Thanks. I haven't notice that API.
