### ISSUE TITLE
file_server.ts is not setting the correct content-type header when serving index.html

### ISSUE THREAD

**Issue by agusbena** [denoland/deno#4056]
When file_server.ts is serving the index.html, the browser is not rendering the page because it is receiving text/plain header for the content-type.

**Comment by zhmushan** [comment]
see https://github.com/denoland/deno/pull/3423#discussion_r352273793
In fact, we should set the `content-type` according to extname, but this will cause inconvenience to browse `.ts` files. In previous versions, some files were downloaded directly instead of displaying the content on the browser, so this was temporarily set to `plain`.
IMO, we can browse files in a way similar to [deno_website2](https://deno.land/std/http/)

**Comment by agusbena** [comment]
Thanks @zhmushan for the clarification!

So is there a basic webserver for Deno anywhere? like http_server from node? i google but didnt found anything.
If there isnt any yet, whould you agree if I upgrade file_server.ts have a mode like Node's http_server or what you would do? 
I do really want so bad to use Deno for the project i am doing, loving it very much so far.
Thank you very much!

**Comment by zhmushan** [comment]
Ideally, html files should be rendered instead of displaying the code directly.

But we will face this issue, if we use the http-server model directly:
Most deno developers often need to browse `typescript` files, but `.ts` extname has been defined as a video file.

Because of the name of `file_server`, I prefer to use it as a file explorer on default mode, and the http-server mode can be enabled by configuration. And we still need to listen to other developers' suggestions.

**Comment by agusbena** [comment]
Fair enough, I agree. So probably we could provide a dedicated web server script like Node's http_server? 
Hopefully anybody that thought about it can leave their comments here.
Thank you!

**Comment by zhmushan** [comment]
@agusbena fixed in #4555 
This issue should be closed
