### ISSUE TITLE
bug: Property 'Err' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by gil0mendes** [denoland/deno#4089]
Hey 👋 

I'm using the latest version of Deno (0.34.0) with the latest Std library and I'm getting the following errors: https://d.pr/i/sAxrRr

I'm using the following import:
```
export { walk } from "https://deno.land/std/fs/mod.ts";
```

There is something that I'm doing wrong?

**Comment by bartlomieju** [comment]
Hey @gil0mendes, `v0.34.0` does not include `Deno.Err` as it was introduced after the release. The problem is that you use untagged import from `std/` which pulls `master` branch (which does include `Deno.Err`). To fix the issue use tagged URL (`https://deno.land/std@v0.34.0/fs/mod.ts`). `Deno.Err` (or probably `Deno.errors` #4067) will be released in `v0.35.0` in a few days.

**Comment by lewislbr** [comment]
Thanks @bartlomieju, I was running into the same issue.

**Comment by gil0mendes** [comment]
Thanks for the explanation, I think that maybe I'll try to compile Deno, I would love to try to contribute a bit, I hope 🙏 ... closing issue 😄
