### ISSUE TITLE
deno upgrade

### ISSUE THREAD

**Issue by ry** [denoland/deno#4191]
This is a new subcommand (which should be written entirely in Rust) that can download the newest deno executable.

Something like this:
1. Check github for latest version
2. Compare against current version
3. If newer version exists, download newest into temp dir
4. replace `std::env::current_exe()` with new.

Should not use github API.  Use https://github.com/denoland/deno_install/blob/master/install.sh for guidance.

**Comment by axetroy** [comment]
Talk about the problems encountered before

In Windows, after downloading a new Deno executable, the file cannot be replaced directly because `the file is using by process`

Solution:

rename `executable` to another name `executable_old`
and move `executable_new` to `executable`

There are already some Deno version management tools
https://github.com/axetroy/dvm
https://github.com/justjavac/dvm
https://github.com/imbsky/dvm

**Comment by bartOssh** [comment]
Is it possible that I can work on it ?

**Comment by ry** [comment]
@bartOssh go for it

**Comment by bartlomieju** [comment]
Done in #4328
