### ISSUE TITLE
Discussion: encoders/decoders and protocols

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#4203]
I wonder what your stand is on implementing encoders and decoders for standard formats like

- [ics](https://en.wikipedia.org/wiki/ICalendar)
- [vcf](https://de.wikipedia.org/wiki/VCard)
- [xml](https://en.wikipedia.org/wiki/XML)
- etc.

I would be in support to have an official deno approved module for each of these since npm has lots of different ones with

1. weird names
2. intransparent code
3. deviant syntaxes

In that sense the discussion is also open for standard protocol/client implementations like

- [ftp](https://en.wikipedia.org/wiki/File_Transfer_Protocol)
- [ftps](https://en.wikipedia.org/wiki/FTPS)
- [smtp](https://de.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol)
- [smtps](https://de.wikipedia.org/wiki/SMTPS)
- etc.

and databases like

- mysql
- mongodb
- postgresdb
- etc.

I have seen that there are modules like [deno-smtp](https://github.com/manyuanrong/deno-smtp) or [deno-mysql](https://github.com/manyuanrong/deno_mysql)  but they are out of date and do not work in the current version of deno.

What is the official stand of deno?

**Comment by ecyrbe** [comment]
I'm no deno maintainer, but in my point of view, there is a big downside having a lot of those implemented in deno (especially databases).
The more you add to deno, the more it becomes a nightmare to maintain. Node grew big, because it was minimal and let everybody build upon it.

my stance is this one :
- if there is a w3c specification for it, deno should ask itself if it should implement it. sometimes it might not make same (like webrtc)
- if there is no w3c specification, but an rfc that is small enough, deno should also ask itself if it has any benefit in implementing it (like jwt tokens that are for me more important than the ones in your list)
- if there are none of the above, i think deno should have no business implementing them.

**Comment by sunsetkookaburra** [comment]
I don't see implementing the file formats such as XML as being an issue, there are already parsers for TOML and YAML so adding XML to std would be reasonable. 
Things such as FTP and SMTP are a possibility, but extra work to maintain. SMTP does however appear in go's standard library, which would seem to make it more of a candidate.

As for databases, these are quite specialised and officially including one may annoy people who use another and lead to bloat in deno's std should all of them be added.
I personally think that adding interfaces similar to the ones in go's database/sql (and driver) pkg would not be a bad idea in deno std. This would require minimal effort if we go with the interfaces already found in go's database pkg.

An example of this module's usage:
```typescript
import { DB } from 'std/db/mod.ts';
import { openmysqlDB } from 'x/mysql/mod.ts';

const db: DB = await openmysqlDB({options});

let result = await db.query('SELECT * FROM Table WHERE Table.field = {value}', {
  'value': 2
});
// result
// [{'field': 2, 'other': 3}, {'field': 2, 'other': 4}]
```
Database might alternatively provide an interface for a method that accepts a condition function (with an input of a row, and return of a row or null), for those less familiar with SQL.

Obviously some more though could be put into this, and some proper discussion would be needed. But I think a Database interface, or similar, in deno std would be helpful for anyone implementing a database as a third party module.

**Comment by timreichen** [comment]
#6794

**Comment by timreichen** [comment]
#7906
