### ISSUE TITLE
True parallelism?

### ISSUE THREAD

**Issue by ArturFormella** [denoland/deno#4216]
Do you plan to provide any kind of true parallelism or shared memory? It would be a game changer :)

**Comment by krnik** [comment]
[Wasm threads](https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md) is the only way I think will be possible anywhere in the future.

**Comment by ry** [comment]
web workers provide parallelism

**Comment by ArturFormella** [comment]
ok, my question was vague.
I was thinking about features known from Java

```
class mySharedObj {
  constructor() {
    this.counter = 0;
  }
  inc () {
    this.counter++;
  };

  dec () {
    this.counter--;
  };
}
const shared = new mySharedObj();

const task1 = new Thread( new Runnabe() => {  // execute in separate thread and use current memory context
  shared.inc();
})

const task2 = new Thread( new Runnabe() => {    // execute in separate thread and use current memory context
  shared.dec();
});

task1.start();
task2.start();
await task1.join();
await task2.join();
console.log(shared.counter);
```

**Comment by kevinkassimo** [comment]
@ArturFormella I would assume what you want is hard to achieve, since it might imply you want to have closures that is able to capture environment variables and share memory. I believe this is hard to achieve since v8 does not really offer too many options here, and the mechanism of sharing memory is mostly through `SharedArrayBuffer` with `Atomics` but not for other types. (the closest thing might look like [this](https://github.com/microsoft/napajs/blob/master/docs/api/zone.md#-zoneexecutefunction-args-any--any-args-any-options-calloptions-promiseany), but based on its requirement I believe it does something like structural cloning or plain serialization and is not really sharing memory)

There is https://github.com/GoogleChromeLabs/comlink that hides the complexity of workers

**Comment by kitsonk** [comment]
And we wouldn't support any model that isn't part of v8 or a browser standard.
