### ISSUE TITLE
issue with camelcase use in fs api

### ISSUE THREAD

**Issue by Mayowa-Ojo** [denoland/deno#4295]
I get the following error when trying to use the exists and existsSync methods:

`error TS2551: Property 'readdirSync' does not exist on type 'typeof Deno'. Did you mean 'readDirSync'?`

Error points to the following file and other instances:
```ts
// https://deno.land/std/fs/copy.ts
// ...
 const files = await Deno.readdir(src);
```
is this supposed to be camel-cased?

**Comment by cknight** [comment]
There was a recent API change in Deno which renamed `readDir` to `readdir`.  While the lack of camelcase can be confusing this was an intentional change to match most other platform/runtimes API of reading a directory.  This change is on the master branch of code but not yet released. At a guess, you may want to link to this instead:
```
https://deno.land/std@v0.35.0/fs/copy.ts
```
Assuming, of course, that you are using the latest release (v0.35.0).

**Comment by Mayowa-Ojo** [comment]
resolved. Thanks for your time
