### ISSUE TITLE
window.close()

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4382]
~~`window.close()` should be equivalent to `Deno.exit(0)`~~ It is actually more complicated than that: `window.close()` waits for `fn` in `setTimeout(fn, 0)` and `Promise.resolve().then(fn)` to complete but not ~~`Promise.resolve().then(fn)` or~~ `requestAnimationFrame(fn)`. [see it yourself](https://gist.github.com/KSXGitHub/e446d95bea54e489d365452d8c92505c)

**Comment by kevinkassimo** [comment]
We don't have `requestAnimationFrame` so that is out of scope.
Actually `Promise.resolve().then(...)` still fires in your given example (which is totally expected since done microtasks are depleted before macrotasks). Also the last `new Promise()` thing won't work due to missing handlers.

**Comment by KSXGitHub** [comment]
@kevinkassimo Didn't notice the mistake. You're right.

**Comment by KSXGitHub** [comment]
@ry You closed this because it had been implemented or wontfix?

**Comment by ry** [comment]
Sorry I was skimming and mistakenly thought this was resolved. 

We still don't have `window.close()` and we should - exact behavior to be hashed out in tests. I think exit(0) is fine for a first pass.

**Comment by KSXGitHub** [comment]
@ry Maybe not `exit(0)` but `Promise.resolve().then(() => Deno.exit(0))` or `setTimeout(() => Deno.exit(0))` as initial implementation.

**Comment by kevinkassimo** [comment]
@KSXGithub Per [spec](https://html.spec.whatwg.org/multipage/window-object.html#dom-window-close) I believe it would be better to be implemented as `setTimeout` with 0 delay, since it mentions about “queue a task” (we don’t really distinguish task sources atm). I was originally worried about that `Deno` namespace might not always be present, but seems to be fine here since this is a method only present on `window`, and in our case the MainWorker (not WebWorker), where Deno ops are fully registered (even if `Deno` namespace can be removed if we were ever to implement such as a sandboxing feature)

**Comment by KSXGitHub** [comment]
@ry The implementation in https://github.com/denoland/deno/pull/4474 is welcomed, but it is [not perfect](https://github.com/kevinkassimo/deno/blob/d76abc67ac202702cffbfaa697d94616a85158f3/cli/js/runtime_main.ts#L43). I think this issue should be re-opened.

**Comment by ry** [comment]
@KSXGitHub Let's start a new issue with a better title. I think for many use cases @kevinkassimo's first pass impl will suffice.
