### ISSUE TITLE
Improve window.close() implementation

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4490]
Currently, `window.close` as implemented by https://github.com/denoland/deno/pull/4474 relies on 2 layers of microtask (a setTimeout call within a promise call) unlike browser's implementation which relies on macrotask. ~~As a consequence, [this file](https://github.com/kevinkassimo/deno/blob/d76abc67ac202702cffbfaa697d94616a85158f3/cli/tests/058_tasks_microtasks_close.ts) will not print `setTimeout 3`, but it should.~~

**Reference:** You may create a static server for [these files](https://gist.github.com/KSXGitHub/259c44084fc8b58d1f67afaba01d3eda) and use Chrome to open `index.html` to test.

**Comment by kevinkassimo** [comment]
@KSXGitHub Actually it shouldn't print `setTimeout 3`, per experiment I did before (since that timer would not be ready when there are no more other ready tasks). The main problem here is that if there are more new `Promise.resolve().then(() => setTimeout(() => {}, 0))` they should also have the timer fire due to timer being ready.

Essentially to make the behavior correct, we have to find a way to force `window.close()` be the last task that is only fired when all other *ready* timers are fired. This implies that having `window.close()` itself being a timer task would have the issue that there might be more timers pushed to queue after it being pushed, and by the moment task for closing is run, these extra timers also technically should have been ready, yet won't be fired due to process exit before they have a chance to run.

**Comment by KSXGitHub** [comment]
@kevinkassimo I didn't notice 100ms delay in your code. Sorry.

**Comment by KSXGitHub** [comment]
@kevinkassimo Anyway, the only way to make it perfect is to have a proper event loop.
