### ISSUE TITLE
How to deal with IIFE javascript modules?

### ISSUE THREAD

**Issue by cdbattags** [denoland/deno#4658]
Consider this:

```js
;(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    global.moment = factory()
}(this, (function () {})
```

On import using:

```ts
import * as moment from '../node_modules/moment/moment.js'
```

I then get a failure:

```
Compile file:///Users/cbattaglia/projects/dtw/dtw-annotations/src/deno-test.ts
error: Uncaught TypeError: Cannot set property 'moment' of undefined
► file:///Users/cbattaglia/projects/dtw/dtw-annotations/node_modules/moment/moment.js:6:19

6     global.moment = factory()
                    ^

    at file:///Users/cbattaglia/projects/dtw/dtw-annotations/node_modules/moment/moment.js:6:19
    at file:///Users/cbattaglia/projects/dtw/dtw-annotations/node_modules/moment/moment.js:7:2
```

Any way around this with maybe some meta-programming or is this fundamentally not supposed to work in deno?

**Comment by kitsonk** [comment]
This type of module is commonly referred to as a UMD module.  Deno only supports ES modules.  It does not natively support other module formats like CommonJS/AMD/UMD/etc...

In particular, Deno loads this file, like all other files as a script file.  That means the `this` that is being passed into the factory is not a reference to the global scope, in fact it is just `undefined`, which then causes the module to fail to load.

Moment doesn't currently have an ESM distribution itself, otherwise you would be able to load it more directly or use https://pika.dev/cdn.  But it does appear that JSPM provides an ESM distribution: https://dev.jspm.io/moment.

**Comment by cdbattags** [comment]
How would I go about using this ESM as an import with deno then?

And is this more or less an ok way to go about researching/prototyping with deno for now?

I'm more than happy to debug through unmatched apis in deno/node/browser when I get to that point but at least to get started.

**Comment by Soremwar** [comment]
import moment from 'https://dev.jspm.io/moment';
