### ISSUE TITLE
console.log throws with special object (object extends Promise.prototype with Object.create)

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#4659]
```javascript
const customPromise= Object.create(Promise.prototype, {then:..., catch:..., finally:...});

console.log(customPromise);
```
It throws a type error.
```bash
error: Uncaught TypeError: Invalid argument
► $deno$/web/console.ts:454:37
    at createPromiseString ($deno$/web/console.ts:454:37)
    at createObjectString ($deno$/web/console.ts:565:12)
    at stringify ($deno$/web/console.ts:294:14)
    at stringifyArgs ($deno$/web/console.ts:679:14)
    at Console.log ($deno$/web/console.ts:723:7)
    at <unknown>:1:9
    at evaluate ($deno$/repl.ts:64:34)
    at replLoop ($deno$/repl.ts:153:13)
```

```bash
deno --version
deno 0.39.0
v8 8.2.308
typescript 3.8.3
```

Same example works well on 0.38 and before.

**Comment by bartlomieju** [comment]
CC @mhvsa

**Comment by Drunpy** [comment]
What would be the expected result here? ` [object Promise]`?

**Comment by grosto** [comment]
![image](https://user-images.githubusercontent.com/19875911/78672595-2a3f7d00-78e1-11ea-8477-4b0625a98107.png)

That's how it should behave.  

`customPromise` is `instanceof` Promise object, but it's not a JS promise because the constructor is never called(it does not have promise state). There is a `get_promise_details` function which throws if passed value is not promise. Ideally it would return none or error, and then object can be formatted with raw object formatter.

**Comment by ry** [comment]
Probably caused by 30fdf6dc83d3a9d44436528959c39d3eab14cbbb

**Comment by Drunpy** [comment]
I would like to work on this.

**Comment by bartlomieju** [comment]
@mhvsa worked on Promises

**Comment by bartlomieju** [comment]
No longer relevant.
