### ISSUE TITLE
Remove Deno.symbols namespace

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#4870]
We shouldn't have a namespace for a type, it removes the opportunity to group them some other logical way. For example a symbol that had to do with errors might instead go in the `Deno.errors` namespace. `Deno.symbols` impedes that. Sometimes a symbol might need to be more ergonomic than `Deno.symbols.foo`, for example `Deno.EOF` wasn't put in there.

**Comment by kevinkassimo** [comment]
I am kind of reluctant to do this change. One major issue is that moving them out and spread across would mean we have to name them in a way that conveys the information that they are symbols. For example, `Deno.symbols.customInspect`, if placed elsewhere or back directly to under the `Deno` namespace, might be mistaken as a name for a function.

If we were to move all symbols out, we should probably instead name all of them as `Deno.customInspectSymbol` or similar (it should not live under `console` IMHO, not a standards thing). `EOF` is a special case that due to its common appearance it might be fine to keep its current form.

**Comment by nayeemrmn** [comment]
> One major issue is that moving them out and spread across would mean we have to name them in a way that conveys the information that they are symbols. For example, `Deno.symbols.customInspect`, if placed elsewhere or back directly to under the `Deno` namespace, might be mistaken as a name for a function.

This sums up why I've also been reluctant, but here's my current take.

The closest thing that exists to a naming convention for symbols as property keys is to name them like you would the regular key, creating a very desirable ergonomic when it's put into practice:
```js
class SomeObject {
  doSomething() {
    // ...
  }

  [doSomethingElse]() {
    // ...
  }
}
```
From this perspective, the shared convention between regular method names and symbols as method keys is unavoidable and will eventually be accepted. I don't think we should try to dodge this by oddly using Hungarian (?) for this one type, when the source of the confusion you describe is mainly just decreasing unfamiliarity with symbols. At least that's how I see it.

What would one be trying to do with `Deno.customInspect()`, assuming they need to have read the doc one way or another? If someone finds themselves in that situation, it's definitely just an unfamiliarity with symbols rather than our API specifically.

**Comment by kitsonk** [comment]
In JS, well known symbols are properties of `Symbol`.  This follows this convention for Deno.  I would not like to spread them out.  Well known symbols also follow the camelCase convention.

**Comment by nayeemrmn** [comment]
Hmm, I thought the `Symbol` namespace was just a matter of avoiding name conflicts for things that had nowhere else to go, like `Symbol.iterator`. Now that I look at the built-ins there are lots of String related symbols that could have easily gone in the `String` namespace.

Okay, once `Deno.EOF` is removed we'll be consistent about it.
