### ISSUE TITLE
eval cache

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#4883]
It would be nice to see the option to cache compilation of eval content.

i.e. `deno eval "source" --key abc`
If the hash has not changed for the specified cache key, the compiled JavaScript can be used instead.

This would simplify using deno as a scripting target.

**Comment by kevinkassimo** [comment]
Personally I don't see an explicit key can be very useful (also it can be hard to use -- you will need separate ways to remember the key yourself. It might be better to use the hash of source itself as key). Also `eval`s are normally one-time evaluation on the fly -- otherwise an explicit script should be a better option. Could you give an explicit example where an actual script does not fit the scenario?

Also `deno eval` without `-T` flag (for TS) should not really compile anything, so cache for normal JS eval does not really make sense (unless we want to cache the evaluation output -- which does not make sense if operation has side effects)

`deno eval` does create in-memory "fake scripts" to help with module resolutions. There can be an option to dump the TS source compilation result to a file for "caching", yet still I don't think it makes much sense.

**Comment by brandonkal** [comment]
Well an explicit key could be optional. I would assume source hash alone is not enough if relative imports are used and the same script is used in different direectories. What I was thinking was something like "shasum:optionalkey"

Wasn't aware of TS being off by default here. That seems off.

This issue was about caching TypeScript, specifically a Makefile alternative that uses markdown blocks for targets.

Implementation would be simpler if deno handled the caching. And that makes sense to speed up eval TS performance everywhere.

**Comment by brandonkal** [comment]
A workaround could be to write information to the source input as a JavaScript comment. Then using the hash as the key alone would work.

**Comment by kitsonk** [comment]
eval doesn't support TypeScript at the moment.  Seems like you are trying to solve a problem that doesn't exist yet.

**Comment by brandonkal** [comment]
?
`deno eval -T compiles and execute TypeScript.
