### ISSUE TITLE
Add cargo-deny to CI

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#5006]
https://embarkstudios.github.io/cargo-deny/index.html

`cargo-deny` provides checks for security advisories and licence checks. 

It'd be very useful to add it to CI to ensure all dependencies have proper licenses and we're up to date with dependencies.

**Comment by Sparkenstein** [comment]
Need some more inputs on this one. The integration of `cargo-deny` with CI is easy but to configure it, it's better if maintainers decide which checks to perform and where to fail etc. Writing short introduction about `cargo-check` checks below so that you don't need to go through the entire docs. It performs 4 types of checks:

- advisories
- licenses
- bans
- sources

as the names suggest these checks look for security vulnerabilities etc, licenses information, deny/allow specific crates and sources location respectively. I went though the recommended configuration, and here's the configuration I came up with: https://github.com/denoland/deno/compare/master...Sparkenstein:cargo-deny . note that I am not familiar with Github CI so I referred `cargo-check`s recommended configuration from the docs.

Now the question is which of these checks would you like to perform in CI? Also what should be the severity of these checks? for current configuration, only Licenses checks are failing as there are few UNLICENSED crates. (You also need to evaluate carefully which licenses should be allowed explicitly in the config). for other checks there are couple of warns about deprecated checks and duplicate entries etc.

**Comment by bartlomieju** [comment]
@Sparkenstein thanks for detailed analysis. For different checks:
- advisories - should be a hard error
- sources - only allow official crates.io, otherwise hard error
- bans - multiple versions should be a warning, the rest hard error
- licenses - I'll get back to you on the list of allowed licences (for sure it'll be MIT), but it should be a hard error as well

Could you point out which crates are unlicensed?

**Comment by bartlomieju** [comment]
@Sparkenstein please open a PR, it will be easier to iterate on living code :)

**Comment by Sparkenstein** [comment]
@bartlomieju the respective PR was closed recently I believe this issue can be closed as well
