### ISSUE TITLE
How to programmatically generate default tsconfig?

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#5040]
Reference: https://deno.land/std/manual.md#typescript-compiler-options

> Following are the currently allowed settings and their default values in Deno:
>
> `{...tsconfig.json data...}`

This is presumably not fixed/stable and will change in future versions. I can generate types using `deno types`. How can I get the current tsconfig.json in a programmatic way?

**Comment by Lonniebiz** [comment]
Perhaps you could just read the file and then parse it using [JSON.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)?

**Comment by jsejcksn** [comment]
Read which file? @Lonniebiz

**Comment by kitsonk** [comment]
> How can I get the current tsconfig.json in a programmatic way?

This is a complex issue, because there are certain settings that are meaningful only to Deno, given the fact that it is the TypeScript host, so just outputting it likely wouldn't produce useful results.  For development purposes, it is best to use an editor plugin because it sets the defaults and overrides the module resolution logic.

Outside of an editor, what would be the use case?  In most cases where you are using something like `tsc` in addition to Deno, you would just setup your `tsconfig.json` as required for `tsc` and pass it to Deno via `--config` and Deno will let you know what it is ignoring in order to ensure it can run the transpiled JavaScript.

**Comment by jsejcksn** [comment]
@kitsonk For setting up a custom development environment (instead of using a plugin or extension) in a version-managed way, having the ability to subscribe to the active binary's defaults.

**Comment by bartlomieju** [comment]
Thanks to @orta Deno config is now available here: https://github.com/tsconfig/bases/pull/12

**Comment by orta** [comment]
Yeah, the tricky thing for deno users here is that it comes vendored from npm (TypeScript / vscode will use the node path resolution to find it in the `"extends"` field) - though grabbing the tsconfig file directly from unpkg could be feasible too.

**Comment by kitsonk** [comment]
@orta well this wouldn't be used by the Deno runtime at all, it would be used by those who are trying to mimic enough of Deno somewhere else, so it being in a npm package is not a limiter there.

**Comment by jsejcksn** [comment]
It seems like this might be more important in consideration of #7732.

**Comment by jsejcksn** [comment]
Not stale

**Comment by tani** [comment]
@jsejcksn I have written up a new proposal about `deno.json` including `tsconfig.json`. Please give us your feedback. Thanks. #12781

**Comment by kitsonk** [comment]
@dsherret feels like this is something that should be in the scope for [dnt](https://github.com/denoland/dnt).

**Comment by lucacasonato** [comment]
`deno init` generates a `deno.json` that can contain compiler options. We're not going to create anything else that generates tsconfig options in the foreseeable future.
