### ISSUE TITLE
server using port 0, can't access to the random port

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#5102]
Ctrl+Z stopped Deno run
but I don't know why, after another `deno run` the port of the server (was 8080) were still in use.
so I tried to use a random free port with the 0.

after a console.warn(server), I got:
```
Server {
 listener: ListenerImpl { rid: 5, addr: { hostname: "127.0.0.1", port: 34263, transport: "tcp" } },
 closing: false,
 connections: []
}
```
but when I tried to access to the port with `server.listener.addr.port`, I had this message:
```
error TS2339: Property 'port' does not exist on type 'Addr'.
  Property 'port' does not exist on type 'UnixAddr'.
```
it doesn't make sense. it seems like port is not defined on type Addr (obvious but confusing)

**Comment by SyrupThinker** [comment]
You need to assert that the `transport` is `"udp"` or `"tcp"` so that TypeScript knows that your [`Addr`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.Addr) is a [`NetAddr`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.NetAddr) and not possibly a [`UnixAddr`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.UnixAddr), which does not have a `port` field.

**Comment by SRNV** [comment]
ok thank you

**Comment by zjopy** [comment]
Please consider asking questions on StackOverflow instead. This is a public issue tracker and not intended for personal code review. Also asking in the [Chat](https://discord.gg/TGMHGv6) might help clear questions beforehand.
