### ISSUE TITLE
deno rationale vs pure rust

### ISSUE THREAD

**Issue by erf** [denoland/deno#5140]
As a person who was on board the node.js train a while back, I think the technology stack for `deno` is the best possible, and it looks like a promising successor to `node`.

That said, I wonder if anyone would elaborate on why we need a Javascript / Typescript runtime engine, or what the biggest advantages is with this, compared to using pure Rust for servers and more.

Is it so people are able to build things with a language and technology they already know, and not have to compile code, or are there other benefits in addition to this.

Good luck on 1.0 :-)

**Comment by ry** [comment]
I'm of the opinion that dynamic languages are useful tools. It's nice to be able to throw together a script quickly - whether that's for manipulating some data, renaming a bunch of files, defining a computation graph for TensorFlow, or prototyping a website - the fast iteration cycle provided by dynamic languages is quite useful.

We are quite deeply into Rust. When you're writing a VM (as we are), or a database, or a kernel, there isn't a better choice. But I still find myself writing scripts.

Deno isn't trying to be a platform for writing databases. It's trying to be a small and simple dynamic language utility tool - a better python, bash, ruby, node - where very complex script can be programming in a single file (rather than a project directory).

Thanks!

**Comment by erf** [comment]
Thanks, great answer!
