### ISSUE TITLE
The github description gives a bad impression of overconfidence to me

### ISSUE THREAD

**Issue by ahungry** [denoland/deno#5162]
It reads:

    "A secure JavaScript and TypeScript runtime https://deno.land/"

I think this should be reworded into something more akin to:

    "A security conscious JavaScript and TypeScript runtime https://deno.land/"

(or any similar statement - "security minded", "security first" etc.)

As is, "secure" is a measurable qualifier that becomes false and untrue as soon as an insecure feature is discovered (such as the --allow-run flag).

Software that is "secure" is imho all or nothing (0 known vulnerabilities), in which case "secure" is still questionable (you can prove software is not secure - but the most you can do with a proof of "secure" is ensure there are no known vulnerabilities - but you can't really prove there never will be any in the future).

On a personal level, it also comes across in a bragging fashion - as if its claiming any programming language which doesn't qualify their own implementation with the "secure" qualifier is therefore "insecure".

**Comment by Soremwar** [comment]
Deno is secure by default. It doesn't have side effects or access to anything outside the application code it's actually running.

That's why security flags exist. So YOU can poke holes in the sandbox to give access to what you need, but it also makes it YOUR responsibility to use this wisely and prevent any side effects this may cause.

Will people use `allow-run` or `allow-all` to throw the sandboxed context out of the window? Some will. But they will be discouraged to do so, and more so, they will be conscient of the security concerns that may bring, unlike other runtimes

Under this context, Deno can definitely be called a secure runtime. It's the user the one with the responsibility to keep it that way
