### ISSUE TITLE
example: https://github.com/denoland/deno/blob/master/docs/examples/file_system_events.md

### ISSUE THREAD

**Issue by jacobdo2** [denoland/deno#5207]
On MacOs 10.15.4, `.watchFs` labels FSEvents as either `create` or `modify`. 

`modify` is fired off for updating, deleting and cloning a file.

**Comment by lucacasonato** [comment]
What exactly is the issue here?

**Comment by jacobdo2** [comment]
The `event` `kind` should reflect more precisely the operation that is done with the file, e.g. `kind` should be `delete` when a file is deleted and not `modify`.

**Comment by bartlomieju** [comment]
We're constrained by the output of [`notify`](https://github.com/notify-rs/notify) crate that is used for `Deno.watchFs` API. Unfortunately that crate doesn't return proper operations in every situation.

**Comment by ParseDark** [comment]
Same Problem. In the Mac platform: Catalina 10.15.7. 

I want to monitor the delete file event. Or rename the event. But it's very hard to know more information. Such as is file change or dir change? Is remove or modify operation.

But I just can see the create and modify event. Does this document maybe have some error? Because actually we just have two event type in the mac os platform: "create" and "modify".

```
interface Deno.FsEvent

kind: "any" | "access" | "create" | "modify" | "remove"
paths: string[]
```

**Comment by ParseDark** [comment]
> We're constrained by the output of [`notify`](https://github.com/notify-rs/notify) crate that is used for `Deno.watchFs` API. Unfortunately that crate doesn't return proper operations in every situation.

I can understand have some tech challenges. But I think these should be posted to the document. And we will know the thing. Because it is a platform issue.
