### ISSUE TITLE
re-exported types turn into any

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#5219]
`test1.ts`
```ts
import {bar} from "./test2.ts";

const a: bar.foo = 123;
```
`test2.ts`
```ts
export * as bar from "./test3.ts";
```
`test3.ts`
```ts
export type foo = boolean;
```
this should not work, but it does. I tried this in node and this will fail to compile, whereas deno will just go on as normal.

**Comment by fox-cat** [comment]
this seems to only be an issue when using the `export * from "module"` syntax

when just re-exporting the type "foo" (e.g.)
```typescript
export { foo } from "./test3.ts"
```
it seems to work as intended

**Comment by kitsonk** [comment]
I think it is related to this, which is being fixed in TypeScript 3.9:

> ### export * is Always Retained
> In previous TypeScript versions, declarations like export * from "foo" would be dropped in our JavaScript output if foo didn’t export any values. This sort of emit is problematic because it’s type-directed and can’t be emulated by Babel. TypeScript 3.9 will always emit these export * declarations. In practice, we don’t expect this to break much existing code.

What happens if there is functional code in `test3.ts`?  Like an exported function or enum?

**Comment by fox-cat** [comment]
it works fine when using `export * from "module"` _(at least, for me)_
the issue only occurs when using `export * as x from "module"`

**Comment by kitsonk** [comment]
again, both with types only and functional code that doesn't get erased?  I think the problem is that there really isn't anything there at runtime to export, so the compiler has nothing to create to hang off the symbol `bar` and so it is mistakingly erasing it and it really is a TypeScript challenge versus a Deno one, but would need to investigate more.

**Comment by fox-cat** [comment]
yes, both with types only and functional code that doesn't get erased
when exporting with `export * as x from "module"`, no matter what is in the module, deno seems to allow `x.anything` as a type

**Comment by kitsonk** [comment]
😖 😕 🤦

**Comment by crowlKats** [comment]
so i guess temporary solution is to export some piece of logic (ie a const) just so the types exist?

**Comment by fox-cat** [comment]
i dont think that fixes it but it's definitely worth a try

**Comment by crowlKats** [comment]
ye nope that does nothing. should have expected that as i have some enums as well... so we still aint sure what the issue is...

**Comment by jsejcksn** [comment]
How about the `import type`/`export type` syntax?

Relevant release notes:

- [Type-Only Imports and Export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export)
- [`export * as ns` Syntax](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#export--as-ns-syntax)

**Comment by crowlKats** [comment]
no difference

**Comment by kitsonk** [comment]
Something might be going wrong with `ts.preProcessFile()`... we have had that before where that didn't detect all the dependencies, and when that happens we get issues like this (basically the module turning into an `any` module.  Since the `export * as ns` is newish, I bet they didn't update `ts.preProcessFile()`, it has never really gotten the love it needs.

Need to investigate further, but that seems like it.

**Comment by bartlomieju** [comment]
In Deno 1.0.1 `ts.preProcessFile()` is no longer used. @crowlKats can you check if this problem still persists?

**Comment by crowlKats** [comment]
yep it indeed works now as it should.
