### ISSUE TITLE
console.log and console.table don't use colors

### ISSUE THREAD

**Issue by Speykious** [denoland/deno#5229]
The `console.log` and `console.table` functions don't use colors when displaying objects. Here is an example for the `console.log` example.
![image](https://user-images.githubusercontent.com/13885008/81581347-e7286c00-93ae-11ea-91e2-e0c706773d29.png)

**Comment by Speykious** [comment]
I made this issue to say that **I am working on it myself**. I also noticed that the indentation string used is one space `" "`. It should be 2 instead, and I'm gonna fix it. Maybe I'll also add the ability to change the default indentation level in the future.

**Comment by kitsonk** [comment]
Effectively duplicate #3165.  We should tie work on this to that issue (and ensure we follow the precedent set that we try to align to Node.js for this type of output).

It is also good to get agreement on something from some of the core contributors, so you don't waste time an effort on something that won't align to the direction.  Not saying this would be the case, but adding colors everywhere isn't necessarily a good thing, but especially because certain colors and formatting have accessibility concerns.

**Comment by Speykious** [comment]
Ok. I'll keep that in mind. I did see a "NoColor" boolean in the code though... I assumed it was used to trigger them, and it is in fact used in the color wrapper functions.

About the core contributors, what can I do to ask them such a thing? The only thing I have been doing for now is discuss about things with other people on Deno's discord server chat room.

**Comment by kitsonk** [comment]
> The only thing I have been doing for now is discuss about things with other people on Deno's discord server chat room.

Opening an issue, and giving time for debate and response is the best course of action.  It can take a day or so for folks to look at it and give guidance.

**Comment by Speykious** [comment]
Oh, fair enough. I'll do that next time.
