### ISSUE TITLE
Add log method "always" for logging non-erroneous statements that need to always be rendered

### ISSUE THREAD

**Issue by matthewadams** [denoland/deno#5281]
In most logging APIs, the only way to ensure that you're statement gets logged is to use the highest log level method, like `log.critical` in deno's case (or `log.fatal` in other logging frameworks).  Problem is, not all statements that you want to always log are erroneous, critical, or fatal in nature.

This issue requests the addition of a new log level method, `log.always`, that always logs the statement regardless of the current logging level.  This allows a caller to always log statements deemed interesting (like config settings, etc) but that are not necessarily error/fatal/critical.  It's numeric value can be the same as `log.critical`, but just has a different default formatter that uses `ALWAYS` instead of `CRITICAL`.

Tagging @cknight after the great work on fixing https://github.com/denoland/deno/issues/5142 with https://github.com/denoland/deno/pull/5192.  Also tagging @ry for his opinion.  WDYT?

**Comment by alisabzevari** [comment]
Can you provide examples of this concept from the popular logging libraries in other ecosystems?

I haven't seen this concept in java or .net or nodejs.

**Comment by matthewadams** [comment]
This concept _doesn't exist_ in _any_ logging systems.  That's the problem.  Deno calls the highest level (AKA the level above `error`) `critical`, other logging systems call it `fatal` ([log4j](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html#FATAL), [bunyan](https://github.com/trentm/node-bunyan#levels)).

If I want to _always_ log, say, my config values, I don't want to have to use `critical` to do it, because that smells like there was a problem.  There's no problem; I just want to always log my config.

Capice?

**Comment by alisabzevari** [comment]
I think other libraries don't have this concept because naturally logging is a diagnostics tool which comes with a cost (performance costs and probably storage cost). So, if you are sure that your system is stable to some extent and as a result, you have increased the `logLevel` to `fatal`, you probably don't care about what is current configuration settings (`info` level logs).

IMO, that's the nice thing about the logLevels. You can raise the bar and reduce the clutter as the system becomes more stable.

**Comment by matthewadams** [comment]
@alisabzevari I feel like deno should not be opinionated about this.  @cknight What do you think?  In the same way that [inline & lazy logging](https://github.com/denoland/deno/pull/5192) was missing, I've always felt an `always` level has been missing.  The idea is that `always` is used sparingly, and documented so.

**Comment by cknight** [comment]
With regards to the concept of 'always', I think this is really talking about more granular support for logging concerns, where some concerns need higher log levels than others.  This functionality is already available.  For example, the API allows you to do this:
```
import * as log from "https://deno.land/std@v0.51.0/log/mod.ts";
await log.setup({
  // Setup a single handler for use by both loggers
  handlers: {
    file: new log.handlers.FileHandler("DEBUG", {
      filename: "./log.txt",
    }),
  },

  loggers: {
    default: {
      level: "ERROR",
      handlers: ["file"],
    },

    config: {
      level: "INFO",
      handlers: ["file"],
    },
  },
});

const logger = log.getLogger();
const configLogger = log.getLogger('config');

logger.info('I will not be logged since default logger is ERROR or above');
configLogger.info('I will be logged since config logger is INFO or above');
```
As both loggers use the same handler, both will log to the same endpoint, e.g. 'log.txt' in this case.  Therefore, I would be against adding an `always` level since I think the above offers better and more flexible support for your requirement.

**Comment by matthewadams** [comment]
Ah ok.  Wasn’t really aware of this.  Still RTFMing, myself.  :)

**Comment by Jquery-aftergiorgio** [comment]
I verified the response https://stackdev.space/questions/logging-at-the-fatal-level-is-necessary-in-log4j
