### ISSUE TITLE
TextDecoder typedefs out of sync with typescript 

### ISSUE THREAD

**Issue by bordoley** [denoland/deno#5299]
Tested using deno 1.0. 

I'm workin on a library that in theory should be compatible with both Deno and the web, but have run into a few issues with the Deno TextDecoder api typedefs.

https://github.com/denoland/deno/blob/a08a4abac116eda498f8ad2df13b3816ec36c9ad/cli/js/lib.deno.shared_globals.d.ts#L989

1)TextDecoderOptions is not defined as a type for the options argument to the TextDecoder constructor. See: https://github.com/microsoft/TypeScript/blob/933c2949236f38e1255a0aa4564246a3fef1518c/src/lib/webworker.generated.d.ts#L3103

2) decoder.decode, doesn't accept true for the stream optional argument.

**Comment by onsah** [comment]
Hi I am new to Deno and wanted start with this issue. I am trying to fix the problem but some help would be appreciated. 

Firstly, [here](https://deno.land/typedoc/classes/textencoding.textdecoder.html) it seems to be defined correctly. But I couldn't understand from where these typedocs are created. I haven't tried yet but since `TextDecoder` is defined in here
https://github.com/denoland/deno/blob/4fa69e890ee92c3b81beed8c8a2b262db8c905ac/cli/js/web/text_encoding.ts#L408-L410
just changing the type of `options` to `TextDecoder` should fix the first part.

Second problem seems to related with these lines:
https://github.com/denoland/deno/blob/4fa69e890ee92c3b81beed8c8a2b262db8c905ac/cli/js/web/text_encoding.ts#L457-L459
I am not sure how to implement stream option. Maybe checking typescript compiler can help.

**Comment by lucacasonato** [comment]
This was resolved a few releases ago.
