### ISSUE TITLE
Calling Deno.close without an rid results in a panic

### ISSUE THREAD

**Issue by isthisnagee** [denoland/deno#5313]
## How to repro:

```
❯ deno repl
Deno 1.0.0
exit using ctrl+d or close()
> Deno.close(0)
undefined
> Deno.close()
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `rid`", line: 0, column: 0)', cli/ops/resources.rs:34:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
zsh: abort      deno repl
```

It seems like [`close`](https://github.com/denoland/deno/blob/master/cli/js/ops/resources.ts#L17) takes in a `rid` as an argument, so not specifying it is against the function definition. But I'm not sure if a panic is the correct behaviour? Should it throw an error instead?

**Comment by kevinkassimo** [comment]
Actually I think this has been a long debatable aspect of Deno. Personally I was supportive of adding some runtime argument type checks, but there is also a strong advocacy against this since TypeScript would enforce compile time checks that does not introduce runtime cost.

Nevertheless panicking is definitely not good user experience. I would say at least a simple Rust side handling is needed.
