### ISSUE TITLE
Question: Are TypeScript upgrades considered as breaking changes for Deno?

### ISSUE THREAD

**Issue by intrnl** [denoland/deno#5335]
TypeScript doesn't make a distinction between major and minor versions. Each version will have breaking changes, big or small.

So if Deno upgrades the built-in TypeScript compiler, is it a breaking change?

**Comment by ry** [comment]
As long as TypeScript doesn't make a breaking change, we will be able to upgrade.

**Comment by intrnl** [comment]
thanks for confirming!

**Comment by Epskampie** [comment]
So, as a casual observer, this seems like a MAJOR issue to me. Considering that:
* typescript will have breaking changes every release
* deno packages can be written in typescript, but don't specify what typescript version

It seems like deno only really has a few options.
* Stay on tsc 3.9 forever.
* Upgrade typescript, break a lot of deno packages.
* Just strip type info from external packages, run them as javascript. Don't know if this is possible / desired?

**Comment by Soremwar** [comment]
@Epskampie You don't lock to a version of TypeScript, but to a version of Deno

The libraries you use should first make a release using the new version of Deno, so you can upgrade them in your dependencies file/import map

The 'upgrade everything' approach in Node brings some problems, so in JavaScript you should update everything explicitly

**Comment by EricEisaman** [comment]
Even under Node LTS they only issue updates on "critical bugs" and "security fixes".  They don't even attempt to update every one of their dependencies to the latest.

**Comment by Epskampie** [comment]
@Soremwar Yeah, so every package should make/fix releases whenever a new deno appears (if the typescript version changed)? That seem like a major downside to me. In practice it will not happen for a lot of packages.

**Comment by Soremwar** [comment]
@Epskampie Well it's only logical

How can I else guarantee that their code is curated for the last version of Deno?

Every other package in every language does the same, but you just do a command update(where available) and done, you didn't even notice that what I described above happened

JavaScript requires you to be explicit about what you are importing however, so the only difference here and there would be for you to check the packages manually

**Comment by Epskampie** [comment]
@Soremwar Ok, good to know that it works this way!

But I don't think that "Every other package in every language does the same" is true.
Most languages such as for example golang, php, javascript (node) etc have pretty strict backwards compatibility guarantees, so that packages will keep working for a long time.
Typescript is not as strict, and doesn't need to be, since it has (stable) javascript as a compile target. If you then ignore that compile target, it might lead to breakage often, but perhaps it will not be so bad, we'll have to see.

**Comment by Epskampie** [comment]
One more question, if you'll allow me. Sorry if they come across as criticism, deno seems awesome, I'm just learning about it. :-)

If you look at packagist for php, you'll see that packages can specify the minimum php version they support. [example](https://packagist.org/packages/symfony/var-dumper)

Since you just explained that deno packages will also support a minimum deno version, will they be able to specify their minimum version somewhere as well?

**Comment by Soremwar** [comment]
@Epskampie It's up to the developers(ups and downs I know 😥 )

There are breaking changes in PHP as long as I know, so there are modules that won't work in higher versions of not updated

The approach here is to being able to work with both JS (backward compatible) and TS (not forward or backward compatible since it's versions), and leaving it up to the developers is the best option to it

I know it's hard to grasp 😉. But in order to fully support the JS model we need to be as flexible/not convention enforcing as possible

**Comment by Epskampie** [comment]
@Soremwar Ok, thanks for the explanations, I'll be sure to follow deno to see how it works out!
