### ISSUE TITLE
std/node: add buffer module

### ISSUE THREAD

**Issue by EvanHahn** [denoland/deno#5374]
For completeness, we should add a polyfill for [Node's buffer module](https://nodejs.org/api/buffer.html).

**Comment by jamilservicos** [comment]
I believe that many depend on Buffer.
so publishing an alternative to the nodejs buffer commands, could open the door to many migrations and adaptations.
mainly for encryption modules.

but it doesn't have to be exactly a compatibility for the nodejs Buffer, being the same done in C, the deno could include its own version in the native module with aliases for the already known methods, to facilitate the migration from one language to another.

**Comment by seishun** [comment]
I'm currently working on it.

**Comment by ahuggins-nhs** [comment]
@seishun I'd like to contribute, but I find the current work on an implementation a little confusing. I'm trying to understand what the goal is, because I don't understand if the effort is simply to polyfill, or if the effort is to also depend on decoders/encoders provided in deno's std lib.

A polyfill [exists currently](https://github.com/feross/buffer); is there a good reason to roll all "new" code for this instead of porting the previous art with its permissive license? Can you help me understand the direction?

Once I can wrap my head around that, I'll have a better idea of how to spend efforts contributing.
