### ISSUE TITLE
Optional parameter values should be in square brackets in help

### ISSUE THREAD

**Issue by JavaScriptDude** [denoland/deno#5429]
When running ```deno run --help```, several parameters have optional values such as ```--allow-net```, ```---allow-read``` and ```--allow-run```. 

To make it clear to users that the values are optional, the help should show square brackets around the value component like ```--allow-net[=<allow-net>]```

**Comment by guzzur** [comment]
@dorsev and I are on it

**Comment by DaemonicNaymon** [comment]
I'm sure this is pretty much implemented now.
![image](https://user-images.githubusercontent.com/24189525/82126920-2e986900-97b0-11ea-83d6-bc08b044b86f.png)

**Comment by guzzur** [comment]
So @dorsev and I checked it and the conclusion is:

Deno uses clap for argument parsing. For example, `cli/flags.rs` uses clap's `require_equals`([docs](https://docs.rs/clap/2.31.1/clap/struct.Arg.html#method.require_equals)), so the user would need to pass `--allow-write='.'` instead of `--allow-write '.'`.

Also, `cli/flags.rs` passes optional argument to it, that is represented ([docs](https://docs.rs/clap/2.31.1/clap/struct.Arg.html#values-value-notation)) as `<some_optional>` **or** `[some_optional]`.

IINM It is not possible to have `--allow-write[=some_path]` or `--allow-write<=some_path>` with clap as is, only `--allow-write=[some_path]` or `--allow-write=<some_path>`.

I agree with @JavaScriptDude that we need to show that the whole assertion `=some_path` is optional, but it will require to make changes in clap, which is probably out of the scope.

Still, I think we should use at least `--allow-write=[some-path]`, instead of `--allow-write=<some-path>`. WDYT?

**Comment by tunnckoCore** [comment]
The `--allow-net[=<foo>]` makes best sense to me too. If it's not supported by Clap, then it should be promosed and considered.

**Comment by guzzur** [comment]
> If clap was supporting `--allow-net foo` then things would be okay here by outputting `--allow-net [foo]`.

Clap does support `--allow-net foo`, we only need to remove `.require_equals(true)` for that.

> The `--allow-net[=<foo>]` makes best sense to me too

Probably you mean `--allow-net[=foo]`, because `<..>` means _required_, and `[...]` means _optional_, which together mean nothing to me 🤷

**Comment by tunnckoCore** [comment]
> Probably you mean --allow-net[=foo]

Nope. When we have/use the `=` it make sense, otherwise I'm agree that it doesn't.

**Comment by bartlomieju** [comment]
Deno uses `clap` for its CLI parser and previous experience thought that hacking around `clap` functionality is hard and impractical, so we should just stick to the default behavior. 

It seems that `clap v3` is on the way and it might provide more options for configuration.
