### ISSUE TITLE
Let the right tools do the right thing

### ISSUE THREAD

**Issue by fhefh2015** [denoland/deno#5434]
As a front end, it felt right to ditch JS and its series early.

JS is not good enough, in the historical baggage, chaos, bugs, many beautiful name for features, after all, it is a short time to make, originally not used like this.

JS has a monopoly on browsers to make a big deal out of it

The focus should be on refining Webassembly and then making all languages browser accessible.

In the future, browsers want to become mainstream platforms, games, videos, software apps, AI, scientific computing, etc. JS is too confusing to carry

Let the right tools do the right thing.

Stop tossing and turning.

**Comment by Soremwar** [comment]
@fhefh2015 I know you feel in the position to criticize the language, and I get it. JS has quite a history

But to ditch all the work people has put into this language? To evolve it? To make it the most used language in the planet?

Maybe you don't understand it as much, but that is up to you to decide what to work in

You prefer C++? You can't how wrong with it then
Like Java's ease of use? The sky is the limit

In the end, it's all about the implementation rather than the syntaxis used for it. Using WebAssembly still has it's caveats, and actually requires you to do JavaScript in order to use it(for now) and perhaps one day JS will no longer have a place in the browser

In the meanwhile, the community behind this awesome language(creators of the most imaginative, crazy and far-fetched stuff ever made) will continue to grow and evolve

Let the tools do what the developer wants to with them

**Comment by Cyberhan123** [comment]
@fhefh2015 Language is not an obstacle, talent is. We want to make it better, not constantly overturn and redo.It looks like the evolution from python2 to pyhton3, which may be more complicated.I'm confident...

**Comment by ry** [comment]
This is for bugs in the deno software. There's probably a better forum for sharing your general thoughts on  these issues.
