### ISSUE TITLE
Add support for abortable fetch

### ISSUE THREAD

**Issue by dasa** [denoland/deno#5471]
Reference: https://developers.google.com/web/updates/2017/09/abortable-fetch

Also `Request` should have a `signal` property.

**Comment by kitsonk** [comment]
We have had a fairly long term "experiment" in rewritting fetch to fully align to the spec, but also break it out as a seperate "op" crate so we break up the Deno CLI a little more.  Abortable fetch falls into that (first we needed abort controller, which we only added recently).

**Comment by sno2** [comment]
Hi, I see that @kitsonk stated that this would require a lot of work to follow the spec.  However, would it be easier to just do a check right now if the signal is included and if it has been aborted before doing the request?  I could see this use-case being pertinent in the case of being rate-limited in your application so you want to abort all future requests with the `AbortController`.  Of course, you could use your own shared variable to tell if you have been rate-limited, but it still would be valuable because otherwise the `signal` property on `RequestInit` is basically useless except for the events it adds.  Here is the current behavior:

```ts
const controller = new AbortController();
controller.abort();

fetch("https://icanhazdadjoke.com", {
  headers: {
    accept: "application/json",
  },
  signal: controller.signal,
})
  .then((res) => res.json())
  .then(console.log); // still logs this out even though controller was closed before the request even happened
```

log:

```json
{
  "id": "ei3T08EQZob",
  "joke": "Hostess: Do you have a preference of where you sit?\r\nDad: Down.",
  "status": 200
}
```

Expected Output: An error explaining that the request was already closed.

**Comment by kitsonk** [comment]
Fetch has been largely written to align to the spec...  At the time of the comment this wasn't the case.  Ping @lucacasonato on the status of abortable fetch?

**Comment by sno2** [comment]
> Fetch has been largely written to align to the spec... At the time of the comment this wasn't the case. Ping @lucacasonato on the status of abortable fetch?

The aborter API is still not working.  I posted a question that I answered myself with this issue in Discord#help:

![image](https://user-images.githubusercontent.com/43641633/118573554-667e1780-b748-11eb-8668-fea9bd4c90a2.png)

Code:

```ts
const controller = new AbortController();

fetch("https://icanhazdadjoke.com", {
  headers: {
    accept: "application/json",
  },
  signal: controller.signal,
})
  .then((res) => res.json())
  .then(console.log);

controller.abort();
```

**Comment by lucacasonato** [comment]
Yeah, it's still not implemented.

**Comment by kitsonk** [comment]
Yes, I understood that, but is it something that would a) be easy to implement b) status with WHATWG and c) something we would want to implement?

**Comment by lucacasonato** [comment]
a) yes
b) implemented in all browsers (https://wpt.fyi/results/fetch/api/abort/general.any.html?label=master&label=experimental&aligned&q=fetch%20abort)
c) yes
