### ISSUE TITLE
Property 'core' does not exist on type 'typeof Deno'

### ISSUE THREAD

**Issue by crabmusket** [denoland/deno#5525]
```
$ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

Operating systems: Windows 10, Ubuntu 16.04.

When running this Typescript file:

`coretest.ts`
```typescript
console.log(Deno.core.ops());
```

Using this:

```
deno run --unstable coretest.ts
```

The result is:

```
error: TS2339 [ERROR]: Property 'core' does not exist on type 'typeof Deno'.
```

`core` is also not documented in the [typedocs](https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts). Working around it with `(Deno as any).core` works, so the feature is available, it's just not typed correctly.

I found this issue when following the example [here](https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.openPlugin):

```typescript
const rid = Deno.openPlugin("./path/to/some/plugin.so");
const opId = Deno.core.ops()["some_op"];
```

**Comment by buckle2000** [comment]
The end of https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts says **unstable**, so it's unstable. Same as #5536 .

**Comment by crabmusket** [comment]
I was already running with the `--unstable` flag as you can see from the steps above. That issue is a runtime error, this one is a typechecking error; if I disable the typecheck using `as any`, the code runs fine.

**Comment by kitsonk** [comment]
`Deno.core` is not intended to be a public API, therefore it is omitted from type definitions.

**Comment by crabmusket** [comment]
Is it worth noting that in the example, which is in the type definitions, which uses `Deno.core.ops()`? At least noting that the example only works in JS and will fail to work in TS. It's probably unly useful info for plugin developers at this point to be fair.

**Comment by ry** [comment]
Deno.core is one of the places we didn’t finalize before 1.0. It’s necessary to access dispatch for plugins - but it’s generally stuff we don’t want to publicly expose. Unfortunately the current situation is that it’s exposed in the runtime but not in the types. We should probably just add the type definitions, since it’s in JS.

**Comment by crabmusket** [comment]
Since plugins _are_ publicly exposed (albeit behind `--unstable`) maybe `Deno.plugins.ops` or similar could be used as an alias to avoid mentioning `core` at all in the documentation.

**Comment by bartlomieju** [comment]
With native plugins removal in #11152 this is no longer relevant

**Comment by marc2332** [comment]
hi

I am using `deno_runtime` embedded into my app, it adds  with an additional global namespace that contains some functions that ultimately call some ops I have defined in a runtime extension, which means, I need to call `Deno.core.opAsync/opSync.` I wanted to do these functions in a TypeScript file and bundle it with `deno bundle` on the build process of my app. But, I get the error:

```shell
error: TS2339 [ERROR]: Property 'core' does not exist on type 'typeof Deno'.
    return Deno.core.opAsync("send_message_to_core", msg);
```

I see this issue was closed because the main use for it was for the old plugin system, this is not the case for me. What should I do ? 🤔 

ty :)
