### ISSUE TITLE
How to import module from Github

### ISSUE THREAD

**Issue by AbmSourav** [denoland/deno#5543]
I've some code here: `https://github.com/AbmSourav/deno-std/blob/master/index.ts`
```ts
export function helloDeno() {
  console.log("Hello Universe..."); 
}
```

Now how I can use this code using `import` in a project?

**Comment by kidonng** [comment]
`blob` -> `raw`:
https://github.com/AbmSourav/deno-std/raw/master/index.ts

**Comment by AbmSourav** [comment]
on my index.ts I did this
```ts
import { helloDeno } from "https://github.com/AbmSourav/deno-std/raw/master/index.ts";
helloDeno();
```

after running `deno run index.ts` I got:
`Uncaught SyntaxError: The requested module 'https://github.com/AbmSourav/deno-std/raw/master/index.ts' does not provide an export named 'helloDeno'`

**Comment by bartlomieju** [comment]
Try using `raw.githubusercontent.com/` as domain - otherwise GH sends wrong Content-Type

**Comment by AbmSourav** [comment]
tried `https://raw.githubusercontent.com/AbmSourav/deno-std/master/index.ts` also and got the same error...

**Comment by bartlomieju** [comment]
Works fine for me:
```
// test.ts
import { helloDeno } from "https://raw.githubusercontent.com/AbmSourav/deno-std/master/index.ts";
helloDeno()
```

```
▶ deno run test.ts
Compile file:///Users/biwanczuk/dev/deno/test.ts
Download https://raw.githubusercontent.com/AbmSourav/deno-std/master/index.ts
Hello Universe...
```

**Comment by kidonng** [comment]
Try use a CDN: `https://cdn.jsdelivr.net/gh/AbmSourav/deno-std/index.ts`

**Comment by mk0y** [comment]
On denoland homepage it's written:

```
Deno can import modules from any location on the web, like GitHub, a personal webserver, or a CDN like pika.dev or jspm.io.
```

I'm also wondering how to import from GitHub. You only have a function defined, I'm trying to use imports but no luck (no docs). Any ideas?

**Comment by seantcanavan** [comment]
> Try using `raw.githubusercontent.com/` as domain - otherwise GH sends wrong Content-Type

This worked thanks so much! Quick question - the [open ai npm project](https://www.npmjs.com/package/openai) contains type however it's my understanding from SO that Deno [can't import type from node modules](https://stackoverflow.com/a/74005693) so I linked directly to the file I needed via github to get the interface:

`import {     ChatCompletion } from "https://raw.githubusercontent.com/openai/openai-node/master/src/resources/chat/completions.ts";` which seems to have worked great.

Just wondering if this is best practice? Still very new to learning Deno.
