### ISSUE TITLE
failed to run custom build command for rusty_v8 v0.4.2

### ISSUE THREAD

**Issue by offline-pixel** [denoland/deno#5616]
>    Compiling phf_codegen v0.7.24
>    Compiling parking_lot v0.7.1
>    Compiling mio-named-pipes v0.1.6
>    Compiling chashmap v2.2.2
>    Compiling serde_derive v1.0.110
>    Compiling pin-project-internal v0.4.17
>    Compiling futures-macro v0.3.5
>    Compiling tokio-macros v0.2.5
> error: failed to run custom build command for `rusty_v8 v0.4.2`
> 
> Caused by:
>   process didn't exit successfully: `C:\Users\COLLEG~1\AppData\Local\Temp\cargo-
> installHR8ikh\release\build\rusty_v8-fa0d03807bee7530\build-script-build` (exit
> code: 101)
> --- stdout
> static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.4.2/ru
> sty_v8_release_i686-pc-windows-msvc.lib
> cargo:rustc-link-search=C:\Users\COLLEG~1\AppData\Local\Temp\cargo-installHR8ikh
> \release\gn_out\obj
> Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/rusty_
> v8_release_i686-pc-windows-msvc.lib
> Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/rusty_
> v8_release_i686-pc-windows-msvc.lib...
> HTTP Error 404: Not Found
> 
> --- stderr
> Traceback (most recent call last):
>   File "./tools/download_file.py", line 63, in <module>
>     sys.exit(main())
>   File "./tools/download_file.py", line 58, in main
>     DownloadUrl(args.url, f)
>   File "./tools/download_file.py", line 44, in DownloadUrl
>     raise e
>   File "./tools/download_file.py", line 28, in DownloadUrl
>     response = urlopen(url)
>   File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\urllib
> \request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\urllib
> \request.py", line 531, in open
>     response = meth(req, response)
>   File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\urllib
> \request.py", line 640, in http_response
>     response = self.parent.error(
>   File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\urllib
> \request.py", line 569, in error
>     return self._call_chain(*args)
>   File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\urllib
> \request.py", line 502, in _call_chain
>     result = func(*args)
>   File "C:\Users\a\AppData\Local\Programs\Python\Python38-32\lib\urllib
> \request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> thread 'main' panicked at 'assertion failed: status.success()', C:\Users\College
> out\.cargo\registry\src\github.com-1ecc6299db9ec823\rusty_v8-0.4.2\build.rs:229:
> 5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `deno v1.0.0`, intermediate artifacts can be found at `
> C:\Users\a\AppData\Local\Temp\cargo-installHR8ikh`
> 
> Caused by:
>   build failed

Tried to add env variable is as
C:\Users\cl\.cargo\bin;
C:\Program Files\MySQL\MySQL Shell 8.0\bin\;
C:\Program Files\MongoDB\Server\3.4\bin;
C:\Program Files\Microsoft VS Code\bin;
C:\Users\cl\AppData\Roaming\npm;
C:\Python27

Downloaded c++ tools also for cargo to work properly
What to do next ?? How can i install the deno on windows 7 64 bit

**Comment by chrmoritz** [comment]
From `rusty_v8_release_i686-pc-windows-msvc.lib` it looks like you're trying to build a 32-bit version of `deno`. However there are no prebuilt binaries available for a 32-bit version of `rusty_v8` and that's why the download fails. If you really intended to build a 32-bit version, you have to set the environment variable `V8_FROM_SOURCE=1` or otherwise target `x86_64-pc-windows-msvc`.

But if you just want to install the latest version of `deno`, then there are also complete binaries available at the [release page](https://github.com/denoland/deno/releases/latest) or you could use [`deno_install`](https://github.com/denoland/deno_install).

**Comment by offline-pixel** [comment]
@chrmoritz  Thank you for the answer however i am not trying to build a 32-bit version. i just followed the installation instructions and i ran **_cargo install deno_** . how can i get more info on setting the environment variable as x86_64-pc-windows-msvc or v8_FROM_SOURCE=1 ?

**Comment by offline-pixel** [comment]
@chrmoritz  Also what are some important artifacts of deno which are stored in AppData\Local\Temp\cargoXXXXX ???
How they are helpful when installation fails ??

**Comment by chrmoritz** [comment]
`AppData\Local\Temp\cargoXXXXX` is just the temporary dictionary, where the build happens on Windows.

Running `set V8_FROM_SOURCE=1` and `cargo install deno` should build an 32-bit version from source (Note that this would require Python 2.7 to be installed.)

May I ask you how you've installed rust? Did you by any chance installed the 32-bit version of rust or did you run any command to change the target architecture from `x86_64-pc-windows-msvc` to `i686-pc-windows-msvc` like passing a `--target` argument to `cargo install deno`? What's the output of running `rustup toolchain list` (if you use `rustup`)?

**Comment by bartlomieju** [comment]
@piscisaureus PTAL

**Comment by offline-pixel** [comment]
@chrmoritz Hi, Finally i deleted my windows 7 OS and installed ubuntu 20.04 on my laptop.
Steps i followed to install deno on ubuntu 20.04

> 1. curl -fsSL https://deno.land/x/install/install.sh | sh

After this, deno --help was working however deno -V was throwing 'deno' command not found
than digging down a little 

> 2. curl -fsSL https://deno.land/x/install/install.sh | sh | sudo DENO_INSTALL=/usr/local sh

Deno worked like a charm

++ FYI,
I installed rust from here: https://doc.rust-lang.org/cargo/getting-started/installation.html
Also, i have python 2.7 installed and may be upgraded to latest version. Always try to install 64bit version though.

Now, this issue does not serve any purpose for me as i can work on deno now. Keeping it still open, maybe you guys need this info or do whatever. THANKS

**Comment by joebarbere** [comment]
I am getting the same error when running

cargo install deno

or

git clone --recurse-submodules https://github.com/denoland/deno.git
cd deno
cargo build -vv

The error:

Running `/home/joebarbere/code/deno/target/debug/build/rusty_v8-94b7cf34c7208d59/build-script-build`
[rusty_v8 0.4.2] static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_debug_x86_64-unknown-linux-gnu.a
[rusty_v8 0.4.2] cargo:rustc-link-search=/home/joebarbere/code/deno/target/debug/gn_out/obj
[rusty_v8 0.4.2] Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_debug_x86_64-unknown-linux-gnu.a
[rusty_v8 0.4.2] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/joebarbere/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.4.2/build.rs:221:18
[rusty_v8 0.4.2] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `rusty_v8 v0.4.2`

Caused by:
  process didn't exit successfully: `/home/joebarbere/code/deno/target/debug/build/rusty_v8-94b7cf34c7208d59/build-script-build` (exit code: 101)
--- stdout
static lib URL: https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_debug_x86_64-unknown-linux-gnu.a
cargo:rustc-link-search=/home/joebarbere/code/deno/target/debug/gn_out/obj
Downloading https://github.com/denoland/rusty_v8/releases/download/v0.4.2/librusty_v8_debug_x86_64-unknown-linux-gnu.a

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/joebarbere/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.4.2/build.rs:221:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

Some version info:

rustc 1.43.1 (8d69840ab 2020-05-04)

I'm running linux, Pop!_OS 20.04 LTS

**Comment by joebarbere** [comment]
Looking into it further it looks like my issue had to do with python2 not being installed.

python3 is installed by default in Pop!_OS 20.04, which is basically the same as Ubuntu 20.04. Since python2 is EOL, 20.04 doesn't even include it as a package.

Running the following fixed the issue for me:

`sudo apt install python-is-python3`

**Comment by bartlomieju** [comment]
Please try again with latest version. Feel free to reopen if issue persists.
