### ISSUE TITLE
Runtime compiler API doesn't require valid specifier

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#5620]
https://doc.deno.land/https/raw.githubusercontent.com/denoland/deno/master/cli/js/lib.deno.unstable.d.ts#Deno.compile

`Deno.compile()` has an option to take a map of source file. In this option specifiers for files can be written as `/foo.ts`, `/bar.js`. It's against other Deno APIs which require valid specifiers and required to add some hackery to make it work:
https://github.com/denoland/deno/blob/1be7ec47ac3b6e63be2b03245a26e060b8268b5e/cli/module_graph.rs#L172-L181

https://github.com/denoland/deno/blob/1be7ec47ac3b6e63be2b03245a26e060b8268b5e/cli/js/compiler.ts#L605-L617

Discussed this situation offline with @ry are there are two potential solutions:
- require valid specifiers for all files - each specifiers must be a valid URL
- add `baseUrl` option to `Deno.compile()` which will be used to create URLs for each specifier

CC @kitsonk

**Comment by kitsonk** [comment]
They are in theory "abstract" resources... requiring them to be them seems quite illogical to me and doesn't sound like good DX.  Why even provide the `baseUrl` option?  Again, that is just to keep things "tidy" on the inside, and bad DX to force a user to do something that means nothing to them.  I didn't catch it in the PR, but now I understand the problem.  It feels like we could more systematically deal with it by just mangling all the `sources` when they are provided like that without requiring a user to specify a `baseUrl` and basically tell them "please fake this information because we don't want to".

Also, this particular cleanup might want to wait for #4752 (or we move forward with that) and we would have a discreet API for providing sources, instead of the more conflated one and it maybe easier to resolve the modules in a clean way.

**Comment by bartlomieju** [comment]
Resolved in #8192
