### ISSUE TITLE
realPathSync returns paths with UNIX "/" separator on Windows

### ISSUE THREAD

**Issue by srackham** [denoland/deno#5685]
Observed on Deno 1.0.1, for example:

```
PS C:\Users\srackham> deno eval "console.log(Deno.realPathSync('.'))"
C:/Users/srackham
```

Other Deno path APIs return '\\' separated paths on Window e.g. Deno.cwd().

**Comment by kwonoj** [comment]
Peeking this bit looks like issues stemmed from https://github.com/rust-lang/rust/issues/42869. canonicalize on windows returns UNC path, stripping unc host (https://github.com/denoland/deno/blob/master/cli/ops/fs.rs#L584) will leave rest of path do not honor win32 path separator. Given std canonicalize does not provide workaround yet, it looks like stripping via drop-in replacement (https://gitlab.com/kornelski/dunce) seems the easiest way to fix instead of re-implementing UNC stripping logics.

Is this feasible approach accepts PR? if so, would love to try to create one.

**Comment by Ciantic** [comment]
This is important to fix, some libraries might not be working correctly, consider this: 

Imagine using a library A that uses realPath, and library that uses join at some point, one can't compare the paths with === without sanitization which becomes messy.

I think simple fix for this, just replace `/` with `\\` on windows.
