### ISSUE TITLE
url updating [feature]

### ISSUE THREAD

**Issue by rubybb** [denoland/deno#5699]
something that's missing naively in deno is the ability to update imported urls.
here is an existing implementation of it.
https://github.com/hayd/deno-udd

perhaps something like deno update or related would be in order?
I think it'd basically just clear the cache and attempt to find new versions of the files.

let me know if there is already a issue or pull request related to this.

**Comment by sholladay** [comment]
> I think it'd basically just clear the cache and attempt to find new versions of the files.

How would this be different than the `--reload` flag? Deno can already download fresh dependencies with `--reload` and if your dependencies are unversioned, then they will be updated to latest. The problem is that when your dependency's URL includes a version number, that information is opaque to Deno. It has no idea that `https://deno.land/x/pogo@v0.3.0/main.js` is version `0.3.0` of Pogo. That's "just a URL" as far as Deno is concerned.

Parsing version info from URLs is potentially tricky. For example deno.land URLs have the version info formatted differently (and in a different position) than GitHub's URLs. On top of that, there's no requirement to even use semver, so version numbers can be practically anything. Deno could give preferential treatment to certain conventions and the community could try to stick to using them. I think that would be fantastic! Just keep in mind it won't work in all cases.

**Comment by nayeemrmn** [comment]
Deno doesn't have an understanding of the structure used to represent versions in URLs. Third party tools can like https://github.com/hayd/deno-udd are welcome to acknowledge a certain structure and only support those, but Deno will intentionally stay agnostic of that. It only understands URLs and has no native concept of versioning.

**Comment by bartlomieju** [comment]
Not actionable for Deno. As pointed above Deno is agnostic of URL structure and any processing should be done by third party tools.
