### ISSUE TITLE
Please make deno simple(installation) as you download an app( like exe file)

### ISSUE THREAD

**Issue by fisforfaheem** [denoland/deno#5727]
it would help a lot, also make it faster i dont wanna learn node.js

**Comment by rafaelferres** [comment]
Hi @fisforfaheem,
I also agree with you. I took the liberty of creating an MSI deno installer.
https://github.com/rafaelferres/deno-windows-installer

**Comment by Divlo** [comment]
Agreed, the installation should be as simple as Node.js.

**Comment by Yamboy1** [comment]
I'm coming here from a Linux point of view rather than windows, but can I ask what's so hard about running a single command in the command prompt to install deno, considering that you need to use the command prompt / powershell to use deno anyway?

**Comment by Divlo** [comment]
I don't mind, I didn't have problem to install Deno but I don't see why they don't make a .exe file as they did for node.js.

**Comment by alisabzevari** [comment]
Also, Microsoft announced Windows official package manager called [winget](https://github.com/microsoft/winget-cli). It looks like they accept msi or exe in their [manifests](https://github.com/microsoft/winget-pkgs#authoring-a-manifest). So, it makes sense to package deno as an executable for Windows.

**Comment by rafaelferres** [comment]
I think having two problems solved or all! So I created these MSI installers

**Comment by fisforfaheem** [comment]
MSI is the best way, it clearly shows everything in visual way....we are
living in 2020 not everything should be 30 years old..i menat use of
command line it sucks...thats why people use windows 10 instead of hardcore
fans who like Linux

**Comment by sholladay** [comment]
To all the downvoters, I just want to point out that OP's profile mentions that they are trying to learn programming. They're just a beginner. Deno is not yet beginner friendly in a number of ways, including its installation process. We should try to be understanding. I also think English may not be their native language (?). It's quite possible that their comment comes off as more rude than intended.

The command line is significantly more fluid and powerful for experienced programmers. But that's not immediately obvious when first learning it.

**Comment by fisforfaheem** [comment]
Thanks bro, for supporting me, much appreciated. Being a beginner VS studio
windows forms apps builder, Command line seems so difficult to me, not
everyone should be allowed to use it, Their should be an option for GUI
based stuff too. I never used linux *tried ubuntu but didnt liked it. I
believe we should make things easier. not only productive

**Comment by MarkTiedemann** [comment]
> I don't see why they don't make a .exe file as they did for node.js.

I think there's a misunderstanding here.

As it says on the frontpage of the website: _"Ships only a single executable file."_

A Deno release for Windows is shipped in a `.zip` file. For example, the version 1.0.2 release (https://github.com/denoland/deno/releases/tag/v1.0.2) lists the following `.zip` file that can be downloaded on Windows: https://github.com/denoland/deno/releases/download/v1.0.2/deno-x86_64-pc-windows-msvc.zip

If you download the `.zip`, you can right click it, and choose "Extract All...". Open the extracted folder, and you will find `deno.exe`. You can double-click `deno.exe` and you'll be in the Deno read-eval-print-loop, and can start typing and executing JS.

All that the installer command does for you is download the `.zip` (as you can do manually), extract the `.zip` (as you can do manually), and put the location of the `.zip` into your path so you can run `deno.exe` or just `deno` from the command line, rather than having to type the full path, e.g. `C:\some-path\deno.exe` (as you can do manually, too).

So the installer is just for convenience. So you don't have to do those 3 things yourself, but rather the installer will do it for you.

Then again, "installer" is kind of the wrong term on Windows at least. There's no `setup.exe` or `setup.msi` or anything like that needed here. It's just an `.exe` file in a `.zip` file.

**Comment by divy-work** [comment]
Here's what I think:
I don't know how you related "not wanting to learn Node" with a "simpler way of installing Deno". Deno is currently in heavy development and making os-specific installers is not relevant right now.
On behalf of the downvoters, I am not quite sure why a single line command would cause chaos that you would need a one-click installer. 
The command-line installation is like copy-paste-enter!
And being a beginner is no way related to hating terminals - they will be with you throughout the journey.
Have a nice day :)

**Comment by divy-work** [comment]
@fisforfaheem If you hate command lines, how will you even run a Deno script? (Assuming you don't want an executable for that too)

**Comment by Yamboy1** [comment]
@MarkTiedemann I think this misunderstanding, which is a perfect description, is due to how installation is depicted by a majority of a windows users. This comes back to what "install" actually means. If we go to the man page for the install command on linux, it says this "install - copy files and set attributes". The reality is that installation it not just the matter of downloading an executable, in this case an exe, but also copying it into a directory on the PATH, so it can be run from any folder in the command line, and also in most cases to create a start menu shortcut, which is less applicable, but is still not a terrible thing to do.

In the case of windows, most people are still used to the idea of "installers" which handle all of this, and it's fair to say that deno is lacking in an installer. Sure you can download the binary, but that means you have to be in the downloads folder every time you run the application, and you have to add .exe on the end. As a linux user, I personally don't think I could live without my "installers", i.e. the package manager.

This thread has gotten a bit toxic in my opinion (even I got caught in it), and has deviated from what the real issue is, the fact that there is no simple exe installer, which is honestly the norm on windows. A command line approach such as using iwr / wget makes a lot of sense from a linux perspective, but imo it's worth thinking about how we can make the deno installation more ergonomic on windows, so that it fits in better with the general windows ecosystem.

Just my 2c.

**Comment by fisforfaheem** [comment]
Thanks everyone for support, and Love, Hope to learn deno on *windows 10( simple and productive .period). *linux is love too but without that bash thingy...
