### ISSUE TITLE
Allow `deno bundle` to target `ES3`

### ISSUE THREAD

**Issue by wongjiahau** [denoland/deno#5913]
Currently, the code emitted by `deno bundle` is targeting ESNext, which render the code un-executable for environments that does not support ESNext yet. 

Therefore, I wish to run `deno bundle` like this:
```
deno bundle --target="ES3"
```

**Comment by kitsonk** [comment]
`deno bundle` is not intended to target other runtimes than Deno, while the unstable `Deno.bundle()` can support your requested feature (https://deno.land/manual/runtime/compiler_apis#denobundle).

**Comment by ry** [comment]
Should be relatively easy to support in the case there are no exports?

**Comment by kitsonk** [comment]
@ry not really, especially targetting ES3.  The bundle loader is written in ESNext and isn't transpiled (see #4559).  Also, we would want to use `--config tsconfig.json` than supporting individual flags.  We don't allow different targets at the moment (we ignore them) for bundling, and I think we should continue to do so, and focus on the compiler APIs for other targets, because it starts to get really messy.

Even without exports, if a module has TLA, it needs to bubble up to the top level module.  There is down emit for it (TypeScript simply errors when the target is < ES2017).

Also, we would want #5427 to work, especially because it would get really ugly doing the transform for ES3.

**Comment by bartlomieju** [comment]
@kitsonk is this issue still actionable?

**Comment by kitsonk** [comment]
We don't have a lot of tests with swc and emitting other targets based on a config file.  I think the action is to add some tests and if we can get swc to reliable target ES3, then we can close this fixed, if we cannot, we can just close it was a design limitation.  I will add some tests.

**Comment by crowlKats** [comment]
This has been deemed as a design limitation, so closing
