### ISSUE TITLE
Deno.setRaw() throws OS error 6 on Windows

### ISSUE THREAD

**Issue by dd-pardal** [denoland/deno#5943]
This error occurs when launching Deno from Git Bash.

```
user@computer MINGW64 /c/fakepath
$ deno repl --unstable
Deno 1.0.2
exit using ctrl+d or close()
Deno.isatty(Deno.stdin.rid)
true
Deno.setRaw(Deno.stdin.rid, true)
Uncaught Error: O identificador é inválido. (os error 6)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.setRaw ($deno$/ops/tty.ts:8:3)
    at <unknown>:1:6
    at evaluate ($deno$/repl.ts:52:34)
    at Object.replLoop ($deno$/repl.ts:149:13)
```

"O identificador é inválido." is Portuguese for "The identifier is invalid.". This works fine in Node.js. Also, it's possible to move the cursor to anywhere on the Git Bash terminal using the arrow keys, something usually only possible if raw mode is enabled and `stdin` is being piped into `stdout`.

**Comment by guybedford** [comment]
This happens when spawning a Windows Deno process with stdin set to null, so that GetConsoleMode is failing, erroring out at that call in `op_set_raw`.

So the question seems to be what to do about a pseudo-tty environment, where one might want to skip the `GetConsoleMode` and `SetConsoleMode` paths entirely then just have `isatty` returning true after the call.

**Comment by piscisaureus** [comment]
This bug is for a very old version of Deno. When I try this in 1.18.0, it works *for me*:

![image](https://user-images.githubusercontent.com/218257/151278544-09e7d155-867a-4a4f-b685-aaa78a8e3329.png)

Note that ultimately the type of the HANDLE that stdin is attached to is determined by the terminal application, not by the shell, so it might be that this is somehow related to the terminal that @dd-pardal was using.

I'm going to close this issue. If the issue persists in the latest version of deno, please open a new issue and tell us which terminal application you are using.
