### ISSUE TITLE
Upgrade relies on `/proc` (Linux)

### ISSUE THREAD

**Issue by mar-kub** [denoland/deno#5969]
`deno upgrade` relies on `/proc` for Linux systems. This leads to an error if `/proc` is not available (e.g. in a chroot environment).

### Problematic code
https://github.com/denoland/deno/blob/dad551a3a77346d190663003e366dd94ce46626d/cli/upgrade.rs#L101

### Error
```rust
Err(Custom { kind: Other, error: "no /proc/self/exe available. Is /proc mounted?" })
```

See also: https://github.com/rust-lang/cargo/issues/4450 and https://github.com/rust-lang/cargo/pull/4634

**Comment by Spoonbender** [comment]
I'd like to try improving this one

**Comment by Spoonbender** [comment]
Posting to update that I have a working solution, which is based on checking the first command line argument as a fallback. I'm now trying to write automated tests for this fix, and a PR will be dispatched in the next few days.

**Comment by lucacasonato** [comment]
@Spoonbender Were you ever able to get this working? Otherwise I'd be happy to take a look.

**Comment by Spoonbender** [comment]
@lucacasonato i have a solution that works BUT!
1. I was unable to write an integration test that safely tests this
2. I was unable to prove that deno is now installable chrooted; i only managed to prove that it doesn't crash due to lack of /proc access - i don't have enough knowledge in chrooting to setup a working chroot environmet (got stuck on DNS issues).

I can look for my code later on tonight, it might help you. 
Feel free to work on this, i won't be able to in the near future.

**Comment by lucacasonato** [comment]
We have not gotten any other reports of this in 3 years. As such I am going to close this.
