### ISSUE TITLE
TypeError in fetch with HTTP 204 response

### ISSUE THREAD

**Issue by ejones** [denoland/deno#5974]
**To reproduce:**
```
$ deno eval 'console.log((await fetch("https://httpbin.org/status/204")).status)'
```

**Actual output:**
```
error: Uncaught TypeError: Response with null body status cannot have body
    at new Response ($deno$/web/fetch.ts:49:13)
    at fetch ($deno$/web/fetch.ts:329:22)
    at async file:///.../__$deno$eval.ts:1:14
```
version string:
```
$ deno --version
deno 1.0.3
v8 8.4.300
typescript 3.9.2
```

**Expected output**:
```
204
```
For example, this is the current behavior when 200 is used in place of 204:
```
$ deno eval 'console.log((await fetch("https://httpbin.org/status/200")).status)'
200
```

**Comment by marcosc90** [comment]
This is indeed a bug. I'll work on this and submit a fix today.

**Comment by marchiore** [comment]
@marcosc90 can i work on this? i'm looking for a first contribution in deno project.

I took a look and the reason is the validation below, that throw an exception on null body.

https://github.com/denoland/deno/blob/550556e948e750dc64039dcffd311752cf8312fd/cli/js/web/fetch.ts#L48

I think to remove the `[/* 101, */ 204, 205, 304].includes(status)` validation and only let the null body check. what do you think?

**Comment by marcosc90** [comment]
Unfortunately, it's a bit more complicated than that. Since while that will fix the `TypeError` it will not make it spec-compliant. It was an oversight on my end when I refactored Response object to be spec-compliant.

We need to add several tests too, to prevent this from happening again and some of them will require changing `http_server.py` to test null-body status code.

I can't prevent you from working on it, but it's not an easy first issue :)

**Comment by marchiore** [comment]
Ok, no problem I will look for a less complex one to start and familiarize myself with the project architecture.
