### ISSUE TITLE
How to handle with version and dedupe?

### ISSUE THREAD

**Issue by zalelion** [denoland/deno#5979]
#### http://server01/a.jsx
```jsx
import React from "http://server01/react.js";

...
```

#### http://server02/b.jsx
```jsx
import React from "http://server02/react.js";
...
```

#### main.jsx
```jsx
import {A} from "http://server01/a.jsx";
import {B} from "http://server02/b.jsx";
...
return <div>
    <A/>
    <B/>
</div>
...
 
```

**Comment by nayeemrmn** [comment]
What duplication is there, first of all?

**Comment by zalelion** [comment]
@nayeemrmn 

implements a.jsx and b.jsx  import same React library

**Comment by nayeemrmn** [comment]
@zalelion Alright I understand. You have indirect dependencies on React from two different hosts. You can use an import map to redirect one to the other.
`import_map.json`:
```json
{
  "imports": {
    "http://server02/react.js": "http://server01/react.js"
  }
}
```
`deno run --importmap import_map.json main.jsx`

(I recommend doing this selectively for any large duplicated dependency you identify, and just not worrying most of the time.)

**Comment by zalelion** [comment]
@nayeemrmn  yes.  but if more deep dep , i don't know everything.

**Comment by zalelion** [comment]
I think need a module.json for depends. 
```ts
import * as React from "http://x/react/index.ts"
```


### deno will see http://x/react/module.json   only example:
```
{
     name: "React",
     version: "~1.0.0",
     ... something
}
```

if  have module.json and meet some conditions, deno can use single react.js. if no have, only to down and use it.

Of course, many conditions can be added.

**Comment by nayeemrmn** [comment]
> yes. but if more deep depends , i don't know everything.

That's why I said you should generally just not worry about duplication. If the size of downloads is bothering you, and you can identify a big duplicated dependency, you can act on that one selectively. If the version ranges don't align then you have duplication anyway.

> #### deno will see http://x/react/module.json
> example:
> 
> ```
> {
>      name: "React",
>      version: "~1.0.0",
>      ... something
> }
> ```

There are some problems with your proposal.
- Our module resolution wants to stay simple and match browsers.
- Deno has no concept of packages so it wouldn't know where to look for a `module.json` for something like `http://x/react/path/to/file.ts`.
- If I understand how this solves duplication, it allows a dependency to identify with the name "React" and then any other dependency which also identifies as "React" with an intersecting version range will just use the same resources. That allows dependencies to hijack each other quite easily... there's no source of truth this system can rely on. It won't work.

**Comment by zalelion** [comment]
@nayeemrmn  ok , thanks.
closed

**Comment by zalelion** [comment]
@nayeemrmn 

Can I use it like this?  if others agreed.

#### import_map.json:

```json
{
  "imports": {
    "react": "http://server01/react.js"
  }
}

```

#### Other people's code  
http://otherlib/Comp.tsx
```tsx
import * as React from "react";

...

```

#### Me code:
```tsx
import * as React from "react";
import {Comp} from "http://otherlib/Comp.tsx";

<Comp/>
```

**Comment by nayeemrmn** [comment]
@zalelion Yes, that would work. Though it's not recommended for people's code to depend on import maps.

I think the best solution against duplication is for library authors to state, on their website or project README, which host/URL they wish for people to canonically use when importing it.

**Comment by zalelion** [comment]
@nayeemrmn  yes. txs. closed
