### ISSUE TITLE
windows doesn't print emojis correctly

### ISSUE THREAD

**Issue by nyctef** [denoland/deno#6001]
Hi! This is my first time looking at Deno, and it seems to be very exciting :)

I was playing around with the examples from the tutorial and noticed this inconsistency: (using powershell and windows terminal):

```
> deno run https://deno.land/std/examples/welcome.ts
Welcome to Deno 🦕
> deno run --allow-net https://deno.land/std/examples/curl.ts https://deno.land/std/examples/welcome.ts
console.log("Welcome to Deno ­ƒªò");
```

I found that editing `curl.ts` to add the line 
```ts
import { decode } from "https://deno.land/std/encoding/utf8.ts";
```
and replacing the `Deno.stdout.write` line with
```ts
console.log(decode(body));
```
seems to make the downloaded file print out correctly.

**Comment by actual-size** [comment]
Cannot reproduce on macOS 10.15.4:
```
~/Desktop ❯❯❯ deno run --allow-net https://deno.land/std/examples/curl.ts https://deno.land/std/examples/welcome.ts
console.log("Welcome to Deno 🦕");
```

**Comment by MarkTiedemann** [comment]
`Deno.stdout.write` writes UTF-8 data but the console code page may be different.

If you run `chcp 65001` (65001 = UTF-8) first, the output is as expected.

**Comment by nyctef** [comment]
> If you run `chcp 65001` (65001 = UTF-8) first, the output is as expected.

Yep, that works for me too 👍 

Seems strange that `console.log` just works here though - is it doing something different that `Deno.stdout.write` could use? I tried browsing through the source to figure out how `console.log` was implemented, but got lost pretty quickly.

**Comment by MarkTiedemann** [comment]
> Seems strange that console.log just works here though - is it doing something different that Deno.stdout.write could use?

I'd assume that it's calling `SetConsoleOutputCP(CP_UTF8)` before logging but I don't know the internals either.

**Comment by piscisaureus** [comment]
I think it uses WriteConsoleW.

Supposedly `SetConsoleOutputCP(CP_UTF8)` should work, but only on the most recent versions of windows.

**Comment by littletof** [comment]
I just run into the same issue trying to use characters like `∎ (U+220E)` `▒ (U+2592)` with `stdout` (win10 powershell).
> If you run `chcp 65001` (65001 = UTF-8) first, the output is as expected.

Worked for me too, as a temp solution.

**Comment by MarkTiedemann** [comment]
> I think it uses WriteConsoleW.

I think `WriteConsoleW` doesn't set the console code page.

In fact, since other programs may run in the same console afterwards, I think it's best practice to reset the code page before exit:

```cpp
UINT original_codepage;

void init() {
        original_codepage = GetConsoleOutputCP();
        SetConsoleOutputCP(CP_UTF8);
}

void cleanup() {
        SetConsoleOutputCP(original_codepage);
}
```

**Comment by oganexon** [comment]
#6131 
This problem is the same, I couldn't display characters with accents. 
 
The details of the problem are explained, and how to solve it under Windows.

**Comment by piscisaureus** [comment]
> I think `WriteConsoleW` doesn't set the console code page.

That's true, but here's the secret: WriteConsoleW doesn't depend on the code page, it always uses UTF16 (technically UCS2).

**Comment by MarkTiedemann** [comment]
> WriteConsoleW doesn't depend on the code page, it always uses UTF16

Thanks for sharing this! That's good to know.

Well, back to the problem:

I'd assume that `WriteConsoleW` is used for `console.log` and something else is used for `Deno.stdout.write`. Otherwise the output would be the same, right? Perhaps instead of `WriteConsoleW(hStdout, ...)`, it's `WriteFile(hStdout, ...)` for `Deno.stdout.write`? I don't think `WriteFile` handles unicode console output automatically like `WriteConsoleW`.

**Comment by MarkTiedemann** [comment]
@piscisaureus I just traced the two commands using [API Monitor](http://www.rohitab.com/apimonitor). I can confirm that `console.log` is using `WriteConsoleW` whereas `Deno.stdout.write` is using `WriteFile`.

<details>
<summary>Screenshots</summary>
<pre>
> deno run https://deno.land/std/examples/welcome.ts
</pre>

![trace1](https://user-images.githubusercontent.com/7062160/84521542-6f16d400-acd5-11ea-975c-ae9a62af32f5.png)

<pre>
> deno run --allow-net https://deno.land/std/examples/curl.ts https://deno.land/std/examples/welcome.ts
</pre>

![trace2](https://user-images.githubusercontent.com/7062160/84521543-6faf6a80-acd5-11ea-85c5-b941a5fff125.png)
</details>

**Comment by nitrospaz** [comment]
Hi I'm pretty new to all this but I thought this was interesting, see my attached screenshot. I found that the emojis did not display correctly in Windows Powershell (2), Powershell 7.1 (3) or the terminal in VS Code (4) but they do display correctly if you use Windows Powershell or Powershell 7.1 with the new Windows Terminal app (1). So maybe the Terminal is able to interpret the unicode properly where as the Powershell by itself isn't a full unicode native.
![Emoji fail 2020-06-19](https://user-images.githubusercontent.com/36904927/85185684-df7ba300-b249-11ea-9dee-ffc25068cb16.png)

**Comment by pedropaulosuzuki** [comment]
#8199

**Comment by prcdpr** [comment]
```powershell
[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8
```

did the trick for me while `chcp 65001` didn't work (I was testing Windows Terminal using Powershell 7.1).

To keep this setting persistent, you can create a `%userprofile%/Documents/PowerShell/profile.ps1` with the line above.

**Comment by LitoMore** [comment]
Same issue when using the [request permissions API](https://deno.land/manual/runtime/permission_apis#request-permissions) in Windows Terminal.

![image](https://user-images.githubusercontent.com/8186898/107876864-ae9c5c80-6f03-11eb-9614-811750db1838.png)

**Comment by midnightnoon** [comment]
Perhaps access to stdout could be standardized. Currently all the `console.*` methods use `stdout().write_all()` internally, but `Deno.stdout.write` uses `Deno.File`.  Ideally a call to `Deno.stdout.write` would just proxy to `stdout().write_all()` which would have the benefit of automatically handling UTF8 support on Windows environments where switching the code page isn't an option due to legacy software crashing due to it being a "beta" feature from Microsoft.

https://github.com/denoland/deno/blob/4d6f412b0b8a415a084605e5353ef46c36bcbe27/core/ops_builtin.rs#L76

As a side note, it's becoming increasingly difficult to consider Deno as a serious platform for our cross-environment development since the core developers treat Windows issues as one of their lowest priorities. I'd gladly pick up some slack and dive into these issues to make Deno have parity on Windows, but I would need some incentive since it would involve taking time to learn Rust as well as time away from my other projects.

**Comment by bartlomieju** [comment]
@piscisaureus PTAL

**Comment by tch1121** [comment]
Invalid set code page
![image](https://user-images.githubusercontent.com/89089119/142461861-25535659-9ea9-4369-bf1b-c8fd1b94f89f.png)
