### ISSUE TITLE
Stdout doesn't handle accents with TextEncoder

### ISSUE THREAD

**Issue by oganexon** [denoland/deno#6131]
When running:
```typescript
import { red } from "https://deno.land/std@0.50.0/fmt/colors.ts";

const text = "accents: é è à ç";

console.log(text);
console.log(red(text))

Deno.writeAllSync(Deno.stdout, new TextEncoder().encode(text));
```

I get: 
![image](https://user-images.githubusercontent.com/52361520/83917135-b0a7fc00-a776-11ea-922f-9f8a7f2d80dc.png)

Seems like the TextEncoder doesn't handle non ASCII characters, how can I change the encoding?

**Comment by oganexon** [comment]
I use Windows.
The screenshot was on Git bash and here on cmd:
![image](https://user-images.githubusercontent.com/52361520/83918559-4f355c80-a779-11ea-8193-93365f823df8.png)

**Comment by caspervonb** [comment]
Your example works for me also; is this old school _cmd.exe_ or the new fancy one?

**Comment by oganexon** [comment]
It's the same on every terminal:

Classic cmd:
![image](https://user-images.githubusercontent.com/52361520/83922397-8a875980-a780-11ea-8b61-7787376d5fd1.png)

cmd on Windows Terminal:
![image](https://user-images.githubusercontent.com/52361520/83922456-9b37cf80-a780-11ea-8483-4e2a1d54fb18.png)

Powershell on Windows Terminal:
![image](https://user-images.githubusercontent.com/52361520/83922504-b1de2680-a780-11ea-9d96-59e55a188e16.png)

Git Bash on Hyper:
![image](https://user-images.githubusercontent.com/52361520/83922533-bc98bb80-a780-11ea-9ed3-5c0e457dbc13.png)

**Comment by lucacasonato** [comment]
This is probably not a very satisfying answer, but this does make sense, and Deno is doing the right thing here although it might be kind of annoying. Let me explain:

`TextEncoder().encode()` encodes to UTF-8 because that is the web standard encoding for text. Windows uses Windows-1252 encoding for many parts of the OS* (although they are working on better UTF-8) support. The reason this works with the console.log is, is because it uses the `Deno.core.print()` function which is aware of the encoding that your terminal supports and correctly outputs Windows-1252. When encoding and writing to stdout, you are taking UTF-8 codepoints and giving them to a terminal that is expecting Windows-1252, which messes up the text. The reason this works on macOS and Linux is because they use UTF-8 for everything by default. The reason it works correctly when saving to a text file and then opening it, is that the text editor you are using to view the file probably has support for UTF-8 encoding and recognized it as such automatically (for example VS Code does this). If you try to `cat` the saved file in your terminal you will probably get the garbled text again.

There is [this blog post](https://akr.am/blog/posts/using-utf-8-in-the-windows-terminal) which has some instructions on how to get UTF-8 working in the new Windows Terminal (haven't tested it so I am not sure this will work, but it's worth a try).

This is really a issue with Windows' use of Windows-1252 & UTF-16LE. It can become better in the future if Windows gets better UTF-8 support. UTF-8 is the industry standard encoding, and Microsoft is slowly taking steps in the right direction, but its slow.

\* For anything in the OS that supports Unicode they use UTF-16LE which has the same compat issues with UTF-8.

---

FYI: Node has the same issue and it is documented here: https://nodejs.org/docs/latest-v13.x/api/fs.html#fs_fs_write_fd_string_position_encoding_callback

> On Windows, if the file descriptor is connected to the console (e.g. fd == 1 or stdout) a string containing non-ASCII characters will not be rendered properly by default, regardless of the encoding used. It is possible to configure the console to render UTF-8 properly by changing the active codepage with the chcp 65001 command. See the chcp docs for more details.

**Comment by oganexon** [comment]
Found a solution on [StackOverflow](https://stackoverflow.com/a/57134096/11964383).
Run `intl.cpl`
![image](https://user-images.githubusercontent.com/52361520/83942063-bb06dc00-a7f0-11ea-99d4-b80259e67394.png)

Everything worked then for me.
I wish it was activated by default.

**Comment by oganexon** [comment]
#6001
