### ISSUE TITLE
discussion: Run web platform tests

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#6229]
[WPT](https://github.com/web-platform-tests/wpt) is an extensive suite of tests that tests nearly all web platform features like `fetch`, `console`, and streams. It would be great if we could run the for us relevant tests during CI. Chrome and Firefox run WPT during testing too.

**Comment by justjavac** [comment]
bump to deno@1.0.5

**Comment by kitsonk** [comment]
Also @benjamingr and I had a side chat.  He was working on it for Node.js and I think was willing to collaberate.

**Comment by benjamingr** [comment]
The major issue I've run into in Node is that a lot of the tests are coupled to APIs Node doesn't implement.

For example: Node implements EventTarget (experimentally) but most of the WPTs for EventTarget assume `document` `Node` and `Element` exist (under [dom/events](https://github.com/web-platform-tests/wpt/tree/master/dom/events)) so tests need to be ported manually.

I've opened an [issue](https://github.com/web-platform-tests/wpt/issues/23858) asking to upstream changes of WPTs from Node to WPT but it didn't get much traction (yet). So far the process is very manual. 

Node does have infrastructure for syncing and running WPTs as well as a harness that shims the WPT test APIs with Node's (which deno can run since std/node is probably a good enough shim). 

It's at https://github.com/nodejs/node-core-utils/blob/master/docs/git-node.md#git-node-wpt the readme of how to sync/add tests is at https://github.com/nodejs/node/tree/master/test/wpt and here is the runner https://github.com/nodejs/node/blob/master/test/common/wpt.js 

I was going to just PR the tests I've manually ported to Node to Deno if there is interest - it's not a lot of work and it improves coverage.

Deno's EventTarget is also not really spec compliant in a lot of regards. EventTarget is really strange API with a lot of quirks - so edge cases probably shouldn't bother Deno too much and I wouldn't focus on it as a priority (but getting coverage and an up-to-date status of where the impl is is important and relatively easy).

**Comment by kitsonk** [comment]
Just thinking that we might want to focus on this again in the near future... it is increasingly becoming a challenge to help ensure we align (e.g. #7217).

**Comment by benjamingr** [comment]
For what it's worth when I worked on EventTarget fixes in Node I ran into several issues that Deno didn't deal with.

I am starting to be convinced the solution for things like EventTarget is to have a third party implementation that's pure JS to run all the tests against and to have both Node and Deno consume it
