### ISSUE TITLE
docs: Describe how to configure shell completions

### ISSUE THREAD

**Issue by muuvmuuv** [denoland/deno#6309]
I would love to use the deno auto completions but cannot get them working with [prezto](https://github.com/sorin-ionescu/prezto). 

```shell
deno completions zsh > /Users/marvinheilemann/.zprezto/modules/deno/init.zsh
```

It says `_deno:12: command not found: _arguments`. I wonder if I need additional steps but I couldn't find any. 

Has anyone setup completions with prezto already or would it be possible to make it prezto compatible?

**Comment by bartlomieju** [comment]
@muuvmuuv these completions are automatically generated by the CLI parser we're using - which is [`clap`](https://github.com/clap-rs/clap). It might be good to ask question there.

**Comment by intgr** [comment]
The issue is that zsh is very picky about how it discovers those completion files. You have to place it with file name `_deno` into some directory in the `$fpath` variable, usually `/usr/local/share/zsh/site-functions`. Unfortunately there are no user-local paths by default.

As a one-liner:
```sh
deno completions zsh |sudo tee /usr/local/share/zsh/site-functions/_deno
```
After that you can run `compinit` in your zsh shell and `deno <TAB>` should automagically work.

**Comment by bartlomieju** [comment]
@intgr thanks for explanation, we should add that to documentation.
