### ISSUE TITLE
Uncaught Error: The response is not writable.

### ISSUE THREAD

**Issue by shakilkhan12** [denoland/deno#6331]
the below code given me an error and the error is an error: **Uncaught Error: The response is not writable. Throw new Error("The response is not writable.")**
```
router.get("/", async (ctx: RouterContext) => {
  const res = await getBooks();
  console.log(res.data);
  ctx.render("index.ejs", {books: res.data, name: 'asad'});
});
```

**Comment by actual-size** [comment]
I assume you're using oak? If so, it looks like there's an [open issue on oakserver/oak](https://github.com/oakserver/oak/issues/148) that looks similar to your error.

From skimming it, it seems using `.then()` instead of async/await is a workaround. Regardless, it doesn't look like a problem with Deno itself.

**Comment by kitsonk** [comment]
Correct, this issue has nothing to do with Deno.
