### ISSUE TITLE
Think about file-scope compiler options (`tsconfig ` or `pragma`?)

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [denoland/deno#6420]
In `NodeJS`, dependencies has themselves `package.json` and babel config, we imported them from `package.json` indicated the entrypoint of the compiled output file.

However, `Deno` allowed us imported module from single remote file with out `package.json`, if we custom compile options used global `tsconfig.json` or other similar, it may caused unexpected problem, [issue#6396](https://github.com/denoland/deno/issues/6396#issuecomment-647120957) supplied a case for it.

Is we need some way to custom compiler options in file-scope? maybe some `compiler progma` like `@jsx` and so on, maybe a comments link to the path of `tsconfig.json`?

Or maybe we should reach an agreement to just export compiled output file, without any custom compiler options? maybe it would caused extra works to build our package before publish them.

**Comment by kitsonk** [comment]
Scoping per module is likely an overhead that would increase the complexity greatly without adding value for invocations on the command line, like `deno run` and `deno bundle`.

If you need flexibility of different configurations for different modules, it would be good to understand how the run time compiler APIs do not meet your requirements, like `Deno.compile()` and `Deno.bundle()`.

**Comment by zhengxiaoyao0716** [comment]
> Scoping per module is likely an overhead that would increase the complexity greatly without adding value for invocations on the command line, like `deno run` and `deno bundle`.
> 
> If you need flexibility of different configurations for different modules, it would be good to understand how the run time compiler APIs do not meet your requirements, like `Deno.compile()` and `Deno.bundle()`.

I have already tried `Deno.compile()` and `Deno.bundle()`, it compiled my code succeed with custom compiler options, but how could I execute the result? just use `eval` function or write into a temp file and import from it?

**Comment by kitsonk** [comment]
Do you have example of mixed code where you would want a different configuration for a `deno run` or `deno bundle` command?  Just wanting it isn't sufficient justification for adding the amount of complexity that you are requesting here.  There is almost always a single configuration, that while potentially allowing errors to go undetected in some modules, would allow the code to be compiled and transpiled properly.  Code run within Deno should have very minimal variation from the defaults and not variation across modules.  If you are producing `deno bundle` code for Deno to run, then that works fine.  If you are producing code for browers to run, you should use `Deno.compile` and `Deno.bundle` and write the output to disk or send it over a connection to a client.

The one use case you mention in #6396 is legitimate, but that is solved by supporting the `@jsx` pragma, which is why the pragma is there, because it is something that should be able to varied on a per module basis.  This is the case with other pragmas that are supported as well.

**Comment by kitsonk** [comment]
There was no response to an example of where this would be required.  Given the discussion on #7732 implementing something like this is impractical and does not have a compelling use case.  Respectfully declined.
