### ISSUE TITLE
No good way to catch non-recognized errors

### ISSUE THREAD

**Issue by rix0rrr** [denoland/deno#6440]
I'm trying to catch the following error:

```
error: Uncaught Error: Directory not empty (os error 66)
```

There seems to be no good way for me to do this. It's not in the list of errors that are given a special type, so I cannot use `instanceof`.

https://github.com/denoland/deno/blob/fab0204cbf20cc1be7874266325bf258fe0ecaca/cli/js/errors.ts

Other than that, I can't see a good way to test for the error number or a symbolic error code. I guessed at `e.code` (as in Node.js) but that was not set.

Is there a way for me to get the error code from non-special-cased errors?

**Comment by caspervonb** [comment]
This came up in wasi as-well; not all error codes are accurate mapping because of the lack of information available.

**Comment by lucacasonato** [comment]
Do you remember what caused this error to be thrown? All our errors should be a `Deno.errors` error. If they are not that is a bug with the specific API. This issue is too generic to be actionable, because I don't know what call threw the error.

If you can provide more details, please re-open the issue :-)
