### ISSUE TITLE
Uncaught SyntaxError: Unexpected token   in JSON at position 694

### ISSUE THREAD

**Issue by viderme** [denoland/deno#6444]
Here is the repro: https://github.com/viderme/automatic-speedtest

I tested the generated JSON in JSON validator, and it's VALID.
I created a code to Deno and other to NodeJs ("Same code"), Deno gives me "Uncaught SyntaxError: Unexpected token   in JSON at position 694". In NodeJs, json is parsed with success.

**Comment by nayeemrmn** [comment]
The repo seems private/non-existent.

**Comment by viderme** [comment]
@nayeemrmn , sorry. I already fixed.

**Comment by nayeemrmn** [comment]
@viderme Okay, so your JSON has a ton of null-characters at the end which is a syntax error in JSON (and doesn't get trimmed). You need to double check that the same string works on Node -- this is not the case. The problem is with your Python script. To demonstrate this, here's a quick fix for your repro:
```diff
- const j = JSON.parse(ab.trim());
+ const j = JSON.parse(ab.trim().replaceAll("\0", ""));
```

**Comment by viderme** [comment]
Thanks!

**Comment by nayeemrmn** [comment]
This can be closed, then.
