### ISSUE TITLE
Deno should have a maximum sandbox mode

### ISSUE THREAD

**Issue by wysisoft** [denoland/deno#6447]
There should be a mode of Deno that is maximum sandbox - 
-No file system access at all (including modules, etc) except for the initial deno command. Put the onus on the developer to package all js/ts in a single file.
-No network at all, except for the ability to respond to http requests from localhost on a single port. no call-out of any kind.
-No console access at all.
-Any error should just successfully exit the process, no error reporting into the OS?
-No command execution at all (except for the initial Deno)
-No nothing of anything else. Just CPU, Memory, the ability to read a single file on startup, and the ability to respond to a single http response to another process on localhost.
-Would be nice to limit the request/response size of the http request

The OS/public facing process will handle
-if the process runs too long
-if Deno attempts to use too much ram or cpu time or use multiple cores

**Comment by nayeemrmn** [comment]
Duplicate of #6039?

**Comment by wysisoft** [comment]
I'm unclear how a public facing process would communicate into the sandbox with #6039?

**Comment by lucacasonato** [comment]
What exactly is the use case? From what you said, your use case seems so specific that you are probably better of embedding deno_core into your application. A little bit of info on embedding Deno: https://deno.land/manual/embedding_deno. If you have questions related to deno_core, the best place to ask would be https://discord.gg/deno.

**Comment by wysisoft** [comment]
I do not think my use case is specific, I think its what the majority of untrusted-code sandbox tools will want. I think implementing this feature will totally trump so many other efforts in js land (vm2, etc). Confidently provide a process that loads an intial file, can respond to a single http request (with the untrusted code sent as the request), and this tool will immediately compete with Firecracker, gVisor, etc

**Comment by teleclimber** [comment]
I sympathize with @wysisoft here because I'm in the same boat, but I have come to the conclusion that the best way forward is to embed deno_core. I just hope it becomes easier to do this over time.

I can imagine two types of Deno users: people using it to run cli scripts on their machine while minimizing risk, and people using it as the sandbox component of an application platform, or to run plugin code as part of a larger app, etc...

If you make the CLI too restrictive to address the latter it is too painful for the first group. (It's already a pain to have to specify --allow-* in addition to the input parameters of the script.)

Furthermore, for the "max sandbox" crowd, there will never be agreement on what that means. For example you mention:

> -No network at all, except for the ability to respond to http requests from localhost on a single port. no call-out of any kind.

In my use-case any listener is a no-no.

Also, I don't want to force all code into a single file.

So: embed and customize.

**Comment by wysisoft** [comment]
Oliver - can you explain a bit more how you are going to run untrusted code using deno? Are you going to create a new process and a new deno instance during an end-users web request? I'm thinking that, like a hotel, you'd make the room ready as soon as the last person moves out and let it sit, instead of making a room ready right before someone moves in? let me know if i'm way off.

I'm OK embedding if the answer to "is a hello world embedded deno equal to a maximum sandbox?" is yes. I'm also OK closing this if the answer to "is deno with all the flags set to max equal to a maximum sandbox" is yes, but other issues seem to imply "no"

**Comment by teleclimber** [comment]
@wysisoft Honestly this is open-ended for me. I think the ultimate solution lies in leveraging deno core and friends to create a custom executable that can start up a sandbox with the right parameters as quickly as possible. I haven't looked into it in any detail though.

**Comment by mcobzarenco** [comment]
Disappointing to see that it is not one of deno's goal to allow an out of the box secure sandbox for untrusted code without high-level of customization / configuration that's easy to get wrong.
