### ISSUE TITLE
Tests in cli/tsc.rs are not deterministic

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#6473]
Following tests are non-deterministic:
- `test_compile`
- `test_bundle` 

They do not use custom `DENO_DIR` but rather rely on the default value - that means they modify files in default location of `DENO_DIR` on developers machine.

**Comment by kitsonk** [comment]
Yeah, I was running into the fact that they also can find the cache during multiple runs, so they aren't actually testing what we think they are testing.  I had a situation where there are subtle differences in the emit between a compile and a `.transpileOnly()` and one of them would win (between `test_compile` and `test_transpile`) and the other would fail because the cached version was returned instead of it actually doing a compile/transpile.

**Comment by bartlomieju** [comment]
@kitsonk yes, I had exactly same problem during work on incremental compile patch. Those tests need to rewritten, removed or made into integration tests.

**Comment by ry** [comment]
solution ought to use `test_util::new_deno_dir()` 

https://github.com/denoland/deno/blob/4cde7fdc9a52088f8dfe3e23569d6be2faa80d0f/test_util/src/lib.rs#L160-L162

**Comment by kitsonk** [comment]
Makes sense... I will add it to the no_check PR.
