### ISSUE TITLE
React HTMLInputElement

### ISSUE THREAD

**Issue by Bidek56** [denoland/deno#6508]
Basic React example using: `deno run .\react.tsx`
```
// @deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"
import React from "https://cdn.pika.dev/react@16.13.1";

const App = () => {

    const userRef = React.useRef<HTMLInputElement | null>(null);

    console.log("User:", userRef?.current?.value)

    return (
        <div>
            <input ref={userRef}/>
        </div>
    );
};

export default App;
```

generates this error: `error: TS2339 [ERROR]: Property 'value' does not exist on type 'HTMLInputElement'.`
This is standard React. Thx

**Comment by MarkTiedemann** [comment]
You need a `tsconfig.json` with proper compiler settings to get full DOM types, e.g.

```json
{
    "compilerOptions": {
        "lib": ["ESNext", "DOM"]
    }
}
```

To use the config, run `deno run --config=tsconfig.json react.tsx`. This should make your example compile.

**Comment by kitsonk** [comment]
If it is server side (SSR) that will run under Deno then you more likely want:

```
{
  "compilerOptions": {
    "lib": ["deno.ns", "dom", "dom.iterable"]
  }
}
```

**Comment by Bidek56** [comment]
Unfortunately adding those options throws 2 errors that I can not seem to get rid of:

```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.59.0/path/posix.ts:438:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.59.0/path/win32.ts:917:18

Found 2 errors.
```

Full code is at: https://github.com/Bidek56/deno-py-websocket Thx

**Comment by Bidek56** [comment]
This simple code seem to be failing with this [tsconfig.json](https://github.com/Bidek56/deno-py-websocket/blob/master/client/tsconfig.json)

`deno run -c .\tsconfig.json .\url.ts`

```
function fromFileUrl(url: string|URL): string {
    return new URL(url).pathname;
}

fromFileUrl("http://tt")
```
Would anyone know a tsconfig option to fix it? or is it a [posix.ts](https://github.com/denoland/deno/blob/master/std/path/posix.ts) bug? Thx

**Comment by sholladay** [comment]
@Bidek56 The problem you are experiencing in your last example is due to the fact that that TypeScript's `dom` lib only accepts `string` for the first argument:
https://github.com/microsoft/TypeScript/blob/df5981319fc9686dec63305142f7a549e2e6b888/lib/lib.dom.d.ts#L15952

Deno's type definition allows `string | URL` for the first argument (and that's what `fromFileUrl()` passes to it):
https://github.com/denoland/deno/blob/7858ebd493afe15b4b583b0218c27e166572b280/cli/js/lib.deno.shared_globals.d.ts#L1240

I'm not sure if there's a way to resolve the conflict. I would expect there to be some way to make Deno's type defs take precedence. But even if there is, that may cause other issues.

In this particular case, a simple fix could be to open a PR to change `fromFileUrl()` to something like this:

```ts
function fromFileUrl(url: string | URL): string {
  return new URL('', url).pathname;
}
```

**Comment by Bidek56** [comment]
I have added a https://github.com/denoland/deno/pull/6582 for it, unfortunately this is a known [issue](https://github.com/denoland/deno/issues/5365) that is being debated ATM.

**Comment by bartlomieju** [comment]
As of `v1.2.0` Deno's `URL` type definition matches definition in TypeScript (which accepts only `string` in `URL` constructor). Closing as resolved.
