### ISSUE TITLE
Deno v1.1.x fails with TypeScript error in deno test

### ISSUE THREAD

**Issue by adrai** [denoland/deno#6595]
[This project](https://github.com/i18next/i18next-http-backend) is not written in TypeScript and has no tsconfig.json file.

Running tests with deno v1.x.x works: https://github.com/i18next/i18next-http-backend/runs/780086740?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1086194/86243674-12595b80-bba7-11ea-8df9-52490eb87ddb.png)

Running tests with deno v1.1.x fails: https://github.com/i18next/i18next-http-backend/runs/826465216?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1086194/86243697-1b4a2d00-bba7-11ea-8ea3-5e74d0cc80c2.png)

Any help is welcome. 🙏

**Comment by ry** [comment]
Hmm this is unfortunate. Sorry you hit it. Ideally we could get some example of what your code is doing into the test suite - because clearly something wasn't covered.

I'm guessing this is caused by some of the ongoing refactors to the module graph maybe #6000 ... @bartlomieju maybe has a better idea?

**Comment by adrai** [comment]
here you see my tests: https://github.com/i18next/i18next-http-backend/tree/master/test/deno
I'm executing them with: `deno test test/deno/*.js --allow-net`

**Comment by bartlomieju** [comment]
`deno test` creates temporary file called `.deno.test.ts` - I guess something goes wrong when that file is rendered - `.cjs` files should be treated like `.js` file and so they shouldn't be type checked. I'll have to take a deeper look into it. CC @kitsonk - this issue is related to supporting `.buildinfo` file for tests.

**Comment by adrai** [comment]
any news about this?

**Comment by ry** [comment]
@adrai It would help us debug if you could provide a standalone example of here in the comment that we can easily run.

**Comment by adrai** [comment]
@ry is this ok?
`deno test https://raw.githubusercontent.com/i18next/i18next-http-backend/master/test/deno/request.spec.js --allow-net`

**Comment by kitsonk** [comment]
@ry @bartlomieju the `.cjs` module isn't being served with a "valid" media type (`text/plain`)

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 477
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "ad74ff81166637024055c926e60b157b68d68eb080fe1f69a04ee0e62054f8de"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0)
X-GitHub-Request-Id: 3512:554E:16F7B8:18A1E4:5F12782D
Accept-Ranges: bytes
Date: Sat, 18 Jul 2020 04:18:58 GMT
Via: 1.1 varnish
X-Served-By: cache-mel19031-MEL
X-Cache: MISS, MISS
X-Cache-Hits: 0, 0
X-Timer: S1595045938.311865,VS0,VE446
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: 6eb9976b4938343d44fec4110c9c81294a0a4b56
Expires: Sat, 18 Jul 2020 04:23:58 GMT
Source-Age: 0
```

So we seem to be defaulting to treating it a TypeScript for some reason (likely because we assume if it is `text/plain` that it is TypeScript?).  Personal opinion is that if the media type isn't right, we should reject it.  _Maybe_ if it is `text/plain` and only that one we try to use the extension.

**Comment by adrai** [comment]
fyi: this worked with v1.x 🤷‍♂️

**Comment by axetroy** [comment]
try `denolib/setup-deno@v2` with `deno-version: v1.2.0`

This made me find a bug about `setup-deno` accidentally

v1.x should point to v1.2.0 not v1.0.0

**Comment by adrai** [comment]
still the save with v1.2.0
```
$ deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2

error: TS2304 [ERROR]: Cannot find name 'global'.
  if (typeof global !== 'undefined' && global.fetch) {
```

**Comment by axetroy** [comment]
BWT. `global` is not a standard object, but `globalThis`

**Comment by adrai** [comment]
> BWT. `global` is not a standard object, use `globalThis` instead

I don't think this is a problem... it works at runtime... it's only a TypeScript problem (without using TypeScript)
It works also in browser and Node environment without problems.

**Comment by kitsonk** [comment]
There are a lot of things that "work" at runtime that aren't valid when you type check. If you don't want to type check it, use `--no-check` or `// @ts-nocheck` in the file.

**Comment by adrai** [comment]
> There are a lot of things that "work" at runtime that aren't valid when you type check. If you don't want to type check it, use `--no-check` or `// @ts-nocheck` in the file.

Yes, this fixes the tests... Nevertheless, it worked without the --no-check argument in v1.0.x

Feel free to close this issue, if you like.

**Comment by bartlomieju** [comment]
This issue should have been fixed by https://github.com/denoland/deno/pull/8310
