### ISSUE TITLE
[Feature Request] More fine-grained permissions

### ISSUE THREAD

**Issue by redradist** [denoland/deno#6657]
`Deno` is very cool, safe environment for modern applications ... but it has lack of fine-granied loсks

What I mean ? I mean that with `--allow-read` flag `Deno` environment allows to read data from file-systems for all scripts that was used as library ...

For example, if I have allowed `--allow-read` for my script in such case:
```javascript
import * as some_module from "https://<some_path>"

await some_module.read(...);
```
I have verified that this script have to access file-system on read

But then I add another script:
```javascript
import * as some_module from "https://<some_path>"
import * as other_module from "https://<other_path>"

await some_module.read(...);
await other_module.run(...);
```

The script `other_module` in this case have access to read from my file-system and I will even have not noticed it (

Would be nice to add flags like this `--allow-read-to=<scripts>` or add some file with map script-permission `permission.json`

**Comment by kt3k** [comment]
We discussed this before. See #171 or #410, for example.

**Comment by ry** [comment]
See linked issues.

**Comment by redradist** [comment]
@ry Looks like now with Deno 2.1 feature ["Stack traces in permission prompts"](https://deno.com/blog/v2.1#stack-traces-in-permission-prompts), Deno runtime knows exactly which script from which package or module requires such permissions.
Now it should be possible to implement `fine-grained permissions` on package level

**Comment by kt3k** [comment]
The permission stack trace is only enabled when `DENO_TRACE_PERMISSIONS` env var is set because it has significant performance penalty. If we implement this idea based on permission stack trace, it significantly slows down the runtime.

**Comment by redradist** [comment]
> The permission stack trace is only enabled when `DENO_TRACE_PERMISSIONS` env var is set because it has significant performance penalty. If we implement this idea based on permission stack trace, it significantly slows down the runtime.

@kt3k This feature means that if Deno knows a file from which was requested permissions to do something, it means that now it is possible to add file based or package based permissions to Deno like it works in Android and iOS applications.
Consumer of package for some package allow access to system environment, but to other do not.

Because I could imagine that some package that loaded after package that requested access to environment variables could do some malicious actions with it, but if permissions would be file or package based than malicious package should request for itself also permissions to access environment variables

**Comment by mindplay-dk** [comment]
> The permission stack trace is only enabled when `DENO_TRACE_PERMISSIONS` env var is set because it has significant performance penalty.

Could it be determined with static analysis, at installation time maybe, and then cached?

**Comment by kt3k** [comment]
> Could it be determined with static analysis

I don't think that works as JavaScript is too dynamic. You can call fetch function like:
```js
const a = "fet";
const b = "ch";
await globalThis[a + b]("https://example.com");
```

**Comment by kt3k** [comment]
We also need to consider nested dependency situation. If we allowed `net` access to `axios` package, then if a malicious package try to make http request via `axios`, what happens with that call, allowed or denied?

**Comment by mindplay-dk** [comment]
> I don't think that works as JavaScript is too dynamic. You can call fetch function like:
> 
> ```js
> const a = "fet";
> const b = "ch";
> await globalThis[a + b]("https://example.com");
> ```

well, the security model would need to be permissive, so this would get rejected and can't be allowed - modules that need access to security sensitive features would need to access those features in a clean way.

> We also need to consider nested dependency situation. If we allowed `net` access to `axios` package, then if a malicious package try to make http request via `axios`, what happens with that call, allowed or denied?

this would be allowed, but you probably wouldn't want to do that. 🙂

okay, let's say you have modules `@`, `a`, `b` and `axios`, where:

* `@` represents your project root (to which you would still be able to give permissions via the CLI flags)
* `a` is an installed module that calls a function in `b`
* `b` is an installed modules that calls a function in `axios`

so there's a call chain through some functions in those modules, e.g. `@ -> a -> b -> axios`.

with the current simple security model, the `net` permission delegates to every package.

but let's say we introduce per-module *delegated* permissions - meaning, when you permission a module, what you're grating is the right for that module to *initialize* calls to `net` related APIs. that is, we want to grant permissions based on "who should be able to use this capability" rather than "who implements this capability".

if you give `net` access to the `@` root, this works like the current security model - the `net` permission is established in the `@` root context, which gives this module permission to start a call chain that eventually hits `axios`, or any module that requires `net` permission. (which also means that this model is backwards compatible.)

if instead you were to give `net` access to `axios`, any module could gain `net` related capabilities indirectly by calling `axios` - you could do that, but this is probably *not* what you want.

if instead you give `net` access to module `b`, only calls made to module `b` could provide the required security context to eventually make `net` related calls, in `axios` or anywhere.

if instead you give access to module `a`, this gives you more granularity, since functions in `b` or `axios` would not be callable from any module other than `a`.

and so on.

you could think of the calling context as something like:

```ts
interface CallContext {
  callStack: string[];        // ["@", "a", "b", "axios"] etc. (displayable in permission error messages)
  activePermissions: Set<Permission>;  // Permissions from modules we've passed through
}
```

the context would build up with each stack frame push (including "stack frames" across async calls through timers or promises) and would tear down with each returning function (or iterator etc) and stack frame pop.

I think it could work, although I'm not sure about the performance implications of tacking this onto something as low-level as function calls. (another option might be something like an actual permission context object that you could acquire from the module via `import.meta` or something - which you could then explicitly pass to another function, allowing it access to your module's granted capabilities. this would likely be a lot less practical to work with though - modules like `axios` wouldn't "just work" but would likely need explicit support for this.)

also, this of course would mean developers need to be conscious of security in their packages - if module `a` or `b` here is, say, an API client with functions like `getProductById(id: number)`, you're probably fine... but if you were to expose a function that accepts a callback that directly exposes a mutable `Request` object or something, yeah, that package is opening itself up to potential abuse - same reason you probably wouldn't grant any permissions to a package like `axios`.

just exploring ideas here, so another approach that doesn't require call tracking would be a security model based on imports and module boundaries. so instead of thinking about permissions in terms of capabilities ("who can make network calls?"), we'd think about them in terms of dependencies ("who can use axios?").

again, assume a permissive model, so by default no modules would be importable by any others. I know how that sounds, but so, for benign modules like `left-pad`, you could simply allow `*` (meaning every module) to import this module without restrictions. whereas for modules like `axios`, you would instead need to whitelist packages permitted to import from it - any newly installed (or updated) package would need to be whitelisted first. existing APIs like `Deno.readFile` would need to be treated like an implicit `import { readFile } from "deno:read"` so you could whitelist specific package to import `deno:read`.

this might be easier to understand and/or implement? not sure.

anyhow, just throwing out ideas, what do you think? 🙂
