### ISSUE TITLE
feat: stdout.cursorTo()

### ISSUE THREAD

**Issue by mikeal** [denoland/deno#6738]
I’ve been working on a test system for native ESM tests and just got the runner working on Deno, but I did have to use a version of the runner’s display code that is less than awesome because there’s currently no way in Deno to move the stdout cursor.

I don’t have a strong opinion about where the API lives or how it should work, only that the functionality is there. In node.js it’s at `process.stdout.cursorTo()` but I don’t know if you want to copy that pattern. Adding properties to the stream seems a little off to me, and if you aren’t going to support the entire API surface that Node.js has here for tty it’s probably best to diverge completely.

**Comment by ry** [comment]
Probably we should start `std/ansi` (`std/term` ? `std/tty` ?) where we can have functions for various things like this.

**Comment by AZMCode** [comment]
Adding properties to streams, or extending Deno.Writer/Reader/Duplex might be inevitable since, surprisingly, stdin/stdout/stderr aren't the only terminal streams Deno can open. See #6706. In linux, for example, one can open /dev/tty, and, if given the perms, any tty on the system. Not sure how it works in windows, but it's likely possible as well.

**Comment by caspervonb** [comment]
Do we want to implement this as syscall ops or escape sequences?

Has been some grievance from users that escape sequences (std/fmt) don't work with (what I consider) outdated terminal emulators.

I think we reached a consensus that we won't go out of our way to support inferior terminal emulators on Windows since modern Windows does support it?
