### ISSUE TITLE
Unable to load types for graphql

### ISSUE THREAD

**Issue by thomas-jeepe** [denoland/deno#6799]
I'm not sure if this is a bug with deno or with pika, but I'll put it put out the problem here.

When importing from pika cdn it seems like the typings are incorrect. An example below:

```typescript
import { assert } from 'https://cdn.pika.dev/superstruct@^0.10.11'

assert("", "not a struct")
```

The file should fail in compilation, but instead will fail at runtime. Inspecting the types in vscode shows that `assert` in the is being typed as `assert(value: any, struct: any): void` when the correct type is `assert<T>(value: unknown, struct: Struct<T>): asserts value is T`.

I think this means that the types deno is using result from the generated Javascript instead of the typings file.

Another example: 

```typescript
import { ExecutionResult, GraphQLScalarType } from "https://cdn.pika.dev/graphql@^15.0.0";

const foo: ExecutionResult = 0 
new GraphQLScalarType({
  parseLiteral: (ast) => {
  },
})
```

Here `GraphQLScalarType` is typed as `(config: any) => void` and `ExecutionResult` just doesn't exist. `ExecutionResult` is an interface and isn't exposed from javascript, only the typings file.

```
deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

**Comment by jacobgc** [comment]
This looks to be an issue with pika rather than Deno. The pika CND distributes javascript files ready for the browser. From what I can see, you shouldn't use pika for Deno if you want any typescript definitions.

**Comment by thomas-jeepe** [comment]
@jacobgc It might be, do you know where I would put the issue for Pika? Can't seem to find it.

**Comment by jacobgc** [comment]
I'll be honest, I doubt this is an issue for pika. Pika looks like its for shipping to the web, rather than development.

**Comment by kitsonk** [comment]
Currently the VSCode plugin does not handle types from Pika properly.  What you see in VSCode does not represent what Deno actually sees at compile time.

Most code from Pika works fine, but not all the typings it acquires automatically work with Deno.  It will always vary a little bit on what works and what doesn't work.

It is a bit noisy and confusing at the moment but `deno run -L debug main.ts` would give you a lot of details about what is going on.

There are some major refactors going on right now, in respect to how we deal with the internal code, but cleaning up things so that it is a bit easier to figure out where the types have gone is important.

@bartlomieju my opinion is that we need to think of a way with `deno info` to represent when we swap out types for runtime JavaScript in the dependency graph for type checking and display that some way.  One of the biggest challenges with `@deno-types` and `X-TypeScript-Types` and the triple-slash directives is that it is unobservable at the moment.  Also while I think we can actually drop the type check from `deno info` if we haven't already, because we shouldn't be doing any dependency analysis in the compiler anymore.

**Comment by thomas-jeepe** [comment]
Thanks for pointing out that about VSCode. I decided to test creating the following file without VSCode (touch, echo and pipe to file):
`import { any } from 'https://cdn.pika.dev/async@^3.0.0';any('this', 'Should', 'Fail')`
That failed compilation (got the correct types). When I opened VSCode the types were incorrect, but it still ran the test file correctly.

Network access for the above file:

`https://cdn.pika.dev/async@^3.0.0`
`https://cdn.pika.dev/-/async@v3.2.0-37k8VjPjRci99rgmN8c1/dist=es2019,mode=types/index.d.ts`
`https://cdn.pika.dev/-/async@v3.2.0-37k8VjPjRci99rgmN8c1/dist=es2019/async.js`

This file failed at runtime instead of at compile time (got the incorrect types): 
`import { assert } from 'https://cdn.pika.dev/superstruct@^0.10.9';assert('', 'not a struct')`

The debug command shows that network access was granted to:

`https://cdn.pika.dev/superstruct@^0.10.9`
`https://cdn.pika.dev/-/superstruct@v0.10.12-YuIZELFdKlGJ8ba1V2r9/dist=es2019/superstruct.js`
