### ISSUE TITLE
--inspect-brk Always get Outbound Breakpoint Result

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/deno#6855]
Here is my launch.json configuration on my visual studio code :

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Deno",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}/v1/api-client",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "run",
        "--inspect-brk",
        "-A",
        "--unstable",
        "index.ts"
      ],
      "port": 9229
    }
  ]
}
```
the path is accurate & name file is right.

Here is the debug console :  
![image](https://user-images.githubusercontent.com/5908094/88276511-5dc7db00-cd09-11ea-9142-7536aba9db07.png)

when i am tried to add breakpoint , its always outbound.. normally before update deno its working normal.
![image](https://user-images.githubusercontent.com/5908094/88276384-29541f00-cd09-11ea-8f62-7d297ea79d2f.png)

**Comment by KrisChambers** [comment]
Can confirm this is happening on my end as well.

Small test case 

main.ts:

```ts
function A() {
   console.log("Hello, World")
}
A();
```
launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Deno",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder}",
        "runtimeExecutable": "deno",
        "runtimeArgs": ["run", "--inspect-brk", "${workspaceFolder}/main.ts"],
        "port": 9229,
        "console": "integratedTerminal"
      }
    ]
  }
```

The --inspect-brk flag is not present in the command when launched from vscode (seen in the above photo).
If --inspect-brk is replaced with just --inspect then the --inspect flag is present and the debugger appears to activate as indicated by a "Debugger listening on ws://...." message.

Dropping a break point on line 4, executing `deno run --inspect-brk main.ts` in the shell, and opening chrome://inspect breaks the program as expected.

Disabling vscode_deno extension doesn't fix anything. 

Possibly a VSCode issue. There are a few bugs regarding the debugging situation since the most recent update: https://github.com/microsoft/vscode/issues/103205#issue-664781193

Looks like the --inspect-brk flag might be getting eaten up by something...

**Comment by EmNudge** [comment]
I can confirm this is a problem with the most recent version of VS Code. 
I downloaded the [May 2020 version from here](https://code.visualstudio.com/updates/v1_46) and it worked fine, whereas I was unable to get the current version working with breakpoints whatsoever.

**Comment by bartlomieju** [comment]
The problem is caused by new JavaScript debugger in VSCode. Can be disabled with `debug.javascript.usePreview: false`
