### ISSUE TITLE
Fetch API doesn't respect forbidden headers

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#6868]
Refs:
- https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
- https://fetch.spec.whatwg.org/#forbidden-header-name

We don't fundamentally need this restriction on the server-side, but for both spec-compliance and practical compatibility with browsers we should force use of a `Deno.HttpClient` to set these headers:
```js
// The Cookie header is silently ignored.
await fetch(
  "https://example.com/",
  { headers: new Headers({ "Accept": "text/html", "Cookie": "foo=bar" }) },
);

// The Cookie header is used.
const client = Deno.createHttpClient({ allowAllHeaders: true });
await fetch(
  "https://example.com/",
  { client, headers: new Headers({ "Accept": "text/html", "Cookie": "foo=bar" }) },
);
```

**Comment by kitsonk** [comment]
The behaviour is to silently drop them, at least in Chrome.  I just did:

```
await fetch("http://localhost:8000", { headers: new Headers([["cookie", "foo=bar"]]) });
```

And it simply stripped the `cookie` header.  The reason why they are forbidden is because the user agent controls them, and can't be overridden by user land.  We should simply document the behaviour in my opinion, since there is no browser error when passed.

**Comment by nayeemrmn** [comment]
> The behaviour is to silently drop them ... And it simply stripped the cookie header

Yep, as I hinted at in the example. But when you author a `fetch()` to a hardcoded URL with a cookie which is prerequisite to getting an `ok` response (auth?), it's likely to propagate into an error anyway, and you end up with a script that is expected to work in Deno but can't work in a browser. This will lead to the same kind of surprise our compatibility rule is supposed to prevent. Code which won't work as expected in a browser should be signalled with a `Deno` reference.

**Comment by kitsonk** [comment]
Ah, I mis-read what you said.  I thought you were suggesting the behaviour of Deno was to silently drop the cookie header, but it is browsers.

The problem is `fetch()` will _always_ behave differently in a server context and a client context.  You have all the situations with same origin and cross origin which just don't make sense in a server context.  I am still just for documenting it.  As you state, Node's implementation just passes forbidden as well.

It is that or we implement some sort of cookie jar per origin that manages the cookies itself, and set the cookies on the document if you "really" want browser compatibility, but that just doesn't seem logical to me.

**Comment by jsejcksn** [comment]
Not stale

**Comment by nayeemrmn** [comment]
@jsejcksn As it says above your comment, the stale label is removed once an appropriate label is added.

**Comment by kt3k** [comment]
The option like `[Deno.extension]: { headers: new Headers({ "Cookie": "foo=bar" }) }` looks too complex to me. How about switching the behavior by a flag in CreateHttpClientOptions?

```js
const client = Deno.createHttpClient({ allowAllHeaders: true });
await fetch("https://example.com", { client, headers: new Headers(/* here you can set any headers */) });
```

**Comment by nayeemrmn** [comment]
@kt3k You're right, `Deno.HttpClient` is our extensive mechanism for `fetch()` now. While I think a symbol is a more general solution to adding Deno-only properties to objects, it's a lot more sane to address this with the client than to propose a new mechanism here.

**Comment by lucacasonato** [comment]
I think the current solution is good enough. We currently do not ignore any headers other than host.
