### ISSUE TITLE
[deno fmt]: Trailing comma

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6932]
When calling ```deno fmt``` and a list of properties/values are long, it will append an unnecessary comma after the last one.

```ts
const object: { longName: boolean, otherLongName: boolean } = { longName: true, otherLongName: false }
```
```sh
deno fmt
```
Output:
```ts
const object: { longName: boolean; otherLongName: boolean } = {
  longName: true,
  otherLongName: false,
};
```
That can result in pretty weird looking code when it is more complex. Is this intentional?

**Comment by jeroenptrs** [comment]
Starting from ES5, trailing commas are gradually being accepted and preferred since this reduces confusion.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

It's also the standard option when using prettier (and obviously dprint defaults to this as well, as you can tell).

**Comment by timreichen** [comment]
Thank you for the link and the explanation. In that case it is therefore intentional.
