### ISSUE TITLE
Suggetion: deno cache --info

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#6971]
# Question
How to get a list of all cached files in deno?
# If not
Maybe we need something like ```deno cache --info``` to get the cached paths as well as the download dates?

**Comment by nayeemrmn** [comment]
Duplicate of #5600.

**Comment by jeroenptrs** [comment]
I don't really see how this would be feasible since module urls get hashed before stored in cache. This will also become true for the gen folder soon since #6911 will be included in next release.
Unless there's a lock.json on root level in DENO_DIR keeping track of all of this, and I don't really consider that a workable alternative.

**Comment by SyrupThinker** [comment]
The cache contains metadata files that allow reverse mapping from hashes to URL

**Comment by ry** [comment]
@timreichen Why do you want this feature?

**Comment by jeroenptrs** [comment]
> The cache contains metadata files that allow reverse mapping from hashes to URL

Good call, didn't know that.

**Comment by timreichen** [comment]
@ry Just to have an overview over all the cached files. I wanted to know what deno cached and which version and found that there is no other way than to check all the [sha256].json files in cache. So more as a convenience feature.

**Comment by jeroenptrs** [comment]
@timreichen you can use this script I whipped up to check it
https://gist.github.com/jeroenptrs/a4d22610a20290c89be22e888f879631

**Comment by timreichen** [comment]
Ok, thanks for your effort. Closing in favor of #5600.
