### ISSUE TITLE
missing transfer argument for postMessage

### ISSUE THREAD

**Issue by nabezokodaikon** [denoland/deno#7021]
postMessage from worker fails.
How can I get it to work properly?

main.ts
```typescript
const worker = new Worker(new URL('worker.ts', import.meta.url).href, {
  type: 'module',
  deno: true
});

worker.postMessage('foo');
```

worker.ts
```typescript
self.onmessage = async (e: any) => {
  console.log(e.data);
  self.postMessage('bar', '*'); // <-- Error
};
```

Running command
``bash
$ deno run --unstable --allow-read  main.ts
``

Error message
```
error: Uncaught Error: TS2554 [ERROR]: Expected 1 arguments, but got 2.
  self.postMessage(message, '*');
                            ~~~
```

**Comment by lucacasonato** [comment]
That parameter is used to zero-copy objects that implement the transferable interface (ArrayBuffer and MessagePort). Deno does not support structured cloning yet (which is a prerequisite for Transferrable), and thus does not support the optional second parameter on `postMessage` yet. Using a string as the second parameter to `postMessage` is not valid anyway because it is not `Transferrable`.

Ref https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage and https://developer.mozilla.org/en-US/docs/Web/API/Transferable

**Comment by nabezokodaikon** [comment]
Thank you. understood.

**Comment by kitsonk** [comment]
Ref #3557

**Comment by bartlomieju** [comment]
Closing in favor of #3557
