### ISSUE TITLE
Small concern regarding integrity checking & lock files

### ISSUE THREAD

**Issue by redbar0n** [denoland/deno#7075]
Re: https://deno.land/manual/linking_to_external_code/integrity_checking

Context:

```
A typical workflow will look like this:

// Add a new dependency to "src/deps.ts", used somewhere else.
export { xyz } from "https://unpkg.com/xyz-lib@v0.9.0/lib.ts";

Then:

# Create/update the lock file "lock.json".
deno cache --lock=lock.json --lock-write src/deps.ts
```

>Runtime verification:
> Like caching above, you can also use the --lock=lock.json option during use of the deno run sub command, validating the integrity of any locked modules during the run. Remember that **this only validates against dependencies previously added to the lock.json file.** New dependencies will be cached but not validated.

My small concern is that someone (inevitably?) will import a new remote module, but then forget to update the lock file. Then that would lead to the remote module by default being cached and loaded, without it being integrity checked first. (If I have understood the docs correctly). It seems like it could easily open up that potential attack vector again ([mentioned in the introduction](https://deno.land/manual/linking_to_external_code/integrity_checking#introduction)). Wouldn't it be better to (1) give a warning that this module is not added to the lock file? And perhaps (2) provide an easy option to add it to the lockfile then and there?

Another thought could be to (3) enable integrity checking by default, and rather make an unlock-file, where devs would specify modules which should _not_ be integrity checked. In the spirit of secure-by-default, and whitelisting over blacklisting (the lock file is currently a kind of blacklist; a list of files not to be trusted by default).

**Comment by kevinkassimo** [comment]
(1) sounds like a good way to go, probably could be accompanied with a new flag e.g. `--lock-strict=lock.json` to simply fail on dependencies not present in the lockfile.

**Comment by ry** [comment]
Thanks for raising this. 

(1) is certainly the easiest immediate fix. But I hope we might be able to enable lock files by default in the future.

**Comment by redbar0n** [comment]
Is this addressed or remembered? 

Would be a shame if a security issue like this got forgotten simply due to a bot auto-closing it.

**Comment by chloekek** [comment]
A temporary workaround for Deno users is to add a step to your CI pipeline which generates a new lock file and then compares it with the lock file that was committed to the repository:

```bash
deno cache --lock=/tmp/deno-lock.json --lock-write server.ts
diff -u lock.json /tmp/deno-lock.json  # exits non-zero if different
```

This makes sure that no incomplete lock file is accidentally merged or deployed.

**Comment by Nainterceptor** [comment]
Since the first message, deno 1.28 released a new lock file version (v2).
This issue is still a mess.

I understood that "auto update" of lockfile is a suggar for developers, things are simpler with that.
But, for ops teams, we _need_ to ensure that dependencies are consistent across environments : they are the same between developers, container images, CI/CD steps, ...
The _only_ way, imo, to ensure that, is to have a way to run deno with lockfile immutability.

Some cases : 
* Consistent Builds: A lockfile ensures that every build is based on the same set of dependencies, regardless of the environment in which it's being built. This helps ensure consistent behavior and makes it easier to reproduce issues.
* Reliable Deployments: When deploying an application to a new environment, the lockfile guarantees that the same versions of dependencies are used as in the original build.
* Collaboration: When working in a team, different developers may have different versions of dependencies installed on their machines, which can lead to issues with compatibility or different behavior when running the code. A lockfile ensures that all developers are using the same versions of dependencies, making collaboration easier.
* Rollbacks: In the event of an issue or bug, a lockfile enables a quick rollback to a known-good state by reverting to the previous lockfile.

At least 1 case detected yesterday where we're not able to offer these guarantees : 
- A file is imported via deno.land without version pinning (like `import { Application } from "https://deno.land/x/oak/mod.ts";`)
- Version in lockfile is 11.x
-  `deno run`/`deno cache --reload` will change lockfile to put version branch in 12.x

I don't think the right title is not "small concern regarding..." but "major concern regarding..."

**Comment by lucacasonato** [comment]
Lock files in Deno have changed a lot in the last 4 years. We are now at a point where:

1. Lock files are created by default
2. If a hash for an existing file mismatches and that hash is already in the lockfile, we error
3. If a hash is not in the existing file, we add it

Users can now pass `--frozen` to prevent 3) (e.g no automatic updates to the lockfile).
