### ISSUE TITLE
performance.now() should strictly require --hrtime

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#7135]
Instead of silently rounding when it's not given. This is an unnecessary pitfall. Also `performance.now()` is precisely for getting high-resolution time so the current behaviour is illogical.

I guess this is a v2.0.0 fix.

**Comment by littletof** [comment]
If I can throw in my two cents,
I think it would complicate cases where you want to run with or without the flag quite a bit.

For example `deno benching` uses `performance.now()` internally. If it would need permission to even call it, you would have to mix in permission handling and call `performance.now()` or `new Date().getTime()` based on permissions, which is not that bad, but I think it would complicate things unnecessarily.

(Also, I assume sync `permissions` query would be stable by 2.0.0, but if not this would also need `--unstable` just because you want to handle running both with or without `--hrtime`).

If you want to force out `hrtime`, you can still check if the flag was provided right now like:

```ts
function usingHrTime(): boolean {
  return performance.now() % 1 !== 0;
}
```

(Also, I dont know the reason `performance.now()` is behind a flag, but does it need to be? Is it because of overall performance?)

**Comment by nayeemrmn** [comment]
> I think it would complicate cases where you want to run with or without the flag quite a bit.

It would throw if you don't provide the flag. Quite simple and already what we do with powerful features.

**Comment by littletof** [comment]
> It would throw if you don't provide the flag

Well, yeah, than I sort of have to retract my previous comment 🙂
I think its simpler now, but agree, that one `try catch` can't hurt that much, if the current silent rounding causes confusion.

**Comment by kitsonk** [comment]
Other platforms do not throw when they fuzz this API. I am against throwing versus properly fuzzing the response. Throwing makes code less portable.

**Comment by nayeemrmn** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

Looks like there is precedent for silently rounding in browsers... then the associated problems aren't for us to solve.
