### ISSUE TITLE
Weird issue with // @deno-types

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#7174]
I know some bugs around deno-types have been reported recently, but this sadly looks like a new one
```javascript
// @deno-types="https://github.com/Soremwar/deno_types/blob/mui/material-ui/styles/v4.9.10/index.d.ts";
import * as mui from "https://cdn.skypack.dev/@material-ui/styles@4.10.0";

console.log(mui)
```

```log
# deno run -c tsconfig.json test.ts
Download https://cdn.skypack.dev/@material-ui/styles@4.10.0
Download https://github.com/Soremwar/deno_types/blob/mui/material-ui/styles/v4.9.10/index.d.ts%22;
error: Import 'https://github.com/Soremwar/deno_types/blob/mui/material-ui/styles/v4.9.10/index.d.ts%22;' failed: 404 Not Found
```

#### Note
Gotta try this out with a tsconfig.json with libs ["DOM", "DOM.Iterable", "ESNext"]

Deno v1.3.1 - Linux

What really bugs me though is the `%22` that is being appended at the end of the file

An even weirder issue (that I couldn't reproduce by network) is Deno failing to execute the following command
```log
# deno run -c tsconfig.json material-ui/styles/v4.9.10/styles/withStyles.d.ts
Check file:///home/nicolas/Documents/Programming/deno_types/material-ui/styles/v4.9.10/styles/withStyles.d.ts
Warning Failed to get compiled source code of "file:///home/nicolas/Documents/Programming/deno_types/material-ui/styles/v4.9.10/styles/withStyles.d.ts".
Reason: No such file or directory (os error 2)
If the source file provides only type exports, prefer to use "import type" or "export type" syntax instead.
```

**Comment by jeroenptrs** [comment]
@Soremwar that second log is a warning not an error, that's the Deno compiler notifying there's no compiled JS code since it's pure types. If you add `--reload` you'd get the message again.

**Comment by kitsonk** [comment]
Remove the `;` from the end of the `@deno-types`... the regex used to parse it out of the comment is not smart enough to ignore it.  I am working on a patch overall that will improve the robustness of parsing these things out as part of my compiler re-write.  I would also personally ditch the quotes.  You also need to use raw github in order to get the proper file served with the correct media type:

```ts
// @deno-types=https://raw.githubusercontent.com/Soremwar/deno_types/mui/material-ui/styles/v4.9.10/index.d.ts
import * as mui from "https://cdn.skypack.dev/@material-ui/styles@4.10.0";

console.log(mui)
```

**Comment by Soremwar** [comment]
@kitsonk Dummy me, changed the import statement, and it works just fine from URL

And even better, I managed to replicate the issue that is actually causing me problems.
This won't work even though the import path is perfectly fine.

#### Even worse, mess with the path a little (remove one of the `../` in the import path or add one and you'll see some interesting results)

https://repl.it/@Soremwar/denotypes#test.ts
`deno run -c tsconfig.json test.ts`

The file that is being errored is the following
https://repl.it/@Soremwar/denotypes#material-ui/styles/v4.9.10/styles/withTheme.d.ts
The import that breaks everything is the react import

#### Note: This only happens when imported from a filesystem, import through URL works fine

**Comment by kitsonk** [comment]
@Soremwar 

You have an error in `makeStyles.d.ts`:

```ts
import {
  ClassNameMap,
  Styles,
  WithStylesOptions,
} from './/withStyles.d.ts';
```

For some reason that doesn't fail, but it sets the module specifier to that, which means all modules trying to be loaded relative to that don't exist, because the path doesn't actually exist.  Modifying the specifier to `'./withStyles.d.ts'` fixes the issue.

We should just error out on invalid specifiers like that, though I am not sure how it actually resolved in the first place.  Clearly an edge case we can create a test for.  It isn't specific to `@deno-types`.

**Comment by Soremwar** [comment]
You are totally right kitsonk

Closing #7174
