### ISSUE TITLE
Add TCP server API

### ISSUE THREAD

**Issue by ry** [denoland/deno#725]
Generally should follow the Go API.
Here is an echo server:
```ts
import * as deno from "deno";
const listener = deno.listen("tcp", ":8080");
for (;;) {
  const conn = await listener.accept();
  deno.copy(conn, conn);
}
```

**Comment by MarkTiedemann** [comment]
Not quite sure whether I understand the API design.

Is `copy(a, b)` sync or is it async (but the returned promise is just not awaited in the example)?

Instead of `for (;;) { const conn = await accept(); /* do stuff */ }` wouldn't it make sense to use async iteration here, as in `for await (const conn = accept()) { /* do stuff */ }`?

**Comment by greim** [comment]
Async iteration is idiomatic to JS/TS and would allow:

```js
for await (const conn of listener.accept()) {
  await deno.copy(conn, conn);
  if (something) break;
}
```

You could hook into `break` by implementing `.return()` on the iterator to perform any cleanup. Also these things naturally handle back pressure and can be composed/pipelined in various interesting ways.

**Comment by kanishkarj** [comment]
Is anyone working on it? if not can someone help me in getting started?

**Comment by ry** [comment]
@kanishkarj It's a big project. We're working towards it. #721 needs to happen first to establish the file descriptor table where sockets will be stored. We'll probably will have that by the end of the week.

**Comment by kanishkarj** [comment]
I see. @ry thanks for the information..
