### ISSUE TITLE
std/fs: add a WalkFn param to the fs.walk() function

### ISSUE THREAD

**Issue by wperron** [denoland/deno#7423]
It'd be nice to be able to pass a function to the `walk` function like the [Golang equivalent](https://golang.org/pkg/path/filepath/#Walk) does. An example use case would be to calculate the total size of a directory, or include/exclude entries based on some criteria other that glob pattern.

**Comment by caspervonb** [comment]
Hmm, don't think Go is comparable since exposes a much lower level interface.

We return an iterator which is a lot more flexible and can be collected into an array then be mapped or reduced et cetera which already covers those use cases?

Granted; async iterator utilities are a bit lacking at the moment but that is being tackled by at-least one TC39 proposal.

**Comment by nayeemrmn** [comment]
@wperron Yes, is there any reason you can't do that in the loop body? That's the substitute of the callback.

**Comment by wperron** [comment]
@nayeemrmn not really, using the loop body would work just fine. I guess I just figured since so much of the std is modelled after Go's it would make sense to provide the same option.

**Comment by nayeemrmn** [comment]
It's modelled after Go, but we use a loop body in place of the callback. Go's can't be looped over, ours doesn't have a callback. Is that sufficient?
