### ISSUE TITLE
Refactor "Deno.customInspect" symbol

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#7536]
Currently `customInspect` is defined in `cli/rt/02_console.js` as:
```js
const customInspect = Symbol("Deno.customInspect");
```

Working on https://github.com/denoland/deno/pull/7524 I found that `customInspect` is used in many Web APIs. We want to move those implementations to `op_crates/web` which means getting rid of as many "dependencies" as possible. 

In this case it should be quite simple by replacing definition of `customInspect` with:
```js
const customInspect = Symbol.for("Deno.customInspect");
```

Doing so will allow to use the symbol inline in `op_crates/web` as such:
```js
class Blob {
   ...

  [Symbol.for("Deno.customInspect")]() {
    ...
  }
}
```

CC @kitsonk @nayeemrmn @ry

**Comment by nayeemrmn** [comment]
The reason we make `Deno.customInspect` a unique symbol is to force a dependency on the `Deno` namespace to reference it. There's absolutely no reason to use `Symbol.for()`, because we may as well just make it a `"denoCustomInspect"` string key. So I see two possibilities:
1. Attach the custom inspect function onto the imported class prototype in the cli crate. This is the correct way of refactoring the current behaviour. If the op crate naturally doesn't have access to the symbol, for the same reason it shouldn't be worrying about implementing the custom inspect function.
2. BREAKING: Reconsider using a symbol at all. A web-compatible script should be able to declare a just-in-case Deno-specific inspect function which is never called when run on the web, but the only way of doing that right now sacrifices web-compatibility. It's counter-productive to use a symbol for custom inspect.
    - As you can see I'm talking about an unrelated issue regarding web-compatibility. Let's go with (1) for now, that's the proper response to this problem.

**Comment by bartlomieju** [comment]
> Attach the custom inspect function onto the imported class prototype in the cli crate. This is the correct way of refactoring the current behaviour. If the op crate naturally doesn't have access to the symbol, for the same reason it shouldn't be worrying about implementing the custom inspect function.

I'm not sure this is possible to pull off - `customInspect` is used by `inspectObject`, which is used by `inspectValue`, which is used by `inspect`. I don't see a way to change this behavior only in CLI.

**Comment by nayeemrmn** [comment]
Ah right, `console` depends on `inspect()`. Hmm, I think the real problem is that we haven't figured out dependencies between op crates such that one can "ensure" that another has been executed.
- `op_crates/util`: Defines `inspect()` etc. and the custom inspect symbol.
- `op_crates/web`: Defines web APIs including `console`. Depends on `op_crates/util`.
- `cli`: Bootstraps. Depends on `op_crates/util` and `op_crates/web`.

This is going to be necessary at some point. I think a mechanism for ensuring modules is needed in `deno_core`.
