### ISSUE TITLE
Inspect should always quote and escape strings

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7545]
This is similar to #7532 but for plain strings.

We are returning strings back as-is from Deno.inspect which isn't very useful.

```typescript
const value = "\x1b[2J";
console.log(Deno.inspect(value));
```

Expected output
```
"\x1b[2j" // Deno.inspect yields a string with \"\\x1b[2j\"
```

Actual output
```
\x1b[2j
```

This manifests itself in quite a few different ways including but not limited to;
- Doing an asserting error with something that returns a terminal sequence can blow up the terminal.
- Impossible to spot string diffs in testing/asserts.
- Typing in a terminal sequence in the prompt can blow up the terminal as it echoes back without being escaped.

**Comment by solson** [comment]
> Expected output
> 
> ```
> "\\x1b[2j"
> ```

Shouldn't this be `"\x1b[2J"`? That is, inspect should produce a canonical string literal that would produce the string if written in code.

I'll get very specific since the levels of escaping can be confusing to talk about:

```js
const value = "\x1b[2J";
```

The string `value` contains the literal bytes `[27, 91, 50, 74]` or `["\x1b", "[", "2", "J"]`. We want `Deno.inspect(value)` to produce a string `"\"\\x1b[2J\""` which has the literal bytes `["\"", "\\", "x", "1", "b", "[", "2", "J", "\""]`. Then `console.log` will output this string literally, with no further escaping, producing the output:

```
"\x1b[2J"
```

Does this make sense?

**Comment by caspervonb** [comment]
Indeed.

I should have used assertions instead of logs to illustrate here.

To put it more simply:

```typescript
assertEquals(Deno.inspect("\0"), "\"\\x00\"");
```
