### ISSUE TITLE
manual: 404 - Not Found

### ISSUE THREAD

**Issue by JerryGreen** [denoland/deno#7699]
Try urls:

https://deno.land/manual
https://deno.land/manual/testing

## Preview
![image](https://user-images.githubusercontent.com/13215662/94345968-e2edaa00-0042-11eb-8082-46b83ee0a802.png)

![image](https://user-images.githubusercontent.com/13215662/94345897-89857b00-0042-11eb-8317-860c1ba219e0.png)

**Comment by jkomyno** [comment]
That's happening only for version 1.4.2, all the other versions seem working. I suspect something went wrong when updating the website for the latest released version of Deno.

**Comment by lucacasonato** [comment]
Sorry about that - fixed now.

**Comment by JerryGreen** [comment]
@lucacasonato thanks! Can you share any details on how did that happen? Sorry, I'm just curious...

**Comment by lucacasonato** [comment]
Sure. The manual gets its content from https://deno.land/x/deno. I manually have to trigger deno.land/x to scrape this specific repo because of some limitations in how we handle versions. I forgot to do that after yesterdays release. Because of this https://deno.land/x/deno@v1.4.2 was not published. The fix was to just manually trigger the scraping.
