### ISSUE TITLE
Target folders of subdirectories are not being ignored by git

### ISSUE THREAD

**Issue by hugotiburtino** [denoland/deno#7737]
Hi, I'm new here and would like to contribute to Deno. 

The very first thing I noticed just after starting to browser the folders of the denoland/deno is that the rust plugin of VS code keeps creating the target/ folder of the sub-directories. At the same time, I get a bunch of files changes at the git tab of the IDE. It is not just annoying but it could lead to an undesirable target folder being committed after building it (even if you don't use VS code).

**Comment by lucacasonato** [comment]
Only a single target folder at the root of the project should be created. Can you check your Rust version (should be 1.46), and that you are using the `rust-analyzer` VS Code extension?

**Comment by caspervonb** [comment]
Welcome welcome!

Looks like something is off with your setup since this is a workspace there should only be a single top level target directory.  Possibly you've got an old version of Rust from your os distro that predates workspaces? Install rustup (http://rustup.rs) and use that to manage rust versions, targets and components.

**Comment by hugotiburtino** [comment]
Hi,
I'm using rust 1.48, but the nightly version. And the extension is called simply Rust, that comes also with rust analyzer.

But anyway, if there should be only one target, then it is a problem of the extension, not here.
Closing it...
