### ISSUE TITLE
Should evaluation errors in the read-eval-print-loop go to stdout?

### ISSUE THREAD

**Issue by caspervonb** [denoland/deno#7849]
This struck me as a bit odd when re-writing the read-eval-print-loop (REPL), we print `throw 'foo'` to stderr.

Node does print everything to stdout which is what I would expect, my rationale being that it is a successful evaluation where the result happens to be an error therefore not an error in the sense that it is a program error that should go to stderr.

Already been sitting on a patch for this for a couple of days trying but I'm curious to see what people's expectations are and what do other REPLs do (Python, Ruby, Lua, et cetera).

**Comment by solson** [comment]
I agree with your rationale. I would reserve `stderr` for things like Rust panics (it's where they go by default) and other implementation errors in the REPL itself, and otherwise expect all output to go to `stdout`.

I took a look at the mentioned languages and was slightly surprised to find this:

| Language | REPL errors written to |
| - | - |
| Ruby | stdout |
| Python | stderr |
| Lua | stderr |

Given that I never noticed any difference between these, it probably doesn't matter too much whether we use `stdout` or `stderr`.
