### ISSUE TITLE
Support for primitive numeric types

### ISSUE THREAD

**Issue by OliverBrotchie** [denoland/deno#7881]
A proposal to support primitive numeric types in a similar manor to [AssemblyScript](https://www.assemblyscript.org/types.html#type-rules).

**For example**:
``` typescript
    let tinyInt: u8 = 20; // An unsigned 8-bit integer
````

**With casting between numeric types like this:**
``` typescript
   u8(20);
```
Giving access to them would not only make possible improvements on memory efficiency, but also run time speed. 
Compiling to Deno is also now supported in [Wasm-pack](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html); these types would also allow for more specific typing when passing in and out of WebAssembly.

**Rust** has native access to these primitive types, so I am confused as to why Deno does not already support them?

**Comment by qwerasd205** [comment]
> Rust has native access to these primitive types, so I am confused as to why Deno does not already support them?

Because Deno works by running JavaScript (compiled from TypeScript if the input file is TypeScript) in v8, which is a JavaScript engine, implementing the ECMAScript specification, which does not have any concept of primitive numeric types outside of TypedArrays. I don't think it would be very easy to add additional types, much less trivial as you seem to imply it would be.

**Comment by bartlomieju** [comment]
Non-issue for Deno.
