### ISSUE TITLE
Missing type declarations for FinalizationRegistry and WeakRef 

### ISSUE THREAD

**Issue by ry** [denoland/deno#8051]
Deno 1.4.6
```
const x = new WeakRef({});
const y = new FinalizationRegistry(() => {});
console.log(x, y);
```

**Comment by kitsonk** [comment]
The are available in [TypeScript 4.1](https://github.com/microsoft/TypeScript/blob/master/src/lib/esnext.weakref.d.ts) which is the first release since they have gone Stage 3.  It is planned to be released on 17th November.

We can back port `esnext.weakref.d.ts` in ahead of time though, which I will create a PR for in a bit.
