### ISSUE TITLE
WebWorker as separate crate 

### ISSUE THREAD

**Issue by olanod** [denoland/deno#8072]
As mentioned in https://github.com/denoland/deno/issues/7928 I'm creating a plugin system where JS/TS/WASM plugins are written using the `WebWorker` interface so they run unchanged in the browser or server. I know this can be done on top of deno-core but ideally deno exposes a crate that "installs" the required APIs to the JS runtime(I'm completely sure how it works but something like deno-fetch?), since this is pretty much done already on deno cli package I hope it wouldn't be a big trouble?

Some pointers on how to create this "`webworker-rs`" crate would be helpful, I'd like to get to the point where I just do something similar as with the browser `let handler = WebWorker::new("plugin.js")` and a ES modules based plugin is automagically loaded and everything just works. Of course even better would be a brave heart that jumps directly into creating this awesome crate 😅

**Comment by bartlomieju** [comment]
Releasing `WebWorker` as a standalone op crate is very non-trivial and I expect it to be one of the last op crates to be produced, if ever. 

The reason is that `WebWorker` is very tightly tied to abstractions in CLI, including, but not limiting to integration with event loop (tokio). I really don't see a straightforward way to move it into a separate crate.

I'm afraid at this point it's a "won't fix" so I'm going to close this issue in favor of #7928.
