### ISSUE TITLE
Linter should display rule docs

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#8227]
There's an on-going effort in `deno_lint` repository to add docs and examples to all rules (https://github.com/denoland/deno_lint/issues/159). We should think about integrating these docs into `deno lint` subcommand. 

Currently `deno lint --rules` shows a plain list of rules that are run. I think we could integrate showing docs by providing rule codes as a value to `--rules`, eg. `deno lint --rules no-explicit-any no-empty`.

Documentation is accessible using `LintRule::docs` method.

I also tried integrating markdown printer to nicely display docs in `dlint` example (https://github.com/denoland/deno_lint/pull/441) but haven't gotten too far.

**Comment by bartlomieju** [comment]
@RDambrosio016 [suggested on Discord](https://discord.com/channels/684898665143206084/684911491035430919/772944237859307531) to use lexer from SWC to provide code highlighting. 

This might also be useful for syntax highlighting in REPL (especially if we were to support TypeScript in REPL). Definitely something to consider especially if it means not having to add new dependency.

**Comment by RDambrosio016** [comment]
All of the highlighting is done [here](https://github.com/RDambrosio016/RSLint/blob/master/crates/rslint_lexer/src/highlight.rs). 
The theme is basically one dark pro 

![highlighting](https://imgur.com/sJ1pbCk.png)

**Comment by bartlomieju** [comment]
@kdy1 what's your opinion on using lexer to provide syntax highlighting in docs? This feature would also be useful for `deno_doc` which has some rudimentary highlighting implemented by manually assembling AST nodes into string reprs.

**Comment by kdy1** [comment]
It will be much easier to maintain, but I'm not sure about the way to distinguish type parameters from less than operator. I guess `dprint` contains logic for it, but I don't expect it to be easy, because typescript syntax is inherently ambiguous. 

Even though, there are not so many ambiguous syntax, so biggest problem is deciding how to deal with it - just rendering them as `less than` can be fine. Also, in almost all cases, if not all, assuming an identifier starting with a capital letter is type parameter will work.
(Closure compiler does inference based on naming conventions, so it's not new)


As a side note, as a capturing utility in the `swc_ecma_parser` uses the parser to discriminate regex from comments, so you don't have to worry about regex being incorrectly treated as comments or division operator.

**Comment by bartlomieju** [comment]
@magurotuna do you have any ideas how we could tackle this issue?

**Comment by magurotuna** [comment]
Lexer-based highlighting would work enough with a little compromise. I'll try to implement a PoC for it.
