### ISSUE TITLE
Adding tools/pre-commit.py to lint git commit messages 

### ISSUE THREAD

**Issue by getspooky** [denoland/deno#8236]
I thinks is good idea to implement a pre-commit script that supports macOS, Linux and Windows.

**Comment by kitsonk** [comment]
I think it is unnecessary... We squash merge commits anyways and clean up the commit messages there.  All it would do is make more friction for contributions, which I think would make everyone 😢 .

**Comment by bartlomieju** [comment]
I agree with @kitsonk, each PR is merged manually and often commit titles are adjusted before merging. I see no point in enforcing commit message style for commits in the PR which is essentially work-in-progress branch.

**Comment by wperron** [comment]
I've had this conversation with multiple colleagues and teams in the past, and local git hooks usually don't stand the test of time because really there's no way to enforce it; contributors are completely to run the init script or not. Bottom line I don't think it would really help maintainers because they'd still have to deal with non-compliant messages.

The current approach of squashing is a better idea in my opinion.

**Comment by kitsonk** [comment]
Enough feedback, thanks everyone.
