### ISSUE TITLE
Benchmark wanted: time it takes to run tools/test.py

### ISSUE THREAD

**Issue by ry** [denoland/deno#824]
Since tools/test.py will have already run when tools/benchmark.py runs, it should be relatively easy to capture the time it took in .travis.yml and pass it via the command line to tools/benchmark.py.

**Comment by bartlomieju** [comment]
I think recently we had a chart at (deno.land)[https://deno.land], has it gone missing?

**Comment by ry** [comment]
I removed the travis benchmark in 514b7d335977eda1b7b110d3ad5f9f93ac60af5b (reasons in commit message). I think it would be useful to track how long test.py takes to run.

**Comment by bartlomieju** [comment]
I explored this subject - Travis exposes API that can be queried during build and I wanted to use that to retrieve running time of current pipeline during benchmarks stage but... API request can be filtered by `commit_id` which is Travis' id (not a git hash, and I couldn't find a way to correlate them) so that's not an option to obtain this time. Does anyone have a better idea?

**Comment by ry** [comment]
This is not so necessary, I'm closing this one.
