### ISSUE TITLE
zsh completion fails for 1.5.4

### ISSUE THREAD

**Issue by 06kellyjac** [denoland/deno#8472]
Reproducing:

Fresh debian container

```
$ apt update
$ apt install -y wget unzip
$ wget https://github.com/denoland/deno/releases/download/v1.5.4/deno-x86_64-unknown-linux-gnu.zip
$ unzip deno-x86_64-unknown-linux-gnu.zip
$ ./deno --help
$ ./deno completions bash
$ ./deno completions zsh
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/completions/zsh.rs:407:29
```

Also failing in https://github.com/NixOS/nixpkgs/pull/104674
Issue filed in the clap repo: https://github.com/clap-rs/clap/issues/2220

Since I don't have familiarity with the changes in `1.5.4` if someone else wants to take over the clap issue by posting a new one I'll be happy to close mine.

**Comment by 06kellyjac** [comment]
> [#2191](https://github.com/clap-rs/clap/pull/2191) would fix this, I think.

https://github.com/clap-rs/clap/issues/2220#issuecomment-732257985

Using an older version might work as previous deno versions have been working just fine.

**Comment by ahkrr** [comment]
I had a problem with zsh completion generation in clap 3 beta in the past 
The problem that I was finding was, when a cli argument was declared as global and also as having conflicts with other arguments which weren't present in all the subcommands that the global argument was present in, then the completion generation would error out.
This would happen because a conflict was declared for which the conflicting argument didn't exist in the command ( or subcommand) that the argument that had the conflict declared on was in.
I looked at the deno cli and couldn't find the problem that I ran into but commenting out these two lines
``` rust
//deno/cli/flags.rs
/*1398:*/fn watch_arg<'a, 'b>() -> Arg<'a, 'b> {
  Arg::with_name("watch")
    .requires("unstable")
    .long("watch")
    // .conflicts_with("inspect")
    // .conflicts_with("inspect-brk")
    .help("Watch for file changes and restart process automatically")
    .long_help(
      "Watch for file changes and restart process automatically.
Only local files from entry point module graph are watched.",
    )
}
```
prevented the crash from happening. Maybe the conflicts that are declared here don't exist in the command ( or subcommand) that watch is part of?

**Comment by crowlKats** [comment]
@ahkrr came across this while working on https://github.com/denoland/deno/pull/8485 as non-existing conflicts fail in v3. indeed watch only encounters inspect & inspect-brk with the run subcommand, but is still used with fmt & bundle.

**Comment by ahkrr** [comment]
Maybe this `panic!` in the `zsh completion generation` should be removed in `clap 3`, because it isn't a fatal error, if the tab completion doesn't find the arguments in the scope that the command is in.
In addition, this problem doesn't show up in the other generation functions.
