### ISSUE TITLE
Skip type checking by default

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#8549]
Instead of `--no-check` consider type checking TypeScript as an opt-in with a `--check` option.

**Comment by littledivy** [comment]
Would make more sense as a subcommand? `deno dev script.ts` for typechecking.

**Comment by David-Else** [comment]
TypeScript is just JavaScript with types, why would you skip type checking? That completely defeats the purpose of using TypeScript. If it is to save time in development just use `--no-check`, a perfect solution with no downsides. This suggestion makes no sense whatsoever to me...

**Comment by RDambrosio016** [comment]
i believe having --no-check on by default is implicit behavior which is too dangerous to excuse, sure, it can be exponentially faster to not run tsc, but type checking is the most important part of typescript, you remove that and now you have javascript with meaningless types. I think --no-check is fine as it is and having it on by default would also be a pretty big suddent change which would be unexpected to a lot of people.

**Comment by MarkTiedemann** [comment]
An argument for skipping type-checking is that, usually, this is already done by a plugin in the editor while working on the code so, usually, you won't run into any type-issues when running `deno run ...`.

**Comment by David-Else** [comment]
@MarkTiedemann The final production code needs to go through the official TypeScript compiler for quality assurance. `--no-check` should be used for development inside the code editor. Users need confidence that TypeScript code IS type-checked by default. Turning off default type checking would be a disaster, I have still not heard a decent argument for doing it.

**Comment by nayeemrmn** [comment]
This issue is carried over from the large amount of discussion about it in #5436, ref https://github.com/denoland/deno/issues/5436#issuecomment-629178613.

> But many developers use IDEs to develop JavaScript or TypeScript. Those editors enforce types as you edit the code. Therefore Deno type checking is effectively redundant.

-1. There's nothing wrong with Deno having some unassertive considerations based on what editors do, but a language's type system not being enforced by default is a big deal. I disagree with basing such a crucial _CLI_ design decision on editor functionality. But even accepting that, if we're taking the perspective of an integrated workflow, why is adding `--no-check` seen as such a burden? It's appropriate that the tool which compensates the type-checking is responsible for opting out of it with `--no-check`. I'm sure that's impractical for some set of reasons but it doesn't change that this is roughly how well-designed tools stack with each other. Not by implicitly skipping a correctness check because it's likely handled visually by a separate tool. That debt will be paid in future issues invoking the role of type-checking in Deno, and editors are now an unwanted factor in every such discussion.

**Comment by kitsonk** [comment]
I should have provided a bit more context. First, to make it abundantly clear, this is open for discussion, and would be for Deno 2.0 at the earliest.

Second, the biggest argument for it in my mind is that Deno is supposed to be fun and productive, and things that get in the way of casual, experimental use of JavaScript or TypeScript make it harder for people to get started and be productive and have fun.  This suggestion wasn't even one that occurred to me until one of the core TypeScript team members said do me "why does Deno even type check by default" which made me think, and is something @ry has also started thinking about.

This doesn't mean that type checking would go away, it just means that it is opt in, which potentially could make it a heck of a lot easier for people to get on board.  Especially since we are strict by default in our type checking, which I think is something we wouldn't ever want to change now, does put a big roadblock in front of people experimenting with Deno.  I have even found myself sometimes writing stuff in JavaScript just to avoid getting bogged down with making sure a quick experiment is 100% valid TypeScript.  I personally want to see more people adopt TypeScript, which means that we need to continue to try to find ways to make it fun and productive when using with Deno.

Another consideration for 2.0 is making TypeScript diagnostics non-terminal.  In that case, you would potentially get a load of errors, but barring a syntactic error, Deno would try to run your code.

**Comment by RDambrosio016** [comment]
> Second, the biggest argument for it in my mind is that Deno is supposed to be fun and productive, and things that get in the way of casual, experimental use of JavaScript or TypeScript make it harder for people to get started and be productive and have fun

to me this argument doesnt hold because coincidentally one of the biggest things that can prevent people from having fun is random bugs because their types dont check out. Moreover, this is even worse for the argument of a beginner, because a beginner is unlikely to know that deno just doesnt run type checking by default. This is why setting this default is incredibly dangerous. 

Even so, the argument of "its easy to just add `--check`" can be spun around as "its also easy to just add `--no-check` and there is no dangerous implicit behavior that way"
