### ISSUE TITLE
deno compile should support cross-platform compilation

### ISSUE THREAD

**Issue by eliassjogreen** [denoland/deno#8567]
Now that a basic `deno compile` subcommand has been merged into deno it might be interesting to consider implementing support for a `--target` flag so that one could compile to all supported platforms from all supported platforms. Because of the approach taken for embedding the code into the binary it would probably be pretty easy to implement, the only slight problem being getting the binaries for the other platforms but those could just be fetched from releases.

**Comment by lucacasonato** [comment]
Yea. This is on my idea list too.

**Comment by lucacasonato** [comment]
From #8657:

> It would be great if you could cross compile binaries for different platforms when using deno compile.
> 
> Example: deno compile --target x86_64-apple-darwin https://deno.land/std@0.79.0/http/file_server.ts from Linux or Windows to create a macOS binary.
> 
> This should be relatively trivial to implement. Instead of using the current binary as the base binary for the compilation, we would download the binary for the specified target (using the same code as deno upgrade), and then use that as a compilation base binary.

**Comment by brannondorsey** [comment]
This would be a major convenience, especially for CI/CD pipelines which build application releases for multiple platforms and architectures from a single Linux box/container. Golang's approach to provide control over these two axises at build time with `GOOS` and `GOARCH` environment variables makes this incredibly easy ([example](https://github.com/brannondorsey/markov/blob/f489191a076587d9ccfe3836052c1acab05f3dd6/Makefile#L14-L27)). Perhaps it would make sense to split OS target and CPU architecture target into separate CLI arguments?

Whatever method is chosen would be fine by me though, as long as cross compilation is eventually supported in Deno. As a long time Node.js user, I've actually started to prefer using Golang to write CLI tools specifically because of the cross-compilation feature. It would be nice to be able to move back to JavaScript/TypeScript to write tools which are distributed to multiple platform and architecture combinations.

In the ideal case, it should be easy to build for all platforms from one development environment, and then install a binary to any platform like so...

```bash
# Build and release for all platforms and architectures on one box
make compile-all upload-release

# Download and run the compiled binary on another box
OS="linux" #windows, macos, etc.
ARCH="x64" #arm7, etc.
wget "https://example.com/releases/$OS/$ARCH/mytool" && chmod +x mytool
./mytool
```

This would be true development bliss 🙏

**Comment by lucacasonato** [comment]
Done in 1.7

**Comment by chovy** [comment]
is there any kind of bundler to ship files like templates and other static files necessary? Having the binary by itself isn't much use if all the necessary files aren't included.

**Comment by Dygear** [comment]
> is there any kind of bundler to ship files like templates and other static files necessary? Having the binary by itself isn't much use if all the necessary files aren't included.

Deno is the runtime environment, that has the built in [Runtime API](https://doc.deno.land/builtin/stable) to connect to the system that it ships with. For everything else there is the [Standard Library](https://deno.land/std) available as an import or the [Third Party Modules](https://deno.land/x) section. The fact that you have to import the libraries or modules at compile time for the first run is actually a feature, you only ever have what you expressly need. Deno's Runtime API should only ever be what you need, and everything else makes it better / easier to work with building on top of these things.

**Comment by chovy** [comment]
I'm talking about if I have like ./views folder. if i don't ship that along with the binary the binary is useless. is there anyway to package this up or an installer for the different OSes so I can install all the required files to /usr/local/myapp

**Comment by Soremwar** [comment]
Import assertions and asset references are two proposals that try to tackle this issue and would probably be the used solution by deno compile

Sadly they are still early in review/implementation

**Comment by jamesdbruner** [comment]
@Soremwar do you happen to know if there's been any progress in either proposal?

**Comment by lotsofthoughts** [comment]
@jamesdbruner Since they aren't moving forward on those proposals, there are other ways to tackle that.  For instance, I'm using the [docker api ](https://deno.land/x/dockerapi@v0.1.1) to pull images down and copy data out and into it's correct location.  Another option would be to pull the gh CLI and run features in deno or pull release tarballs and extract them.  I'm using [cliffy](https://cliffy.io/docs@v1.0.0-rc.7/command#defining-your-command) as a CLI to do those sorts of things.

You might be aware of all this, I'm just giving options.   Deno also has a great kv store for saving and re-using information from JSON files, which can live anywhere.
