### ISSUE TITLE
Extract Deno Tools

### ISSUE THREAD

**Issue by yordis** [denoland/deno#8595]
## Context

1. Would like to leverage `deno doc`, `deno fmt`, `deno lint` agnostic of Deno projects.
2. Would like to be able to extend my own Rust CLI using the underline components from Deno

## Intent

Would like to see Deno take some responsibility for bringing alignment around the JavaScript ecosystem by providing those CLI tools agnostic of Deno projects (as much as possible).

We are in the transition to leverage Deno for incoming projects over NodeJS, but realistically, we are not there yet, but we would like to stop the bikeshedding and misalignment around these tools, and be closer to "a way" to solve particular issues where freedom isn't that valuable, or in the worst case, would be much better to improve "a tool".

## Thoughts

I am not that familiar with Rust, but it seems that the simple wrappers for the underline packages used in Deno CLI actually do some *tedious stuff* around matching files, and so on. Maybe keep raising the level of abstraction would be beneficial.

Also, I tried to use `deno doc https://github.com/straw-hat-team/logger/blob/master/src/index.ts` but didn't work 

```shell
❯ deno doc ./src/index.ts
Cannot resolve module "file:///Users/ubi/Developer/StrawHat/logger/src/logger"
```

**Comment by Soremwar** [comment]
The issue with Deno Doc can't be sorted out currently due to JS resolvers using the standard ES modules, so things like `import x from "a"` won't work cause `a` is not a valid path, `a.js` is.

On the otherhand _deno lint_ can be executed as a standalone binary and `deno fmt` is just an abstraction over a JavaScript formatting tool called `dprint` which is available as a standalone executable as well.

The real issue here would probably be the leveraging of the different formats of JavaScript across the ecosystems, and since I'm not a mantainer I can not speculate about whether those versions (such as CommonJS) will receive support at all in Deno tooling.

**Comment by yordis** [comment]
> so things like import x from "a" won't work cause a is not a valid path, a.js is.

Still waiting for TypeScript to allow me to add extensions to the import.

> On the otherhand deno lint can be executed as a standalone binary and deno fmt is just an abstraction over a JavaScript formatting tool called dprint which is available as a standalone executable as well.

I am not that familiar with Rust, but it seems that the simple wrappers for the underline packages used in Deno CLI actually do some tedious stuff around matching files, and so on

> The real issue here would probably be the leveraging of the different formats of JavaScript across the ecosystems, and since I'm not a mantainer I can not speculate about whether those versions (such as CommonJS) will receive support at all in Deno tooling.

Yeah,  maybe support only ESM.

**Comment by bartlomieju** [comment]
@yordis so do you want a separate binary that has only the tooling but no runtime or do you want to use/consume the tooling as embedded in Rust project? The former is unlikely to happen, while the latter could be available in the future as part of #7928

**Comment by yordis** [comment]
@bartlomieju honestly, having them as a library that would allow me to create a simple binary from it would be amazing.

That being said, I am not sure how hard would be for Deno to ship some `denotools` binary as well, or make Deno tools itself compatible with non-Deno specific things that may happen 🤷🏻 I am not sure.

**Comment by bartlomieju** [comment]
> That being said, I am not sure how hard would be for Deno to ship some denotools binary as well

That's highly unlikely to happen, we're thinking about shipping "lite" binary that doesn't include tooling, but shipping only a tools as a separate binary seems far-fetched at the moment.

> or make Deno tools itself compatible with non-Deno specific things that may happen 🤷🏻 I am not sure.

What do you mean by that? I see in your first comment that you couldn't use `deno doc` because the library uses extension-less imports; this is one of Deno's premises that it requires specifiers with extensions (no guessing if user meant `.js` or `.ts`) and it's only highly unlikely to change.

**Comment by yordis** [comment]
@bartlomieju right .... 😭 which TypeScript itself doesn't allow me to use extensions in the name, which is where I am not sure who should fix what 😭

**Comment by kitsonk** [comment]
The amount of Deno that is independent of the tools is quite trivial.  The tooling actually make up the vast majority of the binary size (specifically the TypeScript compiler).  Having just the tools would be 95% of the current binary size I would suspect, so breaking out the tools separately would only increase the maintenance overhead with little real world value.  I agree with @bartlomieju that it is not something we would likely want to consider.
