### ISSUE TITLE
`deno compile` does not provide the ability to specify permissions or v8 flags

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#8656]
Currently all code run in `deno compile` effectively uses `--allow-all` permissions, and the default `--v8-flags`. This issue exists to investigate if there is demand for specifying permissions or v8 flags for `deno compile`.

**Comment by kitsonk** [comment]
I am uncertain if we should bake permissions into `deno compile`, as I think we should build on the overall Deno model of limiting permissions.  On the other hand, it is currently painful to make a well behaved, interactive, command line utility in Deno because of a lack of stable `Deno.permissions` API.  Personal opinion is we should address that, which would allow people to build a well behaved Deno programme which could be used with `deno compile`.

Specifying v8 flags, is there a compelling use case for that?  What v8 flags do people need to set?  Seems like something that would be a real advanced use case and not something for `deno compile` in my opinion.

**Comment by 3n-mb** [comment]
For now, I make bundle, and use deno binary with bundle. Yes, there are two files instead of one, but two is better than a lot.

**Comment by MichelDiz** [comment]
I also have a problem with compile which looks like a permission issue. The react application in OAK server won't start. The binary is a bit beefy, so probably it is embedding the build path with the react app.
