### ISSUE TITLE
Deno.bundle fails when the files don't export anything

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#8803]
**Reproduction**

```
// a.ts
const [d, o] = await Deno.bundle("./my_ts.ts")
```
```
// my_ts.ts
function greet(name: string): string {
  return "Hello, " + name;
}
```

Output:

```
error: Uncaught (in promise) AssertionError: Assertion failed.
    at Object.assert (deno:cli/rt/06_util.js:33:13)
    at Object.bundle (deno:cli/rt/40_compiler_api.js:85:10)
```

Add `export ` before the function declaration in `my_ts.ts`, run again, and it works

**Comment by kitsonk** [comment]
It isn't the lack of exports... if you actually invoked the function `greet()` somewhere it would bundle fine.

We could react better, the the proper emit of this bundle, with dead-code elimination/tree branching is an empty string.  We double check for undefined or null, instead of falsey values.

I don't think it is an issue with #8799 but will ensure I double check that.

**Comment by satyarohith** [comment]
This isn't an issue anymore. `Deno.emit("./source.ts", { bundle: "esm" })` produces an empty string with the above source examples as one would expect.
