### ISSUE TITLE
Benchmark wanted: copy throughput 

### ISSUE THREAD

**Issue by ry** [denoland/deno#890]
outlined here: https://github.com/denoland/deno/pull/884#issuecomment-426747165

Should wait for #884 to land.

In the future we will want to compare it to TLS throughput.

It makes sense to also compare it to a program that measures stdio throughput:
```js
// time head -c 100000000 /dev/zero | deno this_script.js
import * as deno from "deno";
deno.copy(deno.stdout, deno.stdin);
```

**Comment by alexhultman** [comment]
What counterpart should it compare with? Golang? You need to set a performance goal such as "it should be similar to Golang". Then we need to port all benchmarks to (for instance) Golang so that we get *relative* numbers and not just "1 million unnamed units of performance". You want to get numbers like "0.79x of Golang".

**Comment by ry** [comment]
No counterpart needed for the first version - would like to just get continuous look at the perf

**Comment by ry** [comment]
Likely you are experiencing https://github.com/denoland/deno/issues/919
We’ll have a new release in a day or two
