### ISSUE TITLE
When compiling `lspower v0.1.0 Build fails on 5.10.0-1` build fails due to `bad archive`

### ISSUE THREAD

**Issue by whatever-art** [denoland/deno#8900]
I have never worked with `cargo` && || `deno` before, but I happen to be running kernel version 5.10.0-1; It's also the holidays; And I'm not really part of this repo, but I thought that I'd let y'all know irregardless;

When compiling `lspower v0.1.0`, `cargo install deno` fails with the following error:

![image](https://user-images.githubusercontent.com/74662832/103206120-1ef60c80-48c9-11eb-869c-d4060d87a45b.png)

This was also happening on kernel 5.9; But it was soon resolved;

I hope that helps; I also have very intermittent intermittent internet access; Perhaps this could help you track down the previous ticket which fixed this as I think it's a recurring issue;

Additionally, the `Preview` button doesn't seem to work in offline mode unfortunately;

**Comment by lucacasonato** [comment]
The failure is actually while building rusty_v8, not lspower.

Your intermittent internet is likely to blame here. The rusty_v8 build downloads a precompiled librusty_v8.a from GitHub, because it can take quite a while to build V8. If you would rather build from source, you can set the env var `V8_FROM_SOURCE=1`. The other thing you could do is set up RUSTY_V8_MIRROR as explained here: https://github.com/denoland/rusty_v8#the-rusty_v8_mirror-environment-variable

**Comment by bartlomieju** [comment]
This will be fixed in https://github.com/denoland/deno/pull/8898 and released in 1.6.3.

**Comment by whatever-art** [comment]
@lucacasonato running gentoo would be nice as well; @bartlomieju so IT will take a while; At least it will run on the latest bleeding edge; Thanks;

**Comment by kitsonk** [comment]
#8898 is merged, so closing.

**Comment by whatever-art** [comment]
@kitsonk @bartlomieju @lucacasonato Yes, it seems to work on my machine now; Thank you for your time;
