### ISSUE TITLE
tslint isn't being run on js/*_test.ts

### ISSUE THREAD

**Issue by ry** [denoland/deno#897]
see tools/lint.py

**Comment by cByst** [comment]
@ry It looks like tslint is currently configured to lint only "node_modules/typescript/lib/lib.esnext.d.ts" and "js/main.ts" as well as their imports and their imports imports etc.

Are we missing more than just the tests here? If all we are looking to lint is under the js directory I can modify lint.py to lint the entire js folder which will exclude node_modules/typescript/lib/lib.esnext.d.ts (I dont think we want to be linting this).

Let me know what you think and I can open a pr.

**Comment by cByst** [comment]
hmmm me PR is going to fail CI for linting as this change will lint the test files that have never been linted before introducing what ever formatting and style issues that exist in them. I can open another PR that fixes those issues if you want to merge that before fixing the linter.

**Comment by ry** [comment]
Same PR but two commits would be ideal. Thanks!

**Comment by cByst** [comment]
Unfortunately after some more research it looks like type-checking dependent rules only work when using the project flag (-p) which cant be used to lint both the tests and the project ts files because they are not part of the project.
```
Warning: The 'no-circular-imports' rule requires type information.
Warning: The 'restrict-plus-operands' rule requires type information.
```
I think the best approach would be to break the lint up into 2 separate linting calls
```
run(["node", tslint, "-p", ".", "--exclude", "**/gen/**/*.ts"])
run(["node", tslint, "./js/**/*_test.ts", "./tests/**/*.ts", "--exclude", "**/gen/**/*.ts"])
```

If we implemented it this way we would get the type-checking dependent rules for the project and get everything but the type-checking dependent rules for the tests.

Let me know what you think I will update my PR in the meantime.

**Comment by ry** [comment]
@cbyst ya splitting it up into two commands makes sense - thanks for looking into this
