### ISSUE TITLE
Idea: introduce --csp cli flag

### ISSUE THREAD

**Issue by CrimsonCodes0** [denoland/deno#9021]
Inspired by [dart2js](https://dart.dev/tools/dart2js#analysis-options)'s --csp flag
Somewhat related https://github.com/denoland/deno/issues/1639?

I suggest introducing a --csp flag, or a way to sort of opting into (*some of the*) browser-like [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) restrictions.

Most of CSP is completely irrelevant to JS, but "script-src" could prevent unsafe evaluation of dynamically generated code, and limits fetching to whitelisted domains/URLs. (*Deno may optimize for this by DNS prefetching them?*)
This means that the HTML whatwg spec [HostEnsureCanCompileStrings(callerRealm, calleeRealm)](https://html.spec.whatwg.org/multipage/webappapis.html#hostensurecancompilestrings(callerrealm,-calleerealm)) operation will throw, which I believe Deno doesn't implement, but I believe only `eval`, `setInterval`, `setTimeout`, and `Function` functions depend on it.

Effectively they would just throw now, I believe that a few tests may need to be rewritten to handle the throwing eval.

**Comment by kitsonk** [comment]
I am not sure what benefit this would offer above the existing Deno security model.

Could you provide some specific use cases of something you think Deno should permit, but does, and that throwing an error would be beneficial to the user?

**Comment by 00ff0000red** [comment]
> I am not sure what benefit this would offer above the existing Deno security model.

Well, networking is already covered by --allow-net, so the only other part would be dynamic code generation.
Generally, dynamic code gen isn't a good thing to see, especially with JavaScript, it's not as bad as, say, C, where I've seen some JiT compile the hardware stack and execute it, since JavaScript doesn't have that level of power, but regardless, it's never good.

Maybe the community would have an opinion on this?

**Comment by kitsonk** [comment]
> Generally, dynamic code gen isn't a good thing to see

That is highly subjective viewpoint.  We just added the ability to support data URLs, because it was highly requested from the community, and one of the big use cases is dynamic code generation and execution.  Often times in server situations, being able to generate and re-generate runnable code on the fly is one of the big uses cases.  Again one of the big reasons for the runtime compiler APIs.

**Comment by 00ff0000red** [comment]
Well, I'll admit it is subjective, but it's pretty subjective either way, there's no way around that; there are always other ways to do anything, technically we *could* all replace any functions that return functions with functions that call eval and use string concatenation.
If you believe that this would provide no benefit to the Deno ecosystem, you could close it as something that the Deno team will not consider.

**Comment by benatkin** [comment]
I'd also like to see this. Here is an issue that discusses it in the context of dynamic imports: https://github.com/denoland/deno/issues/8266 I think it is also needed for static imports but I think this issue is a good place to figure out a simple way that covers most use cases.
