### ISSUE TITLE
Unix socket listen() should not remove existing file

### ISSUE THREAD

**Issue by mk12** [denoland/deno#9052]
When you run `Deno.listen({ transport: "unix", path: "foo.sock" })`, it first deletes any existing "foo.sock" file (see [runtime/ops/net_unix.rs](https://github.com/denoland/deno/blob/master/runtime/ops/net_unix.rs#L135-L137)). This is surprising to me, and inconsistent with the Unix socket APIs in Go, Rust, Python, and Ruby. It also encourages the bad practice of neglecting to clean up the socket file on exit.

`Deno.listen` fails if a port is in use, so shouldn't it also fail if a socket file is potentially in use?

**Comment by bnoordhuis** [comment]
FWIW, Node.js behaves the same as Deno. As that is where most new Deno developers will be coming from, there's a case to be made that it reduces the friction new developers experience.

I thought it was Ryan who introduced that change back in the day but turns out it was me: libuv/libuv@4eff34da4. Mea culpa!
