### ISSUE TITLE
Feature Request: deno bench subcommand 

### ISSUE THREAD

**Issue by grian32** [denoland/deno#9175]
Add a `deno bench` subcommand that behaves like `deno test`, this would remove `runBenchmarks()`, this could also be achieved by making it so `deno run` ignores `runBenchmarks()` and `runBenchmarks()` is ran using `deno bench`, or we could add the extra functionality of `runBenchmarks()`(other than running the benchmarks, like the run only based on a regexp etc) as cli args for `deno bench`.

The reason I want this is because I like the way you're encouraged to organize tests in Rust(https://doc.rust-lang.org/book/ch11-03-test-organization.html), and I think this is also a thing for benchmarks, although benchmarks in Rust as of now are unstable.
You can currently do this in deno using `deno test` and having the tests, but I think it'd be nice if you could also do it with benchmarks, which isn't really possible with the way it's currently done.

Would like some feedback on this idea.

**Comment by bartlomieju** [comment]
My personal opinion is that we should add this subcommand. That said, it's gonna be a big endeavour for anyone interested in working on this. We have [`std/testing/bench.ts`](https://deno.land/std@0.119.0/testing/bench.ts) module but there's not much feedback about it and most of the logic would have to be reimplemented in Rust in order to support it as a subcommand.

If anyone is interested in spearheading the effort, please let us know, I'll be glad to help out.
