### ISSUE TITLE
Will MYSQL, SMTP and IMAP support ever be part of the standard library?

### ISSUE THREAD

**Issue by suchislife801** [denoland/deno#9227]
Greetings.

Currently, the only reason I still use PHP is for the superb PDO Class it has, used for MySQL connections and data.

It would be fantastic if Deno supported these right out of the box.

3rd party libraries exist but aren't really usable for MySQL or user friendly. And not even close to PDO.

I'm a PHP developer and since PHP is open source I was wondering if you could port PDO to Deno. This would greatly increase Deno popularity and the code is technically already written; PHP is open source.

The real PDO benefits are:

- security (usable prepared statements)
- usability (many helper functions to automate routine operations)
- re-usability (unified API to access multitude of databases, from SQLite to Oracle)

Ideally only the MySQL driver would be ported.

[https://www.php.net/manual/en/book.pdo.php](https://www.php.net/manual/en/book.pdo.php)

[https://www.php.net/downloads](https://www.php.net/downloads)

**Comment by kitsonk** [comment]
This sort of question is best suited for the discussion forums, not the issue tracker.

It is unlikely we would consider they specific use cases for std. In order to keep the issue tracker focused, I am respectfully closing, though feel free to open a discussion topic. (I would move it, but GitHub has disabled that feature currently due to bugs).
