### ISSUE TITLE
Repl hangs while sending Websockets

### ISSUE THREAD

**Issue by Khobalt** [denoland/deno#9241]
1. Open a terminal tab and run:
`$ deno run --allow-net https://deno.land/std@0.84.0/ws/example_server.ts `

2. Open another terminal tab and run:
`$  deno repl --inspect`

3. Copy and paste - 
```javascript
let ws = new WebSocket("ws://localhost:8080");
ws.send("sdfsdf");
```

[Expected Result]
The WebSocket is sent.

[Result]
The repl hangs, and the WebSocket is not sent.

[Notes]
1. Opening another client will un-stick the blockage.
2. Sometimes it takes a few ws.send() calls to reproduce this bug.

**Comment by lucacasonato** [comment]
cc @caspervonb

**Comment by caspervonb** [comment]
Hum; so the expected behaviour from using the `--inspect` flag would be that it blocks until a client connects to the inspector.

Not sure why this is only reproducible with a WebSocket connection, because the inspector server runs on its thread with its own runtime separate.

Looking into it, bisecting a couple of versions back this used to error.

**Comment by caspervonb** [comment]
So --inspect is a red herring, this deadlocks no matter what eventually.

**Comment by caspervonb** [comment]
Yeah repl is also a red-herring, can reproduce in a plain script.

**Comment by lucacasonato** [comment]
@crowlKats
