### ISSUE TITLE
add semaphore to std/async

### ISSUE THREAD

**Issue by jd1378** [denoland/deno#9260]
Hi
wanted to see if we can add a semaphore implementation to std/async ?

**Comment by kitsonk** [comment]
JavaScript isn't a multi-threaded language, so generally locking mechanisms aren't necessary.  What would be the use case?

This feels like an opportunity to start as a community solution first, and if widely adopted be considered for migration to `std`.

**Comment by jd1378** [comment]
I saw [await-semaphore](https://www.npmjs.com/package/await-semaphore) on npm, and it had somewhat high download, so I thought maybe it is being used widely
I don't have a use case myself yet, I know js is not multi-threaded , but for limiting task execution to a fixed amount is something I think is nice to have some times.

**Comment by kitsonk** [comment]
Just because [something has a high download count on npm](https://www.npmjs.com/package/isarray) doesn't mean it makes sense for inclusion in Deno's `std` library.

Since it lacks a specific use case, I am respectfully closing.  Again, there is nothing preventing the community creating something, just like has been done for Node.js.

**Comment by jd1378** [comment]
You are completely right about that and I agree. thanks for the response
I'll do a quick port of the mentioned await-semaphore, leaving a link here later for anyone interested
https://github.com/jd1378/deno-semaphore
