### ISSUE TITLE
PermissionDenied: read access to <main_module>, even with --allow-read=main_module

### ISSUE THREAD

**Issue by roblav96** [denoland/deno#9283]
## Problem

Accessing `Deno.mainModule` with `--allow-read=main_module` throws `PermissionDenied`, even the `Deno.permissions.query` responds with `{ state: "granted" }`

##### `deno run --unstable --allow-read=main_module mod.ts`

```ts
// mod.ts
let status = await Deno.permissions.query({ name: 'read', path: 'main_module' })
console.log('status ->', status)
// status -> PermissionStatus { state: "granted" }
console.log('Deno.mainModule ->', Deno.mainModule)
// error: Uncaught PermissionDenied: read access to <main_module>, run again with the --allow-read flag
```

**Comment by roblav96** [comment]
Same goes for `Deno.cwd()` with `--allow-read=cwd`

**Comment by kitsonk** [comment]
The error message is slight confusing, and we should look into that, but the value of `--allow-read` is optionally a path, not some arbitrary string.  We sanitise the output, because if we printed the actual values, that would be a way to subvert the permissions in a way, because the main module and the current working directory would be written to the console.  The following works:

```
$ deno run --unstable --allow-read mod.ts
```

_or_

```
$ deno run --unstable --allow-read=. mod.ts
```

Indicating only the current directory (and its decedents) is readable.

**Comment by roblav96** [comment]
@kitsonk The error message lead me to believe that _main_module_ was some sort of dynamic variable that could be used with the `--allow-read` permissions flag. The ladder you mentioned clears things up for me. Cheers!
