### ISSUE TITLE
User control of compile binary meta data

### ISSUE THREAD

**Issue by ghost** [denoland/deno#9395]
Hi. 

1. Do I have the right to sell a CLI application written with the   `Deno compile `   command?
The information contains copyright information

![Screenshot_1](https://user-images.githubusercontent.com/75129392/106830745-05b75b80-66d2-11eb-94ea-9ce3de519e8b.png)

2. If I want to make a free open source CLI app - can I change the Deno icon?
If so, how do I do it?

Thanks...

**Comment by ry** [comment]
Yes you can sell the output of “deno compile”.... we probably need to do some work to remove logo and other metadata...

**Comment by eliassjogreen** [comment]
Related to #8912, would require `rc.exe` on windows.

**Comment by abflow** [comment]
In golang, there is an option for launching the executable in "GUI" mode, in order to hide the console:

`go build -ldflags "-H windowsgui" -o application.exe`

This is something that would be nice to have too in deno, for example in the case of a GUI application launched with the default browser and coupled to a local deno backend. Double-clicking the compiled deno application file would only open the default browser via Deno.open(url), and not the deno console itself.

**Comment by Leokuma** [comment]
Guys, I made a Deno program that allows you to compile Deno apps with custom icon and metadata: https://github.com/Leokuma/wincompile

**Comment by littledivy** [comment]
Icons are now supported: `deno compile --icon icon.ico` (#25039)

Other metadata is cleared by default for binaries produced by `deno compile`

**Comment by RossAscends** [comment]
with a valid (used as a desktop icon in the past) icon.ico in the same directory as main.ts, and using this command:

`deno compile --icon icon.ico --target x86_64-pc-windows-msvc --allow-net --allow-write --allow-read main.ts`

..the exe compiles and runs correctly, and the filesize is larger than with no icon embedded (so the file is getting in there), but there is no icon showing up, and not even an option to set an icon for the EXE in the Windows properties popup.

**Comment by bartlomieju** [comment]
@RossAscends I suggest to open a new issue for that problem, commenting on a closed issue is easy to miss for maintainers.
