### ISSUE TITLE
lsp picks up on ambient d.ts files

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#9541]
**.vscode/settings.json**
```json
{
  "deno.enable": true,
  "deno.lint": false,
  "deno.unstable": false
}
```

**foo.d.ts**
```ts
declare function hello(name: string): void;
```

**main.ts**
```ts
hello(123);
```

foo.d.ts is not referenced from main.ts, yet there is now a diagnostic related to hello defined in foo.d.ts in main.ts: `Argument of type 'number' is not assignable to parameter of type 'string'. deno-ts(2345)`

`deno run` does not pick up on the ambient typings as expected:
```
~/D/t/examples ❯❯❯ deno run main.ts --unstable
Check file:///home/lucacasonato/Downloads/test/examples/main.ts
error: TS2304 [ERROR]: Cannot find name 'hello'.
hello(123);
~~~~~
    at file:///home/lucacasonato/Downloads/test/examples/main.ts:1:1
```

**Comment by kitsonk** [comment]
Ok, I see the problem, when you open a file, it becomes part of the "environment" and `tsc` becomes aware of it.  I suspect if you close `foo.d.ts` in the editor and restart VScode and don't open `foo.d.ts` the diagnostics will align to your expectations.

I'm not sure we want to fix this, because to do so, we would basically have to explicitly set an entry module.

A slightly better solution is we ignore ambient declarations in the LSP and don't tell tsc they exist.  That gets a lot more complicated, especially if someone is trying to edit them in the editor.

**Comment by mgenereu** [comment]
It's no longer for open files. Now it's any files in the workspace as of 1.32.2.

**Comment by lucacasonato** [comment]
I don't think this is a bug actually. This happens because in the LSP all files in the workspace are considered a possible entrypoint, and are thus loaded. There is not really a way to prevent this from happening.
