### ISSUE TITLE
[Feat-Tests]: Requesting Method To Force Deno Tests To Exit Once Complete

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#9603]
### Use Case

I want to shut off everything I enabled during testing like the WebSockets. `ws.close()` doesn't work for me, because we always reopen on close to keep bots online 24/7. We can't add custom handling for a specific code, because out of nowhere the API could begin to use that code and suddenly, we have every bot out there breaking. This potential case is not worth having just for unit tests. In my opinion, there should be a cleaner way to do this.

The `deno test` process does NOT exit if it has something keeping it open like a ws connection. I don't believe the intention behind `deno test` is to stay on forever.

### Potential Solution

- Internally call `Deno.exit(0)` at the end of the test command.
- Allow a callback to be run when all tests complete for example `Deno.onTestsCompleted = () => {}` or `deno tests --onComplete=file.ts *`

### Current Workaround

```ts
// Forcefully exit the Deno process once all tests are done.
Deno.test({
  name: "exit the process forcefully after all the tests are done\n",
  fn() {
    Deno.exit();
  },
});
```

Problem with current workaround, is that when I put deno test in a GHA, it always "succeeds" even when the tests fail. It's not a huge deal breaker but it is something I would prefer done properly.

**Comment by Skillz4Killz** [comment]
Not stale :)

**Comment by caspervonb** [comment]
I'll try to squeeze this in for the coming release.

**Comment by EliteScientist** [comment]
I think my issue is related to this. Some of the unit test cause a part of my system to start up that has WebWorkers. This system needs to be instructed to shutdown. Due to this system running Deno fails to exit after the test complete.

I would add a test to shut it down but I cannot control the order in which the test execute. I have a different test file for different parts of the system.

It would be nice to have a callback or event dispatched when the test execution is complete so that I can shutdown the system. 

I think we are missing the before and after callbacks for the unit test framework.

**Comment by lucacasonato** [comment]
Ref https://github.com/denoland/deno/discussions/10771
