### ISSUE TITLE
Support navigator.onLine and online/offline events

### ISSUE THREAD

**Issue by shadowtime2000** [denoland/deno#9689]
Support for [`navigator.onLine`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) would be nice, and also the [online/offline events](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine#listening_for_changes_in_network_status) for `window.addEventListener`.

**Comment by caspervonb** [comment]
Use case?

**Comment by shadowtime2000** [comment]
@caspervonb Yeah you probably are better off trying to connect for `navigator.onLine`, but the online/offline events would be a little harder to emulate by just trying to connect to something and seeing if it works.

**Comment by kitsonk** [comment]
As @caspervonb 

> Use case?

**Comment by CrimsonCodes0** [comment]
Obviously, a server that sends static web pages would have no use for this, and I can't immediately think of why a server<->client that requires constant connectivity, such as a game, might need this.

But let's consider a web page that only occasionally needs data whenever it's available, such as the many COVID case sites that have recently appeared across the web since the current pandemic had started.
Because only the server knows when new data will be available, the best way to get data to the client would be by having the server push data to the client, which those types of sites could be viably implemented with.

Next, we'll consider what would happen, should the client or server go down. If the client goes down, client-side JavaScript could be setup to handle the browser connectivity events, and attempt to reconnect back to the server once the client comes back online. If the server is down, the client wouldn't even need to know, because it only receives data when sent by the server, this means that it merely won't update the client's UI without data.

First of all, the server needs to know when the host's machine disconnects from the internet, once it does, it should stop serving (as it would fail) and queue the last would-be response. Once the host machine is back online, it would start by attempting reconnection with the last clients, discarding those who it cannot connect back with (maybe the client left the site?) and once again serving data as normal.

Control flow of the implementation using the connectivity event could be incredibly simple, by allowing fetch to fail, and the exception to reach the global error handler:
```js
let queued_last_response = null;

async function main() {
  // serve clients web pages, data, etc

  const connection = ...; // data where we serve from

  for await ( const newest_covid_data of connection ) {
    // store to global in case of failure to send data
    queued_last_response = newest_covid_data;

    // this can throw if we're disconnect from the network
    await serve_to_clients(queued_last_response);
  }
}

globalThis.addEventListener(
  "online",
  async (_event) => {
    await reestablish_last_clients();
    await serve_to_all_clients(queued_last_response);

    // don't await, it'll be called after the call stack is cleared first
    main();
  }
);
```

**Comment by kitsonk** [comment]
I am not sure how `"online"` `"offline"` solve this and it isn't the way [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) or Web sockets work about reconnecting. They already have established mechanisms.

**Comment by caspervonb** [comment]
> await reestablish_last_clients();

Hmm, servers don't really work that way, you can't re-establish low level socket connections.
The client has to call again, registering this as a reconnection to the same "session" is a high level application specific concept.

**Comment by CrimsonCodes0** [comment]
> I am not sure how `"online"` `"offline"` solve this and it isn't the way [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) or Web sockets work about reconnecting. They already have established mechanisms.

Okay, yes it was a unbased idea, but having an unitrusive way to restart a server when it reconnects would be nice. Yes, any WebSockets and HTTP(S) sockets would be disconnected, but it would be able to restart and start serving again on it's own regardless.

**Comment by kitsonk** [comment]
"reconnects" to what? If a server is disconnected from a network, it just stops receiving requests and any re-establishment to clients is specific to the connection protocol. A global "online" event does nothing to solving those problems, so there is nothing to encourage or discourage.

**Comment by CrimsonCodes0** [comment]
> "reconnects" to what? If a server is disconnected from a network, it just stops receiving requests and any re-establishment to clients is specific to the connection protocol. A global "online" event does nothing to solving those problems, so there is nothing to encourage or discourage.

I was a bit unclear when I said "reconnects," I was thinking of simply reconnecting to the network, but the JavaScript wouldn't do that, by the time the event is received, connection has already been reestablished.

I was just saying that the server would begin serving again. Take the basic "hello world" example from Deno's home page:
```ts
import { serve } from "https://deno.land/std@0.98.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```
What happens today when the host's network goes down, and how should users bring their server back online after the network has been reconnected?

**Comment by kitsonk** [comment]
> what happens today when the host's network goes down,

A server application stops receiving requests. Usually that is the only indication and "network down" is a very soft concept as there can be any number of situations where a server cannot receive requests. Being disconnected from the network at the physical host is exceedingly rare.

Servers are different than browser clients, where the presumption of being disconnected from a network isn't an error state, but a common situation when mobile devices end up not being connected to a network.

**Comment by bartlomieju** [comment]
I don't see how it would be useful in server context as explained by @kitsonk and @caspervonb. Respectfully declined.

**Comment by ifiokjr** [comment]
@bartlomieju while this may not be as useful in server environments, it would be very useful in CLI and local machine environments.

For example, before running a command, I would like to check if the user is online / offline. If they are online, I fetch from the network, if offline I fall back to the cache. 

The events might be useful in situations where tracking whether the machine can still connect to the network may change in a long-running process.  

These are possible to implement in user land, but since the web already has a solution, I think it makes sense to implement.

I'll reopen as a new issue.
