### ISSUE TITLE
Feature Request: `deno compile` target for WASM/WASI?

### ISSUE THREAD

**Issue by Momijiichigo** [denoland/deno#9748]
I think it would be really cool if I could compile application scripts that run on Deno into WASM form. Thanks!

**Comment by lucacasonato** [comment]
This is not possible. Javascript can not be compiled to WASM.

**Comment by backkem** [comment]
> This is not possible. Javascript/Typescript can not be compiled to WASM.

This statement is [not entirely true](https://bytecodealliance.org/articles/making-javascript-run-fast-on-webassembly). I think it's worth exploring this. It would enable you to write deno style Javascript/Typescript and run it in WASM environments like Fastly's Compute@Edge.

**Comment by backkem** [comment]
As expected Fastly now [supports JavaScript](https://www.fastly.com/blog/compute-edge-now-supports-javascript) in their WASM edge compute service.

**Comment by bartlomieju** [comment]
@backkem I'm not sure what you're suggesting here. The issue was about suggesting to output WASM file from `deno compile` subcommand, that subcommand bundles your source code alongside the `deno` executable. It's not feasible to compile `deno` to WASM. 

Maybe a separate issue would be better for you request?
