### ISSUE TITLE
proposal: simplify <op_crate>::init code using proc-macros.

### ISSUE THREAD

**Issue by littledivy** [denoland/deno#9804]
Introduce a proc-macro like this:
```rust
use deno_proc_macro::init_js;
init_js!("op_crates/crypto");
```
Expands to:
```rust
 /// Execute this crates' JS source files.
pub fn init(isolate: &mut JsRuntime) {
  let mut files = vec![("deno:<op_crate:01.js>", include_str!("deno:<op_crate:02.js>")), (...)];
  for (url, source_code) in files {
    isolate.execute(url, source_code).unwrap();
  }
}
```
Simplifies code repetition but also adds more code (for proc-macros). I have implemented this here - https://github.com/littledivy/deno/tree/macros
Also note, #9800 will be introducing a new way for op inits. So this might be conflicting with it.

**Comment by AaronO** [comment]
This could be turned into a `include_all_js_files!();` macro that could be useful for crates with many JS files.

The main crate that might benefit from this is `runtime/`, which has ~30 JS files, all other op_crates only have a handful (<10)

I try to avoid procedural macros, since they add a certain degree of complexity. `macro_rules!` are often much easier to grasp and thus maintain.

I think this should NOT be considered as a verbosity improvement (because it's net-neutral or possibly net-negative), I think the main upside would be removing the "mental burden" of `op_crate`/plugin devs of having to sync JS filenames with `lib.rs`

**Comment by littledivy** [comment]
Agreed. Closing this as code simplification is already been taken care in #9800 and proc macros are an overkill for such a small gain.
