### ISSUE TITLE
Using GitLab with Auth Token doesn't work

### ISSUE THREAD

**Issue by andreas-wagner** [denoland/deno#9839]
Hi there :-)

First I'd like to thank you for adding Auth Token support, it's awesome.

Since I'm using GitLab I tried it out.
I've created a token and set it in DENO_AUTH_TOKENS.

Using the raw file URL (https://gitlab.com/(repo)/-/raw/main/mod.ts) didn't work, turns out GitLab doesn't accept the token and redirects to the sign in page.

GitLab however accepts tokens for their API and there's one for getting the raw file (https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository).

This worked in vscode for the lsp (language server), but deno cache fails with "Unknown Media Type".

```bash
deno info "https://gitlab.com/api/v4/projects/<repo>/repository/files/mod%2Ets/raw?ref=main"
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://gitlab.com/api/v4/projects/<repo>/repository/files/mod%2Ets/raw?ref=main
  MediaType: Unknown
```

If I do not escape the dot to %2E in mod.ts I get (notice the download):
```bash
deno info "https://gitlab.com/api/v4/projects/<repo>/repository/files/mod.ts/raw?ref=main"
Download https://gitlab.com/api/v4/projects/<repo>/repository/files/mod.ts/raw?ref=main
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://gitlab.com/api/v4/projects/<repo>/repository/files/mod.ts/raw?ref=main
  MediaType: Unknown
```

I can imagine the URL getting confusing for imports inside the fetched file (as it ends with "/raw" before the query params).
Maybe this can be supported:
```bash
curl --header "Authorization: Bearer <token>" "https://gitlab.com/api/v4/projects/<repo>/repository/files/mod%2Ets?ref=main"
```
Which returns both metadata and the file content, thus being very specific:
```json
{
  "file_name":"mod.ts",
  "file_path":"mod.ts",
  "size":1190,
  "encoding":"base64",
  "content_sha256":"2a2d7c76bfe0f3292a06d54cb4c6aa27c76084b689c0ee7d12ba7356a22e481b",
  "ref":"main",
  "blob_id":"2d6457c0805ffc6df4c9c7bc2b7b3ed581a83b13",
  "commit_id":"593234249b5557b298db065704835afa2f9b94aa",
  "last_commit_id":"50d51ec0ed2d688aeb9d64410c09d99038784885",
  "content":"full file, just base64 encoded as stated in 'encoding'"
}
```

**Comment by andreas-wagner** [comment]
I noticed that `deno cache "https://gitlab.com/api/v4/projects/<repo>/repository/files/mod.ts/raw?ref=main"` does produce the error, but also indeed **does** cache the file.

Inside the `metadata.json` there are
`"content-disposition": "inline; filename=\"mod.ts\"; filename*=UTF-8''mod.ts"` which clarifies the filename and the culprit:
`"content-type": "text/plain; charset=utf-8"`

If I manually change the content-type to `"application/typescript; charset=utf-8"` and then run `deno cache --lock=lock.json --unstable mod.ts mod.test.ts` I get (notice that I did **not** specify `--reload`):
```bash
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://gitlab.com/api/v4/projects/<repo>/repository/files/mod.ts/raw?ref=main
  MediaType: Unknown
```

**Comment by andreas-wagner** [comment]
GitLab seems to have a content-type issue, I opened the issue there:

https://gitlab.com/gitlab-org/gitlab/-/issues/325466

**Comment by kitsonk** [comment]
Regarding the media type, the message is unclear and we have an issue for that #9762.

Interesting that you point out that we don't validate media types in the lsp like we do with `deno run`. Should look into that.

Marking it as a suggestion so we can figure out anything that makes sense to make it more interoperable with Gitlab. Disappointing that they don't accept the bearer tokens like they do on their APIs, but then don't serve the raw files with acceptable media types.

**Comment by azertyfun** [comment]
The [answer from Gitlab](https://gitlab.com/gitlab-org/gitlab/-/work_items/325465#note_536564318) sound reasonable to me: 

> returning a text/plain content-type is a security measure to prevent malicious code from being served under the GitLab domain - the browser security model demands we either do that, or serve this content under a separate domain (like GitHub's "githubusercontent.com"), and so far, we've always picked the first approach.

This issue combined with jsr-io/jsr/issues/203 creates a ridiculous situation. JSR's stance is "private registries aren't supported, just use HTTPS imports". Deno's stance is "HTTPS imports can't work with GitLab + [we don't support git/tarball imports](https://docs.deno.com/examples/local_unpublished_packages_tutorial/#what-is-not-supported)".

The end result is that Github has first-party support with detailed documentation, while GitLab users face this undocumented issue and **must** pack and publish their packages with NPM and deal with the transpiler.

@lucacasonato I don't understand where this conclusion comes from that Deno must rely on the MIME type being correct? Clearly on `https://raw.githubusercontent.com` it works just fine without a `Content-Type` header. Wouldn't it be possible to e.g. add a `DENO_CONTENT_TYPE_IGNORE=gitlab.org.tld` variable to ignore the `Content-Type` header when importing from specific domains?

Although that likely won't work for any subsequent relative imports due to the `/raw` in the API path (`https://domain/api/v4/projects/:id/repository/files/<urlencoded path>/raw?ref=<ref>`). So presumably explicit GitLab API support would be needed.

FWIW I confirmed HTTPS import to be working with GitLab using the following proof-of-concept script that simply restructures the URL and strips the `Content-Type` header. Maybe it can be useful for someone else, for my use-case HTTPS imports aren't flexible enough so I'll keep dealing with the NPM registry.

<details><summary>Details</summary>
<p>


```typescript
const INSTANCE = 'your.gitlab.server';
export default {
    async fetch(req: Request) {
        if (req.method !== "GET") {
            return new Response("Method Not Allowed", { status: 405 })
        }

        const path = new URL(req.url).pathname
        const m = path.match(/^\/(\d+)\/([^/]+)\/(.+)/)
        if (!m) {
            return new Response("Not Found", { status: 404 })
        }
        const [ _, project, ref, file, ] = m

        const token_header = (req.headers.get('Authorization') ?? '')
        const token_match = token_header.match(/Bearer (.+)/)
        const token = token_match ? token_match[1] : ''

        console.log(`Serving file ${file} from project ${project} at ref ${ref}`)

        const r = await fetch(
            `https://${INSTANCE}/api/v4/projects/${project}/repository/files/${encodeURIComponent(file)}/raw?ref=${ref}`,
            {
                headers: {
                    "PRIVATE-TOKEN": token,
                }
            }
        )

        return new Response(r.body)
    }
} satisfies Deno.ServeDefaultExport
```

</p>
</details>
