### ISSUE TITLE
In "deno --types" there is unnecessary redirection.

### ISSUE THREAD

**Issue by ry** [denoland/deno#994]
1. Unnecessary namespace "timers" https://gist.github.com/ry/3c59bfd370a01773d04fa21c861c47ba#file-deno-v0-1-8-d-ts-L1198
1. There is a "globals" module https://gist.github.com/ry/3c59bfd370a01773d04fa21c861c47ba#file-deno-v0-1-8-d-ts-L657 but also a "global" block - https://gist.github.com/ry/3c59bfd370a01773d04fa21c861c47ba#file-deno-v0-1-8-d-ts-L490 ... what's the difference between them?

cc @kitsonk

**Comment by kitsonk** [comment]
@ry 

1. Actually, this isn't unnecessary, as the types are referred to here: https://gist.github.com/ry/3c59bfd370a01773d04fa21c861c47ba#file-deno-v0-1-8-d-ts-L660-L663 and here: https://gist.github.com/ry/3c59bfd370a01773d04fa21c861c47ba#file-deno-v0-1-8-d-ts-L696-L699
  The challenge is that the `"globals"` module is dealt with a bit differently than the way `"deno"` is, because there is a risk of flattening it would cause collisions.  So each contributing module to `globals.ts` has its types extract and namespaced with the same name the as the namespace import in `globals.ts`.  I called it `merge()` in the tool versus `flatten()` which is what we do to `"deno"`.
2. That is because the `globals.ts` is defined as a module which augments the global scope.  Go `global` are the actual augmentations.  Upon reflection, I could actually merge that whole thing into the global scope (but we would still have some type namespaces for those modules that contribute to `globals.ts`.  At first I thought it wasn't going to be possible to unwind it all, but actually I see how it can be done.

So my advice would be to keep this issue open, and I can change the behaviour of `merge()` so that it places everything in the global scope, the `module `"globals"` would disappear, as well as all the `global` ones (except for the ones in `"deno"`) and we would be left with a handful of `namespace foo` which would contain types that contribute to globally scoped items.
