### ISSUE TITLE
Some global symbols not available on globalThis

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#9957]
This issue isn't fixed for other symbols declared with `declare class`, which I think we decided to favour in the past. Seems like only `declare var` is accessible on `globalThis`, I think we need an upstream solution: https://github.com/microsoft/TypeScript/issues/39504. cc @caspervonb @kitsonk

_Originally posted by @nayeemrmn in https://github.com/denoland/deno/issues/5666#issuecomment-811880639_

**Comment by sandersn** [comment]
In microsoft/TypeScript#39504, @Exe-Boss points out that `declare class` can't be accessible on `globalThis` because it contradicts JS semantics.

**Comment by nayeemrmn** [comment]
@sandersn As similarly discussed in that issue we are looking for some other way to declare a class object which _is_ accessible from `globalThis`  e.g. `declare var Foo: typeof class Foo {}` doesn't work. A `var class Foo {}` syntax is proposed there.

Note that we specifically want to use `class` instead of
```ts
interface Foo {}
declare var Foo: {
  prototype: Foo;
  new(): Foo;
}
```
(even for web APIs where it isn't accurate) because it looks better in our generated docs.
